CREATE TABLE OFM_ONLINE_APP_MASTER (
	APP_NAME VARCHAR(16 CHAR) NOT NULL PRIMARY KEY,
	APP_DESC VARCHAR(2000 CHAR)
);

CREATE TABLE OFM_ONLINE_COUNTER (
	CNTR_NAME VARCHAR(16 CHAR) NOT NULL,
	POOL_NAME VARCHAR(16 CHAR) NOT NULL,
	CURR_VALUE NUMBER(19),
	MAX_VALUE NUMBER(19),
	MIN_VALUE NUMBER(19),
	APP_NAME VARCHAR(16 CHAR) NOT NULL,
	PRIMARY KEY (APP_NAME, CNTR_NAME, POOL_NAME),
	CONSTRAINT counterAppID FOREIGN KEY (APP_NAME) REFERENCES OFM_ONLINE_APP_MASTER (APP_NAME)
);

CREATE TABLE OFM_ONLINE_TDQ (
	INSERT_TIME TIMESTAMP(6) NOT NULL,
	TDQ_NAME VARCHAR(16 CHAR) NOT NULL,
	DATA BLOB,
	APP_NAME VARCHAR(16 CHAR) NOT NULL,
	PRIMARY KEY (APP_NAME, INSERT_TIME, TDQ_NAME),
	CONSTRAINT tdqAppId FOREIGN KEY (APP_NAME) REFERENCES OFM_ONLINE_APP_MASTER (APP_NAME)
);

CREATE TABLE OFM_ONLINE_TSQ_META (
	APP_NAME VARCHAR(255 CHAR) NOT NULL ,
	TSQ_NAME VARCHAR(16 CHAR) NOT NULL ,
	ACC_TIME TIMESTAMP(6),
	ITEM_LAST_NUMBER NUMBER(10),
	ITEM_SIZE NUMBER(10),
	TSMODEL_NAME VARCHAR(16 CHAR),
    PRIMARY KEY (APP_NAME, TSQ_NAME),
	CONSTRAINT tsqMetaAppId FOREIGN KEY (APP_NAME) REFERENCES OFM_ONLINE_APP_MASTER (APP_NAME)
);

CREATE TABLE OFM_ONLINE_TSQ (
	ITEM_IDX NUMBER(10) NOT NULL,
	TSQ_DATA BLOB,
	APP_NAME VARCHAR(255 CHAR) NOT NULL,
	TSQ_NAME VARCHAR(16 CHAR) NOT NULL ,
    PRIMARY KEY (APP_NAME, TSQ_NAME, ITEM_IDX),
	CONSTRAINT tsqId FOREIGN KEY (APP_NAME, TSQ_NAME) REFERENCES OFM_ONLINE_TSQ_META (APP_NAME, TSQ_NAME)
);

CREATE TABLE OFM_ONLINE_SCREEN_LOADER (
	ID NUMBER(10) NOT NULL,
	SCREEN_DATA VARCHAR(3000 CHAR),
	TOPIC VARCHAR(255 CHAR),
	PRIMARY KEY (ID)
);