package com.tmax.openframe.variable.group;

import com.tmax.openframe.runtime.cobol.CobStream;
import com.tmax.openframe.runtime.cobol.PictureFormatter;
import java.math.*;
import java.util.*;
import java.util.stream.*;
import lombok.*;
import org.apache.commons.lang3.StringUtils;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:15 KST</p>
 * <hr>
 * <p>Class that defines variables for COPYBOOK item</p>
 */
public @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class CarddemoAdminMenuOptions {
    // [T-Up#INFO][COADM02Y.cpy:21] CDEMO-ADMIN-OPT-COUNT (level: 5)
    private @Getter @Setter @Builder.Default int cdemoAdminOptCount = 4;
    // [T-Up#INFO][COADM02Y.cpy:44] CDEMO-ADMIN-OPTIONS (level: 5)
    private @Getter @Setter @Builder.Default CdemoAdminOptions cdemoAdminOptions = new CdemoAdminOptions();

    public static CarddemoAdminMenuOptions createDefaultValueInstance() {
        return new CarddemoAdminMenuOptions.builder()
                .cdemoAdminOptCount(0)
                .cdemoAdminOptions(
                        CdemoAdminOptions.createDefaultValueInstance()).build();
    }

    public void set(String source) {
        source = StringUtils.truncate(StringUtils.rightPad(source, 182), 182);
        try {
            setCdemoAdminOptCount(CobStream.convZonedStringToInt(
                    source.substring(0, 2), 2));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setCdemoAdminOptCount(0);
        }
        getCdemoAdminOptions().set(source.substring(182, 362));
    }

    public String get() {
        StringBuilder sb = new StringBuilder();
        sb.append(CobStream.convZonedIntToString(getCdemoAdminOptCount(), 2));
        sb.append(getCdemoAdminOptions().get());
        return sb.toString();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(PictureFormatter.intFormatWithoutSign(
                (long) getCdemoAdminOptCount(), "00"));
        sb.append(getCdemoAdminOptions().toString());
        return sb.toString();
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class CdemoAdminOptions {
        // [T-Up#INFO][COADM02Y.cpy:45] CDEMO-ADMIN-OPT (level: 10)
        private @Getter @Setter @Builder.Default CdemoAdminOpt cdemoAdminOpt = new CdemoAdminOpt();

        public static CdemoAdminOptions createDefaultValueInstance() {
            return new CdemoAdminOptions.builder().cdemoAdminOpt(
                    CdemoAdminOpt.createDefaultValueInstance()).build();
        }

        public void set(String source) {
            source = StringUtils.truncate(StringUtils.rightPad(source, 180),
                    180);
            getCdemoAdminOpt().set(source.substring(0, 180));
        }

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(getCdemoAdminOpt().get());
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getCdemoAdminOpt().toString());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class CdemoAdminOpt {
        // [T-Up#INFO][COADM02Y.cpy:46] CDEMO-ADMIN-OPT-NUM (level: 15)
        private @Getter @Setter @Builder.Default int[] cdemoAdminOptNum = new int[] {
                1, 2, 3, 4 };
        // [T-Up#INFO][COADM02Y.cpy:47] CDEMO-ADMIN-OPT-NAME (level: 15)
        private @Getter @Setter @Builder.Default String[] cdemoAdminOptName = new String[] {
                "User List (Security)               ",
                "User Add (Security)                ",
                "User Update (Security)             ",
                "User Delete (Security)             " };
        // [T-Up#INFO][COADM02Y.cpy:48] CDEMO-ADMIN-OPT-PGMNAME (level: 15)
        private @Getter @Setter @Builder.Default String[] cdemoAdminOptPgmname = new String[] {
                "COUSR00C", "COUSR01C", "COUSR02C", "COUSR03C" };

        public static CdemoAdminOpt createDefaultValueInstance() {
            return new CdemoAdminOpt.builder()
                    .cdemoAdminOptNum(new int[4])
                    .cdemoAdminOptName(
                            Collections.nCopies(4, StringUtils.repeat(' ', 35))
                                    .toArray(new String[0]))
                    .cdemoAdminOptPgmname(
                            Collections.nCopies(4, StringUtils.repeat(' ', 8))
                                    .toArray(new String[0])).build();
        }

        public void set(String source) {
            source = StringUtils.truncate(StringUtils.rightPad(source, 180),
                    180);
            setCdemoAdminOptNum(CobStream.convZonedStringToInt(
                    source.substring(0, 8), 4, 2));
            setCdemoAdminOptName(source.split("(?<=\\G.{35})"));
            setCdemoAdminOptPgmname(source.split("(?<=\\G.{8})"));
        }

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(CobStream.convZonedIntToString(getCdemoAdminOptNum(), 2));
            sb.append(Arrays.stream(getCdemoAdminOptName()).collect(
                    Collectors.joining()));
            sb.append(Arrays.stream(getCdemoAdminOptPgmname()).collect(
                    Collectors.joining()));
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(String.join("", Arrays.stream(getCdemoAdminOptNum())
                    .mapToObj(String::valueOf).toArray(String[]::new)));
            sb.append(String.join("", getCdemoAdminOptName()));
            sb.append(String.join("", getCdemoAdminOptPgmname()));
            return sb.toString();
        }

        public int getCdemoAdminOptNum(int index) {
            return cdemoAdminOptNum[index];
        }

        public void setCdemoAdminOptNum(int index, int source) {
            cdemoAdminOptNum[index] = source;
        }

        public String getCdemoAdminOptName(int index) {
            return cdemoAdminOptName[index];
        }

        public void setCdemoAdminOptName(int index, String source) {
            cdemoAdminOptName[index] = source;
        }

        public String getCdemoAdminOptPgmname(int index) {
            return cdemoAdminOptPgmname[index];
        }

        public void setCdemoAdminOptPgmname(int index, String source) {
            cdemoAdminOptPgmname[index] = source;
        }
    }
}
