package com.tmax.openframe.variable.group;

import com.tmax.openframe.runtime.cobol.CobStream;
import com.tmax.openframe.runtime.cobol.PictureFormatter;
import java.math.*;
import java.util.*;
import java.util.stream.*;
import lombok.*;
import org.apache.commons.lang3.StringUtils;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:18 KST</p>
 * <hr>
 * <p>Class that defines variables for COPYBOOK item</p>
 */
public @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class CardXrefRecord {
    // [T-Up#INFO][CVACT03Y.cpy:6] XREF-CARD-NUM (level: 5)
    private @Getter @Builder.Default String xrefCardNum = StringUtils.repeat(
            ' ', 16);
    // [T-Up#INFO][CVACT03Y.cpy:7] XREF-CUST-ID (level: 5)
    private @Getter @Setter int xrefCustId;
    // [T-Up#INFO][CVACT03Y.cpy:8] XREF-ACCT-ID (level: 5)
    private @Getter @Setter long xrefAcctId;
    // [T-Up#INFO][CVACT03Y.cpy:9] FILLER (level: 5)
    private @Getter @Builder.Default String FILLER_1 = StringUtils.repeat(' ',
            14);

    public static CardXrefRecord createDefaultValueInstance() {
        return new CardXrefRecord.builder().build();
    }

    public void set(String source) {
        source = StringUtils.truncate(StringUtils.rightPad(source, 50), 50);
        setXrefCardNum(source.substring(0, 16));
        try {
            setXrefCustId(CobStream.convZonedStringToInt(
                    source.substring(16, 25), 9));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setXrefCustId(0);
        }
        try {
            setXrefAcctId(CobStream.convZonedStringToLong(
                    source.substring(25, 36), 11));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setXrefAcctId(0);
        }
        setFILLER_1(source.substring(36, 50));
    }

    public String get() {
        StringBuilder sb = new StringBuilder();
        sb.append(getXrefCardNum());
        sb.append(CobStream.convZonedIntToString(getXrefCustId(), 9));
        sb.append(CobStream.convZonedLongToString(getXrefAcctId(), 11));
        sb.append(getFILLER_1());
        return sb.toString();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getXrefCardNum());
        sb.append(PictureFormatter.intFormatWithoutSign((long) getXrefCustId(),
                "000000000"));
        sb.append(PictureFormatter.intFormatWithoutSign(getXrefAcctId(),
                "00000000000"));
        sb.append(getFILLER_1());
        return sb.toString();
    }

    public void setXrefCardNum(String source) {
        xrefCardNum = StringUtils
                .truncate(StringUtils.rightPad(source, 16), 16);
    }

    public void setFILLER_1(String source) {
        FILLER_1 = StringUtils.truncate(StringUtils.rightPad(source, 14), 14);
    }
}
