package com.tmax.openframe.variable.group;

import com.tmax.openframe.runtime.cobol.CobStream;
import com.tmax.openframe.runtime.cobol.PictureFormatter;
import java.math.*;
import java.util.*;
import java.util.stream.*;
import lombok.*;
import org.apache.commons.lang3.StringUtils;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:16 KST</p>
 * <hr>
 * <p>Class that defines variables for COPYBOOK item</p>
 */
public @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class CardRecord {
    // [T-Up#INFO][CVACT02Y.cpy:6] CARD-NUM (level: 5)
    private @Getter @Builder.Default String cardNum = StringUtils.repeat(' ',
            16);
    // [T-Up#INFO][CVACT02Y.cpy:7] CARD-ACCT-ID (level: 5)
    private @Getter @Setter long cardAcctId;
    // [T-Up#INFO][CVACT02Y.cpy:8] CARD-CVV-CD (level: 5)
    private @Getter @Setter int cardCvvCd;
    // [T-Up#INFO][CVACT02Y.cpy:9] CARD-EMBOSSED-NAME (level: 5)
    private @Getter @Builder.Default String cardEmbossedName = StringUtils
            .repeat(' ', 50);
    // [T-Up#INFO][CVACT02Y.cpy:10] CARD-EXPIRAION-DATE (level: 5)
    private @Getter @Builder.Default String cardExpiraionDate = StringUtils
            .repeat(' ', 10);
    // [T-Up#INFO][CVACT02Y.cpy:11] CARD-ACTIVE-STATUS (level: 5)
    private @Getter @Builder.Default String cardActiveStatus = StringUtils
            .repeat(' ', 1);
    // [T-Up#INFO][CVACT02Y.cpy:12] FILLER (level: 5)
    private @Getter @Builder.Default String FILLER_1 = StringUtils.repeat(' ',
            59);

    public static CardRecord createDefaultValueInstance() {
        return new CardRecord.builder().build();
    }

    public void set(String source) {
        source = StringUtils.truncate(StringUtils.rightPad(source, 150), 150);
        setCardNum(source.substring(0, 16));
        try {
            setCardAcctId(CobStream.convZonedStringToLong(
                    source.substring(16, 27), 11));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setCardAcctId(0);
        }
        try {
            setCardCvvCd(CobStream.convZonedStringToInt(
                    source.substring(27, 30), 3));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setCardCvvCd(0);
        }
        setCardEmbossedName(source.substring(30, 80));
        setCardExpiraionDate(source.substring(80, 90));
        setCardActiveStatus(source.substring(90, 91));
        setFILLER_1(source.substring(91, 150));
    }

    public String get() {
        StringBuilder sb = new StringBuilder();
        sb.append(getCardNum());
        sb.append(CobStream.convZonedLongToString(getCardAcctId(), 11));
        sb.append(CobStream.convZonedIntToString(getCardCvvCd(), 3));
        sb.append(getCardEmbossedName());
        sb.append(getCardExpiraionDate());
        sb.append(getCardActiveStatus());
        sb.append(getFILLER_1());
        return sb.toString();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getCardNum());
        sb.append(PictureFormatter.intFormatWithoutSign(getCardAcctId(),
                "00000000000"));
        sb.append(PictureFormatter.intFormatWithoutSign((long) getCardCvvCd(),
                "000"));
        sb.append(getCardEmbossedName());
        sb.append(getCardExpiraionDate());
        sb.append(getCardActiveStatus());
        sb.append(getFILLER_1());
        return sb.toString();
    }

    public void setCardNum(String source) {
        cardNum = StringUtils.truncate(StringUtils.rightPad(source, 16), 16);
    }

    public void setCardEmbossedName(String source) {
        cardEmbossedName = StringUtils.truncate(
                StringUtils.rightPad(source, 50), 50);
    }

    public void setCardExpiraionDate(String source) {
        cardExpiraionDate = StringUtils.truncate(
                StringUtils.rightPad(source, 10), 10);
    }

    public void setCardActiveStatus(String source) {
        cardActiveStatus = StringUtils.truncate(
                StringUtils.rightPad(source, 1), 1);
    }

    public void setFILLER_1(String source) {
        FILLER_1 = StringUtils.truncate(StringUtils.rightPad(source, 59), 59);
    }
}
