package com.tmax.openframe.variable.group;

import com.tmax.openframe.runtime.cobol.CobStream;
import com.tmax.openframe.runtime.cobol.PictureFormatter;
import java.math.*;
import java.text.DecimalFormat;
import java.util.*;
import java.util.function.Function;
import java.util.stream.*;
import lombok.*;
import org.apache.commons.lang3.StringUtils;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:11 KST</p>
 * <hr>
 * <p>Class that defines variables for COBOL group item TRANSACTION-DETAIL-REPORT</p>
 */
public @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class Cbtrn03cTransactionDetailReport {
    // [T-Up#INFO][CVTRA07Y.cpy:17] TRAN-REPORT-TRANS-ID (level: 5)
    private @Getter @Builder.Default String tranReportTransId = StringUtils
            .repeat(' ', 16);
    // [T-Up#INFO][CVTRA07Y.cpy:18] FILLER (level: 5)
    private @Getter @Builder.Default String FILLER_1 = " ";
    // [T-Up#INFO][CVTRA07Y.cpy:19] TRAN-REPORT-ACCOUNT-ID (level: 5)
    private @Getter @Builder.Default String tranReportAccountId = StringUtils
            .repeat(' ', 11);
    // [T-Up#INFO][CVTRA07Y.cpy:20] FILLER (level: 5)
    private @Getter @Builder.Default String FILLER_2 = " ";
    // [T-Up#INFO][CVTRA07Y.cpy:21] TRAN-REPORT-TYPE-CD (level: 5)
    private @Getter @Builder.Default String tranReportTypeCd = StringUtils
            .repeat(' ', 2);
    // [T-Up#INFO][CVTRA07Y.cpy:22] FILLER (level: 5)
    private @Getter @Builder.Default String FILLER_3 = "-";
    // [T-Up#INFO][CVTRA07Y.cpy:23] TRAN-REPORT-TYPE-DESC (level: 5)
    private @Getter @Builder.Default String tranReportTypeDesc = StringUtils
            .repeat(' ', 15);
    // [T-Up#INFO][CVTRA07Y.cpy:24] FILLER (level: 5)
    private @Getter @Builder.Default String FILLER_4 = " ";
    // [T-Up#INFO][CVTRA07Y.cpy:25] TRAN-REPORT-CAT-CD (level: 5)
    private @Getter @Setter int tranReportCatCd;
    // [T-Up#INFO][CVTRA07Y.cpy:26] FILLER (level: 5)
    private @Getter @Builder.Default String FILLER_5 = "-";
    // [T-Up#INFO][CVTRA07Y.cpy:27] TRAN-REPORT-CAT-DESC (level: 5)
    private @Getter @Builder.Default String tranReportCatDesc = StringUtils
            .repeat(' ', 29);
    // [T-Up#INFO][CVTRA07Y.cpy:28] FILLER (level: 5)
    private @Getter @Builder.Default String FILLER_6 = " ";
    // [T-Up#INFO][CVTRA07Y.cpy:29] TRAN-REPORT-SOURCE (level: 5)
    private @Getter @Builder.Default String tranReportSource = StringUtils
            .repeat(' ', 10);
    // [T-Up#INFO][CVTRA07Y.cpy:30] FILLER (level: 5)
    private @Getter @Builder.Default String FILLER_7 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][CVTRA07Y.cpy:31] TRAN-REPORT-AMT (level: 5)
    private @Getter @Builder.Default String tranReportAmt = tranReportAmtFormat
            .apply(0L);
    private final static Function<Long, String> tranReportAmtFormat = (data) -> {
        DecimalFormat nf = new DecimalFormat();
        nf.setNegativePrefix("");
        nf.applyPattern(" ###,###,###.##;-###,###,###.##");
        return StringUtils.leftPad(nf.format(data), 11, ' ');
    };
    // [T-Up#INFO][CVTRA07Y.cpy:32] FILLER (level: 5)
    private @Getter @Builder.Default String FILLER_8 = StringUtils.repeat(' ',
            2);

    public static Cbtrn03cTransactionDetailReport createDefaultValueInstance() {
        return new Cbtrn03cTransactionDetailReport.builder().build();
    }

    public void set(String source) {
        source = StringUtils.truncate(StringUtils.rightPad(source, 114), 114);
        setTranReportTransId(source.substring(0, 16));
        setFILLER_1(source.substring(16, 17));
        setTranReportAccountId(source.substring(17, 28));
        setFILLER_2(source.substring(28, 29));
        setTranReportTypeCd(source.substring(29, 31));
        setFILLER_3(source.substring(31, 32));
        setTranReportTypeDesc(source.substring(32, 47));
        setFILLER_4(source.substring(47, 48));
        try {
            setTranReportCatCd(CobStream.convZonedStringToInt(
                    source.substring(48, 52), 4));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setTranReportCatCd(0);
        }
        setFILLER_5(source.substring(52, 53));
        setTranReportCatDesc(source.substring(53, 82));
        setFILLER_6(source.substring(82, 83));
        setTranReportSource(source.substring(83, 93));
        setFILLER_7(source.substring(93, 97));
        setTranReportAmt(source.substring(97, 112));
        setFILLER_8(source.substring(112, 114));
    }

    public String get() {
        StringBuilder sb = new StringBuilder();
        sb.append(getTranReportTransId());
        sb.append(getFILLER_1());
        sb.append(getTranReportAccountId());
        sb.append(getFILLER_2());
        sb.append(getTranReportTypeCd());
        sb.append(getFILLER_3());
        sb.append(getTranReportTypeDesc());
        sb.append(getFILLER_4());
        sb.append(CobStream.convZonedIntToString(getTranReportCatCd(), 4));
        sb.append(getFILLER_5());
        sb.append(getTranReportCatDesc());
        sb.append(getFILLER_6());
        sb.append(getTranReportSource());
        sb.append(getFILLER_7());
        sb.append(getTranReportAmt());
        sb.append(getFILLER_8());
        return sb.toString();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getTranReportTransId());
        sb.append(getFILLER_1());
        sb.append(getTranReportAccountId());
        sb.append(getFILLER_2());
        sb.append(getTranReportTypeCd());
        sb.append(getFILLER_3());
        sb.append(getTranReportTypeDesc());
        sb.append(getFILLER_4());
        sb.append(PictureFormatter.intFormatWithoutSign(
                (long) getTranReportCatCd(), "0000"));
        sb.append(getFILLER_5());
        sb.append(getTranReportCatDesc());
        sb.append(getFILLER_6());
        sb.append(getTranReportSource());
        sb.append(getFILLER_7());
        sb.append(getTranReportAmt());
        sb.append(getFILLER_8());
        return sb.toString();
    }

    public void setTranReportTransId(String source) {
        tranReportTransId = StringUtils.truncate(
                StringUtils.rightPad(source, 16), 16);
    }

    public void setFILLER_1(String source) {
        FILLER_1 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setTranReportAccountId(String source) {
        tranReportAccountId = StringUtils.truncate(
                StringUtils.rightPad(source, 11), 11);
    }

    public void setFILLER_2(String source) {
        FILLER_2 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setTranReportTypeCd(String source) {
        tranReportTypeCd = StringUtils.truncate(
                StringUtils.rightPad(source, 2), 2);
    }

    public void setFILLER_3(String source) {
        FILLER_3 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setTranReportTypeDesc(String source) {
        tranReportTypeDesc = StringUtils.truncate(
                StringUtils.rightPad(source, 15), 15);
    }

    public void setFILLER_4(String source) {
        FILLER_4 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setFILLER_5(String source) {
        FILLER_5 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setTranReportCatDesc(String source) {
        tranReportCatDesc = StringUtils.truncate(
                StringUtils.rightPad(source, 29), 29);
    }

    public void setFILLER_6(String source) {
        FILLER_6 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setTranReportSource(String source) {
        tranReportSource = StringUtils.truncate(
                StringUtils.rightPad(source, 10), 10);
    }

    public void setFILLER_7(String source) {
        FILLER_7 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setTranReportAmt(String source) {
        tranReportAmt = StringUtils.truncate(StringUtils.rightPad(source, 15),
                15);
    }

    public void setTranReportAmt(long source) {
        tranReportAmt = tranReportAmtFormat.apply(source);
    }

    public void setFILLER_8(String source) {
        FILLER_8 = StringUtils.truncate(StringUtils.rightPad(source, 2), 2);
    }
}
