package com.tmax.openframe.variable.group;

import com.tmax.openframe.runtime.cobol.CobStream;
import java.math.*;
import java.util.*;
import java.util.stream.*;
import lombok.*;
import org.apache.commons.lang3.StringUtils;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:16 KST</p>
 * <hr>
 * <p>Class that defines variables for COBOL group item CCRDUPAI</p>
 */
public @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class Ccrdupai {
    // [T-Up#INFO][COCRDUP.CPY:19] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_1 = StringUtils.repeat(' ',
            12);
    // [T-Up#INFO][COCRDUP.CPY:20] TRNNAMEL (level: 2)
    private @Getter @Setter int trnnamel;
    // [T-Up#INFO][COCRDUP.CPY:21] TRNNAMEF (level: 2)
    private @Getter @Builder.Default String trnnamef = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COCRDUP.CPY:24] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_2 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:25] TRNNAMEI (level: 2)
    private @Getter @Builder.Default String trnnamei = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:26] TITLE01L (level: 2)
    private @Getter @Setter int title01l;
    // [T-Up#INFO][COCRDUP.CPY:27] TITLE01F (level: 2)
    private @Getter @Builder.Default String title01f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COCRDUP.CPY:30] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_3 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:31] TITLE01I (level: 2)
    private @Getter @Builder.Default String title01i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COCRDUP.CPY:32] CURDATEL (level: 2)
    private @Getter @Setter int curdatel;
    // [T-Up#INFO][COCRDUP.CPY:33] CURDATEF (level: 2)
    private @Getter @Builder.Default String curdatef = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COCRDUP.CPY:36] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_4 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:37] CURDATEI (level: 2)
    private @Getter @Builder.Default String curdatei = StringUtils.repeat(' ',
            8);
    // [T-Up#INFO][COCRDUP.CPY:38] PGMNAMEL (level: 2)
    private @Getter @Setter int pgmnamel;
    // [T-Up#INFO][COCRDUP.CPY:39] PGMNAMEF (level: 2)
    private @Getter @Builder.Default String pgmnamef = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COCRDUP.CPY:42] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_5 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:43] PGMNAMEI (level: 2)
    private @Getter @Builder.Default String pgmnamei = StringUtils.repeat(' ',
            8);
    // [T-Up#INFO][COCRDUP.CPY:44] TITLE02L (level: 2)
    private @Getter @Setter int title02l;
    // [T-Up#INFO][COCRDUP.CPY:45] TITLE02F (level: 2)
    private @Getter @Builder.Default String title02f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COCRDUP.CPY:48] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_6 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:49] TITLE02I (level: 2)
    private @Getter @Builder.Default String title02i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COCRDUP.CPY:50] CURTIMEL (level: 2)
    private @Getter @Setter int curtimel;
    // [T-Up#INFO][COCRDUP.CPY:51] CURTIMEF (level: 2)
    private @Getter @Builder.Default String curtimef = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COCRDUP.CPY:54] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_7 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:55] CURTIMEI (level: 2)
    private @Getter @Builder.Default String curtimei = StringUtils.repeat(' ',
            8);
    // [T-Up#INFO][COCRDUP.CPY:56] ACCTSIDL (level: 2)
    private @Getter @Setter int acctsidl;
    // [T-Up#INFO][COCRDUP.CPY:57] ACCTSIDF (level: 2)
    private @Getter @Builder.Default String acctsidf = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COCRDUP.CPY:60] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_8 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:61] ACCTSIDI (level: 2)
    private @Getter @Builder.Default String acctsidi = StringUtils.repeat(' ',
            11);
    // [T-Up#INFO][COCRDUP.CPY:62] CARDSIDL (level: 2)
    private @Getter @Setter int cardsidl;
    // [T-Up#INFO][COCRDUP.CPY:63] CARDSIDF (level: 2)
    private @Getter @Builder.Default String cardsidf = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COCRDUP.CPY:66] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_9 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:67] CARDSIDI (level: 2)
    private @Getter @Builder.Default String cardsidi = StringUtils.repeat(' ',
            16);
    // [T-Up#INFO][COCRDUP.CPY:68] CRDNAMEL (level: 2)
    private @Getter @Setter int crdnamel;
    // [T-Up#INFO][COCRDUP.CPY:69] CRDNAMEF (level: 2)
    private @Getter @Builder.Default String crdnamef = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COCRDUP.CPY:72] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_10 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:73] CRDNAMEI (level: 2)
    private @Getter @Builder.Default String crdnamei = StringUtils.repeat(' ',
            50);
    // [T-Up#INFO][COCRDUP.CPY:74] CRDSTCDL (level: 2)
    private @Getter @Setter int crdstcdl;
    // [T-Up#INFO][COCRDUP.CPY:75] CRDSTCDF (level: 2)
    private @Getter @Builder.Default String crdstcdf = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COCRDUP.CPY:78] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_11 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:79] CRDSTCDI (level: 2)
    private @Getter @Builder.Default String crdstcdi = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COCRDUP.CPY:80] EXPMONL (level: 2)
    private @Getter @Setter int expmonl;
    // [T-Up#INFO][COCRDUP.CPY:81] EXPMONF (level: 2)
    private @Getter @Builder.Default String expmonf = StringUtils
            .repeat(' ', 1);
    // [T-Up#INFO][COCRDUP.CPY:84] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_12 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:85] EXPMONI (level: 2)
    private @Getter @Builder.Default String expmoni = StringUtils
            .repeat(' ', 2);
    // [T-Up#INFO][COCRDUP.CPY:86] EXPYEARL (level: 2)
    private @Getter @Setter int expyearl;
    // [T-Up#INFO][COCRDUP.CPY:87] EXPYEARF (level: 2)
    private @Getter @Builder.Default String expyearf = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COCRDUP.CPY:90] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_13 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:91] EXPYEARI (level: 2)
    private @Getter @Builder.Default String expyeari = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:92] EXPDAYL (level: 2)
    private @Getter @Setter int expdayl;
    // [T-Up#INFO][COCRDUP.CPY:93] EXPDAYF (level: 2)
    private @Getter @Builder.Default String expdayf = StringUtils
            .repeat(' ', 1);
    // [T-Up#INFO][COCRDUP.CPY:96] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_14 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:97] EXPDAYI (level: 2)
    private @Getter @Builder.Default String expdayi = StringUtils
            .repeat(' ', 2);
    // [T-Up#INFO][COCRDUP.CPY:98] INFOMSGL (level: 2)
    private @Getter @Setter int infomsgl;
    // [T-Up#INFO][COCRDUP.CPY:99] INFOMSGF (level: 2)
    private @Getter @Builder.Default String infomsgf = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COCRDUP.CPY:102] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_15 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:103] INFOMSGI (level: 2)
    private @Getter @Builder.Default String infomsgi = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COCRDUP.CPY:104] ERRMSGL (level: 2)
    private @Getter @Setter int errmsgl;
    // [T-Up#INFO][COCRDUP.CPY:105] ERRMSGF (level: 2)
    private @Getter @Builder.Default String errmsgf = StringUtils
            .repeat(' ', 1);
    // [T-Up#INFO][COCRDUP.CPY:108] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_16 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:109] ERRMSGI (level: 2)
    private @Getter @Builder.Default String errmsgi = StringUtils.repeat(' ',
            80);
    // [T-Up#INFO][COCRDUP.CPY:110] FKEYSL (level: 2)
    private @Getter @Setter int fkeysl;
    // [T-Up#INFO][COCRDUP.CPY:111] FKEYSF (level: 2)
    private @Getter @Builder.Default String fkeysf = StringUtils.repeat(' ', 1);
    // [T-Up#INFO][COCRDUP.CPY:114] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_17 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:115] FKEYSI (level: 2)
    private @Getter @Builder.Default String fkeysi = StringUtils
            .repeat(' ', 21);
    // [T-Up#INFO][COCRDUP.CPY:116] FKEYSCL (level: 2)
    private @Getter @Setter int fkeyscl;
    // [T-Up#INFO][COCRDUP.CPY:117] FKEYSCF (level: 2)
    private @Getter @Builder.Default String fkeyscf = StringUtils
            .repeat(' ', 1);
    // [T-Up#INFO][COCRDUP.CPY:120] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_18 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COCRDUP.CPY:121] FKEYSCI (level: 2)
    private @Getter @Builder.Default String fkeysci = StringUtils.repeat(' ',
            18);

    public static Ccrdupai createDefaultValueInstance() {
        return new Ccrdupai.builder().build();
    }

    public void set(String source) {
        source = StringUtils.truncate(StringUtils.rightPad(source, 484), 484);
        setFILLER_1(source.substring(0, 12));
        try {
            setTrnnamel(CobStream.convStringToShort(source.substring(12, 14)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setTrnnamel(0);
        }
        setTrnnamef(source.substring(14, 15));
        setFILLER_2(source.substring(15, 19));
        setTrnnamei(source.substring(19, 23));
        try {
            setTitle01l(CobStream.convStringToShort(source.substring(23, 25)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setTitle01l(0);
        }
        setTitle01f(source.substring(25, 26));
        setFILLER_3(source.substring(26, 30));
        setTitle01i(source.substring(30, 70));
        try {
            setCurdatel(CobStream.convStringToShort(source.substring(70, 72)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setCurdatel(0);
        }
        setCurdatef(source.substring(72, 73));
        setFILLER_4(source.substring(73, 77));
        setCurdatei(source.substring(77, 85));
        try {
            setPgmnamel(CobStream.convStringToShort(source.substring(85, 87)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setPgmnamel(0);
        }
        setPgmnamef(source.substring(87, 88));
        setFILLER_5(source.substring(88, 92));
        setPgmnamei(source.substring(92, 100));
        try {
            setTitle02l(CobStream.convStringToShort(source.substring(100, 102)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setTitle02l(0);
        }
        setTitle02f(source.substring(102, 103));
        setFILLER_6(source.substring(103, 107));
        setTitle02i(source.substring(107, 147));
        try {
            setCurtimel(CobStream.convStringToShort(source.substring(147, 149)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setCurtimel(0);
        }
        setCurtimef(source.substring(149, 150));
        setFILLER_7(source.substring(150, 154));
        setCurtimei(source.substring(154, 162));
        try {
            setAcctsidl(CobStream.convStringToShort(source.substring(162, 164)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setAcctsidl(0);
        }
        setAcctsidf(source.substring(164, 165));
        setFILLER_8(source.substring(165, 169));
        setAcctsidi(source.substring(169, 180));
        try {
            setCardsidl(CobStream.convStringToShort(source.substring(180, 182)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setCardsidl(0);
        }
        setCardsidf(source.substring(182, 183));
        setFILLER_9(source.substring(183, 187));
        setCardsidi(source.substring(187, 203));
        try {
            setCrdnamel(CobStream.convStringToShort(source.substring(203, 205)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setCrdnamel(0);
        }
        setCrdnamef(source.substring(205, 206));
        setFILLER_10(source.substring(206, 210));
        setCrdnamei(source.substring(210, 260));
        try {
            setCrdstcdl(CobStream.convStringToShort(source.substring(260, 262)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setCrdstcdl(0);
        }
        setCrdstcdf(source.substring(262, 263));
        setFILLER_11(source.substring(263, 267));
        setCrdstcdi(source.substring(267, 268));
        try {
            setExpmonl(CobStream.convStringToShort(source.substring(268, 270)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setExpmonl(0);
        }
        setExpmonf(source.substring(270, 271));
        setFILLER_12(source.substring(271, 275));
        setExpmoni(source.substring(275, 277));
        try {
            setExpyearl(CobStream.convStringToShort(source.substring(277, 279)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setExpyearl(0);
        }
        setExpyearf(source.substring(279, 280));
        setFILLER_13(source.substring(280, 284));
        setExpyeari(source.substring(284, 288));
        try {
            setExpdayl(CobStream.convStringToShort(source.substring(288, 290)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setExpdayl(0);
        }
        setExpdayf(source.substring(290, 291));
        setFILLER_14(source.substring(291, 295));
        setExpdayi(source.substring(295, 297));
        try {
            setInfomsgl(CobStream.convStringToShort(source.substring(297, 299)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setInfomsgl(0);
        }
        setInfomsgf(source.substring(299, 300));
        setFILLER_15(source.substring(300, 304));
        setInfomsgi(source.substring(304, 344));
        try {
            setErrmsgl(CobStream.convStringToShort(source.substring(344, 346)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setErrmsgl(0);
        }
        setErrmsgf(source.substring(346, 347));
        setFILLER_16(source.substring(347, 351));
        setErrmsgi(source.substring(351, 431));
        try {
            setFkeysl(CobStream.convStringToShort(source.substring(431, 433)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setFkeysl(0);
        }
        setFkeysf(source.substring(433, 434));
        setFILLER_17(source.substring(434, 438));
        setFkeysi(source.substring(438, 459));
        try {
            setFkeyscl(CobStream.convStringToShort(source.substring(459, 461)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setFkeyscl(0);
        }
        setFkeyscf(source.substring(461, 462));
        setFILLER_18(source.substring(462, 466));
        setFkeysci(source.substring(466, 484));
    }

    public String get() {
        StringBuilder sb = new StringBuilder();
        sb.append(getFILLER_1());
        sb.append(CobStream.convShortToString((short) getTrnnamel()));
        sb.append(getTrnnamef());
        sb.append(getFILLER_2());
        sb.append(getTrnnamei());
        sb.append(CobStream.convShortToString((short) getTitle01l()));
        sb.append(getTitle01f());
        sb.append(getFILLER_3());
        sb.append(getTitle01i());
        sb.append(CobStream.convShortToString((short) getCurdatel()));
        sb.append(getCurdatef());
        sb.append(getFILLER_4());
        sb.append(getCurdatei());
        sb.append(CobStream.convShortToString((short) getPgmnamel()));
        sb.append(getPgmnamef());
        sb.append(getFILLER_5());
        sb.append(getPgmnamei());
        sb.append(CobStream.convShortToString((short) getTitle02l()));
        sb.append(getTitle02f());
        sb.append(getFILLER_6());
        sb.append(getTitle02i());
        sb.append(CobStream.convShortToString((short) getCurtimel()));
        sb.append(getCurtimef());
        sb.append(getFILLER_7());
        sb.append(getCurtimei());
        sb.append(CobStream.convShortToString((short) getAcctsidl()));
        sb.append(getAcctsidf());
        sb.append(getFILLER_8());
        sb.append(getAcctsidi());
        sb.append(CobStream.convShortToString((short) getCardsidl()));
        sb.append(getCardsidf());
        sb.append(getFILLER_9());
        sb.append(getCardsidi());
        sb.append(CobStream.convShortToString((short) getCrdnamel()));
        sb.append(getCrdnamef());
        sb.append(getFILLER_10());
        sb.append(getCrdnamei());
        sb.append(CobStream.convShortToString((short) getCrdstcdl()));
        sb.append(getCrdstcdf());
        sb.append(getFILLER_11());
        sb.append(getCrdstcdi());
        sb.append(CobStream.convShortToString((short) getExpmonl()));
        sb.append(getExpmonf());
        sb.append(getFILLER_12());
        sb.append(getExpmoni());
        sb.append(CobStream.convShortToString((short) getExpyearl()));
        sb.append(getExpyearf());
        sb.append(getFILLER_13());
        sb.append(getExpyeari());
        sb.append(CobStream.convShortToString((short) getExpdayl()));
        sb.append(getExpdayf());
        sb.append(getFILLER_14());
        sb.append(getExpdayi());
        sb.append(CobStream.convShortToString((short) getInfomsgl()));
        sb.append(getInfomsgf());
        sb.append(getFILLER_15());
        sb.append(getInfomsgi());
        sb.append(CobStream.convShortToString((short) getErrmsgl()));
        sb.append(getErrmsgf());
        sb.append(getFILLER_16());
        sb.append(getErrmsgi());
        sb.append(CobStream.convShortToString((short) getFkeysl()));
        sb.append(getFkeysf());
        sb.append(getFILLER_17());
        sb.append(getFkeysi());
        sb.append(CobStream.convShortToString((short) getFkeyscl()));
        sb.append(getFkeyscf());
        sb.append(getFILLER_18());
        sb.append(getFkeysci());
        return sb.toString();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getFILLER_1());
        sb.append(String.valueOf(getTrnnamel()));
        sb.append(getTrnnamef());
        sb.append(getFILLER_2());
        sb.append(getTrnnamei());
        sb.append(String.valueOf(getTitle01l()));
        sb.append(getTitle01f());
        sb.append(getFILLER_3());
        sb.append(getTitle01i());
        sb.append(String.valueOf(getCurdatel()));
        sb.append(getCurdatef());
        sb.append(getFILLER_4());
        sb.append(getCurdatei());
        sb.append(String.valueOf(getPgmnamel()));
        sb.append(getPgmnamef());
        sb.append(getFILLER_5());
        sb.append(getPgmnamei());
        sb.append(String.valueOf(getTitle02l()));
        sb.append(getTitle02f());
        sb.append(getFILLER_6());
        sb.append(getTitle02i());
        sb.append(String.valueOf(getCurtimel()));
        sb.append(getCurtimef());
        sb.append(getFILLER_7());
        sb.append(getCurtimei());
        sb.append(String.valueOf(getAcctsidl()));
        sb.append(getAcctsidf());
        sb.append(getFILLER_8());
        sb.append(getAcctsidi());
        sb.append(String.valueOf(getCardsidl()));
        sb.append(getCardsidf());
        sb.append(getFILLER_9());
        sb.append(getCardsidi());
        sb.append(String.valueOf(getCrdnamel()));
        sb.append(getCrdnamef());
        sb.append(getFILLER_10());
        sb.append(getCrdnamei());
        sb.append(String.valueOf(getCrdstcdl()));
        sb.append(getCrdstcdf());
        sb.append(getFILLER_11());
        sb.append(getCrdstcdi());
        sb.append(String.valueOf(getExpmonl()));
        sb.append(getExpmonf());
        sb.append(getFILLER_12());
        sb.append(getExpmoni());
        sb.append(String.valueOf(getExpyearl()));
        sb.append(getExpyearf());
        sb.append(getFILLER_13());
        sb.append(getExpyeari());
        sb.append(String.valueOf(getExpdayl()));
        sb.append(getExpdayf());
        sb.append(getFILLER_14());
        sb.append(getExpdayi());
        sb.append(String.valueOf(getInfomsgl()));
        sb.append(getInfomsgf());
        sb.append(getFILLER_15());
        sb.append(getInfomsgi());
        sb.append(String.valueOf(getErrmsgl()));
        sb.append(getErrmsgf());
        sb.append(getFILLER_16());
        sb.append(getErrmsgi());
        sb.append(String.valueOf(getFkeysl()));
        sb.append(getFkeysf());
        sb.append(getFILLER_17());
        sb.append(getFkeysi());
        sb.append(String.valueOf(getFkeyscl()));
        sb.append(getFkeyscf());
        sb.append(getFILLER_18());
        sb.append(getFkeysci());
        return sb.toString();
    }

    public void setFILLER_1(String source) {
        FILLER_1 = StringUtils.truncate(StringUtils.rightPad(source, 12), 12);
    }

    public void setTrnnamef(String source) {
        trnnamef = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_10 getFILLER_REDEFINE_10() {
        return _FILLER_REDEFINE_10.builder().trnnamea(getTrnnamea()).build();
    }

    public void setFILLER_REDEFINE_10(String source) {
        setTrnnamea(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_10(_FILLER_REDEFINE_10 source) {
        setFILLER_REDEFINE_10(source.get());
    }

    public String getTrnnamea() {
        return getTrnnamef();
    }

    public void setTrnnamea(String source) {
        setTrnnamef(source);
    }

    public void setFILLER_2(String source) {
        FILLER_2 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setTrnnamei(String source) {
        trnnamei = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setTitle01f(String source) {
        title01f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_12 getFILLER_REDEFINE_12() {
        return _FILLER_REDEFINE_12.builder().title01a(getTitle01a()).build();
    }

    public void setFILLER_REDEFINE_12(String source) {
        setTitle01a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_12(_FILLER_REDEFINE_12 source) {
        setFILLER_REDEFINE_12(source.get());
    }

    public String getTitle01a() {
        return getTitle01f();
    }

    public void setTitle01a(String source) {
        setTitle01f(source);
    }

    public void setFILLER_3(String source) {
        FILLER_3 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setTitle01i(String source) {
        title01i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setCurdatef(String source) {
        curdatef = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_14 getFILLER_REDEFINE_14() {
        return _FILLER_REDEFINE_14.builder().curdatea(getCurdatea()).build();
    }

    public void setFILLER_REDEFINE_14(String source) {
        setCurdatea(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_14(_FILLER_REDEFINE_14 source) {
        setFILLER_REDEFINE_14(source.get());
    }

    public String getCurdatea() {
        return getCurdatef();
    }

    public void setCurdatea(String source) {
        setCurdatef(source);
    }

    public void setFILLER_4(String source) {
        FILLER_4 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setCurdatei(String source) {
        curdatei = StringUtils.truncate(StringUtils.rightPad(source, 8), 8);
    }

    public void setPgmnamef(String source) {
        pgmnamef = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_16 getFILLER_REDEFINE_16() {
        return _FILLER_REDEFINE_16.builder().pgmnamea(getPgmnamea()).build();
    }

    public void setFILLER_REDEFINE_16(String source) {
        setPgmnamea(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_16(_FILLER_REDEFINE_16 source) {
        setFILLER_REDEFINE_16(source.get());
    }

    public String getPgmnamea() {
        return getPgmnamef();
    }

    public void setPgmnamea(String source) {
        setPgmnamef(source);
    }

    public void setFILLER_5(String source) {
        FILLER_5 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setPgmnamei(String source) {
        pgmnamei = StringUtils.truncate(StringUtils.rightPad(source, 8), 8);
    }

    public void setTitle02f(String source) {
        title02f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_18 getFILLER_REDEFINE_18() {
        return _FILLER_REDEFINE_18.builder().title02a(getTitle02a()).build();
    }

    public void setFILLER_REDEFINE_18(String source) {
        setTitle02a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_18(_FILLER_REDEFINE_18 source) {
        setFILLER_REDEFINE_18(source.get());
    }

    public String getTitle02a() {
        return getTitle02f();
    }

    public void setTitle02a(String source) {
        setTitle02f(source);
    }

    public void setFILLER_6(String source) {
        FILLER_6 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setTitle02i(String source) {
        title02i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setCurtimef(String source) {
        curtimef = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_20 getFILLER_REDEFINE_20() {
        return _FILLER_REDEFINE_20.builder().curtimea(getCurtimea()).build();
    }

    public void setFILLER_REDEFINE_20(String source) {
        setCurtimea(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_20(_FILLER_REDEFINE_20 source) {
        setFILLER_REDEFINE_20(source.get());
    }

    public String getCurtimea() {
        return getCurtimef();
    }

    public void setCurtimea(String source) {
        setCurtimef(source);
    }

    public void setFILLER_7(String source) {
        FILLER_7 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setCurtimei(String source) {
        curtimei = StringUtils.truncate(StringUtils.rightPad(source, 8), 8);
    }

    public void setAcctsidf(String source) {
        acctsidf = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_22 getFILLER_REDEFINE_22() {
        return _FILLER_REDEFINE_22.builder().acctsida(getAcctsida()).build();
    }

    public void setFILLER_REDEFINE_22(String source) {
        setAcctsida(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_22(_FILLER_REDEFINE_22 source) {
        setFILLER_REDEFINE_22(source.get());
    }

    public String getAcctsida() {
        return getAcctsidf();
    }

    public void setAcctsida(String source) {
        setAcctsidf(source);
    }

    public void setFILLER_8(String source) {
        FILLER_8 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setAcctsidi(String source) {
        acctsidi = StringUtils.truncate(StringUtils.rightPad(source, 11), 11);
    }

    public void setCardsidf(String source) {
        cardsidf = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_24 getFILLER_REDEFINE_24() {
        return _FILLER_REDEFINE_24.builder().cardsida(getCardsida()).build();
    }

    public void setFILLER_REDEFINE_24(String source) {
        setCardsida(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_24(_FILLER_REDEFINE_24 source) {
        setFILLER_REDEFINE_24(source.get());
    }

    public String getCardsida() {
        return getCardsidf();
    }

    public void setCardsida(String source) {
        setCardsidf(source);
    }

    public void setFILLER_9(String source) {
        FILLER_9 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setCardsidi(String source) {
        cardsidi = StringUtils.truncate(StringUtils.rightPad(source, 16), 16);
    }

    public void setCrdnamef(String source) {
        crdnamef = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_26 getFILLER_REDEFINE_26() {
        return _FILLER_REDEFINE_26.builder().crdnamea(getCrdnamea()).build();
    }

    public void setFILLER_REDEFINE_26(String source) {
        setCrdnamea(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_26(_FILLER_REDEFINE_26 source) {
        setFILLER_REDEFINE_26(source.get());
    }

    public String getCrdnamea() {
        return getCrdnamef();
    }

    public void setCrdnamea(String source) {
        setCrdnamef(source);
    }

    public void setFILLER_10(String source) {
        FILLER_10 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setCrdnamei(String source) {
        crdnamei = StringUtils.truncate(StringUtils.rightPad(source, 50), 50);
    }

    public void setCrdstcdf(String source) {
        crdstcdf = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_28 getFILLER_REDEFINE_28() {
        return _FILLER_REDEFINE_28.builder().crdstcda(getCrdstcda()).build();
    }

    public void setFILLER_REDEFINE_28(String source) {
        setCrdstcda(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_28(_FILLER_REDEFINE_28 source) {
        setFILLER_REDEFINE_28(source.get());
    }

    public String getCrdstcda() {
        return getCrdstcdf();
    }

    public void setCrdstcda(String source) {
        setCrdstcdf(source);
    }

    public void setFILLER_11(String source) {
        FILLER_11 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setCrdstcdi(String source) {
        crdstcdi = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setExpmonf(String source) {
        expmonf = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_30 getFILLER_REDEFINE_30() {
        return _FILLER_REDEFINE_30.builder().expmona(getExpmona()).build();
    }

    public void setFILLER_REDEFINE_30(String source) {
        setExpmona(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_30(_FILLER_REDEFINE_30 source) {
        setFILLER_REDEFINE_30(source.get());
    }

    public String getExpmona() {
        return getExpmonf();
    }

    public void setExpmona(String source) {
        setExpmonf(source);
    }

    public void setFILLER_12(String source) {
        FILLER_12 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setExpmoni(String source) {
        expmoni = StringUtils.truncate(StringUtils.rightPad(source, 2), 2);
    }

    public void setExpyearf(String source) {
        expyearf = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_32 getFILLER_REDEFINE_32() {
        return _FILLER_REDEFINE_32.builder().expyeara(getExpyeara()).build();
    }

    public void setFILLER_REDEFINE_32(String source) {
        setExpyeara(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_32(_FILLER_REDEFINE_32 source) {
        setFILLER_REDEFINE_32(source.get());
    }

    public String getExpyeara() {
        return getExpyearf();
    }

    public void setExpyeara(String source) {
        setExpyearf(source);
    }

    public void setFILLER_13(String source) {
        FILLER_13 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setExpyeari(String source) {
        expyeari = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setExpdayf(String source) {
        expdayf = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_34 getFILLER_REDEFINE_34() {
        return _FILLER_REDEFINE_34.builder().expdaya(getExpdaya()).build();
    }

    public void setFILLER_REDEFINE_34(String source) {
        setExpdaya(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_34(_FILLER_REDEFINE_34 source) {
        setFILLER_REDEFINE_34(source.get());
    }

    public String getExpdaya() {
        return getExpdayf();
    }

    public void setExpdaya(String source) {
        setExpdayf(source);
    }

    public void setFILLER_14(String source) {
        FILLER_14 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setExpdayi(String source) {
        expdayi = StringUtils.truncate(StringUtils.rightPad(source, 2), 2);
    }

    public void setInfomsgf(String source) {
        infomsgf = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_36 getFILLER_REDEFINE_36() {
        return _FILLER_REDEFINE_36.builder().infomsga(getInfomsga()).build();
    }

    public void setFILLER_REDEFINE_36(String source) {
        setInfomsga(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_36(_FILLER_REDEFINE_36 source) {
        setFILLER_REDEFINE_36(source.get());
    }

    public String getInfomsga() {
        return getInfomsgf();
    }

    public void setInfomsga(String source) {
        setInfomsgf(source);
    }

    public void setFILLER_15(String source) {
        FILLER_15 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setInfomsgi(String source) {
        infomsgi = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setErrmsgf(String source) {
        errmsgf = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_38 getFILLER_REDEFINE_38() {
        return _FILLER_REDEFINE_38.builder().errmsga(getErrmsga()).build();
    }

    public void setFILLER_REDEFINE_38(String source) {
        setErrmsga(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_38(_FILLER_REDEFINE_38 source) {
        setFILLER_REDEFINE_38(source.get());
    }

    public String getErrmsga() {
        return getErrmsgf();
    }

    public void setErrmsga(String source) {
        setErrmsgf(source);
    }

    public void setFILLER_16(String source) {
        FILLER_16 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setErrmsgi(String source) {
        errmsgi = StringUtils.truncate(StringUtils.rightPad(source, 80), 80);
    }

    public void setFkeysf(String source) {
        fkeysf = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_40 getFILLER_REDEFINE_40() {
        return _FILLER_REDEFINE_40.builder().fkeysa(getFkeysa()).build();
    }

    public void setFILLER_REDEFINE_40(String source) {
        setFkeysa(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_40(_FILLER_REDEFINE_40 source) {
        setFILLER_REDEFINE_40(source.get());
    }

    public String getFkeysa() {
        return getFkeysf();
    }

    public void setFkeysa(String source) {
        setFkeysf(source);
    }

    public void setFILLER_17(String source) {
        FILLER_17 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setFkeysi(String source) {
        fkeysi = StringUtils.truncate(StringUtils.rightPad(source, 21), 21);
    }

    public void setFkeyscf(String source) {
        fkeyscf = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_42 getFILLER_REDEFINE_42() {
        return _FILLER_REDEFINE_42.builder().fkeysca(getFkeysca()).build();
    }

    public void setFILLER_REDEFINE_42(String source) {
        setFkeysca(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_42(_FILLER_REDEFINE_42 source) {
        setFILLER_REDEFINE_42(source.get());
    }

    public String getFkeysca() {
        return getFkeyscf();
    }

    public void setFkeysca(String source) {
        setFkeyscf(source);
    }

    public void setFILLER_18(String source) {
        FILLER_18 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setFkeysci(String source) {
        fkeysci = StringUtils.truncate(StringUtils.rightPad(source, 18), 18);
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_10 {
        // [T-Up#INFO][COCRDUP.CPY:23] TRNNAMEA (level: 3)
        private @Getter @Builder.Default String trnnamea = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(trnnamea);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getTrnnamea());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_12 {
        // [T-Up#INFO][COCRDUP.CPY:29] TITLE01A (level: 3)
        private @Getter @Builder.Default String title01a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(title01a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getTitle01a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_14 {
        // [T-Up#INFO][COCRDUP.CPY:35] CURDATEA (level: 3)
        private @Getter @Builder.Default String curdatea = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(curdatea);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getCurdatea());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_16 {
        // [T-Up#INFO][COCRDUP.CPY:41] PGMNAMEA (level: 3)
        private @Getter @Builder.Default String pgmnamea = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(pgmnamea);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getPgmnamea());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_18 {
        // [T-Up#INFO][COCRDUP.CPY:47] TITLE02A (level: 3)
        private @Getter @Builder.Default String title02a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(title02a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getTitle02a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_20 {
        // [T-Up#INFO][COCRDUP.CPY:53] CURTIMEA (level: 3)
        private @Getter @Builder.Default String curtimea = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(curtimea);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getCurtimea());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_22 {
        // [T-Up#INFO][COCRDUP.CPY:59] ACCTSIDA (level: 3)
        private @Getter @Builder.Default String acctsida = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(acctsida);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getAcctsida());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_24 {
        // [T-Up#INFO][COCRDUP.CPY:65] CARDSIDA (level: 3)
        private @Getter @Builder.Default String cardsida = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(cardsida);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getCardsida());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_26 {
        // [T-Up#INFO][COCRDUP.CPY:71] CRDNAMEA (level: 3)
        private @Getter @Builder.Default String crdnamea = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(crdnamea);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getCrdnamea());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_28 {
        // [T-Up#INFO][COCRDUP.CPY:77] CRDSTCDA (level: 3)
        private @Getter @Builder.Default String crdstcda = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(crdstcda);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getCrdstcda());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_30 {
        // [T-Up#INFO][COCRDUP.CPY:83] EXPMONA (level: 3)
        private @Getter @Builder.Default String expmona = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(expmona);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getExpmona());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_32 {
        // [T-Up#INFO][COCRDUP.CPY:89] EXPYEARA (level: 3)
        private @Getter @Builder.Default String expyeara = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(expyeara);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getExpyeara());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_34 {
        // [T-Up#INFO][COCRDUP.CPY:95] EXPDAYA (level: 3)
        private @Getter @Builder.Default String expdaya = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(expdaya);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getExpdaya());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_36 {
        // [T-Up#INFO][COCRDUP.CPY:101] INFOMSGA (level: 3)
        private @Getter @Builder.Default String infomsga = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(infomsga);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getInfomsga());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_38 {
        // [T-Up#INFO][COCRDUP.CPY:107] ERRMSGA (level: 3)
        private @Getter @Builder.Default String errmsga = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(errmsga);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getErrmsga());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_40 {
        // [T-Up#INFO][COCRDUP.CPY:113] FKEYSA (level: 3)
        private @Getter @Builder.Default String fkeysa = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(fkeysa);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getFkeysa());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_42 {
        // [T-Up#INFO][COCRDUP.CPY:119] FKEYSCA (level: 3)
        private @Getter @Builder.Default String fkeysca = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(fkeysca);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getFkeysca());
            return sb.toString();
        }
    }
}
