package com.tmax.openframe.variable.group;

import com.tmax.openframe.runtime.cobol.CobStream;
import java.math.*;
import java.util.*;
import java.util.stream.*;
import lombok.*;
import org.apache.commons.lang3.StringUtils;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:17 KST</p>
 * <hr>
 * <p>Class that defines variables for COBOL group item COMEN1AI</p>
 */
public @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class Comen1ai {
    // [T-Up#INFO][COMEN01.CPY:19] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_1 = StringUtils.repeat(' ',
            12);
    // [T-Up#INFO][COMEN01.CPY:20] TRNNAMEL (level: 2)
    private @Getter @Setter int trnnamel;
    // [T-Up#INFO][COMEN01.CPY:21] TRNNAMEF (level: 2)
    private @Getter @Builder.Default String trnnamef = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:24] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_2 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:25] TRNNAMEI (level: 2)
    private @Getter @Builder.Default String trnnamei = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:26] TITLE01L (level: 2)
    private @Getter @Setter int title01l;
    // [T-Up#INFO][COMEN01.CPY:27] TITLE01F (level: 2)
    private @Getter @Builder.Default String title01f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:30] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_3 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:31] TITLE01I (level: 2)
    private @Getter @Builder.Default String title01i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY:32] CURDATEL (level: 2)
    private @Getter @Setter int curdatel;
    // [T-Up#INFO][COMEN01.CPY:33] CURDATEF (level: 2)
    private @Getter @Builder.Default String curdatef = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:36] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_4 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:37] CURDATEI (level: 2)
    private @Getter @Builder.Default String curdatei = StringUtils.repeat(' ',
            8);
    // [T-Up#INFO][COMEN01.CPY:38] PGMNAMEL (level: 2)
    private @Getter @Setter int pgmnamel;
    // [T-Up#INFO][COMEN01.CPY:39] PGMNAMEF (level: 2)
    private @Getter @Builder.Default String pgmnamef = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:42] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_5 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:43] PGMNAMEI (level: 2)
    private @Getter @Builder.Default String pgmnamei = StringUtils.repeat(' ',
            8);
    // [T-Up#INFO][COMEN01.CPY:44] TITLE02L (level: 2)
    private @Getter @Setter int title02l;
    // [T-Up#INFO][COMEN01.CPY:45] TITLE02F (level: 2)
    private @Getter @Builder.Default String title02f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:48] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_6 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:49] TITLE02I (level: 2)
    private @Getter @Builder.Default String title02i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY:50] CURTIMEL (level: 2)
    private @Getter @Setter int curtimel;
    // [T-Up#INFO][COMEN01.CPY:51] CURTIMEF (level: 2)
    private @Getter @Builder.Default String curtimef = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:54] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_7 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:55] CURTIMEI (level: 2)
    private @Getter @Builder.Default String curtimei = StringUtils.repeat(' ',
            8);
    // [T-Up#INFO][COMEN01.CPY:56] OPTN001L (level: 2)
    private @Getter @Setter int optn001l;
    // [T-Up#INFO][COMEN01.CPY:57] OPTN001F (level: 2)
    private @Getter @Builder.Default String optn001f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:60] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_8 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:61] OPTN001I (level: 2)
    private @Getter @Builder.Default String optn001i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY:62] OPTN002L (level: 2)
    private @Getter @Setter int optn002l;
    // [T-Up#INFO][COMEN01.CPY:63] OPTN002F (level: 2)
    private @Getter @Builder.Default String optn002f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:66] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_9 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:67] OPTN002I (level: 2)
    private @Getter @Builder.Default String optn002i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY:68] OPTN003L (level: 2)
    private @Getter @Setter int optn003l;
    // [T-Up#INFO][COMEN01.CPY:69] OPTN003F (level: 2)
    private @Getter @Builder.Default String optn003f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:72] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_10 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:73] OPTN003I (level: 2)
    private @Getter @Builder.Default String optn003i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY:74] OPTN004L (level: 2)
    private @Getter @Setter int optn004l;
    // [T-Up#INFO][COMEN01.CPY:75] OPTN004F (level: 2)
    private @Getter @Builder.Default String optn004f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:78] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_11 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:79] OPTN004I (level: 2)
    private @Getter @Builder.Default String optn004i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY:80] OPTN005L (level: 2)
    private @Getter @Setter int optn005l;
    // [T-Up#INFO][COMEN01.CPY:81] OPTN005F (level: 2)
    private @Getter @Builder.Default String optn005f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:84] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_12 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:85] OPTN005I (level: 2)
    private @Getter @Builder.Default String optn005i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY:86] OPTN006L (level: 2)
    private @Getter @Setter int optn006l;
    // [T-Up#INFO][COMEN01.CPY:87] OPTN006F (level: 2)
    private @Getter @Builder.Default String optn006f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:90] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_13 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:91] OPTN006I (level: 2)
    private @Getter @Builder.Default String optn006i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY:92] OPTN007L (level: 2)
    private @Getter @Setter int optn007l;
    // [T-Up#INFO][COMEN01.CPY:93] OPTN007F (level: 2)
    private @Getter @Builder.Default String optn007f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:96] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_14 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:97] OPTN007I (level: 2)
    private @Getter @Builder.Default String optn007i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY:98] OPTN008L (level: 2)
    private @Getter @Setter int optn008l;
    // [T-Up#INFO][COMEN01.CPY:99] OPTN008F (level: 2)
    private @Getter @Builder.Default String optn008f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:102] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_15 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:103] OPTN008I (level: 2)
    private @Getter @Builder.Default String optn008i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY:104] OPTN009L (level: 2)
    private @Getter @Setter int optn009l;
    // [T-Up#INFO][COMEN01.CPY:105] OPTN009F (level: 2)
    private @Getter @Builder.Default String optn009f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:108] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_16 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:109] OPTN009I (level: 2)
    private @Getter @Builder.Default String optn009i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY:110] OPTN010L (level: 2)
    private @Getter @Setter int optn010l;
    // [T-Up#INFO][COMEN01.CPY:111] OPTN010F (level: 2)
    private @Getter @Builder.Default String optn010f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:114] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_17 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:115] OPTN010I (level: 2)
    private @Getter @Builder.Default String optn010i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY:116] OPTN011L (level: 2)
    private @Getter @Setter int optn011l;
    // [T-Up#INFO][COMEN01.CPY:117] OPTN011F (level: 2)
    private @Getter @Builder.Default String optn011f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:120] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_18 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:121] OPTN011I (level: 2)
    private @Getter @Builder.Default String optn011i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY:122] OPTN012L (level: 2)
    private @Getter @Setter int optn012l;
    // [T-Up#INFO][COMEN01.CPY:123] OPTN012F (level: 2)
    private @Getter @Builder.Default String optn012f = StringUtils.repeat(' ',
            1);
    // [T-Up#INFO][COMEN01.CPY:126] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_19 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:127] OPTN012I (level: 2)
    private @Getter @Builder.Default String optn012i = StringUtils.repeat(' ',
            40);
    // [T-Up#INFO][COMEN01.CPY:128] OPTIONL (level: 2)
    private @Getter @Setter int optionl;
    // [T-Up#INFO][COMEN01.CPY:129] OPTIONF (level: 2)
    private @Getter @Builder.Default String optionf = StringUtils
            .repeat(' ', 1);
    // [T-Up#INFO][COMEN01.CPY:132] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_20 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:133] OPTIONI (level: 2)
    private @Getter @Builder.Default String optioni = StringUtils
            .repeat(' ', 2);
    // [T-Up#INFO][COMEN01.CPY:134] ERRMSGL (level: 2)
    private @Getter @Setter int errmsgl;
    // [T-Up#INFO][COMEN01.CPY:135] ERRMSGF (level: 2)
    private @Getter @Builder.Default String errmsgf = StringUtils
            .repeat(' ', 1);
    // [T-Up#INFO][COMEN01.CPY:138] FILLER (level: 2)
    private @Getter @Builder.Default String FILLER_21 = StringUtils.repeat(' ',
            4);
    // [T-Up#INFO][COMEN01.CPY:139] ERRMSGI (level: 2)
    private @Getter @Builder.Default String errmsgi = StringUtils.repeat(' ',
            78);

    public static Comen1ai createDefaultValueInstance() {
        return new Comen1ai.builder().build();
    }

    public void set(String source) {
        source = StringUtils.truncate(StringUtils.rightPad(source, 820), 820);
        setFILLER_1(source.substring(0, 12));
        try {
            setTrnnamel(CobStream.convStringToShort(source.substring(12, 14)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setTrnnamel(0);
        }
        setTrnnamef(source.substring(14, 15));
        setFILLER_2(source.substring(15, 19));
        setTrnnamei(source.substring(19, 23));
        try {
            setTitle01l(CobStream.convStringToShort(source.substring(23, 25)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setTitle01l(0);
        }
        setTitle01f(source.substring(25, 26));
        setFILLER_3(source.substring(26, 30));
        setTitle01i(source.substring(30, 70));
        try {
            setCurdatel(CobStream.convStringToShort(source.substring(70, 72)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setCurdatel(0);
        }
        setCurdatef(source.substring(72, 73));
        setFILLER_4(source.substring(73, 77));
        setCurdatei(source.substring(77, 85));
        try {
            setPgmnamel(CobStream.convStringToShort(source.substring(85, 87)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setPgmnamel(0);
        }
        setPgmnamef(source.substring(87, 88));
        setFILLER_5(source.substring(88, 92));
        setPgmnamei(source.substring(92, 100));
        try {
            setTitle02l(CobStream.convStringToShort(source.substring(100, 102)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setTitle02l(0);
        }
        setTitle02f(source.substring(102, 103));
        setFILLER_6(source.substring(103, 107));
        setTitle02i(source.substring(107, 147));
        try {
            setCurtimel(CobStream.convStringToShort(source.substring(147, 149)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setCurtimel(0);
        }
        setCurtimef(source.substring(149, 150));
        setFILLER_7(source.substring(150, 154));
        setCurtimei(source.substring(154, 162));
        try {
            setOptn001l(CobStream.convStringToShort(source.substring(162, 164)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setOptn001l(0);
        }
        setOptn001f(source.substring(164, 165));
        setFILLER_8(source.substring(165, 169));
        setOptn001i(source.substring(169, 209));
        try {
            setOptn002l(CobStream.convStringToShort(source.substring(209, 211)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setOptn002l(0);
        }
        setOptn002f(source.substring(211, 212));
        setFILLER_9(source.substring(212, 216));
        setOptn002i(source.substring(216, 256));
        try {
            setOptn003l(CobStream.convStringToShort(source.substring(256, 258)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setOptn003l(0);
        }
        setOptn003f(source.substring(258, 259));
        setFILLER_10(source.substring(259, 263));
        setOptn003i(source.substring(263, 303));
        try {
            setOptn004l(CobStream.convStringToShort(source.substring(303, 305)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setOptn004l(0);
        }
        setOptn004f(source.substring(305, 306));
        setFILLER_11(source.substring(306, 310));
        setOptn004i(source.substring(310, 350));
        try {
            setOptn005l(CobStream.convStringToShort(source.substring(350, 352)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setOptn005l(0);
        }
        setOptn005f(source.substring(352, 353));
        setFILLER_12(source.substring(353, 357));
        setOptn005i(source.substring(357, 397));
        try {
            setOptn006l(CobStream.convStringToShort(source.substring(397, 399)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setOptn006l(0);
        }
        setOptn006f(source.substring(399, 400));
        setFILLER_13(source.substring(400, 404));
        setOptn006i(source.substring(404, 444));
        try {
            setOptn007l(CobStream.convStringToShort(source.substring(444, 446)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setOptn007l(0);
        }
        setOptn007f(source.substring(446, 447));
        setFILLER_14(source.substring(447, 451));
        setOptn007i(source.substring(451, 491));
        try {
            setOptn008l(CobStream.convStringToShort(source.substring(491, 493)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setOptn008l(0);
        }
        setOptn008f(source.substring(493, 494));
        setFILLER_15(source.substring(494, 498));
        setOptn008i(source.substring(498, 538));
        try {
            setOptn009l(CobStream.convStringToShort(source.substring(538, 540)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setOptn009l(0);
        }
        setOptn009f(source.substring(540, 541));
        setFILLER_16(source.substring(541, 545));
        setOptn009i(source.substring(545, 585));
        try {
            setOptn010l(CobStream.convStringToShort(source.substring(585, 587)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setOptn010l(0);
        }
        setOptn010f(source.substring(587, 588));
        setFILLER_17(source.substring(588, 592));
        setOptn010i(source.substring(592, 632));
        try {
            setOptn011l(CobStream.convStringToShort(source.substring(632, 634)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setOptn011l(0);
        }
        setOptn011f(source.substring(634, 635));
        setFILLER_18(source.substring(635, 639));
        setOptn011i(source.substring(639, 679));
        try {
            setOptn012l(CobStream.convStringToShort(source.substring(679, 681)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setOptn012l(0);
        }
        setOptn012f(source.substring(681, 682));
        setFILLER_19(source.substring(682, 686));
        setOptn012i(source.substring(686, 726));
        try {
            setOptionl(CobStream.convStringToShort(source.substring(726, 728)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setOptionl(0);
        }
        setOptionf(source.substring(728, 729));
        setFILLER_20(source.substring(729, 733));
        setOptioni(source.substring(733, 735));
        try {
            setErrmsgl(CobStream.convStringToShort(source.substring(735, 737)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setErrmsgl(0);
        }
        setErrmsgf(source.substring(737, 738));
        setFILLER_21(source.substring(738, 742));
        setErrmsgi(source.substring(742, 820));
    }

    public String get() {
        StringBuilder sb = new StringBuilder();
        sb.append(getFILLER_1());
        sb.append(CobStream.convShortToString((short) getTrnnamel()));
        sb.append(getTrnnamef());
        sb.append(getFILLER_2());
        sb.append(getTrnnamei());
        sb.append(CobStream.convShortToString((short) getTitle01l()));
        sb.append(getTitle01f());
        sb.append(getFILLER_3());
        sb.append(getTitle01i());
        sb.append(CobStream.convShortToString((short) getCurdatel()));
        sb.append(getCurdatef());
        sb.append(getFILLER_4());
        sb.append(getCurdatei());
        sb.append(CobStream.convShortToString((short) getPgmnamel()));
        sb.append(getPgmnamef());
        sb.append(getFILLER_5());
        sb.append(getPgmnamei());
        sb.append(CobStream.convShortToString((short) getTitle02l()));
        sb.append(getTitle02f());
        sb.append(getFILLER_6());
        sb.append(getTitle02i());
        sb.append(CobStream.convShortToString((short) getCurtimel()));
        sb.append(getCurtimef());
        sb.append(getFILLER_7());
        sb.append(getCurtimei());
        sb.append(CobStream.convShortToString((short) getOptn001l()));
        sb.append(getOptn001f());
        sb.append(getFILLER_8());
        sb.append(getOptn001i());
        sb.append(CobStream.convShortToString((short) getOptn002l()));
        sb.append(getOptn002f());
        sb.append(getFILLER_9());
        sb.append(getOptn002i());
        sb.append(CobStream.convShortToString((short) getOptn003l()));
        sb.append(getOptn003f());
        sb.append(getFILLER_10());
        sb.append(getOptn003i());
        sb.append(CobStream.convShortToString((short) getOptn004l()));
        sb.append(getOptn004f());
        sb.append(getFILLER_11());
        sb.append(getOptn004i());
        sb.append(CobStream.convShortToString((short) getOptn005l()));
        sb.append(getOptn005f());
        sb.append(getFILLER_12());
        sb.append(getOptn005i());
        sb.append(CobStream.convShortToString((short) getOptn006l()));
        sb.append(getOptn006f());
        sb.append(getFILLER_13());
        sb.append(getOptn006i());
        sb.append(CobStream.convShortToString((short) getOptn007l()));
        sb.append(getOptn007f());
        sb.append(getFILLER_14());
        sb.append(getOptn007i());
        sb.append(CobStream.convShortToString((short) getOptn008l()));
        sb.append(getOptn008f());
        sb.append(getFILLER_15());
        sb.append(getOptn008i());
        sb.append(CobStream.convShortToString((short) getOptn009l()));
        sb.append(getOptn009f());
        sb.append(getFILLER_16());
        sb.append(getOptn009i());
        sb.append(CobStream.convShortToString((short) getOptn010l()));
        sb.append(getOptn010f());
        sb.append(getFILLER_17());
        sb.append(getOptn010i());
        sb.append(CobStream.convShortToString((short) getOptn011l()));
        sb.append(getOptn011f());
        sb.append(getFILLER_18());
        sb.append(getOptn011i());
        sb.append(CobStream.convShortToString((short) getOptn012l()));
        sb.append(getOptn012f());
        sb.append(getFILLER_19());
        sb.append(getOptn012i());
        sb.append(CobStream.convShortToString((short) getOptionl()));
        sb.append(getOptionf());
        sb.append(getFILLER_20());
        sb.append(getOptioni());
        sb.append(CobStream.convShortToString((short) getErrmsgl()));
        sb.append(getErrmsgf());
        sb.append(getFILLER_21());
        sb.append(getErrmsgi());
        return sb.toString();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getFILLER_1());
        sb.append(String.valueOf(getTrnnamel()));
        sb.append(getTrnnamef());
        sb.append(getFILLER_2());
        sb.append(getTrnnamei());
        sb.append(String.valueOf(getTitle01l()));
        sb.append(getTitle01f());
        sb.append(getFILLER_3());
        sb.append(getTitle01i());
        sb.append(String.valueOf(getCurdatel()));
        sb.append(getCurdatef());
        sb.append(getFILLER_4());
        sb.append(getCurdatei());
        sb.append(String.valueOf(getPgmnamel()));
        sb.append(getPgmnamef());
        sb.append(getFILLER_5());
        sb.append(getPgmnamei());
        sb.append(String.valueOf(getTitle02l()));
        sb.append(getTitle02f());
        sb.append(getFILLER_6());
        sb.append(getTitle02i());
        sb.append(String.valueOf(getCurtimel()));
        sb.append(getCurtimef());
        sb.append(getFILLER_7());
        sb.append(getCurtimei());
        sb.append(String.valueOf(getOptn001l()));
        sb.append(getOptn001f());
        sb.append(getFILLER_8());
        sb.append(getOptn001i());
        sb.append(String.valueOf(getOptn002l()));
        sb.append(getOptn002f());
        sb.append(getFILLER_9());
        sb.append(getOptn002i());
        sb.append(String.valueOf(getOptn003l()));
        sb.append(getOptn003f());
        sb.append(getFILLER_10());
        sb.append(getOptn003i());
        sb.append(String.valueOf(getOptn004l()));
        sb.append(getOptn004f());
        sb.append(getFILLER_11());
        sb.append(getOptn004i());
        sb.append(String.valueOf(getOptn005l()));
        sb.append(getOptn005f());
        sb.append(getFILLER_12());
        sb.append(getOptn005i());
        sb.append(String.valueOf(getOptn006l()));
        sb.append(getOptn006f());
        sb.append(getFILLER_13());
        sb.append(getOptn006i());
        sb.append(String.valueOf(getOptn007l()));
        sb.append(getOptn007f());
        sb.append(getFILLER_14());
        sb.append(getOptn007i());
        sb.append(String.valueOf(getOptn008l()));
        sb.append(getOptn008f());
        sb.append(getFILLER_15());
        sb.append(getOptn008i());
        sb.append(String.valueOf(getOptn009l()));
        sb.append(getOptn009f());
        sb.append(getFILLER_16());
        sb.append(getOptn009i());
        sb.append(String.valueOf(getOptn010l()));
        sb.append(getOptn010f());
        sb.append(getFILLER_17());
        sb.append(getOptn010i());
        sb.append(String.valueOf(getOptn011l()));
        sb.append(getOptn011f());
        sb.append(getFILLER_18());
        sb.append(getOptn011i());
        sb.append(String.valueOf(getOptn012l()));
        sb.append(getOptn012f());
        sb.append(getFILLER_19());
        sb.append(getOptn012i());
        sb.append(String.valueOf(getOptionl()));
        sb.append(getOptionf());
        sb.append(getFILLER_20());
        sb.append(getOptioni());
        sb.append(String.valueOf(getErrmsgl()));
        sb.append(getErrmsgf());
        sb.append(getFILLER_21());
        sb.append(getErrmsgi());
        return sb.toString();
    }

    public void setFILLER_1(String source) {
        FILLER_1 = StringUtils.truncate(StringUtils.rightPad(source, 12), 12);
    }

    public void setTrnnamef(String source) {
        trnnamef = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_2 getFILLER_REDEFINE_2() {
        return _FILLER_REDEFINE_2.builder().trnnamea(getTrnnamea()).build();
    }

    public void setFILLER_REDEFINE_2(String source) {
        setTrnnamea(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_2(_FILLER_REDEFINE_2 source) {
        setFILLER_REDEFINE_2(source.get());
    }

    public String getTrnnamea() {
        return getTrnnamef();
    }

    public void setTrnnamea(String source) {
        setTrnnamef(source);
    }

    public void setFILLER_2(String source) {
        FILLER_2 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setTrnnamei(String source) {
        trnnamei = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setTitle01f(String source) {
        title01f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_4 getFILLER_REDEFINE_4() {
        return _FILLER_REDEFINE_4.builder().title01a(getTitle01a()).build();
    }

    public void setFILLER_REDEFINE_4(String source) {
        setTitle01a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_4(_FILLER_REDEFINE_4 source) {
        setFILLER_REDEFINE_4(source.get());
    }

    public String getTitle01a() {
        return getTitle01f();
    }

    public void setTitle01a(String source) {
        setTitle01f(source);
    }

    public void setFILLER_3(String source) {
        FILLER_3 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setTitle01i(String source) {
        title01i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setCurdatef(String source) {
        curdatef = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_6 getFILLER_REDEFINE_6() {
        return _FILLER_REDEFINE_6.builder().curdatea(getCurdatea()).build();
    }

    public void setFILLER_REDEFINE_6(String source) {
        setCurdatea(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_6(_FILLER_REDEFINE_6 source) {
        setFILLER_REDEFINE_6(source.get());
    }

    public String getCurdatea() {
        return getCurdatef();
    }

    public void setCurdatea(String source) {
        setCurdatef(source);
    }

    public void setFILLER_4(String source) {
        FILLER_4 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setCurdatei(String source) {
        curdatei = StringUtils.truncate(StringUtils.rightPad(source, 8), 8);
    }

    public void setPgmnamef(String source) {
        pgmnamef = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_8 getFILLER_REDEFINE_8() {
        return _FILLER_REDEFINE_8.builder().pgmnamea(getPgmnamea()).build();
    }

    public void setFILLER_REDEFINE_8(String source) {
        setPgmnamea(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_8(_FILLER_REDEFINE_8 source) {
        setFILLER_REDEFINE_8(source.get());
    }

    public String getPgmnamea() {
        return getPgmnamef();
    }

    public void setPgmnamea(String source) {
        setPgmnamef(source);
    }

    public void setFILLER_5(String source) {
        FILLER_5 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setPgmnamei(String source) {
        pgmnamei = StringUtils.truncate(StringUtils.rightPad(source, 8), 8);
    }

    public void setTitle02f(String source) {
        title02f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_10 getFILLER_REDEFINE_10() {
        return _FILLER_REDEFINE_10.builder().title02a(getTitle02a()).build();
    }

    public void setFILLER_REDEFINE_10(String source) {
        setTitle02a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_10(_FILLER_REDEFINE_10 source) {
        setFILLER_REDEFINE_10(source.get());
    }

    public String getTitle02a() {
        return getTitle02f();
    }

    public void setTitle02a(String source) {
        setTitle02f(source);
    }

    public void setFILLER_6(String source) {
        FILLER_6 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setTitle02i(String source) {
        title02i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setCurtimef(String source) {
        curtimef = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_12 getFILLER_REDEFINE_12() {
        return _FILLER_REDEFINE_12.builder().curtimea(getCurtimea()).build();
    }

    public void setFILLER_REDEFINE_12(String source) {
        setCurtimea(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_12(_FILLER_REDEFINE_12 source) {
        setFILLER_REDEFINE_12(source.get());
    }

    public String getCurtimea() {
        return getCurtimef();
    }

    public void setCurtimea(String source) {
        setCurtimef(source);
    }

    public void setFILLER_7(String source) {
        FILLER_7 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setCurtimei(String source) {
        curtimei = StringUtils.truncate(StringUtils.rightPad(source, 8), 8);
    }

    public void setOptn001f(String source) {
        optn001f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_14 getFILLER_REDEFINE_14() {
        return _FILLER_REDEFINE_14.builder().optn001a(getOptn001a()).build();
    }

    public void setFILLER_REDEFINE_14(String source) {
        setOptn001a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_14(_FILLER_REDEFINE_14 source) {
        setFILLER_REDEFINE_14(source.get());
    }

    public String getOptn001a() {
        return getOptn001f();
    }

    public void setOptn001a(String source) {
        setOptn001f(source);
    }

    public void setFILLER_8(String source) {
        FILLER_8 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn001i(String source) {
        optn001i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn002f(String source) {
        optn002f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_16 getFILLER_REDEFINE_16() {
        return _FILLER_REDEFINE_16.builder().optn002a(getOptn002a()).build();
    }

    public void setFILLER_REDEFINE_16(String source) {
        setOptn002a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_16(_FILLER_REDEFINE_16 source) {
        setFILLER_REDEFINE_16(source.get());
    }

    public String getOptn002a() {
        return getOptn002f();
    }

    public void setOptn002a(String source) {
        setOptn002f(source);
    }

    public void setFILLER_9(String source) {
        FILLER_9 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn002i(String source) {
        optn002i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn003f(String source) {
        optn003f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_18 getFILLER_REDEFINE_18() {
        return _FILLER_REDEFINE_18.builder().optn003a(getOptn003a()).build();
    }

    public void setFILLER_REDEFINE_18(String source) {
        setOptn003a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_18(_FILLER_REDEFINE_18 source) {
        setFILLER_REDEFINE_18(source.get());
    }

    public String getOptn003a() {
        return getOptn003f();
    }

    public void setOptn003a(String source) {
        setOptn003f(source);
    }

    public void setFILLER_10(String source) {
        FILLER_10 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn003i(String source) {
        optn003i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn004f(String source) {
        optn004f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_20 getFILLER_REDEFINE_20() {
        return _FILLER_REDEFINE_20.builder().optn004a(getOptn004a()).build();
    }

    public void setFILLER_REDEFINE_20(String source) {
        setOptn004a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_20(_FILLER_REDEFINE_20 source) {
        setFILLER_REDEFINE_20(source.get());
    }

    public String getOptn004a() {
        return getOptn004f();
    }

    public void setOptn004a(String source) {
        setOptn004f(source);
    }

    public void setFILLER_11(String source) {
        FILLER_11 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn004i(String source) {
        optn004i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn005f(String source) {
        optn005f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_22 getFILLER_REDEFINE_22() {
        return _FILLER_REDEFINE_22.builder().optn005a(getOptn005a()).build();
    }

    public void setFILLER_REDEFINE_22(String source) {
        setOptn005a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_22(_FILLER_REDEFINE_22 source) {
        setFILLER_REDEFINE_22(source.get());
    }

    public String getOptn005a() {
        return getOptn005f();
    }

    public void setOptn005a(String source) {
        setOptn005f(source);
    }

    public void setFILLER_12(String source) {
        FILLER_12 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn005i(String source) {
        optn005i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn006f(String source) {
        optn006f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_24 getFILLER_REDEFINE_24() {
        return _FILLER_REDEFINE_24.builder().optn006a(getOptn006a()).build();
    }

    public void setFILLER_REDEFINE_24(String source) {
        setOptn006a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_24(_FILLER_REDEFINE_24 source) {
        setFILLER_REDEFINE_24(source.get());
    }

    public String getOptn006a() {
        return getOptn006f();
    }

    public void setOptn006a(String source) {
        setOptn006f(source);
    }

    public void setFILLER_13(String source) {
        FILLER_13 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn006i(String source) {
        optn006i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn007f(String source) {
        optn007f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_26 getFILLER_REDEFINE_26() {
        return _FILLER_REDEFINE_26.builder().optn007a(getOptn007a()).build();
    }

    public void setFILLER_REDEFINE_26(String source) {
        setOptn007a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_26(_FILLER_REDEFINE_26 source) {
        setFILLER_REDEFINE_26(source.get());
    }

    public String getOptn007a() {
        return getOptn007f();
    }

    public void setOptn007a(String source) {
        setOptn007f(source);
    }

    public void setFILLER_14(String source) {
        FILLER_14 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn007i(String source) {
        optn007i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn008f(String source) {
        optn008f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_28 getFILLER_REDEFINE_28() {
        return _FILLER_REDEFINE_28.builder().optn008a(getOptn008a()).build();
    }

    public void setFILLER_REDEFINE_28(String source) {
        setOptn008a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_28(_FILLER_REDEFINE_28 source) {
        setFILLER_REDEFINE_28(source.get());
    }

    public String getOptn008a() {
        return getOptn008f();
    }

    public void setOptn008a(String source) {
        setOptn008f(source);
    }

    public void setFILLER_15(String source) {
        FILLER_15 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn008i(String source) {
        optn008i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn009f(String source) {
        optn009f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_30 getFILLER_REDEFINE_30() {
        return _FILLER_REDEFINE_30.builder().optn009a(getOptn009a()).build();
    }

    public void setFILLER_REDEFINE_30(String source) {
        setOptn009a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_30(_FILLER_REDEFINE_30 source) {
        setFILLER_REDEFINE_30(source.get());
    }

    public String getOptn009a() {
        return getOptn009f();
    }

    public void setOptn009a(String source) {
        setOptn009f(source);
    }

    public void setFILLER_16(String source) {
        FILLER_16 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn009i(String source) {
        optn009i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn010f(String source) {
        optn010f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_32 getFILLER_REDEFINE_32() {
        return _FILLER_REDEFINE_32.builder().optn010a(getOptn010a()).build();
    }

    public void setFILLER_REDEFINE_32(String source) {
        setOptn010a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_32(_FILLER_REDEFINE_32 source) {
        setFILLER_REDEFINE_32(source.get());
    }

    public String getOptn010a() {
        return getOptn010f();
    }

    public void setOptn010a(String source) {
        setOptn010f(source);
    }

    public void setFILLER_17(String source) {
        FILLER_17 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn010i(String source) {
        optn010i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn011f(String source) {
        optn011f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_34 getFILLER_REDEFINE_34() {
        return _FILLER_REDEFINE_34.builder().optn011a(getOptn011a()).build();
    }

    public void setFILLER_REDEFINE_34(String source) {
        setOptn011a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_34(_FILLER_REDEFINE_34 source) {
        setFILLER_REDEFINE_34(source.get());
    }

    public String getOptn011a() {
        return getOptn011f();
    }

    public void setOptn011a(String source) {
        setOptn011f(source);
    }

    public void setFILLER_18(String source) {
        FILLER_18 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn011i(String source) {
        optn011i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptn012f(String source) {
        optn012f = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_36 getFILLER_REDEFINE_36() {
        return _FILLER_REDEFINE_36.builder().optn012a(getOptn012a()).build();
    }

    public void setFILLER_REDEFINE_36(String source) {
        setOptn012a(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_36(_FILLER_REDEFINE_36 source) {
        setFILLER_REDEFINE_36(source.get());
    }

    public String getOptn012a() {
        return getOptn012f();
    }

    public void setOptn012a(String source) {
        setOptn012f(source);
    }

    public void setFILLER_19(String source) {
        FILLER_19 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptn012i(String source) {
        optn012i = StringUtils.truncate(StringUtils.rightPad(source, 40), 40);
    }

    public void setOptionf(String source) {
        optionf = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_38 getFILLER_REDEFINE_38() {
        return _FILLER_REDEFINE_38.builder().optiona(getOptiona()).build();
    }

    public void setFILLER_REDEFINE_38(String source) {
        setOptiona(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_38(_FILLER_REDEFINE_38 source) {
        setFILLER_REDEFINE_38(source.get());
    }

    public String getOptiona() {
        return getOptionf();
    }

    public void setOptiona(String source) {
        setOptionf(source);
    }

    public void setFILLER_20(String source) {
        FILLER_20 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setOptioni(String source) {
        optioni = StringUtils.truncate(StringUtils.rightPad(source, 2), 2);
    }

    public void setErrmsgf(String source) {
        errmsgf = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public _FILLER_REDEFINE_40 getFILLER_REDEFINE_40() {
        return _FILLER_REDEFINE_40.builder().errmsga(getErrmsga()).build();
    }

    public void setFILLER_REDEFINE_40(String source) {
        setErrmsga(source.substring(0, 1));
    }

    public void setFILLER_REDEFINE_40(_FILLER_REDEFINE_40 source) {
        setFILLER_REDEFINE_40(source.get());
    }

    public String getErrmsga() {
        return getErrmsgf();
    }

    public void setErrmsga(String source) {
        setErrmsgf(source);
    }

    public void setFILLER_21(String source) {
        FILLER_21 = StringUtils.truncate(StringUtils.rightPad(source, 4), 4);
    }

    public void setErrmsgi(String source) {
        errmsgi = StringUtils.truncate(StringUtils.rightPad(source, 78), 78);
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_2 {
        // [T-Up#INFO][COMEN01.CPY:23] TRNNAMEA (level: 3)
        private @Getter @Builder.Default String trnnamea = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(trnnamea);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getTrnnamea());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_4 {
        // [T-Up#INFO][COMEN01.CPY:29] TITLE01A (level: 3)
        private @Getter @Builder.Default String title01a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(title01a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getTitle01a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_6 {
        // [T-Up#INFO][COMEN01.CPY:35] CURDATEA (level: 3)
        private @Getter @Builder.Default String curdatea = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(curdatea);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getCurdatea());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_8 {
        // [T-Up#INFO][COMEN01.CPY:41] PGMNAMEA (level: 3)
        private @Getter @Builder.Default String pgmnamea = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(pgmnamea);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getPgmnamea());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_10 {
        // [T-Up#INFO][COMEN01.CPY:47] TITLE02A (level: 3)
        private @Getter @Builder.Default String title02a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(title02a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getTitle02a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_12 {
        // [T-Up#INFO][COMEN01.CPY:53] CURTIMEA (level: 3)
        private @Getter @Builder.Default String curtimea = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(curtimea);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getCurtimea());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_14 {
        // [T-Up#INFO][COMEN01.CPY:59] OPTN001A (level: 3)
        private @Getter @Builder.Default String optn001a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn001a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getOptn001a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_16 {
        // [T-Up#INFO][COMEN01.CPY:65] OPTN002A (level: 3)
        private @Getter @Builder.Default String optn002a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn002a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getOptn002a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_18 {
        // [T-Up#INFO][COMEN01.CPY:71] OPTN003A (level: 3)
        private @Getter @Builder.Default String optn003a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn003a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getOptn003a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_20 {
        // [T-Up#INFO][COMEN01.CPY:77] OPTN004A (level: 3)
        private @Getter @Builder.Default String optn004a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn004a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getOptn004a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_22 {
        // [T-Up#INFO][COMEN01.CPY:83] OPTN005A (level: 3)
        private @Getter @Builder.Default String optn005a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn005a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getOptn005a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_24 {
        // [T-Up#INFO][COMEN01.CPY:89] OPTN006A (level: 3)
        private @Getter @Builder.Default String optn006a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn006a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getOptn006a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_26 {
        // [T-Up#INFO][COMEN01.CPY:95] OPTN007A (level: 3)
        private @Getter @Builder.Default String optn007a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn007a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getOptn007a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_28 {
        // [T-Up#INFO][COMEN01.CPY:101] OPTN008A (level: 3)
        private @Getter @Builder.Default String optn008a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn008a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getOptn008a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_30 {
        // [T-Up#INFO][COMEN01.CPY:107] OPTN009A (level: 3)
        private @Getter @Builder.Default String optn009a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn009a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getOptn009a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_32 {
        // [T-Up#INFO][COMEN01.CPY:113] OPTN010A (level: 3)
        private @Getter @Builder.Default String optn010a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn010a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getOptn010a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_34 {
        // [T-Up#INFO][COMEN01.CPY:119] OPTN011A (level: 3)
        private @Getter @Builder.Default String optn011a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn011a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getOptn011a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_36 {
        // [T-Up#INFO][COMEN01.CPY:125] OPTN012A (level: 3)
        private @Getter @Builder.Default String optn012a = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optn012a);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getOptn012a());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_38 {
        // [T-Up#INFO][COMEN01.CPY:131] OPTIONA (level: 3)
        private @Getter @Builder.Default String optiona = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(optiona);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getOptiona());
            return sb.toString();
        }
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class _FILLER_REDEFINE_40 {
        // [T-Up#INFO][COMEN01.CPY:137] ERRMSGA (level: 3)
        private @Getter @Builder.Default String errmsga = StringUtils.repeat(
                ' ', 1);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(errmsga);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getErrmsga());
            return sb.toString();
        }
    }
}
