package com.tmax.openframe.variable.group;

import com.tmax.openframe.runtime.cobol.CobStream;
import com.tmax.openframe.runtime.cobol.PictureFormatter;
import java.math.*;
import java.util.*;
import java.util.stream.*;
import lombok.*;
import org.apache.commons.lang3.StringUtils;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:10 KST</p>
 * <hr>
 * <p>Class that defines variables for COPYBOOK item</p>
 */
public @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class DalytranRecord {
    // [T-Up#INFO][CVTRA06Y.cpy:6] DALYTRAN-ID (level: 5)
    private @Getter @Builder.Default String dalytranId = StringUtils.repeat(
            ' ', 16);
    // [T-Up#INFO][CVTRA06Y.cpy:7] DALYTRAN-TYPE-CD (level: 5)
    private @Getter @Builder.Default String dalytranTypeCd = StringUtils
            .repeat(' ', 2);
    // [T-Up#INFO][CVTRA06Y.cpy:8] DALYTRAN-CAT-CD (level: 5)
    private @Getter @Setter int dalytranCatCd;
    // [T-Up#INFO][CVTRA06Y.cpy:9] DALYTRAN-SOURCE (level: 5)
    private @Getter @Builder.Default String dalytranSource = StringUtils
            .repeat(' ', 10);
    // [T-Up#INFO][CVTRA06Y.cpy:10] DALYTRAN-DESC (level: 5)
    private @Getter @Builder.Default String dalytranDesc = StringUtils.repeat(
            ' ', 100);
    // [T-Up#INFO][CVTRA06Y.cpy:11] DALYTRAN-AMT (level: 5)
    private @Getter @Builder.Default BigDecimal dalytranAmt = BigDecimal.ZERO;
    // [T-Up#INFO][CVTRA06Y.cpy:12] DALYTRAN-MERCHANT-ID (level: 5)
    private @Getter @Setter int dalytranMerchantId;
    // [T-Up#INFO][CVTRA06Y.cpy:13] DALYTRAN-MERCHANT-NAME (level: 5)
    private @Getter @Builder.Default String dalytranMerchantName = StringUtils
            .repeat(' ', 50);
    // [T-Up#INFO][CVTRA06Y.cpy:14] DALYTRAN-MERCHANT-CITY (level: 5)
    private @Getter @Builder.Default String dalytranMerchantCity = StringUtils
            .repeat(' ', 50);
    // [T-Up#INFO][CVTRA06Y.cpy:15] DALYTRAN-MERCHANT-ZIP (level: 5)
    private @Getter @Builder.Default String dalytranMerchantZip = StringUtils
            .repeat(' ', 10);
    // [T-Up#INFO][CVTRA06Y.cpy:16] DALYTRAN-CARD-NUM (level: 5)
    private @Getter @Builder.Default String dalytranCardNum = StringUtils
            .repeat(' ', 16);
    // [T-Up#INFO][CVTRA06Y.cpy:17] DALYTRAN-ORIG-TS (level: 5)
    private @Getter @Builder.Default String dalytranOrigTs = StringUtils
            .repeat(' ', 26);
    // [T-Up#INFO][CVTRA06Y.cpy:18] DALYTRAN-PROC-TS (level: 5)
    private @Getter @Builder.Default String dalytranProcTs = StringUtils
            .repeat(' ', 26);
    // [T-Up#INFO][CVTRA06Y.cpy:19] FILLER (level: 5)
    private @Getter @Builder.Default String FILLER_1 = StringUtils.repeat(' ',
            20);

    public static DalytranRecord createDefaultValueInstance() {
        return new DalytranRecord.builder().build();
    }

    public void set(String source) {
        source = StringUtils.truncate(StringUtils.rightPad(source, 350), 350);
        setDalytranId(source.substring(0, 16));
        setDalytranTypeCd(source.substring(16, 18));
        try {
            setDalytranCatCd(CobStream.convZonedStringToInt(
                    source.substring(18, 22), 4));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setDalytranCatCd(0);
        }
        setDalytranSource(source.substring(22, 32));
        setDalytranDesc(source.substring(32, 132));
        try {
            setDalytranAmt(CobStream.convZonedStringToBigDecimal(
                    source.substring(132, 143), 11, 2));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setDalytranAmt(BigDecimal.ZERO);
        }
        try {
            setDalytranMerchantId(CobStream.convZonedStringToInt(
                    source.substring(143, 152), 9));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            setDalytranMerchantId(0);
        }
        setDalytranMerchantName(source.substring(152, 202));
        setDalytranMerchantCity(source.substring(202, 252));
        setDalytranMerchantZip(source.substring(252, 262));
        setDalytranCardNum(source.substring(262, 278));
        setDalytranOrigTs(source.substring(278, 304));
        setDalytranProcTs(source.substring(304, 330));
        setFILLER_1(source.substring(330, 350));
    }

    public String get() {
        StringBuilder sb = new StringBuilder();
        sb.append(getDalytranId());
        sb.append(getDalytranTypeCd());
        sb.append(CobStream.convZonedIntToString(getDalytranCatCd(), 4));
        sb.append(getDalytranSource());
        sb.append(getDalytranDesc());
        sb.append(CobStream
                .convZonedBigDecimalToString(getDalytranAmt(), 11, 2));
        sb.append(CobStream.convZonedIntToString(getDalytranMerchantId(), 9));
        sb.append(getDalytranMerchantName());
        sb.append(getDalytranMerchantCity());
        sb.append(getDalytranMerchantZip());
        sb.append(getDalytranCardNum());
        sb.append(getDalytranOrigTs());
        sb.append(getDalytranProcTs());
        sb.append(getFILLER_1());
        return sb.toString();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getDalytranId());
        sb.append(getDalytranTypeCd());
        sb.append(PictureFormatter.intFormatWithoutSign(
                (long) getDalytranCatCd(), "0000"));
        sb.append(getDalytranSource());
        sb.append(getDalytranDesc());
        sb.append(PictureFormatter.decimalFormatWithSign(getDalytranAmt(),
                "000000000.00"));
        sb.append(PictureFormatter.intFormatWithoutSign(
                (long) getDalytranMerchantId(), "000000000"));
        sb.append(getDalytranMerchantName());
        sb.append(getDalytranMerchantCity());
        sb.append(getDalytranMerchantZip());
        sb.append(getDalytranCardNum());
        sb.append(getDalytranOrigTs());
        sb.append(getDalytranProcTs());
        sb.append(getFILLER_1());
        return sb.toString();
    }

    public void setDalytranId(String source) {
        dalytranId = StringUtils.truncate(StringUtils.rightPad(source, 16), 16);
    }

    public void setDalytranTypeCd(String source) {
        dalytranTypeCd = StringUtils.truncate(StringUtils.rightPad(source, 2),
                2);
    }

    public void setDalytranSource(String source) {
        dalytranSource = StringUtils.truncate(StringUtils.rightPad(source, 10),
                10);
    }

    public void setDalytranDesc(String source) {
        dalytranDesc = StringUtils.truncate(StringUtils.rightPad(source, 100),
                100);
    }

    public void setDalytranAmt(BigDecimal source) {
        dalytranAmt = source.setScale(2, RoundingMode.DOWN);
    }

    public void setDalytranMerchantName(String source) {
        dalytranMerchantName = StringUtils.truncate(
                StringUtils.rightPad(source, 50), 50);
    }

    public void setDalytranMerchantCity(String source) {
        dalytranMerchantCity = StringUtils.truncate(
                StringUtils.rightPad(source, 50), 50);
    }

    public void setDalytranMerchantZip(String source) {
        dalytranMerchantZip = StringUtils.truncate(
                StringUtils.rightPad(source, 10), 10);
    }

    public void setDalytranCardNum(String source) {
        dalytranCardNum = StringUtils.truncate(
                StringUtils.rightPad(source, 16), 16);
    }

    public void setDalytranOrigTs(String source) {
        dalytranOrigTs = StringUtils.truncate(StringUtils.rightPad(source, 26),
                26);
    }

    public void setDalytranProcTs(String source) {
        dalytranProcTs = StringUtils.truncate(StringUtils.rightPad(source, 26),
                26);
    }

    public void setFILLER_1(String source) {
        FILLER_1 = StringUtils.truncate(StringUtils.rightPad(source, 20), 20);
    }
}
