package com.tmax.openframe.variable.group;

import java.math.*;
import java.util.*;
import java.util.stream.*;
import lombok.*;
import org.apache.commons.lang3.StringUtils;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:20 KST</p>
 * <hr>
 * <p>Class that defines variables for COPYBOOK item</p>
 */
public @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class Dfhaid {
    // [T-Up#INFO][DFHAID.cpy:3] DFHNULL (level: 2)
    private @Getter @Builder.Default String dfhnull = " ";
    // [T-Up#INFO][DFHAID.cpy:4] DFHENTER (level: 2)
    private @Getter @Builder.Default String dfhenter = "'";
    // [T-Up#INFO][DFHAID.cpy:5] DFHCLEAR (level: 2)
    private @Getter @Builder.Default String dfhclear = "_";
    // [T-Up#INFO][DFHAID.cpy:6] DFHCLRP (level: 2)
    private @Getter @Builder.Default String dfhclrp = "|";
    // [T-Up#INFO][DFHAID.cpy:7] DFHPEN (level: 2)
    private @Getter @Builder.Default String dfhpen = "=";
    // [T-Up#INFO][DFHAID.cpy:8] DFHOPID (level: 2)
    private @Getter @Builder.Default String dfhopid = "W";
    // [T-Up#INFO][DFHAID.cpy:9] DFHMSRE (level: 2)
    private @Getter @Builder.Default String dfhmsre = "X";
    // [T-Up#INFO][DFHAID.cpy:10] DFHSTRF (level: 2)
    private @Getter @Builder.Default String dfhstrf = "h";
    // [T-Up#INFO][DFHAID.cpy:11] DFHTRIG (level: 2)
    private @Getter @Builder.Default String dfhtrig = "\"";
    // [T-Up#INFO][DFHAID.cpy:12] DFHPA1 (level: 2)
    private @Getter @Builder.Default String dfhpa1 = "%";
    // [T-Up#INFO][DFHAID.cpy:13] DFHPA2 (level: 2)
    private @Getter @Builder.Default String dfhpa2 = ">";
    // [T-Up#INFO][DFHAID.cpy:14] DFHPA3 (level: 2)
    private @Getter @Builder.Default String dfhpa3 = ",";
    // [T-Up#INFO][DFHAID.cpy:15] DFHPF1 (level: 2)
    private @Getter @Builder.Default String dfhpf1 = "1";
    // [T-Up#INFO][DFHAID.cpy:16] DFHPF2 (level: 2)
    private @Getter @Builder.Default String dfhpf2 = "2";
    // [T-Up#INFO][DFHAID.cpy:17] DFHPF3 (level: 2)
    private @Getter @Builder.Default String dfhpf3 = "3";
    // [T-Up#INFO][DFHAID.cpy:18] DFHPF4 (level: 2)
    private @Getter @Builder.Default String dfhpf4 = "4";
    // [T-Up#INFO][DFHAID.cpy:19] DFHPF5 (level: 2)
    private @Getter @Builder.Default String dfhpf5 = "5";
    // [T-Up#INFO][DFHAID.cpy:20] DFHPF6 (level: 2)
    private @Getter @Builder.Default String dfhpf6 = "6";
    // [T-Up#INFO][DFHAID.cpy:21] DFHPF7 (level: 2)
    private @Getter @Builder.Default String dfhpf7 = "7";
    // [T-Up#INFO][DFHAID.cpy:22] DFHPF8 (level: 2)
    private @Getter @Builder.Default String dfhpf8 = "8";
    // [T-Up#INFO][DFHAID.cpy:23] DFHPF9 (level: 2)
    private @Getter @Builder.Default String dfhpf9 = "9";
    // [T-Up#INFO][DFHAID.cpy:24] DFHPF10 (level: 2)
    private @Getter @Builder.Default String dfhpf10 = ":";
    // [T-Up#INFO][DFHAID.cpy:25] DFHPF11 (level: 2)
    private @Getter @Builder.Default String dfhpf11 = "#";
    // [T-Up#INFO][DFHAID.cpy:26] DFHPF12 (level: 2)
    private @Getter @Builder.Default String dfhpf12 = "@";
    // [T-Up#INFO][DFHAID.cpy:27] DFHPF13 (level: 2)
    private @Getter @Builder.Default String dfhpf13 = "A";
    // [T-Up#INFO][DFHAID.cpy:28] DFHPF14 (level: 2)
    private @Getter @Builder.Default String dfhpf14 = "B";
    // [T-Up#INFO][DFHAID.cpy:29] DFHPF15 (level: 2)
    private @Getter @Builder.Default String dfhpf15 = "C";
    // [T-Up#INFO][DFHAID.cpy:30] DFHPF16 (level: 2)
    private @Getter @Builder.Default String dfhpf16 = "D";
    // [T-Up#INFO][DFHAID.cpy:31] DFHPF17 (level: 2)
    private @Getter @Builder.Default String dfhpf17 = "E";
    // [T-Up#INFO][DFHAID.cpy:32] DFHPF18 (level: 2)
    private @Getter @Builder.Default String dfhpf18 = "F";
    // [T-Up#INFO][DFHAID.cpy:33] DFHPF19 (level: 2)
    private @Getter @Builder.Default String dfhpf19 = "G";
    // [T-Up#INFO][DFHAID.cpy:34] DFHPF20 (level: 2)
    private @Getter @Builder.Default String dfhpf20 = "H";
    // [T-Up#INFO][DFHAID.cpy:35] DFHPF21 (level: 2)
    private @Getter @Builder.Default String dfhpf21 = "I";
    // [T-Up#INFO][DFHAID.cpy:36] DFHPF22 (level: 2)
    private @Getter @Builder.Default String dfhpf22 = "[";
    // [T-Up#INFO][DFHAID.cpy:37] DFHPF23 (level: 2)
    private @Getter @Builder.Default String dfhpf23 = ".";
    // [T-Up#INFO][DFHAID.cpy:38] DFHPF24 (level: 2)
    private @Getter @Builder.Default String dfhpf24 = "<";

    public static Dfhaid createDefaultValueInstance() {
        return new Dfhaid.builder().dfhnull(StringUtils.repeat(' ', 1))
                .dfhenter(StringUtils.repeat(' ', 1))
                .dfhclear(StringUtils.repeat(' ', 1))
                .dfhclrp(StringUtils.repeat(' ', 1))
                .dfhpen(StringUtils.repeat(' ', 1))
                .dfhopid(StringUtils.repeat(' ', 1))
                .dfhmsre(StringUtils.repeat(' ', 1))
                .dfhstrf(StringUtils.repeat(' ', 1))
                .dfhtrig(StringUtils.repeat(' ', 1))
                .dfhpa1(StringUtils.repeat(' ', 1))
                .dfhpa2(StringUtils.repeat(' ', 1))
                .dfhpa3(StringUtils.repeat(' ', 1))
                .dfhpf1(StringUtils.repeat(' ', 1))
                .dfhpf2(StringUtils.repeat(' ', 1))
                .dfhpf3(StringUtils.repeat(' ', 1))
                .dfhpf4(StringUtils.repeat(' ', 1))
                .dfhpf5(StringUtils.repeat(' ', 1))
                .dfhpf6(StringUtils.repeat(' ', 1))
                .dfhpf7(StringUtils.repeat(' ', 1))
                .dfhpf8(StringUtils.repeat(' ', 1))
                .dfhpf9(StringUtils.repeat(' ', 1))
                .dfhpf10(StringUtils.repeat(' ', 1))
                .dfhpf11(StringUtils.repeat(' ', 1))
                .dfhpf12(StringUtils.repeat(' ', 1))
                .dfhpf13(StringUtils.repeat(' ', 1))
                .dfhpf14(StringUtils.repeat(' ', 1))
                .dfhpf15(StringUtils.repeat(' ', 1))
                .dfhpf16(StringUtils.repeat(' ', 1))
                .dfhpf17(StringUtils.repeat(' ', 1))
                .dfhpf18(StringUtils.repeat(' ', 1))
                .dfhpf19(StringUtils.repeat(' ', 1))
                .dfhpf20(StringUtils.repeat(' ', 1))
                .dfhpf21(StringUtils.repeat(' ', 1))
                .dfhpf22(StringUtils.repeat(' ', 1))
                .dfhpf23(StringUtils.repeat(' ', 1))
                .dfhpf24(StringUtils.repeat(' ', 1)).build();
    }

    public void set(String source) {
        source = StringUtils.truncate(StringUtils.rightPad(source, 36), 36);
        setDfhnull(source.substring(0, 1));
        setDfhenter(source.substring(1, 2));
        setDfhclear(source.substring(2, 3));
        setDfhclrp(source.substring(3, 4));
        setDfhpen(source.substring(4, 5));
        setDfhopid(source.substring(5, 6));
        setDfhmsre(source.substring(6, 7));
        setDfhstrf(source.substring(7, 8));
        setDfhtrig(source.substring(8, 9));
        setDfhpa1(source.substring(9, 10));
        setDfhpa2(source.substring(10, 11));
        setDfhpa3(source.substring(11, 12));
        setDfhpf1(source.substring(12, 13));
        setDfhpf2(source.substring(13, 14));
        setDfhpf3(source.substring(14, 15));
        setDfhpf4(source.substring(15, 16));
        setDfhpf5(source.substring(16, 17));
        setDfhpf6(source.substring(17, 18));
        setDfhpf7(source.substring(18, 19));
        setDfhpf8(source.substring(19, 20));
        setDfhpf9(source.substring(20, 21));
        setDfhpf10(source.substring(21, 22));
        setDfhpf11(source.substring(22, 23));
        setDfhpf12(source.substring(23, 24));
        setDfhpf13(source.substring(24, 25));
        setDfhpf14(source.substring(25, 26));
        setDfhpf15(source.substring(26, 27));
        setDfhpf16(source.substring(27, 28));
        setDfhpf17(source.substring(28, 29));
        setDfhpf18(source.substring(29, 30));
        setDfhpf19(source.substring(30, 31));
        setDfhpf20(source.substring(31, 32));
        setDfhpf21(source.substring(32, 33));
        setDfhpf22(source.substring(33, 34));
        setDfhpf23(source.substring(34, 35));
        setDfhpf24(source.substring(35, 36));
    }

    public String get() {
        StringBuilder sb = new StringBuilder();
        sb.append(getDfhnull());
        sb.append(getDfhenter());
        sb.append(getDfhclear());
        sb.append(getDfhclrp());
        sb.append(getDfhpen());
        sb.append(getDfhopid());
        sb.append(getDfhmsre());
        sb.append(getDfhstrf());
        sb.append(getDfhtrig());
        sb.append(getDfhpa1());
        sb.append(getDfhpa2());
        sb.append(getDfhpa3());
        sb.append(getDfhpf1());
        sb.append(getDfhpf2());
        sb.append(getDfhpf3());
        sb.append(getDfhpf4());
        sb.append(getDfhpf5());
        sb.append(getDfhpf6());
        sb.append(getDfhpf7());
        sb.append(getDfhpf8());
        sb.append(getDfhpf9());
        sb.append(getDfhpf10());
        sb.append(getDfhpf11());
        sb.append(getDfhpf12());
        sb.append(getDfhpf13());
        sb.append(getDfhpf14());
        sb.append(getDfhpf15());
        sb.append(getDfhpf16());
        sb.append(getDfhpf17());
        sb.append(getDfhpf18());
        sb.append(getDfhpf19());
        sb.append(getDfhpf20());
        sb.append(getDfhpf21());
        sb.append(getDfhpf22());
        sb.append(getDfhpf23());
        sb.append(getDfhpf24());
        return sb.toString();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getDfhnull());
        sb.append(getDfhenter());
        sb.append(getDfhclear());
        sb.append(getDfhclrp());
        sb.append(getDfhpen());
        sb.append(getDfhopid());
        sb.append(getDfhmsre());
        sb.append(getDfhstrf());
        sb.append(getDfhtrig());
        sb.append(getDfhpa1());
        sb.append(getDfhpa2());
        sb.append(getDfhpa3());
        sb.append(getDfhpf1());
        sb.append(getDfhpf2());
        sb.append(getDfhpf3());
        sb.append(getDfhpf4());
        sb.append(getDfhpf5());
        sb.append(getDfhpf6());
        sb.append(getDfhpf7());
        sb.append(getDfhpf8());
        sb.append(getDfhpf9());
        sb.append(getDfhpf10());
        sb.append(getDfhpf11());
        sb.append(getDfhpf12());
        sb.append(getDfhpf13());
        sb.append(getDfhpf14());
        sb.append(getDfhpf15());
        sb.append(getDfhpf16());
        sb.append(getDfhpf17());
        sb.append(getDfhpf18());
        sb.append(getDfhpf19());
        sb.append(getDfhpf20());
        sb.append(getDfhpf21());
        sb.append(getDfhpf22());
        sb.append(getDfhpf23());
        sb.append(getDfhpf24());
        return sb.toString();
    }

    public void setDfhnull(String source) {
        dfhnull = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhenter(String source) {
        dfhenter = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhclear(String source) {
        dfhclear = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhclrp(String source) {
        dfhclrp = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpen(String source) {
        dfhpen = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhopid(String source) {
        dfhopid = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhmsre(String source) {
        dfhmsre = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhstrf(String source) {
        dfhstrf = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhtrig(String source) {
        dfhtrig = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpa1(String source) {
        dfhpa1 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpa2(String source) {
        dfhpa2 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpa3(String source) {
        dfhpa3 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf1(String source) {
        dfhpf1 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf2(String source) {
        dfhpf2 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf3(String source) {
        dfhpf3 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf4(String source) {
        dfhpf4 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf5(String source) {
        dfhpf5 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf6(String source) {
        dfhpf6 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf7(String source) {
        dfhpf7 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf8(String source) {
        dfhpf8 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf9(String source) {
        dfhpf9 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf10(String source) {
        dfhpf10 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf11(String source) {
        dfhpf11 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf12(String source) {
        dfhpf12 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf13(String source) {
        dfhpf13 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf14(String source) {
        dfhpf14 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf15(String source) {
        dfhpf15 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf16(String source) {
        dfhpf16 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf17(String source) {
        dfhpf17 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf18(String source) {
        dfhpf18 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf19(String source) {
        dfhpf19 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf20(String source) {
        dfhpf20 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf21(String source) {
        dfhpf21 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf22(String source) {
        dfhpf22 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf23(String source) {
        dfhpf23 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }

    public void setDfhpf24(String source) {
        dfhpf24 = StringUtils.truncate(StringUtils.rightPad(source, 1), 1);
    }
}
