package com.tmax.openframe.variable;

import com.tmax.openframe.runtime.cobol.CobStream;
import com.tmax.openframe.variable.group.*;
import java.math.*;
import java.util.*;
import lombok.*;
import org.apache.commons.lang3.StringUtils;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:17 KST</p>
 * <hr>
 * <p>Class that defines variables that defined in the data division of COBOL program</p>
 */
public class Comen01cVariableContainer {
    // *----------------------------------------------------------------*
    // *                     WORKING STORAGE SECTION
    // *----------------------------------------------------------------*
    // [T-Up#INFO][COMEN01C.cbl:35] WS-VARIABLES (level: 1)
    private @Getter @Setter Comen01cWsVariables wsVariables = new Comen01cWsVariables();
    //       *COPY COCOM01Y.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/COCOM01Y.cpy)
    // ******************************************************************
    // * Communication area for CardDemo application programs
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // [T-Up#INFO][COCOM01Y.cpy:20] CARDDEMO-COMMAREA (level: 1)
    private @Getter @Setter CarddemoCommarea carddemoCommarea = new CarddemoCommarea();
    // *
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:15:57 CDT
    // *
    //       *COPY COMEN02Y.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/COMEN02Y.cpy)
    // ******************************************************************
    // * CardDemo - Admin Menu Options
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // [T-Up#INFO][COMEN02Y.cpy:20] CARDDEMO-MAIN-MENU-OPTIONS (level: 1)
    private @Getter @Setter CarddemoMainMenuOptions carddemoMainMenuOptions = new CarddemoMainMenuOptions();
    // *
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:15:58 CDT
    // *
    //       *COPY COMEN01.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/COMEN01.CPY)
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // [T-Up#INFO][COMEN01.CPY:18] COMEN1AI (level: 1)
    private @Getter @Setter Comen1ai comen1ai = new Comen1ai();
    //       *COPY COTTL01Y.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/COTTL01Y.cpy)
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // [T-Up#INFO][COTTL01Y.cpy:18] CCDA-SCREEN-TITLE (level: 1)
    private @Getter @Setter CcdaScreenTitle ccdaScreenTitle = new CcdaScreenTitle();
    // *
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:15:58 CDT
    // *
    //       *COPY CSDAT01Y.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/CSDAT01Y.cpy)
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // [T-Up#INFO][CSDAT01Y.cpy:18] WS-DATE-TIME (level: 1)
    private @Getter @Setter WsDateTime wsDateTime = new WsDateTime();
    // *
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:15:58 CDT
    // *
    //       *COPY CSMSG01Y.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/CSMSG01Y.cpy)
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // [T-Up#INFO][CSMSG01Y.cpy:18] CCDA-COMMON-MESSAGES (level: 1)
    private @Getter @Setter CcdaCommonMessages ccdaCommonMessages = new CcdaCommonMessages();
    // *
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:15:58 CDT
    // *
    //       *COPY CSUSR01Y.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/CSUSR01Y.cpy)
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // [T-Up#INFO][CSUSR01Y.cpy:18] SEC-USER-DATA (level: 1)
    private @Getter @Setter SecUserData secUserData = new SecUserData();
    // *
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:15:59 CDT
    // *
    //       *COPY DFHAID.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/DFHAID.cpy)
    // [T-Up#INFO][DFHAID.cpy:2] DFHAID (level: 1)
    private @Getter @Setter Dfhaid dfhaid = new Dfhaid();
    //       *COPY DFHBMSCA.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/DFHBMSCA.cpy)
    // [T-Up#INFO][DFHBMSCA.cpy:2] DFHBMSCA (level: 1)
    private @Getter @Setter Dfhbmsca dfhbmsca = new Dfhbmsca();
    // *----------------------------------------------------------------*
    // *                        LINKAGE SECTION
    // *----------------------------------------------------------------*
    // [T-Up#INFO][COMEN01C.cbl:67] DFHCOMMAREA (level: 1)
    private @Getter @Setter Comen01cDfhcommarea dfhcommarea = new Comen01cDfhcommarea();

    public Comen01cComen1ao getComen1ao() {
        return Comen01cComen1ao.builder()
                .FILLER_REDEFINE_41(getFILLER_REDEFINE_41())
                .FILLER_REDEFINE_42(getFILLER_REDEFINE_42())
                .trnnamec(getTrnnamec()).trnnamep(getTrnnamep())
                .trnnameh(getTrnnameh()).trnnamev(getTrnnamev())
                .trnnameo(getTrnnameo())
                .FILLER_REDEFINE_43(getFILLER_REDEFINE_43())
                .title01c(getTitle01c()).title01p(getTitle01p())
                .title01h(getTitle01h()).title01v(getTitle01v())
                .title01o(getTitle01o())
                .FILLER_REDEFINE_44(getFILLER_REDEFINE_44())
                .curdatec(getCurdatec()).curdatep(getCurdatep())
                .curdateh(getCurdateh()).curdatev(getCurdatev())
                .curdateo(getCurdateo())
                .FILLER_REDEFINE_45(getFILLER_REDEFINE_45())
                .pgmnamec(getPgmnamec()).pgmnamep(getPgmnamep())
                .pgmnameh(getPgmnameh()).pgmnamev(getPgmnamev())
                .pgmnameo(getPgmnameo())
                .FILLER_REDEFINE_46(getFILLER_REDEFINE_46())
                .title02c(getTitle02c()).title02p(getTitle02p())
                .title02h(getTitle02h()).title02v(getTitle02v())
                .title02o(getTitle02o())
                .FILLER_REDEFINE_47(getFILLER_REDEFINE_47())
                .curtimec(getCurtimec()).curtimep(getCurtimep())
                .curtimeh(getCurtimeh()).curtimev(getCurtimev())
                .curtimeo(getCurtimeo())
                .FILLER_REDEFINE_48(getFILLER_REDEFINE_48())
                .optn001c(getOptn001c()).optn001p(getOptn001p())
                .optn001h(getOptn001h()).optn001v(getOptn001v())
                .optn001o(getOptn001o())
                .FILLER_REDEFINE_49(getFILLER_REDEFINE_49())
                .optn002c(getOptn002c()).optn002p(getOptn002p())
                .optn002h(getOptn002h()).optn002v(getOptn002v())
                .optn002o(getOptn002o())
                .FILLER_REDEFINE_50(getFILLER_REDEFINE_50())
                .optn003c(getOptn003c()).optn003p(getOptn003p())
                .optn003h(getOptn003h()).optn003v(getOptn003v())
                .optn003o(getOptn003o())
                .FILLER_REDEFINE_51(getFILLER_REDEFINE_51())
                .optn004c(getOptn004c()).optn004p(getOptn004p())
                .optn004h(getOptn004h()).optn004v(getOptn004v())
                .optn004o(getOptn004o())
                .FILLER_REDEFINE_52(getFILLER_REDEFINE_52())
                .optn005c(getOptn005c()).optn005p(getOptn005p())
                .optn005h(getOptn005h()).optn005v(getOptn005v())
                .optn005o(getOptn005o())
                .FILLER_REDEFINE_53(getFILLER_REDEFINE_53())
                .optn006c(getOptn006c()).optn006p(getOptn006p())
                .optn006h(getOptn006h()).optn006v(getOptn006v())
                .optn006o(getOptn006o())
                .FILLER_REDEFINE_54(getFILLER_REDEFINE_54())
                .optn007c(getOptn007c()).optn007p(getOptn007p())
                .optn007h(getOptn007h()).optn007v(getOptn007v())
                .optn007o(getOptn007o())
                .FILLER_REDEFINE_55(getFILLER_REDEFINE_55())
                .optn008c(getOptn008c()).optn008p(getOptn008p())
                .optn008h(getOptn008h()).optn008v(getOptn008v())
                .optn008o(getOptn008o())
                .FILLER_REDEFINE_56(getFILLER_REDEFINE_56())
                .optn009c(getOptn009c()).optn009p(getOptn009p())
                .optn009h(getOptn009h()).optn009v(getOptn009v())
                .optn009o(getOptn009o())
                .FILLER_REDEFINE_57(getFILLER_REDEFINE_57())
                .optn010c(getOptn010c()).optn010p(getOptn010p())
                .optn010h(getOptn010h()).optn010v(getOptn010v())
                .optn010o(getOptn010o())
                .FILLER_REDEFINE_58(getFILLER_REDEFINE_58())
                .optn011c(getOptn011c()).optn011p(getOptn011p())
                .optn011h(getOptn011h()).optn011v(getOptn011v())
                .optn011o(getOptn011o())
                .FILLER_REDEFINE_59(getFILLER_REDEFINE_59())
                .optn012c(getOptn012c()).optn012p(getOptn012p())
                .optn012h(getOptn012h()).optn012v(getOptn012v())
                .optn012o(getOptn012o())
                .FILLER_REDEFINE_60(getFILLER_REDEFINE_60())
                .optionc(getOptionc()).optionp(getOptionp())
                .optionh(getOptionh()).optionv(getOptionv())
                .optiono(getOptiono())
                .FILLER_REDEFINE_61(getFILLER_REDEFINE_61())
                .errmsgc(getErrmsgc()).errmsgp(getErrmsgp())
                .errmsgh(getErrmsgh()).errmsgv(getErrmsgv())
                .errmsgo(getErrmsgo()).build();
    }

    public void setComen1ao(String source) {
        setFILLER_REDEFINE_41(source.substring(0, 12));
        setFILLER_REDEFINE_42(source.substring(12, 15));
        setTrnnamec(source.substring(15, 16));
        setTrnnamep(source.substring(16, 17));
        setTrnnameh(source.substring(17, 18));
        setTrnnamev(source.substring(18, 19));
        setTrnnameo(source.substring(19, 23));
        setFILLER_REDEFINE_43(source.substring(23, 26));
        setTitle01c(source.substring(26, 27));
        setTitle01p(source.substring(27, 28));
        setTitle01h(source.substring(28, 29));
        setTitle01v(source.substring(29, 30));
        setTitle01o(source.substring(30, 70));
        setFILLER_REDEFINE_44(source.substring(70, 73));
        setCurdatec(source.substring(73, 74));
        setCurdatep(source.substring(74, 75));
        setCurdateh(source.substring(75, 76));
        setCurdatev(source.substring(76, 77));
        setCurdateo(source.substring(77, 85));
        setFILLER_REDEFINE_45(source.substring(85, 88));
        setPgmnamec(source.substring(88, 89));
        setPgmnamep(source.substring(89, 90));
        setPgmnameh(source.substring(90, 91));
        setPgmnamev(source.substring(91, 92));
        setPgmnameo(source.substring(92, 100));
        setFILLER_REDEFINE_46(source.substring(100, 103));
        setTitle02c(source.substring(103, 104));
        setTitle02p(source.substring(104, 105));
        setTitle02h(source.substring(105, 106));
        setTitle02v(source.substring(106, 107));
        setTitle02o(source.substring(107, 147));
        setFILLER_REDEFINE_47(source.substring(147, 150));
        setCurtimec(source.substring(150, 151));
        setCurtimep(source.substring(151, 152));
        setCurtimeh(source.substring(152, 153));
        setCurtimev(source.substring(153, 154));
        setCurtimeo(source.substring(154, 162));
        setFILLER_REDEFINE_48(source.substring(162, 165));
        setOptn001c(source.substring(165, 166));
        setOptn001p(source.substring(166, 167));
        setOptn001h(source.substring(167, 168));
        setOptn001v(source.substring(168, 169));
        setOptn001o(source.substring(169, 209));
        setFILLER_REDEFINE_49(source.substring(209, 212));
        setOptn002c(source.substring(212, 213));
        setOptn002p(source.substring(213, 214));
        setOptn002h(source.substring(214, 215));
        setOptn002v(source.substring(215, 216));
        setOptn002o(source.substring(216, 256));
        setFILLER_REDEFINE_50(source.substring(256, 259));
        setOptn003c(source.substring(259, 260));
        setOptn003p(source.substring(260, 261));
        setOptn003h(source.substring(261, 262));
        setOptn003v(source.substring(262, 263));
        setOptn003o(source.substring(263, 303));
        setFILLER_REDEFINE_51(source.substring(303, 306));
        setOptn004c(source.substring(306, 307));
        setOptn004p(source.substring(307, 308));
        setOptn004h(source.substring(308, 309));
        setOptn004v(source.substring(309, 310));
        setOptn004o(source.substring(310, 350));
        setFILLER_REDEFINE_52(source.substring(350, 353));
        setOptn005c(source.substring(353, 354));
        setOptn005p(source.substring(354, 355));
        setOptn005h(source.substring(355, 356));
        setOptn005v(source.substring(356, 357));
        setOptn005o(source.substring(357, 397));
        setFILLER_REDEFINE_53(source.substring(397, 400));
        setOptn006c(source.substring(400, 401));
        setOptn006p(source.substring(401, 402));
        setOptn006h(source.substring(402, 403));
        setOptn006v(source.substring(403, 404));
        setOptn006o(source.substring(404, 444));
        setFILLER_REDEFINE_54(source.substring(444, 447));
        setOptn007c(source.substring(447, 448));
        setOptn007p(source.substring(448, 449));
        setOptn007h(source.substring(449, 450));
        setOptn007v(source.substring(450, 451));
        setOptn007o(source.substring(451, 491));
        setFILLER_REDEFINE_55(source.substring(491, 494));
        setOptn008c(source.substring(494, 495));
        setOptn008p(source.substring(495, 496));
        setOptn008h(source.substring(496, 497));
        setOptn008v(source.substring(497, 498));
        setOptn008o(source.substring(498, 538));
        setFILLER_REDEFINE_56(source.substring(538, 541));
        setOptn009c(source.substring(541, 542));
        setOptn009p(source.substring(542, 543));
        setOptn009h(source.substring(543, 544));
        setOptn009v(source.substring(544, 545));
        setOptn009o(source.substring(545, 585));
        setFILLER_REDEFINE_57(source.substring(585, 588));
        setOptn010c(source.substring(588, 589));
        setOptn010p(source.substring(589, 590));
        setOptn010h(source.substring(590, 591));
        setOptn010v(source.substring(591, 592));
        setOptn010o(source.substring(592, 632));
        setFILLER_REDEFINE_58(source.substring(632, 635));
        setOptn011c(source.substring(635, 636));
        setOptn011p(source.substring(636, 637));
        setOptn011h(source.substring(637, 638));
        setOptn011v(source.substring(638, 639));
        setOptn011o(source.substring(639, 679));
        setFILLER_REDEFINE_59(source.substring(679, 682));
        setOptn012c(source.substring(682, 683));
        setOptn012p(source.substring(683, 684));
        setOptn012h(source.substring(684, 685));
        setOptn012v(source.substring(685, 686));
        setOptn012o(source.substring(686, 726));
        setFILLER_REDEFINE_60(source.substring(726, 729));
        setOptionc(source.substring(729, 730));
        setOptionp(source.substring(730, 731));
        setOptionh(source.substring(731, 732));
        setOptionv(source.substring(732, 733));
        setOptiono(source.substring(733, 735));
        setFILLER_REDEFINE_61(source.substring(735, 738));
        setErrmsgc(source.substring(738, 739));
        setErrmsgp(source.substring(739, 740));
        setErrmsgh(source.substring(740, 741));
        setErrmsgv(source.substring(741, 742));
        setErrmsgo(source.substring(742, 820));
    }

    public void setComen1ao(Comen01cComen1ao source) {
        setComen1ao(source.get());
    }

    public String getFILLER_REDEFINE_41() {
        return getComen1ai().getFILLER_1();
    }

    public void setFILLER_REDEFINE_41(String source) {
        getComen1ai().setFILLER_1(source);
    }

    public String getFILLER_REDEFINE_42() {
        return CobStream.convShortToString((short) getComen1ai().getTrnnamel())
                + getComen1ai().getTrnnamef();
    }

    public void setFILLER_REDEFINE_42(String source) {
        try {
            getComen1ai().setTrnnamel(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setTrnnamel(0);
        }
        getComen1ai().setTrnnamef(source.substring(2, 3));
    }

    public String getTrnnamec() {
        return getComen1ai().getFILLER_2().substring(0, 1);
    }

    public void setTrnnamec(String source) {
        getComen1ai().setFILLER_2(
                StringUtils.overlay(getComen1ai().getFILLER_2(), source, 0, 1));
    }

    public String getTrnnamep() {
        return getComen1ai().getFILLER_2().substring(1, 2);
    }

    public void setTrnnamep(String source) {
        getComen1ai().setFILLER_2(
                StringUtils.overlay(getComen1ai().getFILLER_2(), source, 1, 2));
    }

    public String getTrnnameh() {
        return getComen1ai().getFILLER_2().substring(2, 3);
    }

    public void setTrnnameh(String source) {
        getComen1ai().setFILLER_2(
                StringUtils.overlay(getComen1ai().getFILLER_2(), source, 2, 3));
    }

    public String getTrnnamev() {
        return getComen1ai().getFILLER_2().substring(3, 4);
    }

    public void setTrnnamev(String source) {
        getComen1ai().setFILLER_2(
                StringUtils.overlay(getComen1ai().getFILLER_2(), source, 3, 4));
    }

    public String getTrnnameo() {
        return getComen1ai().getTrnnamei();
    }

    public void setTrnnameo(String source) {
        getComen1ai().setTrnnamei(source);
    }

    public String getFILLER_REDEFINE_43() {
        return CobStream.convShortToString((short) getComen1ai().getTitle01l())
                + getComen1ai().getTitle01f();
    }

    public void setFILLER_REDEFINE_43(String source) {
        try {
            getComen1ai().setTitle01l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setTitle01l(0);
        }
        getComen1ai().setTitle01f(source.substring(2, 3));
    }

    public String getTitle01c() {
        return getComen1ai().getFILLER_3().substring(0, 1);
    }

    public void setTitle01c(String source) {
        getComen1ai().setFILLER_3(
                StringUtils.overlay(getComen1ai().getFILLER_3(), source, 0, 1));
    }

    public String getTitle01p() {
        return getComen1ai().getFILLER_3().substring(1, 2);
    }

    public void setTitle01p(String source) {
        getComen1ai().setFILLER_3(
                StringUtils.overlay(getComen1ai().getFILLER_3(), source, 1, 2));
    }

    public String getTitle01h() {
        return getComen1ai().getFILLER_3().substring(2, 3);
    }

    public void setTitle01h(String source) {
        getComen1ai().setFILLER_3(
                StringUtils.overlay(getComen1ai().getFILLER_3(), source, 2, 3));
    }

    public String getTitle01v() {
        return getComen1ai().getFILLER_3().substring(3, 4);
    }

    public void setTitle01v(String source) {
        getComen1ai().setFILLER_3(
                StringUtils.overlay(getComen1ai().getFILLER_3(), source, 3, 4));
    }

    public String getTitle01o() {
        return getComen1ai().getTitle01i();
    }

    public void setTitle01o(String source) {
        getComen1ai().setTitle01i(source);
    }

    public String getFILLER_REDEFINE_44() {
        return CobStream.convShortToString((short) getComen1ai().getCurdatel())
                + getComen1ai().getCurdatef();
    }

    public void setFILLER_REDEFINE_44(String source) {
        try {
            getComen1ai().setCurdatel(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setCurdatel(0);
        }
        getComen1ai().setCurdatef(source.substring(2, 3));
    }

    public String getCurdatec() {
        return getComen1ai().getFILLER_4().substring(0, 1);
    }

    public void setCurdatec(String source) {
        getComen1ai().setFILLER_4(
                StringUtils.overlay(getComen1ai().getFILLER_4(), source, 0, 1));
    }

    public String getCurdatep() {
        return getComen1ai().getFILLER_4().substring(1, 2);
    }

    public void setCurdatep(String source) {
        getComen1ai().setFILLER_4(
                StringUtils.overlay(getComen1ai().getFILLER_4(), source, 1, 2));
    }

    public String getCurdateh() {
        return getComen1ai().getFILLER_4().substring(2, 3);
    }

    public void setCurdateh(String source) {
        getComen1ai().setFILLER_4(
                StringUtils.overlay(getComen1ai().getFILLER_4(), source, 2, 3));
    }

    public String getCurdatev() {
        return getComen1ai().getFILLER_4().substring(3, 4);
    }

    public void setCurdatev(String source) {
        getComen1ai().setFILLER_4(
                StringUtils.overlay(getComen1ai().getFILLER_4(), source, 3, 4));
    }

    public String getCurdateo() {
        return getComen1ai().getCurdatei();
    }

    public void setCurdateo(String source) {
        getComen1ai().setCurdatei(source);
    }

    public String getFILLER_REDEFINE_45() {
        return CobStream.convShortToString((short) getComen1ai().getPgmnamel())
                + getComen1ai().getPgmnamef();
    }

    public void setFILLER_REDEFINE_45(String source) {
        try {
            getComen1ai().setPgmnamel(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setPgmnamel(0);
        }
        getComen1ai().setPgmnamef(source.substring(2, 3));
    }

    public String getPgmnamec() {
        return getComen1ai().getFILLER_5().substring(0, 1);
    }

    public void setPgmnamec(String source) {
        getComen1ai().setFILLER_5(
                StringUtils.overlay(getComen1ai().getFILLER_5(), source, 0, 1));
    }

    public String getPgmnamep() {
        return getComen1ai().getFILLER_5().substring(1, 2);
    }

    public void setPgmnamep(String source) {
        getComen1ai().setFILLER_5(
                StringUtils.overlay(getComen1ai().getFILLER_5(), source, 1, 2));
    }

    public String getPgmnameh() {
        return getComen1ai().getFILLER_5().substring(2, 3);
    }

    public void setPgmnameh(String source) {
        getComen1ai().setFILLER_5(
                StringUtils.overlay(getComen1ai().getFILLER_5(), source, 2, 3));
    }

    public String getPgmnamev() {
        return getComen1ai().getFILLER_5().substring(3, 4);
    }

    public void setPgmnamev(String source) {
        getComen1ai().setFILLER_5(
                StringUtils.overlay(getComen1ai().getFILLER_5(), source, 3, 4));
    }

    public String getPgmnameo() {
        return getComen1ai().getPgmnamei();
    }

    public void setPgmnameo(String source) {
        getComen1ai().setPgmnamei(source);
    }

    public String getFILLER_REDEFINE_46() {
        return CobStream.convShortToString((short) getComen1ai().getTitle02l())
                + getComen1ai().getTitle02f();
    }

    public void setFILLER_REDEFINE_46(String source) {
        try {
            getComen1ai().setTitle02l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setTitle02l(0);
        }
        getComen1ai().setTitle02f(source.substring(2, 3));
    }

    public String getTitle02c() {
        return getComen1ai().getFILLER_6().substring(0, 1);
    }

    public void setTitle02c(String source) {
        getComen1ai().setFILLER_6(
                StringUtils.overlay(getComen1ai().getFILLER_6(), source, 0, 1));
    }

    public String getTitle02p() {
        return getComen1ai().getFILLER_6().substring(1, 2);
    }

    public void setTitle02p(String source) {
        getComen1ai().setFILLER_6(
                StringUtils.overlay(getComen1ai().getFILLER_6(), source, 1, 2));
    }

    public String getTitle02h() {
        return getComen1ai().getFILLER_6().substring(2, 3);
    }

    public void setTitle02h(String source) {
        getComen1ai().setFILLER_6(
                StringUtils.overlay(getComen1ai().getFILLER_6(), source, 2, 3));
    }

    public String getTitle02v() {
        return getComen1ai().getFILLER_6().substring(3, 4);
    }

    public void setTitle02v(String source) {
        getComen1ai().setFILLER_6(
                StringUtils.overlay(getComen1ai().getFILLER_6(), source, 3, 4));
    }

    public String getTitle02o() {
        return getComen1ai().getTitle02i();
    }

    public void setTitle02o(String source) {
        getComen1ai().setTitle02i(source);
    }

    public String getFILLER_REDEFINE_47() {
        return CobStream.convShortToString((short) getComen1ai().getCurtimel())
                + getComen1ai().getCurtimef();
    }

    public void setFILLER_REDEFINE_47(String source) {
        try {
            getComen1ai().setCurtimel(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setCurtimel(0);
        }
        getComen1ai().setCurtimef(source.substring(2, 3));
    }

    public String getCurtimec() {
        return getComen1ai().getFILLER_7().substring(0, 1);
    }

    public void setCurtimec(String source) {
        getComen1ai().setFILLER_7(
                StringUtils.overlay(getComen1ai().getFILLER_7(), source, 0, 1));
    }

    public String getCurtimep() {
        return getComen1ai().getFILLER_7().substring(1, 2);
    }

    public void setCurtimep(String source) {
        getComen1ai().setFILLER_7(
                StringUtils.overlay(getComen1ai().getFILLER_7(), source, 1, 2));
    }

    public String getCurtimeh() {
        return getComen1ai().getFILLER_7().substring(2, 3);
    }

    public void setCurtimeh(String source) {
        getComen1ai().setFILLER_7(
                StringUtils.overlay(getComen1ai().getFILLER_7(), source, 2, 3));
    }

    public String getCurtimev() {
        return getComen1ai().getFILLER_7().substring(3, 4);
    }

    public void setCurtimev(String source) {
        getComen1ai().setFILLER_7(
                StringUtils.overlay(getComen1ai().getFILLER_7(), source, 3, 4));
    }

    public String getCurtimeo() {
        return getComen1ai().getCurtimei();
    }

    public void setCurtimeo(String source) {
        getComen1ai().setCurtimei(source);
    }

    public String getFILLER_REDEFINE_48() {
        return CobStream.convShortToString((short) getComen1ai().getOptn001l())
                + getComen1ai().getOptn001f();
    }

    public void setFILLER_REDEFINE_48(String source) {
        try {
            getComen1ai().setOptn001l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setOptn001l(0);
        }
        getComen1ai().setOptn001f(source.substring(2, 3));
    }

    public String getOptn001c() {
        return getComen1ai().getFILLER_8().substring(0, 1);
    }

    public void setOptn001c(String source) {
        getComen1ai().setFILLER_8(
                StringUtils.overlay(getComen1ai().getFILLER_8(), source, 0, 1));
    }

    public String getOptn001p() {
        return getComen1ai().getFILLER_8().substring(1, 2);
    }

    public void setOptn001p(String source) {
        getComen1ai().setFILLER_8(
                StringUtils.overlay(getComen1ai().getFILLER_8(), source, 1, 2));
    }

    public String getOptn001h() {
        return getComen1ai().getFILLER_8().substring(2, 3);
    }

    public void setOptn001h(String source) {
        getComen1ai().setFILLER_8(
                StringUtils.overlay(getComen1ai().getFILLER_8(), source, 2, 3));
    }

    public String getOptn001v() {
        return getComen1ai().getFILLER_8().substring(3, 4);
    }

    public void setOptn001v(String source) {
        getComen1ai().setFILLER_8(
                StringUtils.overlay(getComen1ai().getFILLER_8(), source, 3, 4));
    }

    public String getOptn001o() {
        return getComen1ai().getOptn001i();
    }

    public void setOptn001o(String source) {
        getComen1ai().setOptn001i(source);
    }

    public String getFILLER_REDEFINE_49() {
        return CobStream.convShortToString((short) getComen1ai().getOptn002l())
                + getComen1ai().getOptn002f();
    }

    public void setFILLER_REDEFINE_49(String source) {
        try {
            getComen1ai().setOptn002l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setOptn002l(0);
        }
        getComen1ai().setOptn002f(source.substring(2, 3));
    }

    public String getOptn002c() {
        return getComen1ai().getFILLER_9().substring(0, 1);
    }

    public void setOptn002c(String source) {
        getComen1ai().setFILLER_9(
                StringUtils.overlay(getComen1ai().getFILLER_9(), source, 0, 1));
    }

    public String getOptn002p() {
        return getComen1ai().getFILLER_9().substring(1, 2);
    }

    public void setOptn002p(String source) {
        getComen1ai().setFILLER_9(
                StringUtils.overlay(getComen1ai().getFILLER_9(), source, 1, 2));
    }

    public String getOptn002h() {
        return getComen1ai().getFILLER_9().substring(2, 3);
    }

    public void setOptn002h(String source) {
        getComen1ai().setFILLER_9(
                StringUtils.overlay(getComen1ai().getFILLER_9(), source, 2, 3));
    }

    public String getOptn002v() {
        return getComen1ai().getFILLER_9().substring(3, 4);
    }

    public void setOptn002v(String source) {
        getComen1ai().setFILLER_9(
                StringUtils.overlay(getComen1ai().getFILLER_9(), source, 3, 4));
    }

    public String getOptn002o() {
        return getComen1ai().getOptn002i();
    }

    public void setOptn002o(String source) {
        getComen1ai().setOptn002i(source);
    }

    public String getFILLER_REDEFINE_50() {
        return CobStream.convShortToString((short) getComen1ai().getOptn003l())
                + getComen1ai().getOptn003f();
    }

    public void setFILLER_REDEFINE_50(String source) {
        try {
            getComen1ai().setOptn003l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setOptn003l(0);
        }
        getComen1ai().setOptn003f(source.substring(2, 3));
    }

    public String getOptn003c() {
        return getComen1ai().getFILLER_10().substring(0, 1);
    }

    public void setOptn003c(String source) {
        getComen1ai()
                .setFILLER_10(
                        StringUtils.overlay(getComen1ai().getFILLER_10(),
                                source, 0, 1));
    }

    public String getOptn003p() {
        return getComen1ai().getFILLER_10().substring(1, 2);
    }

    public void setOptn003p(String source) {
        getComen1ai()
                .setFILLER_10(
                        StringUtils.overlay(getComen1ai().getFILLER_10(),
                                source, 1, 2));
    }

    public String getOptn003h() {
        return getComen1ai().getFILLER_10().substring(2, 3);
    }

    public void setOptn003h(String source) {
        getComen1ai()
                .setFILLER_10(
                        StringUtils.overlay(getComen1ai().getFILLER_10(),
                                source, 2, 3));
    }

    public String getOptn003v() {
        return getComen1ai().getFILLER_10().substring(3, 4);
    }

    public void setOptn003v(String source) {
        getComen1ai()
                .setFILLER_10(
                        StringUtils.overlay(getComen1ai().getFILLER_10(),
                                source, 3, 4));
    }

    public String getOptn003o() {
        return getComen1ai().getOptn003i();
    }

    public void setOptn003o(String source) {
        getComen1ai().setOptn003i(source);
    }

    public String getFILLER_REDEFINE_51() {
        return CobStream.convShortToString((short) getComen1ai().getOptn004l())
                + getComen1ai().getOptn004f();
    }

    public void setFILLER_REDEFINE_51(String source) {
        try {
            getComen1ai().setOptn004l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setOptn004l(0);
        }
        getComen1ai().setOptn004f(source.substring(2, 3));
    }

    public String getOptn004c() {
        return getComen1ai().getFILLER_11().substring(0, 1);
    }

    public void setOptn004c(String source) {
        getComen1ai()
                .setFILLER_11(
                        StringUtils.overlay(getComen1ai().getFILLER_11(),
                                source, 0, 1));
    }

    public String getOptn004p() {
        return getComen1ai().getFILLER_11().substring(1, 2);
    }

    public void setOptn004p(String source) {
        getComen1ai()
                .setFILLER_11(
                        StringUtils.overlay(getComen1ai().getFILLER_11(),
                                source, 1, 2));
    }

    public String getOptn004h() {
        return getComen1ai().getFILLER_11().substring(2, 3);
    }

    public void setOptn004h(String source) {
        getComen1ai()
                .setFILLER_11(
                        StringUtils.overlay(getComen1ai().getFILLER_11(),
                                source, 2, 3));
    }

    public String getOptn004v() {
        return getComen1ai().getFILLER_11().substring(3, 4);
    }

    public void setOptn004v(String source) {
        getComen1ai()
                .setFILLER_11(
                        StringUtils.overlay(getComen1ai().getFILLER_11(),
                                source, 3, 4));
    }

    public String getOptn004o() {
        return getComen1ai().getOptn004i();
    }

    public void setOptn004o(String source) {
        getComen1ai().setOptn004i(source);
    }

    public String getFILLER_REDEFINE_52() {
        return CobStream.convShortToString((short) getComen1ai().getOptn005l())
                + getComen1ai().getOptn005f();
    }

    public void setFILLER_REDEFINE_52(String source) {
        try {
            getComen1ai().setOptn005l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setOptn005l(0);
        }
        getComen1ai().setOptn005f(source.substring(2, 3));
    }

    public String getOptn005c() {
        return getComen1ai().getFILLER_12().substring(0, 1);
    }

    public void setOptn005c(String source) {
        getComen1ai()
                .setFILLER_12(
                        StringUtils.overlay(getComen1ai().getFILLER_12(),
                                source, 0, 1));
    }

    public String getOptn005p() {
        return getComen1ai().getFILLER_12().substring(1, 2);
    }

    public void setOptn005p(String source) {
        getComen1ai()
                .setFILLER_12(
                        StringUtils.overlay(getComen1ai().getFILLER_12(),
                                source, 1, 2));
    }

    public String getOptn005h() {
        return getComen1ai().getFILLER_12().substring(2, 3);
    }

    public void setOptn005h(String source) {
        getComen1ai()
                .setFILLER_12(
                        StringUtils.overlay(getComen1ai().getFILLER_12(),
                                source, 2, 3));
    }

    public String getOptn005v() {
        return getComen1ai().getFILLER_12().substring(3, 4);
    }

    public void setOptn005v(String source) {
        getComen1ai()
                .setFILLER_12(
                        StringUtils.overlay(getComen1ai().getFILLER_12(),
                                source, 3, 4));
    }

    public String getOptn005o() {
        return getComen1ai().getOptn005i();
    }

    public void setOptn005o(String source) {
        getComen1ai().setOptn005i(source);
    }

    public String getFILLER_REDEFINE_53() {
        return CobStream.convShortToString((short) getComen1ai().getOptn006l())
                + getComen1ai().getOptn006f();
    }

    public void setFILLER_REDEFINE_53(String source) {
        try {
            getComen1ai().setOptn006l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setOptn006l(0);
        }
        getComen1ai().setOptn006f(source.substring(2, 3));
    }

    public String getOptn006c() {
        return getComen1ai().getFILLER_13().substring(0, 1);
    }

    public void setOptn006c(String source) {
        getComen1ai()
                .setFILLER_13(
                        StringUtils.overlay(getComen1ai().getFILLER_13(),
                                source, 0, 1));
    }

    public String getOptn006p() {
        return getComen1ai().getFILLER_13().substring(1, 2);
    }

    public void setOptn006p(String source) {
        getComen1ai()
                .setFILLER_13(
                        StringUtils.overlay(getComen1ai().getFILLER_13(),
                                source, 1, 2));
    }

    public String getOptn006h() {
        return getComen1ai().getFILLER_13().substring(2, 3);
    }

    public void setOptn006h(String source) {
        getComen1ai()
                .setFILLER_13(
                        StringUtils.overlay(getComen1ai().getFILLER_13(),
                                source, 2, 3));
    }

    public String getOptn006v() {
        return getComen1ai().getFILLER_13().substring(3, 4);
    }

    public void setOptn006v(String source) {
        getComen1ai()
                .setFILLER_13(
                        StringUtils.overlay(getComen1ai().getFILLER_13(),
                                source, 3, 4));
    }

    public String getOptn006o() {
        return getComen1ai().getOptn006i();
    }

    public void setOptn006o(String source) {
        getComen1ai().setOptn006i(source);
    }

    public String getFILLER_REDEFINE_54() {
        return CobStream.convShortToString((short) getComen1ai().getOptn007l())
                + getComen1ai().getOptn007f();
    }

    public void setFILLER_REDEFINE_54(String source) {
        try {
            getComen1ai().setOptn007l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setOptn007l(0);
        }
        getComen1ai().setOptn007f(source.substring(2, 3));
    }

    public String getOptn007c() {
        return getComen1ai().getFILLER_14().substring(0, 1);
    }

    public void setOptn007c(String source) {
        getComen1ai()
                .setFILLER_14(
                        StringUtils.overlay(getComen1ai().getFILLER_14(),
                                source, 0, 1));
    }

    public String getOptn007p() {
        return getComen1ai().getFILLER_14().substring(1, 2);
    }

    public void setOptn007p(String source) {
        getComen1ai()
                .setFILLER_14(
                        StringUtils.overlay(getComen1ai().getFILLER_14(),
                                source, 1, 2));
    }

    public String getOptn007h() {
        return getComen1ai().getFILLER_14().substring(2, 3);
    }

    public void setOptn007h(String source) {
        getComen1ai()
                .setFILLER_14(
                        StringUtils.overlay(getComen1ai().getFILLER_14(),
                                source, 2, 3));
    }

    public String getOptn007v() {
        return getComen1ai().getFILLER_14().substring(3, 4);
    }

    public void setOptn007v(String source) {
        getComen1ai()
                .setFILLER_14(
                        StringUtils.overlay(getComen1ai().getFILLER_14(),
                                source, 3, 4));
    }

    public String getOptn007o() {
        return getComen1ai().getOptn007i();
    }

    public void setOptn007o(String source) {
        getComen1ai().setOptn007i(source);
    }

    public String getFILLER_REDEFINE_55() {
        return CobStream.convShortToString((short) getComen1ai().getOptn008l())
                + getComen1ai().getOptn008f();
    }

    public void setFILLER_REDEFINE_55(String source) {
        try {
            getComen1ai().setOptn008l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setOptn008l(0);
        }
        getComen1ai().setOptn008f(source.substring(2, 3));
    }

    public String getOptn008c() {
        return getComen1ai().getFILLER_15().substring(0, 1);
    }

    public void setOptn008c(String source) {
        getComen1ai()
                .setFILLER_15(
                        StringUtils.overlay(getComen1ai().getFILLER_15(),
                                source, 0, 1));
    }

    public String getOptn008p() {
        return getComen1ai().getFILLER_15().substring(1, 2);
    }

    public void setOptn008p(String source) {
        getComen1ai()
                .setFILLER_15(
                        StringUtils.overlay(getComen1ai().getFILLER_15(),
                                source, 1, 2));
    }

    public String getOptn008h() {
        return getComen1ai().getFILLER_15().substring(2, 3);
    }

    public void setOptn008h(String source) {
        getComen1ai()
                .setFILLER_15(
                        StringUtils.overlay(getComen1ai().getFILLER_15(),
                                source, 2, 3));
    }

    public String getOptn008v() {
        return getComen1ai().getFILLER_15().substring(3, 4);
    }

    public void setOptn008v(String source) {
        getComen1ai()
                .setFILLER_15(
                        StringUtils.overlay(getComen1ai().getFILLER_15(),
                                source, 3, 4));
    }

    public String getOptn008o() {
        return getComen1ai().getOptn008i();
    }

    public void setOptn008o(String source) {
        getComen1ai().setOptn008i(source);
    }

    public String getFILLER_REDEFINE_56() {
        return CobStream.convShortToString((short) getComen1ai().getOptn009l())
                + getComen1ai().getOptn009f();
    }

    public void setFILLER_REDEFINE_56(String source) {
        try {
            getComen1ai().setOptn009l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setOptn009l(0);
        }
        getComen1ai().setOptn009f(source.substring(2, 3));
    }

    public String getOptn009c() {
        return getComen1ai().getFILLER_16().substring(0, 1);
    }

    public void setOptn009c(String source) {
        getComen1ai()
                .setFILLER_16(
                        StringUtils.overlay(getComen1ai().getFILLER_16(),
                                source, 0, 1));
    }

    public String getOptn009p() {
        return getComen1ai().getFILLER_16().substring(1, 2);
    }

    public void setOptn009p(String source) {
        getComen1ai()
                .setFILLER_16(
                        StringUtils.overlay(getComen1ai().getFILLER_16(),
                                source, 1, 2));
    }

    public String getOptn009h() {
        return getComen1ai().getFILLER_16().substring(2, 3);
    }

    public void setOptn009h(String source) {
        getComen1ai()
                .setFILLER_16(
                        StringUtils.overlay(getComen1ai().getFILLER_16(),
                                source, 2, 3));
    }

    public String getOptn009v() {
        return getComen1ai().getFILLER_16().substring(3, 4);
    }

    public void setOptn009v(String source) {
        getComen1ai()
                .setFILLER_16(
                        StringUtils.overlay(getComen1ai().getFILLER_16(),
                                source, 3, 4));
    }

    public String getOptn009o() {
        return getComen1ai().getOptn009i();
    }

    public void setOptn009o(String source) {
        getComen1ai().setOptn009i(source);
    }

    public String getFILLER_REDEFINE_57() {
        return CobStream.convShortToString((short) getComen1ai().getOptn010l())
                + getComen1ai().getOptn010f();
    }

    public void setFILLER_REDEFINE_57(String source) {
        try {
            getComen1ai().setOptn010l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setOptn010l(0);
        }
        getComen1ai().setOptn010f(source.substring(2, 3));
    }

    public String getOptn010c() {
        return getComen1ai().getFILLER_17().substring(0, 1);
    }

    public void setOptn010c(String source) {
        getComen1ai()
                .setFILLER_17(
                        StringUtils.overlay(getComen1ai().getFILLER_17(),
                                source, 0, 1));
    }

    public String getOptn010p() {
        return getComen1ai().getFILLER_17().substring(1, 2);
    }

    public void setOptn010p(String source) {
        getComen1ai()
                .setFILLER_17(
                        StringUtils.overlay(getComen1ai().getFILLER_17(),
                                source, 1, 2));
    }

    public String getOptn010h() {
        return getComen1ai().getFILLER_17().substring(2, 3);
    }

    public void setOptn010h(String source) {
        getComen1ai()
                .setFILLER_17(
                        StringUtils.overlay(getComen1ai().getFILLER_17(),
                                source, 2, 3));
    }

    public String getOptn010v() {
        return getComen1ai().getFILLER_17().substring(3, 4);
    }

    public void setOptn010v(String source) {
        getComen1ai()
                .setFILLER_17(
                        StringUtils.overlay(getComen1ai().getFILLER_17(),
                                source, 3, 4));
    }

    public String getOptn010o() {
        return getComen1ai().getOptn010i();
    }

    public void setOptn010o(String source) {
        getComen1ai().setOptn010i(source);
    }

    public String getFILLER_REDEFINE_58() {
        return CobStream.convShortToString((short) getComen1ai().getOptn011l())
                + getComen1ai().getOptn011f();
    }

    public void setFILLER_REDEFINE_58(String source) {
        try {
            getComen1ai().setOptn011l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setOptn011l(0);
        }
        getComen1ai().setOptn011f(source.substring(2, 3));
    }

    public String getOptn011c() {
        return getComen1ai().getFILLER_18().substring(0, 1);
    }

    public void setOptn011c(String source) {
        getComen1ai()
                .setFILLER_18(
                        StringUtils.overlay(getComen1ai().getFILLER_18(),
                                source, 0, 1));
    }

    public String getOptn011p() {
        return getComen1ai().getFILLER_18().substring(1, 2);
    }

    public void setOptn011p(String source) {
        getComen1ai()
                .setFILLER_18(
                        StringUtils.overlay(getComen1ai().getFILLER_18(),
                                source, 1, 2));
    }

    public String getOptn011h() {
        return getComen1ai().getFILLER_18().substring(2, 3);
    }

    public void setOptn011h(String source) {
        getComen1ai()
                .setFILLER_18(
                        StringUtils.overlay(getComen1ai().getFILLER_18(),
                                source, 2, 3));
    }

    public String getOptn011v() {
        return getComen1ai().getFILLER_18().substring(3, 4);
    }

    public void setOptn011v(String source) {
        getComen1ai()
                .setFILLER_18(
                        StringUtils.overlay(getComen1ai().getFILLER_18(),
                                source, 3, 4));
    }

    public String getOptn011o() {
        return getComen1ai().getOptn011i();
    }

    public void setOptn011o(String source) {
        getComen1ai().setOptn011i(source);
    }

    public String getFILLER_REDEFINE_59() {
        return CobStream.convShortToString((short) getComen1ai().getOptn012l())
                + getComen1ai().getOptn012f();
    }

    public void setFILLER_REDEFINE_59(String source) {
        try {
            getComen1ai().setOptn012l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setOptn012l(0);
        }
        getComen1ai().setOptn012f(source.substring(2, 3));
    }

    public String getOptn012c() {
        return getComen1ai().getFILLER_19().substring(0, 1);
    }

    public void setOptn012c(String source) {
        getComen1ai()
                .setFILLER_19(
                        StringUtils.overlay(getComen1ai().getFILLER_19(),
                                source, 0, 1));
    }

    public String getOptn012p() {
        return getComen1ai().getFILLER_19().substring(1, 2);
    }

    public void setOptn012p(String source) {
        getComen1ai()
                .setFILLER_19(
                        StringUtils.overlay(getComen1ai().getFILLER_19(),
                                source, 1, 2));
    }

    public String getOptn012h() {
        return getComen1ai().getFILLER_19().substring(2, 3);
    }

    public void setOptn012h(String source) {
        getComen1ai()
                .setFILLER_19(
                        StringUtils.overlay(getComen1ai().getFILLER_19(),
                                source, 2, 3));
    }

    public String getOptn012v() {
        return getComen1ai().getFILLER_19().substring(3, 4);
    }

    public void setOptn012v(String source) {
        getComen1ai()
                .setFILLER_19(
                        StringUtils.overlay(getComen1ai().getFILLER_19(),
                                source, 3, 4));
    }

    public String getOptn012o() {
        return getComen1ai().getOptn012i();
    }

    public void setOptn012o(String source) {
        getComen1ai().setOptn012i(source);
    }

    public String getFILLER_REDEFINE_60() {
        return CobStream.convShortToString((short) getComen1ai().getOptionl())
                + getComen1ai().getOptionf();
    }

    public void setFILLER_REDEFINE_60(String source) {
        try {
            getComen1ai().setOptionl(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setOptionl(0);
        }
        getComen1ai().setOptionf(source.substring(2, 3));
    }

    public String getOptionc() {
        return getComen1ai().getFILLER_20().substring(0, 1);
    }

    public void setOptionc(String source) {
        getComen1ai()
                .setFILLER_20(
                        StringUtils.overlay(getComen1ai().getFILLER_20(),
                                source, 0, 1));
    }

    public String getOptionp() {
        return getComen1ai().getFILLER_20().substring(1, 2);
    }

    public void setOptionp(String source) {
        getComen1ai()
                .setFILLER_20(
                        StringUtils.overlay(getComen1ai().getFILLER_20(),
                                source, 1, 2));
    }

    public String getOptionh() {
        return getComen1ai().getFILLER_20().substring(2, 3);
    }

    public void setOptionh(String source) {
        getComen1ai()
                .setFILLER_20(
                        StringUtils.overlay(getComen1ai().getFILLER_20(),
                                source, 2, 3));
    }

    public String getOptionv() {
        return getComen1ai().getFILLER_20().substring(3, 4);
    }

    public void setOptionv(String source) {
        getComen1ai()
                .setFILLER_20(
                        StringUtils.overlay(getComen1ai().getFILLER_20(),
                                source, 3, 4));
    }

    public String getOptiono() {
        return getComen1ai().getOptioni();
    }

    public void setOptiono(String source) {
        getComen1ai().setOptioni(source);
    }

    public String getFILLER_REDEFINE_61() {
        return CobStream.convShortToString((short) getComen1ai().getErrmsgl())
                + getComen1ai().getErrmsgf();
    }

    public void setFILLER_REDEFINE_61(String source) {
        try {
            getComen1ai().setErrmsgl(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getComen1ai().setErrmsgl(0);
        }
        getComen1ai().setErrmsgf(source.substring(2, 3));
    }

    public String getErrmsgc() {
        return getComen1ai().getFILLER_21().substring(0, 1);
    }

    public void setErrmsgc(String source) {
        getComen1ai()
                .setFILLER_21(
                        StringUtils.overlay(getComen1ai().getFILLER_21(),
                                source, 0, 1));
    }

    public String getErrmsgp() {
        return getComen1ai().getFILLER_21().substring(1, 2);
    }

    public void setErrmsgp(String source) {
        getComen1ai()
                .setFILLER_21(
                        StringUtils.overlay(getComen1ai().getFILLER_21(),
                                source, 1, 2));
    }

    public String getErrmsgh() {
        return getComen1ai().getFILLER_21().substring(2, 3);
    }

    public void setErrmsgh(String source) {
        getComen1ai()
                .setFILLER_21(
                        StringUtils.overlay(getComen1ai().getFILLER_21(),
                                source, 2, 3));
    }

    public String getErrmsgv() {
        return getComen1ai().getFILLER_21().substring(3, 4);
    }

    public void setErrmsgv(String source) {
        getComen1ai()
                .setFILLER_21(
                        StringUtils.overlay(getComen1ai().getFILLER_21(),
                                source, 3, 4));
    }

    public String getErrmsgo() {
        return getComen1ai().getErrmsgi();
    }

    public void setErrmsgo(String source) {
        getComen1ai().setErrmsgi(source);
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class Comen01cComen1ao {
        // [T-Up#INFO][COMEN01.CPY:141] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_41 = StringUtils.repeat(' ', 12);
        // [T-Up#INFO][COMEN01.CPY:142] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_42 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:143] TRNNAMEC (level: 2)
        private @Getter String trnnamec = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:144] TRNNAMEP (level: 2)
        private @Getter String trnnamep = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:145] TRNNAMEH (level: 2)
        private @Getter String trnnameh = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:146] TRNNAMEV (level: 2)
        private @Getter String trnnamev = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:147] TRNNAMEO (level: 2)
        private @Getter String trnnameo = StringUtils.repeat(' ', 4);
        // [T-Up#INFO][COMEN01.CPY:148] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_43 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:149] TITLE01C (level: 2)
        private @Getter String title01c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:150] TITLE01P (level: 2)
        private @Getter String title01p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:151] TITLE01H (level: 2)
        private @Getter String title01h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:152] TITLE01V (level: 2)
        private @Getter String title01v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:153] TITLE01O (level: 2)
        private @Getter String title01o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COMEN01.CPY:154] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_44 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:155] CURDATEC (level: 2)
        private @Getter String curdatec = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:156] CURDATEP (level: 2)
        private @Getter String curdatep = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:157] CURDATEH (level: 2)
        private @Getter String curdateh = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:158] CURDATEV (level: 2)
        private @Getter String curdatev = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:159] CURDATEO (level: 2)
        private @Getter String curdateo = StringUtils.repeat(' ', 8);
        // [T-Up#INFO][COMEN01.CPY:160] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_45 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:161] PGMNAMEC (level: 2)
        private @Getter String pgmnamec = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:162] PGMNAMEP (level: 2)
        private @Getter String pgmnamep = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:163] PGMNAMEH (level: 2)
        private @Getter String pgmnameh = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:164] PGMNAMEV (level: 2)
        private @Getter String pgmnamev = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:165] PGMNAMEO (level: 2)
        private @Getter String pgmnameo = StringUtils.repeat(' ', 8);
        // [T-Up#INFO][COMEN01.CPY:166] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_46 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:167] TITLE02C (level: 2)
        private @Getter String title02c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:168] TITLE02P (level: 2)
        private @Getter String title02p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:169] TITLE02H (level: 2)
        private @Getter String title02h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:170] TITLE02V (level: 2)
        private @Getter String title02v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:171] TITLE02O (level: 2)
        private @Getter String title02o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COMEN01.CPY:172] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_47 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:173] CURTIMEC (level: 2)
        private @Getter String curtimec = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:174] CURTIMEP (level: 2)
        private @Getter String curtimep = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:175] CURTIMEH (level: 2)
        private @Getter String curtimeh = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:176] CURTIMEV (level: 2)
        private @Getter String curtimev = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:177] CURTIMEO (level: 2)
        private @Getter String curtimeo = StringUtils.repeat(' ', 8);
        // [T-Up#INFO][COMEN01.CPY:178] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_48 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:179] OPTN001C (level: 2)
        private @Getter String optn001c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:180] OPTN001P (level: 2)
        private @Getter String optn001p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:181] OPTN001H (level: 2)
        private @Getter String optn001h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:182] OPTN001V (level: 2)
        private @Getter String optn001v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:183] OPTN001O (level: 2)
        private @Getter String optn001o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COMEN01.CPY:184] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_49 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:185] OPTN002C (level: 2)
        private @Getter String optn002c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:186] OPTN002P (level: 2)
        private @Getter String optn002p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:187] OPTN002H (level: 2)
        private @Getter String optn002h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:188] OPTN002V (level: 2)
        private @Getter String optn002v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:189] OPTN002O (level: 2)
        private @Getter String optn002o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COMEN01.CPY:190] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_50 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:191] OPTN003C (level: 2)
        private @Getter String optn003c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:192] OPTN003P (level: 2)
        private @Getter String optn003p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:193] OPTN003H (level: 2)
        private @Getter String optn003h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:194] OPTN003V (level: 2)
        private @Getter String optn003v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:195] OPTN003O (level: 2)
        private @Getter String optn003o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COMEN01.CPY:196] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_51 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:197] OPTN004C (level: 2)
        private @Getter String optn004c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:198] OPTN004P (level: 2)
        private @Getter String optn004p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:199] OPTN004H (level: 2)
        private @Getter String optn004h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:200] OPTN004V (level: 2)
        private @Getter String optn004v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:201] OPTN004O (level: 2)
        private @Getter String optn004o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COMEN01.CPY:202] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_52 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:203] OPTN005C (level: 2)
        private @Getter String optn005c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:204] OPTN005P (level: 2)
        private @Getter String optn005p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:205] OPTN005H (level: 2)
        private @Getter String optn005h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:206] OPTN005V (level: 2)
        private @Getter String optn005v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:207] OPTN005O (level: 2)
        private @Getter String optn005o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COMEN01.CPY:208] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_53 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:209] OPTN006C (level: 2)
        private @Getter String optn006c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:210] OPTN006P (level: 2)
        private @Getter String optn006p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:211] OPTN006H (level: 2)
        private @Getter String optn006h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:212] OPTN006V (level: 2)
        private @Getter String optn006v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:213] OPTN006O (level: 2)
        private @Getter String optn006o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COMEN01.CPY:214] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_54 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:215] OPTN007C (level: 2)
        private @Getter String optn007c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:216] OPTN007P (level: 2)
        private @Getter String optn007p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:217] OPTN007H (level: 2)
        private @Getter String optn007h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:218] OPTN007V (level: 2)
        private @Getter String optn007v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:219] OPTN007O (level: 2)
        private @Getter String optn007o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COMEN01.CPY:220] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_55 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:221] OPTN008C (level: 2)
        private @Getter String optn008c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:222] OPTN008P (level: 2)
        private @Getter String optn008p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:223] OPTN008H (level: 2)
        private @Getter String optn008h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:224] OPTN008V (level: 2)
        private @Getter String optn008v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:225] OPTN008O (level: 2)
        private @Getter String optn008o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COMEN01.CPY:226] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_56 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:227] OPTN009C (level: 2)
        private @Getter String optn009c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:228] OPTN009P (level: 2)
        private @Getter String optn009p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:229] OPTN009H (level: 2)
        private @Getter String optn009h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:230] OPTN009V (level: 2)
        private @Getter String optn009v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:231] OPTN009O (level: 2)
        private @Getter String optn009o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COMEN01.CPY:232] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_57 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:233] OPTN010C (level: 2)
        private @Getter String optn010c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:234] OPTN010P (level: 2)
        private @Getter String optn010p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:235] OPTN010H (level: 2)
        private @Getter String optn010h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:236] OPTN010V (level: 2)
        private @Getter String optn010v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:237] OPTN010O (level: 2)
        private @Getter String optn010o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COMEN01.CPY:238] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_58 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:239] OPTN011C (level: 2)
        private @Getter String optn011c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:240] OPTN011P (level: 2)
        private @Getter String optn011p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:241] OPTN011H (level: 2)
        private @Getter String optn011h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:242] OPTN011V (level: 2)
        private @Getter String optn011v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:243] OPTN011O (level: 2)
        private @Getter String optn011o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COMEN01.CPY:244] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_59 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:245] OPTN012C (level: 2)
        private @Getter String optn012c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:246] OPTN012P (level: 2)
        private @Getter String optn012p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:247] OPTN012H (level: 2)
        private @Getter String optn012h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:248] OPTN012V (level: 2)
        private @Getter String optn012v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:249] OPTN012O (level: 2)
        private @Getter String optn012o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COMEN01.CPY:250] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_60 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:251] OPTIONC (level: 2)
        private @Getter String optionc = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:252] OPTIONP (level: 2)
        private @Getter String optionp = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:253] OPTIONH (level: 2)
        private @Getter String optionh = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:254] OPTIONV (level: 2)
        private @Getter String optionv = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:255] OPTIONO (level: 2)
        private @Getter String optiono = StringUtils.repeat(' ', 2);
        // [T-Up#INFO][COMEN01.CPY:256] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_61 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COMEN01.CPY:257] ERRMSGC (level: 2)
        private @Getter String errmsgc = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:258] ERRMSGP (level: 2)
        private @Getter String errmsgp = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:259] ERRMSGH (level: 2)
        private @Getter String errmsgh = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:260] ERRMSGV (level: 2)
        private @Getter String errmsgv = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COMEN01.CPY:261] ERRMSGO (level: 2)
        private @Getter String errmsgo = StringUtils.repeat(' ', 78);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(FILLER_REDEFINE_41);
            sb.append(FILLER_REDEFINE_42);
            sb.append(trnnamec);
            sb.append(trnnamep);
            sb.append(trnnameh);
            sb.append(trnnamev);
            sb.append(trnnameo);
            sb.append(FILLER_REDEFINE_43);
            sb.append(title01c);
            sb.append(title01p);
            sb.append(title01h);
            sb.append(title01v);
            sb.append(title01o);
            sb.append(FILLER_REDEFINE_44);
            sb.append(curdatec);
            sb.append(curdatep);
            sb.append(curdateh);
            sb.append(curdatev);
            sb.append(curdateo);
            sb.append(FILLER_REDEFINE_45);
            sb.append(pgmnamec);
            sb.append(pgmnamep);
            sb.append(pgmnameh);
            sb.append(pgmnamev);
            sb.append(pgmnameo);
            sb.append(FILLER_REDEFINE_46);
            sb.append(title02c);
            sb.append(title02p);
            sb.append(title02h);
            sb.append(title02v);
            sb.append(title02o);
            sb.append(FILLER_REDEFINE_47);
            sb.append(curtimec);
            sb.append(curtimep);
            sb.append(curtimeh);
            sb.append(curtimev);
            sb.append(curtimeo);
            sb.append(FILLER_REDEFINE_48);
            sb.append(optn001c);
            sb.append(optn001p);
            sb.append(optn001h);
            sb.append(optn001v);
            sb.append(optn001o);
            sb.append(FILLER_REDEFINE_49);
            sb.append(optn002c);
            sb.append(optn002p);
            sb.append(optn002h);
            sb.append(optn002v);
            sb.append(optn002o);
            sb.append(FILLER_REDEFINE_50);
            sb.append(optn003c);
            sb.append(optn003p);
            sb.append(optn003h);
            sb.append(optn003v);
            sb.append(optn003o);
            sb.append(FILLER_REDEFINE_51);
            sb.append(optn004c);
            sb.append(optn004p);
            sb.append(optn004h);
            sb.append(optn004v);
            sb.append(optn004o);
            sb.append(FILLER_REDEFINE_52);
            sb.append(optn005c);
            sb.append(optn005p);
            sb.append(optn005h);
            sb.append(optn005v);
            sb.append(optn005o);
            sb.append(FILLER_REDEFINE_53);
            sb.append(optn006c);
            sb.append(optn006p);
            sb.append(optn006h);
            sb.append(optn006v);
            sb.append(optn006o);
            sb.append(FILLER_REDEFINE_54);
            sb.append(optn007c);
            sb.append(optn007p);
            sb.append(optn007h);
            sb.append(optn007v);
            sb.append(optn007o);
            sb.append(FILLER_REDEFINE_55);
            sb.append(optn008c);
            sb.append(optn008p);
            sb.append(optn008h);
            sb.append(optn008v);
            sb.append(optn008o);
            sb.append(FILLER_REDEFINE_56);
            sb.append(optn009c);
            sb.append(optn009p);
            sb.append(optn009h);
            sb.append(optn009v);
            sb.append(optn009o);
            sb.append(FILLER_REDEFINE_57);
            sb.append(optn010c);
            sb.append(optn010p);
            sb.append(optn010h);
            sb.append(optn010v);
            sb.append(optn010o);
            sb.append(FILLER_REDEFINE_58);
            sb.append(optn011c);
            sb.append(optn011p);
            sb.append(optn011h);
            sb.append(optn011v);
            sb.append(optn011o);
            sb.append(FILLER_REDEFINE_59);
            sb.append(optn012c);
            sb.append(optn012p);
            sb.append(optn012h);
            sb.append(optn012v);
            sb.append(optn012o);
            sb.append(FILLER_REDEFINE_60);
            sb.append(optionc);
            sb.append(optionp);
            sb.append(optionh);
            sb.append(optionv);
            sb.append(optiono);
            sb.append(FILLER_REDEFINE_61);
            sb.append(errmsgc);
            sb.append(errmsgp);
            sb.append(errmsgh);
            sb.append(errmsgv);
            sb.append(errmsgo);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(FILLER_REDEFINE_41);
            sb.append(FILLER_REDEFINE_42);
            sb.append(getTrnnamec());
            sb.append(getTrnnamep());
            sb.append(getTrnnameh());
            sb.append(getTrnnamev());
            sb.append(getTrnnameo());
            sb.append(FILLER_REDEFINE_43);
            sb.append(getTitle01c());
            sb.append(getTitle01p());
            sb.append(getTitle01h());
            sb.append(getTitle01v());
            sb.append(getTitle01o());
            sb.append(FILLER_REDEFINE_44);
            sb.append(getCurdatec());
            sb.append(getCurdatep());
            sb.append(getCurdateh());
            sb.append(getCurdatev());
            sb.append(getCurdateo());
            sb.append(FILLER_REDEFINE_45);
            sb.append(getPgmnamec());
            sb.append(getPgmnamep());
            sb.append(getPgmnameh());
            sb.append(getPgmnamev());
            sb.append(getPgmnameo());
            sb.append(FILLER_REDEFINE_46);
            sb.append(getTitle02c());
            sb.append(getTitle02p());
            sb.append(getTitle02h());
            sb.append(getTitle02v());
            sb.append(getTitle02o());
            sb.append(FILLER_REDEFINE_47);
            sb.append(getCurtimec());
            sb.append(getCurtimep());
            sb.append(getCurtimeh());
            sb.append(getCurtimev());
            sb.append(getCurtimeo());
            sb.append(FILLER_REDEFINE_48);
            sb.append(getOptn001c());
            sb.append(getOptn001p());
            sb.append(getOptn001h());
            sb.append(getOptn001v());
            sb.append(getOptn001o());
            sb.append(FILLER_REDEFINE_49);
            sb.append(getOptn002c());
            sb.append(getOptn002p());
            sb.append(getOptn002h());
            sb.append(getOptn002v());
            sb.append(getOptn002o());
            sb.append(FILLER_REDEFINE_50);
            sb.append(getOptn003c());
            sb.append(getOptn003p());
            sb.append(getOptn003h());
            sb.append(getOptn003v());
            sb.append(getOptn003o());
            sb.append(FILLER_REDEFINE_51);
            sb.append(getOptn004c());
            sb.append(getOptn004p());
            sb.append(getOptn004h());
            sb.append(getOptn004v());
            sb.append(getOptn004o());
            sb.append(FILLER_REDEFINE_52);
            sb.append(getOptn005c());
            sb.append(getOptn005p());
            sb.append(getOptn005h());
            sb.append(getOptn005v());
            sb.append(getOptn005o());
            sb.append(FILLER_REDEFINE_53);
            sb.append(getOptn006c());
            sb.append(getOptn006p());
            sb.append(getOptn006h());
            sb.append(getOptn006v());
            sb.append(getOptn006o());
            sb.append(FILLER_REDEFINE_54);
            sb.append(getOptn007c());
            sb.append(getOptn007p());
            sb.append(getOptn007h());
            sb.append(getOptn007v());
            sb.append(getOptn007o());
            sb.append(FILLER_REDEFINE_55);
            sb.append(getOptn008c());
            sb.append(getOptn008p());
            sb.append(getOptn008h());
            sb.append(getOptn008v());
            sb.append(getOptn008o());
            sb.append(FILLER_REDEFINE_56);
            sb.append(getOptn009c());
            sb.append(getOptn009p());
            sb.append(getOptn009h());
            sb.append(getOptn009v());
            sb.append(getOptn009o());
            sb.append(FILLER_REDEFINE_57);
            sb.append(getOptn010c());
            sb.append(getOptn010p());
            sb.append(getOptn010h());
            sb.append(getOptn010v());
            sb.append(getOptn010o());
            sb.append(FILLER_REDEFINE_58);
            sb.append(getOptn011c());
            sb.append(getOptn011p());
            sb.append(getOptn011h());
            sb.append(getOptn011v());
            sb.append(getOptn011o());
            sb.append(FILLER_REDEFINE_59);
            sb.append(getOptn012c());
            sb.append(getOptn012p());
            sb.append(getOptn012h());
            sb.append(getOptn012v());
            sb.append(getOptn012o());
            sb.append(FILLER_REDEFINE_60);
            sb.append(getOptionc());
            sb.append(getOptionp());
            sb.append(getOptionh());
            sb.append(getOptionv());
            sb.append(getOptiono());
            sb.append(FILLER_REDEFINE_61);
            sb.append(getErrmsgc());
            sb.append(getErrmsgp());
            sb.append(getErrmsgh());
            sb.append(getErrmsgv());
            sb.append(getErrmsgo());
            return sb.toString();
        }
    }
}
