package com.tmax.openframe.variable;

import com.tmax.openframe.runtime.cobol.CobStream;
import com.tmax.openframe.variable.group.*;
import java.math.*;
import java.util.*;
import lombok.*;
import org.apache.commons.lang3.StringUtils;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:17 KST</p>
 * <hr>
 * <p>Class that defines variables that defined in the data division of COBOL program</p>
 */
public class Cosgn00cVariableContainer {
    // *----------------------------------------------------------------*
    // *                     WORKING STORAGE SECTION
    // *----------------------------------------------------------------*
    // [T-Up#INFO][COSGN00C.cbl:35] WS-VARIABLES (level: 1)
    private @Getter @Setter Cosgn00cWsVariables wsVariables = new Cosgn00cWsVariables();
    //       *COPY COCOM01Y.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/COCOM01Y.cpy)
    // ******************************************************************
    // * Communication area for CardDemo application programs
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // [T-Up#INFO][COCOM01Y.cpy:20] CARDDEMO-COMMAREA (level: 1)
    private @Getter @Setter CarddemoCommarea carddemoCommarea = new CarddemoCommarea();
    // *
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:15:57 CDT
    // *
    //       *COPY COSGN00.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/COSGN00.CPY)
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // [T-Up#INFO][COSGN00.CPY:18] COSGN0AI (level: 1)
    private @Getter @Setter Cosgn0ai cosgn0ai = new Cosgn0ai();
    //       *COPY COTTL01Y.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/COTTL01Y.cpy)
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // [T-Up#INFO][COTTL01Y.cpy:18] CCDA-SCREEN-TITLE (level: 1)
    private @Getter @Setter CcdaScreenTitle ccdaScreenTitle = new CcdaScreenTitle();
    // *
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:15:58 CDT
    // *
    //       *COPY CSDAT01Y.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/CSDAT01Y.cpy)
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // [T-Up#INFO][CSDAT01Y.cpy:18] WS-DATE-TIME (level: 1)
    private @Getter @Setter WsDateTime wsDateTime = new WsDateTime();
    // *
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:15:58 CDT
    // *
    //       *COPY CSMSG01Y.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/CSMSG01Y.cpy)
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // [T-Up#INFO][CSMSG01Y.cpy:18] CCDA-COMMON-MESSAGES (level: 1)
    private @Getter @Setter CcdaCommonMessages ccdaCommonMessages = new CcdaCommonMessages();
    // *
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:15:58 CDT
    // *
    //       *COPY CSUSR01Y.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/CSUSR01Y.cpy)
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // [T-Up#INFO][CSUSR01Y.cpy:18] SEC-USER-DATA (level: 1)
    private @Getter @Setter SecUserData secUserData = new SecUserData();
    // *
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:15:59 CDT
    // *
    //       *COPY DFHAID.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/DFHAID.cpy)
    // [T-Up#INFO][DFHAID.cpy:2] DFHAID (level: 1)
    private @Getter @Setter Dfhaid dfhaid = new Dfhaid();
    //       *COPY DFHBMSCA.
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/DFHBMSCA.cpy)
    // [T-Up#INFO][DFHBMSCA.cpy:2] DFHBMSCA (level: 1)
    private @Getter @Setter Dfhbmsca dfhbmsca = new Dfhbmsca();
    // *COPY DFHATTR.
    // *----------------------------------------------------------------*
    // *                        LINKAGE SECTION
    // *----------------------------------------------------------------*
    // [T-Up#INFO][COSGN00C.cbl:65] DFHCOMMAREA (level: 1)
    private @Getter @Setter Cosgn00cDfhcommarea dfhcommarea = new Cosgn00cDfhcommarea();

    public Cosgn00cCosgn0ao getCosgn0ao() {
        return Cosgn00cCosgn0ao.builder()
                .FILLER_REDEFINE_23(getFILLER_REDEFINE_23())
                .FILLER_REDEFINE_24(getFILLER_REDEFINE_24())
                .trnnamec(getTrnnamec()).trnnamep(getTrnnamep())
                .trnnameh(getTrnnameh()).trnnamev(getTrnnamev())
                .trnnameo(getTrnnameo())
                .FILLER_REDEFINE_25(getFILLER_REDEFINE_25())
                .title01c(getTitle01c()).title01p(getTitle01p())
                .title01h(getTitle01h()).title01v(getTitle01v())
                .title01o(getTitle01o())
                .FILLER_REDEFINE_26(getFILLER_REDEFINE_26())
                .curdatec(getCurdatec()).curdatep(getCurdatep())
                .curdateh(getCurdateh()).curdatev(getCurdatev())
                .curdateo(getCurdateo())
                .FILLER_REDEFINE_27(getFILLER_REDEFINE_27())
                .pgmnamec(getPgmnamec()).pgmnamep(getPgmnamep())
                .pgmnameh(getPgmnameh()).pgmnamev(getPgmnamev())
                .pgmnameo(getPgmnameo())
                .FILLER_REDEFINE_28(getFILLER_REDEFINE_28())
                .title02c(getTitle02c()).title02p(getTitle02p())
                .title02h(getTitle02h()).title02v(getTitle02v())
                .title02o(getTitle02o())
                .FILLER_REDEFINE_29(getFILLER_REDEFINE_29())
                .curtimec(getCurtimec()).curtimep(getCurtimep())
                .curtimeh(getCurtimeh()).curtimev(getCurtimev())
                .curtimeo(getCurtimeo())
                .FILLER_REDEFINE_30(getFILLER_REDEFINE_30())
                .applidc(getApplidc()).applidp(getApplidp())
                .applidh(getApplidh()).applidv(getApplidv())
                .applido(getApplido())
                .FILLER_REDEFINE_31(getFILLER_REDEFINE_31())
                .sysidc(getSysidc()).sysidp(getSysidp()).sysidh(getSysidh())
                .sysidv(getSysidv()).sysido(getSysido())
                .FILLER_REDEFINE_32(getFILLER_REDEFINE_32())
                .useridc(getUseridc()).useridp(getUseridp())
                .useridh(getUseridh()).useridv(getUseridv())
                .userido(getUserido())
                .FILLER_REDEFINE_33(getFILLER_REDEFINE_33())
                .passwdc(getPasswdc()).passwdp(getPasswdp())
                .passwdh(getPasswdh()).passwdv(getPasswdv())
                .passwdo(getPasswdo())
                .FILLER_REDEFINE_34(getFILLER_REDEFINE_34())
                .errmsgc(getErrmsgc()).errmsgp(getErrmsgp())
                .errmsgh(getErrmsgh()).errmsgv(getErrmsgv())
                .errmsgo(getErrmsgo()).build();
    }

    public void setCosgn0ao(String source) {
        setFILLER_REDEFINE_23(source.substring(0, 12));
        setFILLER_REDEFINE_24(source.substring(12, 15));
        setTrnnamec(source.substring(15, 16));
        setTrnnamep(source.substring(16, 17));
        setTrnnameh(source.substring(17, 18));
        setTrnnamev(source.substring(18, 19));
        setTrnnameo(source.substring(19, 23));
        setFILLER_REDEFINE_25(source.substring(23, 26));
        setTitle01c(source.substring(26, 27));
        setTitle01p(source.substring(27, 28));
        setTitle01h(source.substring(28, 29));
        setTitle01v(source.substring(29, 30));
        setTitle01o(source.substring(30, 70));
        setFILLER_REDEFINE_26(source.substring(70, 73));
        setCurdatec(source.substring(73, 74));
        setCurdatep(source.substring(74, 75));
        setCurdateh(source.substring(75, 76));
        setCurdatev(source.substring(76, 77));
        setCurdateo(source.substring(77, 85));
        setFILLER_REDEFINE_27(source.substring(85, 88));
        setPgmnamec(source.substring(88, 89));
        setPgmnamep(source.substring(89, 90));
        setPgmnameh(source.substring(90, 91));
        setPgmnamev(source.substring(91, 92));
        setPgmnameo(source.substring(92, 100));
        setFILLER_REDEFINE_28(source.substring(100, 103));
        setTitle02c(source.substring(103, 104));
        setTitle02p(source.substring(104, 105));
        setTitle02h(source.substring(105, 106));
        setTitle02v(source.substring(106, 107));
        setTitle02o(source.substring(107, 147));
        setFILLER_REDEFINE_29(source.substring(147, 150));
        setCurtimec(source.substring(150, 151));
        setCurtimep(source.substring(151, 152));
        setCurtimeh(source.substring(152, 153));
        setCurtimev(source.substring(153, 154));
        setCurtimeo(source.substring(154, 163));
        setFILLER_REDEFINE_30(source.substring(163, 166));
        setApplidc(source.substring(166, 167));
        setApplidp(source.substring(167, 168));
        setApplidh(source.substring(168, 169));
        setApplidv(source.substring(169, 170));
        setApplido(source.substring(170, 178));
        setFILLER_REDEFINE_31(source.substring(178, 181));
        setSysidc(source.substring(181, 182));
        setSysidp(source.substring(182, 183));
        setSysidh(source.substring(183, 184));
        setSysidv(source.substring(184, 185));
        setSysido(source.substring(185, 193));
        setFILLER_REDEFINE_32(source.substring(193, 196));
        setUseridc(source.substring(196, 197));
        setUseridp(source.substring(197, 198));
        setUseridh(source.substring(198, 199));
        setUseridv(source.substring(199, 200));
        setUserido(source.substring(200, 208));
        setFILLER_REDEFINE_33(source.substring(208, 211));
        setPasswdc(source.substring(211, 212));
        setPasswdp(source.substring(212, 213));
        setPasswdh(source.substring(213, 214));
        setPasswdv(source.substring(214, 215));
        setPasswdo(source.substring(215, 223));
        setFILLER_REDEFINE_34(source.substring(223, 226));
        setErrmsgc(source.substring(226, 227));
        setErrmsgp(source.substring(227, 228));
        setErrmsgh(source.substring(228, 229));
        setErrmsgv(source.substring(229, 230));
        setErrmsgo(source.substring(230, 308));
    }

    public void setCosgn0ao(Cosgn00cCosgn0ao source) {
        setCosgn0ao(source.get());
    }

    public String getFILLER_REDEFINE_23() {
        return getCosgn0ai().getFILLER_1();
    }

    public void setFILLER_REDEFINE_23(String source) {
        getCosgn0ai().setFILLER_1(source);
    }

    public String getFILLER_REDEFINE_24() {
        return CobStream.convShortToString((short) getCosgn0ai().getTrnnamel())
                + getCosgn0ai().getTrnnamef();
    }

    public void setFILLER_REDEFINE_24(String source) {
        try {
            getCosgn0ai().setTrnnamel(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getCosgn0ai().setTrnnamel(0);
        }
        getCosgn0ai().setTrnnamef(source.substring(2, 3));
    }

    public String getTrnnamec() {
        return getCosgn0ai().getFILLER_2().substring(0, 1);
    }

    public void setTrnnamec(String source) {
        getCosgn0ai().setFILLER_2(
                StringUtils.overlay(getCosgn0ai().getFILLER_2(), source, 0, 1));
    }

    public String getTrnnamep() {
        return getCosgn0ai().getFILLER_2().substring(1, 2);
    }

    public void setTrnnamep(String source) {
        getCosgn0ai().setFILLER_2(
                StringUtils.overlay(getCosgn0ai().getFILLER_2(), source, 1, 2));
    }

    public String getTrnnameh() {
        return getCosgn0ai().getFILLER_2().substring(2, 3);
    }

    public void setTrnnameh(String source) {
        getCosgn0ai().setFILLER_2(
                StringUtils.overlay(getCosgn0ai().getFILLER_2(), source, 2, 3));
    }

    public String getTrnnamev() {
        return getCosgn0ai().getFILLER_2().substring(3, 4);
    }

    public void setTrnnamev(String source) {
        getCosgn0ai().setFILLER_2(
                StringUtils.overlay(getCosgn0ai().getFILLER_2(), source, 3, 4));
    }

    public String getTrnnameo() {
        return getCosgn0ai().getTrnnamei();
    }

    public void setTrnnameo(String source) {
        getCosgn0ai().setTrnnamei(source);
    }

    public String getFILLER_REDEFINE_25() {
        return CobStream.convShortToString((short) getCosgn0ai().getTitle01l())
                + getCosgn0ai().getTitle01f();
    }

    public void setFILLER_REDEFINE_25(String source) {
        try {
            getCosgn0ai().setTitle01l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getCosgn0ai().setTitle01l(0);
        }
        getCosgn0ai().setTitle01f(source.substring(2, 3));
    }

    public String getTitle01c() {
        return getCosgn0ai().getFILLER_3().substring(0, 1);
    }

    public void setTitle01c(String source) {
        getCosgn0ai().setFILLER_3(
                StringUtils.overlay(getCosgn0ai().getFILLER_3(), source, 0, 1));
    }

    public String getTitle01p() {
        return getCosgn0ai().getFILLER_3().substring(1, 2);
    }

    public void setTitle01p(String source) {
        getCosgn0ai().setFILLER_3(
                StringUtils.overlay(getCosgn0ai().getFILLER_3(), source, 1, 2));
    }

    public String getTitle01h() {
        return getCosgn0ai().getFILLER_3().substring(2, 3);
    }

    public void setTitle01h(String source) {
        getCosgn0ai().setFILLER_3(
                StringUtils.overlay(getCosgn0ai().getFILLER_3(), source, 2, 3));
    }

    public String getTitle01v() {
        return getCosgn0ai().getFILLER_3().substring(3, 4);
    }

    public void setTitle01v(String source) {
        getCosgn0ai().setFILLER_3(
                StringUtils.overlay(getCosgn0ai().getFILLER_3(), source, 3, 4));
    }

    public String getTitle01o() {
        return getCosgn0ai().getTitle01i();
    }

    public void setTitle01o(String source) {
        getCosgn0ai().setTitle01i(source);
    }

    public String getFILLER_REDEFINE_26() {
        return CobStream.convShortToString((short) getCosgn0ai().getCurdatel())
                + getCosgn0ai().getCurdatef();
    }

    public void setFILLER_REDEFINE_26(String source) {
        try {
            getCosgn0ai().setCurdatel(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getCosgn0ai().setCurdatel(0);
        }
        getCosgn0ai().setCurdatef(source.substring(2, 3));
    }

    public String getCurdatec() {
        return getCosgn0ai().getFILLER_4().substring(0, 1);
    }

    public void setCurdatec(String source) {
        getCosgn0ai().setFILLER_4(
                StringUtils.overlay(getCosgn0ai().getFILLER_4(), source, 0, 1));
    }

    public String getCurdatep() {
        return getCosgn0ai().getFILLER_4().substring(1, 2);
    }

    public void setCurdatep(String source) {
        getCosgn0ai().setFILLER_4(
                StringUtils.overlay(getCosgn0ai().getFILLER_4(), source, 1, 2));
    }

    public String getCurdateh() {
        return getCosgn0ai().getFILLER_4().substring(2, 3);
    }

    public void setCurdateh(String source) {
        getCosgn0ai().setFILLER_4(
                StringUtils.overlay(getCosgn0ai().getFILLER_4(), source, 2, 3));
    }

    public String getCurdatev() {
        return getCosgn0ai().getFILLER_4().substring(3, 4);
    }

    public void setCurdatev(String source) {
        getCosgn0ai().setFILLER_4(
                StringUtils.overlay(getCosgn0ai().getFILLER_4(), source, 3, 4));
    }

    public String getCurdateo() {
        return getCosgn0ai().getCurdatei();
    }

    public void setCurdateo(String source) {
        getCosgn0ai().setCurdatei(source);
    }

    public String getFILLER_REDEFINE_27() {
        return CobStream.convShortToString((short) getCosgn0ai().getPgmnamel())
                + getCosgn0ai().getPgmnamef();
    }

    public void setFILLER_REDEFINE_27(String source) {
        try {
            getCosgn0ai().setPgmnamel(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getCosgn0ai().setPgmnamel(0);
        }
        getCosgn0ai().setPgmnamef(source.substring(2, 3));
    }

    public String getPgmnamec() {
        return getCosgn0ai().getFILLER_5().substring(0, 1);
    }

    public void setPgmnamec(String source) {
        getCosgn0ai().setFILLER_5(
                StringUtils.overlay(getCosgn0ai().getFILLER_5(), source, 0, 1));
    }

    public String getPgmnamep() {
        return getCosgn0ai().getFILLER_5().substring(1, 2);
    }

    public void setPgmnamep(String source) {
        getCosgn0ai().setFILLER_5(
                StringUtils.overlay(getCosgn0ai().getFILLER_5(), source, 1, 2));
    }

    public String getPgmnameh() {
        return getCosgn0ai().getFILLER_5().substring(2, 3);
    }

    public void setPgmnameh(String source) {
        getCosgn0ai().setFILLER_5(
                StringUtils.overlay(getCosgn0ai().getFILLER_5(), source, 2, 3));
    }

    public String getPgmnamev() {
        return getCosgn0ai().getFILLER_5().substring(3, 4);
    }

    public void setPgmnamev(String source) {
        getCosgn0ai().setFILLER_5(
                StringUtils.overlay(getCosgn0ai().getFILLER_5(), source, 3, 4));
    }

    public String getPgmnameo() {
        return getCosgn0ai().getPgmnamei();
    }

    public void setPgmnameo(String source) {
        getCosgn0ai().setPgmnamei(source);
    }

    public String getFILLER_REDEFINE_28() {
        return CobStream.convShortToString((short) getCosgn0ai().getTitle02l())
                + getCosgn0ai().getTitle02f();
    }

    public void setFILLER_REDEFINE_28(String source) {
        try {
            getCosgn0ai().setTitle02l(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getCosgn0ai().setTitle02l(0);
        }
        getCosgn0ai().setTitle02f(source.substring(2, 3));
    }

    public String getTitle02c() {
        return getCosgn0ai().getFILLER_6().substring(0, 1);
    }

    public void setTitle02c(String source) {
        getCosgn0ai().setFILLER_6(
                StringUtils.overlay(getCosgn0ai().getFILLER_6(), source, 0, 1));
    }

    public String getTitle02p() {
        return getCosgn0ai().getFILLER_6().substring(1, 2);
    }

    public void setTitle02p(String source) {
        getCosgn0ai().setFILLER_6(
                StringUtils.overlay(getCosgn0ai().getFILLER_6(), source, 1, 2));
    }

    public String getTitle02h() {
        return getCosgn0ai().getFILLER_6().substring(2, 3);
    }

    public void setTitle02h(String source) {
        getCosgn0ai().setFILLER_6(
                StringUtils.overlay(getCosgn0ai().getFILLER_6(), source, 2, 3));
    }

    public String getTitle02v() {
        return getCosgn0ai().getFILLER_6().substring(3, 4);
    }

    public void setTitle02v(String source) {
        getCosgn0ai().setFILLER_6(
                StringUtils.overlay(getCosgn0ai().getFILLER_6(), source, 3, 4));
    }

    public String getTitle02o() {
        return getCosgn0ai().getTitle02i();
    }

    public void setTitle02o(String source) {
        getCosgn0ai().setTitle02i(source);
    }

    public String getFILLER_REDEFINE_29() {
        return CobStream.convShortToString((short) getCosgn0ai().getCurtimel())
                + getCosgn0ai().getCurtimef();
    }

    public void setFILLER_REDEFINE_29(String source) {
        try {
            getCosgn0ai().setCurtimel(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getCosgn0ai().setCurtimel(0);
        }
        getCosgn0ai().setCurtimef(source.substring(2, 3));
    }

    public String getCurtimec() {
        return getCosgn0ai().getFILLER_7().substring(0, 1);
    }

    public void setCurtimec(String source) {
        getCosgn0ai().setFILLER_7(
                StringUtils.overlay(getCosgn0ai().getFILLER_7(), source, 0, 1));
    }

    public String getCurtimep() {
        return getCosgn0ai().getFILLER_7().substring(1, 2);
    }

    public void setCurtimep(String source) {
        getCosgn0ai().setFILLER_7(
                StringUtils.overlay(getCosgn0ai().getFILLER_7(), source, 1, 2));
    }

    public String getCurtimeh() {
        return getCosgn0ai().getFILLER_7().substring(2, 3);
    }

    public void setCurtimeh(String source) {
        getCosgn0ai().setFILLER_7(
                StringUtils.overlay(getCosgn0ai().getFILLER_7(), source, 2, 3));
    }

    public String getCurtimev() {
        return getCosgn0ai().getFILLER_7().substring(3, 4);
    }

    public void setCurtimev(String source) {
        getCosgn0ai().setFILLER_7(
                StringUtils.overlay(getCosgn0ai().getFILLER_7(), source, 3, 4));
    }

    public String getCurtimeo() {
        return getCosgn0ai().getCurtimei();
    }

    public void setCurtimeo(String source) {
        getCosgn0ai().setCurtimei(source);
    }

    public String getFILLER_REDEFINE_30() {
        return CobStream.convShortToString((short) getCosgn0ai().getApplidl())
                + getCosgn0ai().getApplidf();
    }

    public void setFILLER_REDEFINE_30(String source) {
        try {
            getCosgn0ai().setApplidl(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getCosgn0ai().setApplidl(0);
        }
        getCosgn0ai().setApplidf(source.substring(2, 3));
    }

    public String getApplidc() {
        return getCosgn0ai().getFILLER_8().substring(0, 1);
    }

    public void setApplidc(String source) {
        getCosgn0ai().setFILLER_8(
                StringUtils.overlay(getCosgn0ai().getFILLER_8(), source, 0, 1));
    }

    public String getApplidp() {
        return getCosgn0ai().getFILLER_8().substring(1, 2);
    }

    public void setApplidp(String source) {
        getCosgn0ai().setFILLER_8(
                StringUtils.overlay(getCosgn0ai().getFILLER_8(), source, 1, 2));
    }

    public String getApplidh() {
        return getCosgn0ai().getFILLER_8().substring(2, 3);
    }

    public void setApplidh(String source) {
        getCosgn0ai().setFILLER_8(
                StringUtils.overlay(getCosgn0ai().getFILLER_8(), source, 2, 3));
    }

    public String getApplidv() {
        return getCosgn0ai().getFILLER_8().substring(3, 4);
    }

    public void setApplidv(String source) {
        getCosgn0ai().setFILLER_8(
                StringUtils.overlay(getCosgn0ai().getFILLER_8(), source, 3, 4));
    }

    public String getApplido() {
        return getCosgn0ai().getApplidi();
    }

    public void setApplido(String source) {
        getCosgn0ai().setApplidi(source);
    }

    public String getFILLER_REDEFINE_31() {
        return CobStream.convShortToString((short) getCosgn0ai().getSysidl())
                + getCosgn0ai().getSysidf();
    }

    public void setFILLER_REDEFINE_31(String source) {
        try {
            getCosgn0ai().setSysidl(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getCosgn0ai().setSysidl(0);
        }
        getCosgn0ai().setSysidf(source.substring(2, 3));
    }

    public String getSysidc() {
        return getCosgn0ai().getFILLER_9().substring(0, 1);
    }

    public void setSysidc(String source) {
        getCosgn0ai().setFILLER_9(
                StringUtils.overlay(getCosgn0ai().getFILLER_9(), source, 0, 1));
    }

    public String getSysidp() {
        return getCosgn0ai().getFILLER_9().substring(1, 2);
    }

    public void setSysidp(String source) {
        getCosgn0ai().setFILLER_9(
                StringUtils.overlay(getCosgn0ai().getFILLER_9(), source, 1, 2));
    }

    public String getSysidh() {
        return getCosgn0ai().getFILLER_9().substring(2, 3);
    }

    public void setSysidh(String source) {
        getCosgn0ai().setFILLER_9(
                StringUtils.overlay(getCosgn0ai().getFILLER_9(), source, 2, 3));
    }

    public String getSysidv() {
        return getCosgn0ai().getFILLER_9().substring(3, 4);
    }

    public void setSysidv(String source) {
        getCosgn0ai().setFILLER_9(
                StringUtils.overlay(getCosgn0ai().getFILLER_9(), source, 3, 4));
    }

    public String getSysido() {
        return getCosgn0ai().getSysidi();
    }

    public void setSysido(String source) {
        getCosgn0ai().setSysidi(source);
    }

    public String getFILLER_REDEFINE_32() {
        return CobStream.convShortToString((short) getCosgn0ai().getUseridl())
                + getCosgn0ai().getUseridf();
    }

    public void setFILLER_REDEFINE_32(String source) {
        try {
            getCosgn0ai().setUseridl(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getCosgn0ai().setUseridl(0);
        }
        getCosgn0ai().setUseridf(source.substring(2, 3));
    }

    public String getUseridc() {
        return getCosgn0ai().getFILLER_10().substring(0, 1);
    }

    public void setUseridc(String source) {
        getCosgn0ai()
                .setFILLER_10(
                        StringUtils.overlay(getCosgn0ai().getFILLER_10(),
                                source, 0, 1));
    }

    public String getUseridp() {
        return getCosgn0ai().getFILLER_10().substring(1, 2);
    }

    public void setUseridp(String source) {
        getCosgn0ai()
                .setFILLER_10(
                        StringUtils.overlay(getCosgn0ai().getFILLER_10(),
                                source, 1, 2));
    }

    public String getUseridh() {
        return getCosgn0ai().getFILLER_10().substring(2, 3);
    }

    public void setUseridh(String source) {
        getCosgn0ai()
                .setFILLER_10(
                        StringUtils.overlay(getCosgn0ai().getFILLER_10(),
                                source, 2, 3));
    }

    public String getUseridv() {
        return getCosgn0ai().getFILLER_10().substring(3, 4);
    }

    public void setUseridv(String source) {
        getCosgn0ai()
                .setFILLER_10(
                        StringUtils.overlay(getCosgn0ai().getFILLER_10(),
                                source, 3, 4));
    }

    public String getUserido() {
        return getCosgn0ai().getUseridi();
    }

    public void setUserido(String source) {
        getCosgn0ai().setUseridi(source);
    }

    public String getFILLER_REDEFINE_33() {
        return CobStream.convShortToString((short) getCosgn0ai().getPasswdl())
                + getCosgn0ai().getPasswdf();
    }

    public void setFILLER_REDEFINE_33(String source) {
        try {
            getCosgn0ai().setPasswdl(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getCosgn0ai().setPasswdl(0);
        }
        getCosgn0ai().setPasswdf(source.substring(2, 3));
    }

    public String getPasswdc() {
        return getCosgn0ai().getFILLER_11().substring(0, 1);
    }

    public void setPasswdc(String source) {
        getCosgn0ai()
                .setFILLER_11(
                        StringUtils.overlay(getCosgn0ai().getFILLER_11(),
                                source, 0, 1));
    }

    public String getPasswdp() {
        return getCosgn0ai().getFILLER_11().substring(1, 2);
    }

    public void setPasswdp(String source) {
        getCosgn0ai()
                .setFILLER_11(
                        StringUtils.overlay(getCosgn0ai().getFILLER_11(),
                                source, 1, 2));
    }

    public String getPasswdh() {
        return getCosgn0ai().getFILLER_11().substring(2, 3);
    }

    public void setPasswdh(String source) {
        getCosgn0ai()
                .setFILLER_11(
                        StringUtils.overlay(getCosgn0ai().getFILLER_11(),
                                source, 2, 3));
    }

    public String getPasswdv() {
        return getCosgn0ai().getFILLER_11().substring(3, 4);
    }

    public void setPasswdv(String source) {
        getCosgn0ai()
                .setFILLER_11(
                        StringUtils.overlay(getCosgn0ai().getFILLER_11(),
                                source, 3, 4));
    }

    public String getPasswdo() {
        return getCosgn0ai().getPasswdi();
    }

    public void setPasswdo(String source) {
        getCosgn0ai().setPasswdi(source);
    }

    public String getFILLER_REDEFINE_34() {
        return CobStream.convShortToString((short) getCosgn0ai().getErrmsgl())
                + getCosgn0ai().getErrmsgf();
    }

    public void setFILLER_REDEFINE_34(String source) {
        try {
            getCosgn0ai().setErrmsgl(
                    CobStream.convStringToShort(source.substring(0, 2)));
        } catch (NumberFormatException exception) {
            exception.printStackTrace();
            getCosgn0ai().setErrmsgl(0);
        }
        getCosgn0ai().setErrmsgf(source.substring(2, 3));
    }

    public String getErrmsgc() {
        return getCosgn0ai().getFILLER_12().substring(0, 1);
    }

    public void setErrmsgc(String source) {
        getCosgn0ai()
                .setFILLER_12(
                        StringUtils.overlay(getCosgn0ai().getFILLER_12(),
                                source, 0, 1));
    }

    public String getErrmsgp() {
        return getCosgn0ai().getFILLER_12().substring(1, 2);
    }

    public void setErrmsgp(String source) {
        getCosgn0ai()
                .setFILLER_12(
                        StringUtils.overlay(getCosgn0ai().getFILLER_12(),
                                source, 1, 2));
    }

    public String getErrmsgh() {
        return getCosgn0ai().getFILLER_12().substring(2, 3);
    }

    public void setErrmsgh(String source) {
        getCosgn0ai()
                .setFILLER_12(
                        StringUtils.overlay(getCosgn0ai().getFILLER_12(),
                                source, 2, 3));
    }

    public String getErrmsgv() {
        return getCosgn0ai().getFILLER_12().substring(3, 4);
    }

    public void setErrmsgv(String source) {
        getCosgn0ai()
                .setFILLER_12(
                        StringUtils.overlay(getCosgn0ai().getFILLER_12(),
                                source, 3, 4));
    }

    public String getErrmsgo() {
        return getCosgn0ai().getErrmsgi();
    }

    public void setErrmsgo(String source) {
        getCosgn0ai().setErrmsgi(source);
    }

    public static @AllArgsConstructor @NoArgsConstructor @Builder(builderClassName = "builder") class Cosgn00cCosgn0ao {
        // [T-Up#INFO][COSGN00.CPY:87] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_23 = StringUtils.repeat(' ', 12);
        // [T-Up#INFO][COSGN00.CPY:88] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_24 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COSGN00.CPY:89] TRNNAMEC (level: 2)
        private @Getter String trnnamec = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:90] TRNNAMEP (level: 2)
        private @Getter String trnnamep = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:91] TRNNAMEH (level: 2)
        private @Getter String trnnameh = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:92] TRNNAMEV (level: 2)
        private @Getter String trnnamev = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:93] TRNNAMEO (level: 2)
        private @Getter String trnnameo = StringUtils.repeat(' ', 4);
        // [T-Up#INFO][COSGN00.CPY:94] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_25 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COSGN00.CPY:95] TITLE01C (level: 2)
        private @Getter String title01c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:96] TITLE01P (level: 2)
        private @Getter String title01p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:97] TITLE01H (level: 2)
        private @Getter String title01h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:98] TITLE01V (level: 2)
        private @Getter String title01v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:99] TITLE01O (level: 2)
        private @Getter String title01o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COSGN00.CPY:100] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_26 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COSGN00.CPY:101] CURDATEC (level: 2)
        private @Getter String curdatec = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:102] CURDATEP (level: 2)
        private @Getter String curdatep = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:103] CURDATEH (level: 2)
        private @Getter String curdateh = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:104] CURDATEV (level: 2)
        private @Getter String curdatev = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:105] CURDATEO (level: 2)
        private @Getter String curdateo = StringUtils.repeat(' ', 8);
        // [T-Up#INFO][COSGN00.CPY:106] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_27 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COSGN00.CPY:107] PGMNAMEC (level: 2)
        private @Getter String pgmnamec = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:108] PGMNAMEP (level: 2)
        private @Getter String pgmnamep = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:109] PGMNAMEH (level: 2)
        private @Getter String pgmnameh = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:110] PGMNAMEV (level: 2)
        private @Getter String pgmnamev = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:111] PGMNAMEO (level: 2)
        private @Getter String pgmnameo = StringUtils.repeat(' ', 8);
        // [T-Up#INFO][COSGN00.CPY:112] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_28 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COSGN00.CPY:113] TITLE02C (level: 2)
        private @Getter String title02c = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:114] TITLE02P (level: 2)
        private @Getter String title02p = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:115] TITLE02H (level: 2)
        private @Getter String title02h = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:116] TITLE02V (level: 2)
        private @Getter String title02v = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:117] TITLE02O (level: 2)
        private @Getter String title02o = StringUtils.repeat(' ', 40);
        // [T-Up#INFO][COSGN00.CPY:118] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_29 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COSGN00.CPY:119] CURTIMEC (level: 2)
        private @Getter String curtimec = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:120] CURTIMEP (level: 2)
        private @Getter String curtimep = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:121] CURTIMEH (level: 2)
        private @Getter String curtimeh = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:122] CURTIMEV (level: 2)
        private @Getter String curtimev = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:123] CURTIMEO (level: 2)
        private @Getter String curtimeo = StringUtils.repeat(' ', 9);
        // [T-Up#INFO][COSGN00.CPY:124] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_30 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COSGN00.CPY:125] APPLIDC (level: 2)
        private @Getter String applidc = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:126] APPLIDP (level: 2)
        private @Getter String applidp = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:127] APPLIDH (level: 2)
        private @Getter String applidh = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:128] APPLIDV (level: 2)
        private @Getter String applidv = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:129] APPLIDO (level: 2)
        private @Getter String applido = StringUtils.repeat(' ', 8);
        // [T-Up#INFO][COSGN00.CPY:130] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_31 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COSGN00.CPY:131] SYSIDC (level: 2)
        private @Getter String sysidc = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:132] SYSIDP (level: 2)
        private @Getter String sysidp = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:133] SYSIDH (level: 2)
        private @Getter String sysidh = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:134] SYSIDV (level: 2)
        private @Getter String sysidv = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:135] SYSIDO (level: 2)
        private @Getter String sysido = StringUtils.repeat(' ', 8);
        // [T-Up#INFO][COSGN00.CPY:136] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_32 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COSGN00.CPY:137] USERIDC (level: 2)
        private @Getter String useridc = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:138] USERIDP (level: 2)
        private @Getter String useridp = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:139] USERIDH (level: 2)
        private @Getter String useridh = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:140] USERIDV (level: 2)
        private @Getter String useridv = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:141] USERIDO (level: 2)
        private @Getter String userido = StringUtils.repeat(' ', 8);
        // [T-Up#INFO][COSGN00.CPY:142] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_33 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COSGN00.CPY:143] PASSWDC (level: 2)
        private @Getter String passwdc = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:144] PASSWDP (level: 2)
        private @Getter String passwdp = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:145] PASSWDH (level: 2)
        private @Getter String passwdh = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:146] PASSWDV (level: 2)
        private @Getter String passwdv = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:147] PASSWDO (level: 2)
        private @Getter String passwdo = StringUtils.repeat(' ', 8);
        // [T-Up#INFO][COSGN00.CPY:148] FILLER (level: 2)
        private @Getter String FILLER_REDEFINE_34 = StringUtils.repeat(' ', 3);
        // [T-Up#INFO][COSGN00.CPY:149] ERRMSGC (level: 2)
        private @Getter String errmsgc = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:150] ERRMSGP (level: 2)
        private @Getter String errmsgp = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:151] ERRMSGH (level: 2)
        private @Getter String errmsgh = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:152] ERRMSGV (level: 2)
        private @Getter String errmsgv = StringUtils.repeat(' ', 1);
        // [T-Up#INFO][COSGN00.CPY:153] ERRMSGO (level: 2)
        private @Getter String errmsgo = StringUtils.repeat(' ', 78);

        public String get() {
            StringBuilder sb = new StringBuilder();
            sb.append(FILLER_REDEFINE_23);
            sb.append(FILLER_REDEFINE_24);
            sb.append(trnnamec);
            sb.append(trnnamep);
            sb.append(trnnameh);
            sb.append(trnnamev);
            sb.append(trnnameo);
            sb.append(FILLER_REDEFINE_25);
            sb.append(title01c);
            sb.append(title01p);
            sb.append(title01h);
            sb.append(title01v);
            sb.append(title01o);
            sb.append(FILLER_REDEFINE_26);
            sb.append(curdatec);
            sb.append(curdatep);
            sb.append(curdateh);
            sb.append(curdatev);
            sb.append(curdateo);
            sb.append(FILLER_REDEFINE_27);
            sb.append(pgmnamec);
            sb.append(pgmnamep);
            sb.append(pgmnameh);
            sb.append(pgmnamev);
            sb.append(pgmnameo);
            sb.append(FILLER_REDEFINE_28);
            sb.append(title02c);
            sb.append(title02p);
            sb.append(title02h);
            sb.append(title02v);
            sb.append(title02o);
            sb.append(FILLER_REDEFINE_29);
            sb.append(curtimec);
            sb.append(curtimep);
            sb.append(curtimeh);
            sb.append(curtimev);
            sb.append(curtimeo);
            sb.append(FILLER_REDEFINE_30);
            sb.append(applidc);
            sb.append(applidp);
            sb.append(applidh);
            sb.append(applidv);
            sb.append(applido);
            sb.append(FILLER_REDEFINE_31);
            sb.append(sysidc);
            sb.append(sysidp);
            sb.append(sysidh);
            sb.append(sysidv);
            sb.append(sysido);
            sb.append(FILLER_REDEFINE_32);
            sb.append(useridc);
            sb.append(useridp);
            sb.append(useridh);
            sb.append(useridv);
            sb.append(userido);
            sb.append(FILLER_REDEFINE_33);
            sb.append(passwdc);
            sb.append(passwdp);
            sb.append(passwdh);
            sb.append(passwdv);
            sb.append(passwdo);
            sb.append(FILLER_REDEFINE_34);
            sb.append(errmsgc);
            sb.append(errmsgp);
            sb.append(errmsgh);
            sb.append(errmsgv);
            sb.append(errmsgo);
            return sb.toString();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(FILLER_REDEFINE_23);
            sb.append(FILLER_REDEFINE_24);
            sb.append(getTrnnamec());
            sb.append(getTrnnamep());
            sb.append(getTrnnameh());
            sb.append(getTrnnamev());
            sb.append(getTrnnameo());
            sb.append(FILLER_REDEFINE_25);
            sb.append(getTitle01c());
            sb.append(getTitle01p());
            sb.append(getTitle01h());
            sb.append(getTitle01v());
            sb.append(getTitle01o());
            sb.append(FILLER_REDEFINE_26);
            sb.append(getCurdatec());
            sb.append(getCurdatep());
            sb.append(getCurdateh());
            sb.append(getCurdatev());
            sb.append(getCurdateo());
            sb.append(FILLER_REDEFINE_27);
            sb.append(getPgmnamec());
            sb.append(getPgmnamep());
            sb.append(getPgmnameh());
            sb.append(getPgmnamev());
            sb.append(getPgmnameo());
            sb.append(FILLER_REDEFINE_28);
            sb.append(getTitle02c());
            sb.append(getTitle02p());
            sb.append(getTitle02h());
            sb.append(getTitle02v());
            sb.append(getTitle02o());
            sb.append(FILLER_REDEFINE_29);
            sb.append(getCurtimec());
            sb.append(getCurtimep());
            sb.append(getCurtimeh());
            sb.append(getCurtimev());
            sb.append(getCurtimeo());
            sb.append(FILLER_REDEFINE_30);
            sb.append(getApplidc());
            sb.append(getApplidp());
            sb.append(getApplidh());
            sb.append(getApplidv());
            sb.append(getApplido());
            sb.append(FILLER_REDEFINE_31);
            sb.append(getSysidc());
            sb.append(getSysidp());
            sb.append(getSysidh());
            sb.append(getSysidv());
            sb.append(getSysido());
            sb.append(FILLER_REDEFINE_32);
            sb.append(getUseridc());
            sb.append(getUseridp());
            sb.append(getUseridh());
            sb.append(getUseridv());
            sb.append(getUserido());
            sb.append(FILLER_REDEFINE_33);
            sb.append(getPasswdc());
            sb.append(getPasswdp());
            sb.append(getPasswdh());
            sb.append(getPasswdv());
            sb.append(getPasswdo());
            sb.append(FILLER_REDEFINE_34);
            sb.append(getErrmsgc());
            sb.append(getErrmsgp());
            sb.append(getErrmsgh());
            sb.append(getErrmsgv());
            sb.append(getErrmsgo());
            return sb.toString();
        }
    }
}
