package com.tmax.openframe.mapper;

import com.tmax.openframe.runtime.cobol.CobStream;
import com.tmax.openframe.variable.group.CardXrefRecord;
import com.tmax.openframe.variable.group.Cbact03cFdXreffileRec;
import com.tmax.openframe.variable.group.Cbact03cIoStatus;
import com.tmax.openframe.variable.group.Cbact03cIoStatus04;
import com.tmax.openframe.variable.group.Cbact03cXreffileStatus;
import java.math.*;
import java.util.*;
import lombok.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:10 KST</p>
 * <hr>
 * <p>Mapper class for converting data between different classes</p>
 */
public interface Cbact03cMapperInterface {
    /** 
     * <p>Mapper class to convert data for COBOL group variable to COBOL group variable</p>
     * <ul>
     * <li>source class: {@link Cbact03cFdXreffileRec}</li>
     * <li>target class: {@link CardXrefRecord}</li>
     * </ul>
     */
    class Cbact03cFdXreffileRecToCardXrefRecord {
        public static void set(Cbact03cFdXreffileRec source,
                CardXrefRecord target) {
            target.setXrefCardNum(source.getFdXrefCardNum());
            target.setXrefCustId(CobStream.convZonedStringToInt(source
                    .getFdXrefData().substring(0, 9), 9));
            target.setXrefAcctId(CobStream.convZonedStringToLong(source
                    .getFdXrefData().substring(9, 20), 11));
            target.setFILLER_1(source.getFdXrefData().substring(20, 34));
        }
    }

    /** 
     * <p>Mapper class to convert data for COBOL group variable to COBOL group variable</p>
     * <ul>
     * <li>source class: {@link Cbact03cXreffileStatus}</li>
     * <li>target class: {@link Cbact03cIoStatus}</li>
     * </ul>
     */
    class Cbact03cXreffileStatusToCbact03cIoStatus {
        public static void set(Cbact03cXreffileStatus source,
                Cbact03cIoStatus target) {
            target.setIoStat1(source.getXreffileStat1());
            target.setIoStat2(source.getXreffileStat2());
        }
    }

    /** 
     * <p>Mapper class to convert data for COBOL group variable to COBOL group variable</p>
     * <ul>
     * <li>source class: {@link Cbact03cIoStatus}</li>
     * <li>target class: {@link Cbact03cIoStatus04}</li>
     * </ul>
     */
    class Cbact03cIoStatusToCbact03cIoStatus04 {
        public static void set(Cbact03cIoStatus source,
                Cbact03cIoStatus04 target) {
            target.setIoStatus0401(CobStream.convZonedStringToInt(
                    source.getIoStat1(), 1));
            target.setIoStatus0403(CobStream.convZonedStringToInt(
                    source.getIoStat2(), 3));
        }
    }
}
