package com.tmax.openframe.mapper;

import com.tmax.openframe.runtime.cobol.CobStream;
import com.tmax.openframe.variable.group.CardRecord;
import com.tmax.openframe.variable.group.Cbact02cCardfileStatus;
import com.tmax.openframe.variable.group.Cbact02cFdCardfileRec;
import com.tmax.openframe.variable.group.Cbact02cIoStatus;
import com.tmax.openframe.variable.group.Cbact02cIoStatus04;
import java.math.*;
import java.util.*;
import lombok.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:10 KST</p>
 * <hr>
 * <p>Mapper class for converting data between different classes</p>
 */
public interface Cbact02cMapperInterface {
    /** 
     * <p>Mapper class to convert data for COBOL group variable to COBOL group variable</p>
     * <ul>
     * <li>source class: {@link Cbact02cIoStatus}</li>
     * <li>target class: {@link Cbact02cIoStatus04}</li>
     * </ul>
     */
    class Cbact02cIoStatusToCbact02cIoStatus04 {
        public static void set(Cbact02cIoStatus source,
                Cbact02cIoStatus04 target) {
            target.setIoStatus0401(CobStream.convZonedStringToInt(
                    source.getIoStat1(), 1));
            target.setIoStatus0403(CobStream.convZonedStringToInt(
                    source.getIoStat2(), 3));
        }
    }

    /** 
     * <p>Mapper class to convert data for COBOL group variable to COBOL group variable</p>
     * <ul>
     * <li>source class: {@link Cbact02cFdCardfileRec}</li>
     * <li>target class: {@link CardRecord}</li>
     * </ul>
     */
    class Cbact02cFdCardfileRecToCardRecord {
        public static void set(Cbact02cFdCardfileRec source, CardRecord target) {
            target.setCardNum(source.getFdCardNum());
            target.setCardAcctId(CobStream.convZonedStringToLong(source
                    .getFdCardData().substring(0, 11), 11));
            target.setCardCvvCd(CobStream.convZonedStringToInt(source
                    .getFdCardData().substring(11, 14), 3));
            target.setCardEmbossedName(source.getFdCardData().substring(14, 64));
            target.setCardExpiraionDate(source.getFdCardData()
                    .substring(64, 74));
            target.setCardActiveStatus(source.getFdCardData().substring(74, 75));
            target.setFILLER_1(source.getFdCardData().substring(75, 134));
        }
    }

    /** 
     * <p>Mapper class to convert data for COBOL group variable to COBOL group variable</p>
     * <ul>
     * <li>source class: {@link Cbact02cCardfileStatus}</li>
     * <li>target class: {@link Cbact02cIoStatus}</li>
     * </ul>
     */
    class Cbact02cCardfileStatusToCbact02cIoStatus {
        public static void set(Cbact02cCardfileStatus source,
                Cbact02cIoStatus target) {
            target.setIoStat1(source.getCardfileStat1());
            target.setIoStat2(source.getCardfileStat2());
        }
    }
}
