package com.tmax.openframe.mapper;

import com.tmax.openframe.runtime.cobol.CobStream;
import com.tmax.openframe.variable.group.Cbcus01cCustfileStatus;
import com.tmax.openframe.variable.group.Cbcus01cFdCustfileRec;
import com.tmax.openframe.variable.group.Cbcus01cIoStatus;
import com.tmax.openframe.variable.group.Cbcus01cIoStatus04;
import com.tmax.openframe.variable.group.CustomerRecord;
import java.math.*;
import java.util.*;
import lombok.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:10 KST</p>
 * <hr>
 * <p>Mapper class for converting data between different classes</p>
 */
public interface Cbcus01cMapperInterface {
    /** 
     * <p>Mapper class to convert data for COBOL group variable to COBOL group variable</p>
     * <ul>
     * <li>source class: {@link Cbcus01cCustfileStatus}</li>
     * <li>target class: {@link Cbcus01cIoStatus}</li>
     * </ul>
     */
    class Cbcus01cCustfileStatusToCbcus01cIoStatus {
        public static void set(Cbcus01cCustfileStatus source,
                Cbcus01cIoStatus target) {
            target.setIoStat1(source.getCustfileStat1());
            target.setIoStat2(source.getCustfileStat2());
        }
    }

    /** 
     * <p>Mapper class to convert data for COBOL group variable to COBOL group variable</p>
     * <ul>
     * <li>source class: {@link Cbcus01cFdCustfileRec}</li>
     * <li>target class: {@link CustomerRecord}</li>
     * </ul>
     */
    class Cbcus01cFdCustfileRecToCustomerRecord {
        public static void set(Cbcus01cFdCustfileRec source,
                CustomerRecord target) {
            target.setCustId(source.getFdCustId());
            target.setCustFirstName(source.getFdCustData().substring(0, 25));
            target.setCustMiddleName(source.getFdCustData().substring(25, 50));
            target.setCustLastName(source.getFdCustData().substring(50, 75));
            target.setCustAddrLine1(source.getFdCustData().substring(75, 125));
            target.setCustAddrLine2(source.getFdCustData().substring(125, 175));
            target.setCustAddrLine3(source.getFdCustData().substring(175, 225));
            target.setCustAddrStateCd(source.getFdCustData()
                    .substring(225, 227));
            target.setCustAddrCountryCd(source.getFdCustData().substring(227,
                    230));
            target.setCustAddrZip(source.getFdCustData().substring(230, 240));
            target.setCustPhoneNum1(source.getFdCustData().substring(240, 255));
            target.setCustPhoneNum2(source.getFdCustData().substring(255, 270));
            target.setCustSsn(CobStream.convZonedStringToInt(source
                    .getFdCustData().substring(270, 279), 9));
            target.setCustGovtIssuedId(source.getFdCustData().substring(279,
                    299));
            target.setCustDobYyyyMmDd(source.getFdCustData()
                    .substring(299, 309));
            target.setCustEftAccountId(source.getFdCustData().substring(309,
                    319));
            target.setCustPriCardHolderInd(source.getFdCustData().substring(
                    319, 320));
            target.setCustFicoCreditScore(CobStream.convZonedStringToInt(source
                    .getFdCustData().substring(320, 323), 3));
            target.setFILLER_1(source.getFdCustData().substring(323, 491));
        }
    }

    /** 
     * <p>Mapper class to convert data for COBOL group variable to COBOL group variable</p>
     * <ul>
     * <li>source class: {@link Cbcus01cIoStatus}</li>
     * <li>target class: {@link Cbcus01cIoStatus04}</li>
     * </ul>
     */
    class Cbcus01cIoStatusToCbcus01cIoStatus04 {
        public static void set(Cbcus01cIoStatus source,
                Cbcus01cIoStatus04 target) {
            target.setIoStatus0401(CobStream.convZonedStringToInt(
                    source.getIoStat1(), 1));
            target.setIoStatus0403(CobStream.convZonedStringToInt(
                    source.getIoStat2(), 3));
        }
    }
}
