package com.tmax.openframe.mapper;

import com.tmax.openframe.DataConverter;
import org.apache.commons.lang3.StringUtils;
import org.mapstruct.*;
import org.mapstruct.factory.*;
import com.tmax.openframe.variable.group.AccountRecord;
import com.tmax.openframe.dto.AwsM2CarddemoAcctdataVsamKsdsDto;
import com.tmax.openframe.variable.group.CardXrefRecord;
import com.tmax.openframe.dto.AwsM2CarddemoCardxrefVsamKsdsDto;
import com.tmax.openframe.variable.group.CustomerRecord;
import com.tmax.openframe.dto.AwsM2CarddemoCustdataVsamKsdsDto;
import com.tmax.openframe.variable.group.CarddemoCommarea;
import com.tmax.openframe.variable.group.Comen01cDfhcommarea;
import java.math.*;
import java.util.*;
import lombok.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:14 KST</p>
 * <hr>
 * <p>Mapper class for converting data between different classes</p>
 */
public interface CoactvwcMapperInterface {
    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link AccountRecord}</li>
     * <li>target class: {@link AwsM2CarddemoAcctdataVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @org.mapstruct.Builder(disableBuilder = true))
    public interface AccountRecordToAwsM2CarddemoAcctdataVsamKsdsDto {
        AccountRecordToAwsM2CarddemoAcctdataVsamKsdsDto INSTANCE = Mappers
                .getMapper(AccountRecordToAwsM2CarddemoAcctdataVsamKsdsDto.class);

        @Mapping(source = "acctId", target = "acctId")
        @Mapping(source = "acctActiveStatus", target = "acctActiveStatus")
        @Mapping(source = "acctCurrBal", target = "acctCurrBal")
        @Mapping(source = "acctCreditLimit", target = "acctCreditLimit")
        @Mapping(source = "acctCashCreditLimit", target = "acctCashCreditLimit")
        @Mapping(source = "acctOpenDate", target = "acctOpenDate")
        @Mapping(source = "acctExpiraionDate", target = "acctExpiraionDate")
        @Mapping(source = "acctReissueDate", target = "acctReissueDate")
        @Mapping(source = "acctCurrCycCredit", target = "acctCurrCycCredit")
        @Mapping(source = "acctCurrCycDebit", target = "acctCurrCycDebit")
        @Mapping(source = "acctAddrZip", target = "acctAddrZip")
        @Mapping(source = "acctGroupId", target = "acctGroupId")
        @Mapping(source = "FILLER_1", target = "filler")
        AwsM2CarddemoAcctdataVsamKsdsDto toTarget(AccountRecord source);

        @Mapping(source = "acctId", target = "acctId")
        @Mapping(source = "acctActiveStatus", target = "acctActiveStatus")
        @Mapping(source = "acctCurrBal", target = "acctCurrBal")
        @Mapping(source = "acctCreditLimit", target = "acctCreditLimit")
        @Mapping(source = "acctCashCreditLimit", target = "acctCashCreditLimit")
        @Mapping(source = "acctOpenDate", target = "acctOpenDate")
        @Mapping(source = "acctExpiraionDate", target = "acctExpiraionDate")
        @Mapping(source = "acctReissueDate", target = "acctReissueDate")
        @Mapping(source = "acctCurrCycCredit", target = "acctCurrCycCredit")
        @Mapping(source = "acctCurrCycDebit", target = "acctCurrCycDebit")
        @Mapping(source = "acctAddrZip", target = "acctAddrZip")
        @Mapping(source = "acctGroupId", target = "acctGroupId")
        @Mapping(source = "filler", target = "FILLER_1")
        AccountRecord toSource(AwsM2CarddemoAcctdataVsamKsdsDto source);
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link CardXrefRecord}</li>
     * <li>target class: {@link AwsM2CarddemoCardxrefVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @org.mapstruct.Builder(disableBuilder = true))
    public interface CardXrefRecordToAwsM2CarddemoCardxrefVsamKsdsDto {
        CardXrefRecordToAwsM2CarddemoCardxrefVsamKsdsDto INSTANCE = Mappers
                .getMapper(CardXrefRecordToAwsM2CarddemoCardxrefVsamKsdsDto.class);

        @Mapping(source = "xrefCardNum", target = "xrefCardNum")
        @Mapping(source = "xrefCustId", target = "xrefCustId")
        @Mapping(source = "xrefAcctId", target = "xrefAcctId")
        @Mapping(source = "FILLER_1", target = "filler")
        AwsM2CarddemoCardxrefVsamKsdsDto toTarget(CardXrefRecord source);

        @Mapping(source = "xrefCardNum", target = "xrefCardNum")
        @Mapping(source = "xrefCustId", target = "xrefCustId")
        @Mapping(source = "xrefAcctId", target = "xrefAcctId")
        @Mapping(source = "filler", target = "FILLER_1")
        CardXrefRecord toSource(AwsM2CarddemoCardxrefVsamKsdsDto source);
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link CustomerRecord}</li>
     * <li>target class: {@link AwsM2CarddemoCustdataVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @org.mapstruct.Builder(disableBuilder = true))
    public interface CustomerRecordToAwsM2CarddemoCustdataVsamKsdsDto {
        CustomerRecordToAwsM2CarddemoCustdataVsamKsdsDto INSTANCE = Mappers
                .getMapper(CustomerRecordToAwsM2CarddemoCustdataVsamKsdsDto.class);

        @Mapping(source = "custId", target = "custId")
        @Mapping(source = "custFirstName", target = "custFirstName")
        @Mapping(source = "custMiddleName", target = "custMiddleName")
        @Mapping(source = "custLastName", target = "custLastName")
        @Mapping(source = "custAddrLine1", target = "custAddrLine1")
        @Mapping(source = "custAddrLine2", target = "custAddrLine2")
        @Mapping(source = "custAddrLine3", target = "custAddrLine3")
        @Mapping(source = "custAddrStateCd", target = "custAddrStateCd")
        @Mapping(source = "custAddrCountryCd", target = "custAddrCountryCd")
        @Mapping(source = "custAddrZip", target = "custAddrZip")
        @Mapping(source = "custPhoneNum1", target = "custPhoneNum1")
        @Mapping(source = "custPhoneNum2", target = "custPhoneNum2")
        @Mapping(source = "custSsn", target = "custSsn")
        @Mapping(source = "custGovtIssuedId", target = "custGovtIssuedId")
        @Mapping(source = "custDobYyyyMmDd", target = "custDobYyyymmdd")
        @Mapping(source = "custEftAccountId", target = "custEftAccountId")
        @Mapping(source = "custPriCardHolderInd", target = "custPriCardHolderInd")
        @Mapping(source = "custFicoCreditScore", target = "custFicoCreditScore")
        @Mapping(source = "FILLER_1", target = "filler")
        AwsM2CarddemoCustdataVsamKsdsDto toTarget(CustomerRecord source);

        @Mapping(source = "custId", target = "custId")
        @Mapping(source = "custFirstName", target = "custFirstName")
        @Mapping(source = "custMiddleName", target = "custMiddleName")
        @Mapping(source = "custLastName", target = "custLastName")
        @Mapping(source = "custAddrLine1", target = "custAddrLine1")
        @Mapping(source = "custAddrLine2", target = "custAddrLine2")
        @Mapping(source = "custAddrLine3", target = "custAddrLine3")
        @Mapping(source = "custAddrStateCd", target = "custAddrStateCd")
        @Mapping(source = "custAddrCountryCd", target = "custAddrCountryCd")
        @Mapping(source = "custAddrZip", target = "custAddrZip")
        @Mapping(source = "custPhoneNum1", target = "custPhoneNum1")
        @Mapping(source = "custPhoneNum2", target = "custPhoneNum2")
        @Mapping(source = "custSsn", target = "custSsn")
        @Mapping(source = "custGovtIssuedId", target = "custGovtIssuedId")
        @Mapping(source = "custDobYyyymmdd", target = "custDobYyyyMmDd")
        @Mapping(source = "custEftAccountId", target = "custEftAccountId")
        @Mapping(source = "custPriCardHolderInd", target = "custPriCardHolderInd")
        @Mapping(source = "custFicoCreditScore", target = "custFicoCreditScore")
        @Mapping(source = "filler", target = "FILLER_1")
        CustomerRecord toSource(AwsM2CarddemoCustdataVsamKsdsDto source);
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link CarddemoCommarea}</li>
     * <li>target class: {@link Comen01cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @org.mapstruct.Builder(disableBuilder = true))
    public interface CarddemoCommareaToComen01cDfhcommarea {
        CarddemoCommareaToComen01cDfhcommarea INSTANCE = Mappers
                .getMapper(CarddemoCommareaToComen01cDfhcommarea.class);

        Comen01cDfhcommarea toTarget(CarddemoCommarea source);

        CarddemoCommarea toSource(Comen01cDfhcommarea source);

        @AfterMapping
        default void makeTarget(CarddemoCommarea source,
                @MappingTarget Comen01cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset());
        }

        @AfterMapping
        default void makeSource(Comen01cDfhcommarea source,
                @MappingTarget CarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    StringUtils.substring(source.getLkCommarea(), 0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    StringUtils.substring(source.getLkCommarea(), 4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    StringUtils.substring(source.getLkCommarea(), 12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    StringUtils.substring(source.getLkCommarea(), 16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    StringUtils.substring(source.getLkCommarea(), 24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    StringUtils.substring(source.getLkCommarea(), 32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    StringUtils.substring(source.getLkCommarea(), 43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    StringUtils.substring(source.getLkCommarea(), 68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    StringUtils.substring(source.getLkCommarea(), 93, 118));
            try {
                target.getCdemoAccountInfo().setCdemoAcctId(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 118, 129),
                                11));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    StringUtils.substring(source.getLkCommarea(), 129, 130));
            try {
                target.getCdemoCardInfo().setCdemoCardNum(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 130, 146),
                                16));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoMoreInfo().setCdemoLastMap(
                    StringUtils.substring(source.getLkCommarea(), 146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    StringUtils.substring(source.getLkCommarea(), 153, 160));
        }
    }
}
