package com.tmax.openframe.mapper;

import com.tmax.openframe.DataConverter;
import org.apache.commons.lang3.StringUtils;
import org.mapstruct.*;
import org.mapstruct.factory.*;
import com.tmax.openframe.variable.group.CarddemoCommarea;
import com.tmax.openframe.variable.group.Cousr00cDfhcommarea;
import com.tmax.openframe.variable.group.Cousr03cDfhcommarea;
import com.tmax.openframe.variable.group.Cousr02cDfhcommarea;
import com.tmax.openframe.variable.group.Coadm01cDfhcommarea;
import com.tmax.openframe.variable.group.Cousr01cDfhcommarea;
import java.math.*;
import java.util.*;
import lombok.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:15 KST</p>
 * <hr>
 * <p>Mapper class for converting data between different classes</p>
 */
public interface Coadm01cMapperInterface {
    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link CarddemoCommarea}</li>
     * <li>target class: {@link Cousr00cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @org.mapstruct.Builder(disableBuilder = true))
    public interface CarddemoCommareaToCousr00cDfhcommarea {
        CarddemoCommareaToCousr00cDfhcommarea INSTANCE = Mappers
                .getMapper(CarddemoCommareaToCousr00cDfhcommarea.class);

        Cousr00cDfhcommarea toTarget(CarddemoCommarea source);

        CarddemoCommarea toSource(Cousr00cDfhcommarea source);

        @AfterMapping
        default void makeTarget(CarddemoCommarea source,
                @MappingTarget Cousr00cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset());
        }

        @AfterMapping
        default void makeSource(Cousr00cDfhcommarea source,
                @MappingTarget CarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    StringUtils.substring(source.getLkCommarea(), 0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    StringUtils.substring(source.getLkCommarea(), 4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    StringUtils.substring(source.getLkCommarea(), 12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    StringUtils.substring(source.getLkCommarea(), 16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    StringUtils.substring(source.getLkCommarea(), 24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    StringUtils.substring(source.getLkCommarea(), 32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    StringUtils.substring(source.getLkCommarea(), 43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    StringUtils.substring(source.getLkCommarea(), 68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    StringUtils.substring(source.getLkCommarea(), 93, 118));
            try {
                target.getCdemoAccountInfo().setCdemoAcctId(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 118, 129),
                                11));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    StringUtils.substring(source.getLkCommarea(), 129, 130));
            try {
                target.getCdemoCardInfo().setCdemoCardNum(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 130, 146),
                                16));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoMoreInfo().setCdemoLastMap(
                    StringUtils.substring(source.getLkCommarea(), 146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    StringUtils.substring(source.getLkCommarea(), 153, 160));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link CarddemoCommarea}</li>
     * <li>target class: {@link Cousr03cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @org.mapstruct.Builder(disableBuilder = true))
    public interface CarddemoCommareaToCousr03cDfhcommarea {
        CarddemoCommareaToCousr03cDfhcommarea INSTANCE = Mappers
                .getMapper(CarddemoCommareaToCousr03cDfhcommarea.class);

        Cousr03cDfhcommarea toTarget(CarddemoCommarea source);

        CarddemoCommarea toSource(Cousr03cDfhcommarea source);

        @AfterMapping
        default void makeTarget(CarddemoCommarea source,
                @MappingTarget Cousr03cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset());
        }

        @AfterMapping
        default void makeSource(Cousr03cDfhcommarea source,
                @MappingTarget CarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    StringUtils.substring(source.getLkCommarea(), 0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    StringUtils.substring(source.getLkCommarea(), 4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    StringUtils.substring(source.getLkCommarea(), 12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    StringUtils.substring(source.getLkCommarea(), 16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    StringUtils.substring(source.getLkCommarea(), 24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    StringUtils.substring(source.getLkCommarea(), 32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    StringUtils.substring(source.getLkCommarea(), 43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    StringUtils.substring(source.getLkCommarea(), 68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    StringUtils.substring(source.getLkCommarea(), 93, 118));
            try {
                target.getCdemoAccountInfo().setCdemoAcctId(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 118, 129),
                                11));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    StringUtils.substring(source.getLkCommarea(), 129, 130));
            try {
                target.getCdemoCardInfo().setCdemoCardNum(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 130, 146),
                                16));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoMoreInfo().setCdemoLastMap(
                    StringUtils.substring(source.getLkCommarea(), 146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    StringUtils.substring(source.getLkCommarea(), 153, 160));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link CarddemoCommarea}</li>
     * <li>target class: {@link Cousr02cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @org.mapstruct.Builder(disableBuilder = true))
    public interface CarddemoCommareaToCousr02cDfhcommarea {
        CarddemoCommareaToCousr02cDfhcommarea INSTANCE = Mappers
                .getMapper(CarddemoCommareaToCousr02cDfhcommarea.class);

        Cousr02cDfhcommarea toTarget(CarddemoCommarea source);

        CarddemoCommarea toSource(Cousr02cDfhcommarea source);

        @AfterMapping
        default void makeTarget(CarddemoCommarea source,
                @MappingTarget Cousr02cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset());
        }

        @AfterMapping
        default void makeSource(Cousr02cDfhcommarea source,
                @MappingTarget CarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    StringUtils.substring(source.getLkCommarea(), 0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    StringUtils.substring(source.getLkCommarea(), 4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    StringUtils.substring(source.getLkCommarea(), 12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    StringUtils.substring(source.getLkCommarea(), 16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    StringUtils.substring(source.getLkCommarea(), 24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    StringUtils.substring(source.getLkCommarea(), 32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    StringUtils.substring(source.getLkCommarea(), 43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    StringUtils.substring(source.getLkCommarea(), 68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    StringUtils.substring(source.getLkCommarea(), 93, 118));
            try {
                target.getCdemoAccountInfo().setCdemoAcctId(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 118, 129),
                                11));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    StringUtils.substring(source.getLkCommarea(), 129, 130));
            try {
                target.getCdemoCardInfo().setCdemoCardNum(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 130, 146),
                                16));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoMoreInfo().setCdemoLastMap(
                    StringUtils.substring(source.getLkCommarea(), 146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    StringUtils.substring(source.getLkCommarea(), 153, 160));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link CarddemoCommarea}</li>
     * <li>target class: {@link Coadm01cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @org.mapstruct.Builder(disableBuilder = true))
    public interface CarddemoCommareaToCoadm01cDfhcommarea {
        CarddemoCommareaToCoadm01cDfhcommarea INSTANCE = Mappers
                .getMapper(CarddemoCommareaToCoadm01cDfhcommarea.class);

        Coadm01cDfhcommarea toTarget(CarddemoCommarea source);

        CarddemoCommarea toSource(Coadm01cDfhcommarea source);

        @AfterMapping
        default void makeTarget(CarddemoCommarea source,
                @MappingTarget Coadm01cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset());
        }

        @AfterMapping
        default void makeSource(Coadm01cDfhcommarea source,
                @MappingTarget CarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    StringUtils.substring(source.getLkCommarea(), 0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    StringUtils.substring(source.getLkCommarea(), 4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    StringUtils.substring(source.getLkCommarea(), 12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    StringUtils.substring(source.getLkCommarea(), 16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    StringUtils.substring(source.getLkCommarea(), 24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    StringUtils.substring(source.getLkCommarea(), 32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    StringUtils.substring(source.getLkCommarea(), 43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    StringUtils.substring(source.getLkCommarea(), 68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    StringUtils.substring(source.getLkCommarea(), 93, 118));
            try {
                target.getCdemoAccountInfo().setCdemoAcctId(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 118, 129),
                                11));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    StringUtils.substring(source.getLkCommarea(), 129, 130));
            try {
                target.getCdemoCardInfo().setCdemoCardNum(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 130, 146),
                                16));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoMoreInfo().setCdemoLastMap(
                    StringUtils.substring(source.getLkCommarea(), 146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    StringUtils.substring(source.getLkCommarea(), 153, 160));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link CarddemoCommarea}</li>
     * <li>target class: {@link Cousr01cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @org.mapstruct.Builder(disableBuilder = true))
    public interface CarddemoCommareaToCousr01cDfhcommarea {
        CarddemoCommareaToCousr01cDfhcommarea INSTANCE = Mappers
                .getMapper(CarddemoCommareaToCousr01cDfhcommarea.class);

        Cousr01cDfhcommarea toTarget(CarddemoCommarea source);

        CarddemoCommarea toSource(Cousr01cDfhcommarea source);

        @AfterMapping
        default void makeTarget(CarddemoCommarea source,
                @MappingTarget Cousr01cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset());
        }

        @AfterMapping
        default void makeSource(Cousr01cDfhcommarea source,
                @MappingTarget CarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    StringUtils.substring(source.getLkCommarea(), 0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    StringUtils.substring(source.getLkCommarea(), 4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    StringUtils.substring(source.getLkCommarea(), 12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    StringUtils.substring(source.getLkCommarea(), 16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    StringUtils.substring(source.getLkCommarea(), 24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    StringUtils.substring(source.getLkCommarea(), 32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    StringUtils.substring(source.getLkCommarea(), 43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    StringUtils.substring(source.getLkCommarea(), 68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    StringUtils.substring(source.getLkCommarea(), 93, 118));
            try {
                target.getCdemoAccountInfo().setCdemoAcctId(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 118, 129),
                                11));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    StringUtils.substring(source.getLkCommarea(), 129, 130));
            try {
                target.getCdemoCardInfo().setCdemoCardNum(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 130, 146),
                                16));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoMoreInfo().setCdemoLastMap(
                    StringUtils.substring(source.getLkCommarea(), 146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    StringUtils.substring(source.getLkCommarea(), 153, 160));
        }
    }
}
