package com.tmax.openframe.mapper;

import com.tmax.openframe.DataConverter;
import org.apache.commons.lang3.StringUtils;
import org.mapstruct.*;
import org.mapstruct.factory.*;
import com.tmax.openframe.variable.group.AccountRecord;
import com.tmax.openframe.dto.AwsM2CarddemoAcctdataVsamKsdsDto;
import com.tmax.openframe.variable.group.Cobil00cCarddemoCommarea;
import com.tmax.openframe.variable.group.Cosgn00cDfhcommarea;
import com.tmax.openframe.variable.group.Cobil00cDfhcommarea;
import com.tmax.openframe.variable.group.CardXrefRecord;
import com.tmax.openframe.dto.AwsM2CarddemoCardxrefVsamKsdsDto;
import com.tmax.openframe.variable.group.Comen01cDfhcommarea;
import com.tmax.openframe.variable.group.TranRecord;
import com.tmax.openframe.dto.AwsM2CarddemoTransactVsamKsdsDto;
import java.math.*;
import java.util.*;
import lombok.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:15 KST</p>
 * <hr>
 * <p>Mapper class for converting data between different classes</p>
 */
public interface Cobil00cMapperInterface {
    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link AccountRecord}</li>
     * <li>target class: {@link AwsM2CarddemoAcctdataVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @org.mapstruct.Builder(disableBuilder = true))
    public interface AccountRecordToAwsM2CarddemoAcctdataVsamKsdsDto {
        AccountRecordToAwsM2CarddemoAcctdataVsamKsdsDto INSTANCE = Mappers
                .getMapper(AccountRecordToAwsM2CarddemoAcctdataVsamKsdsDto.class);

        @Mapping(source = "acctId", target = "acctId")
        @Mapping(source = "acctActiveStatus", target = "acctActiveStatus")
        @Mapping(source = "acctCurrBal", target = "acctCurrBal")
        @Mapping(source = "acctCreditLimit", target = "acctCreditLimit")
        @Mapping(source = "acctCashCreditLimit", target = "acctCashCreditLimit")
        @Mapping(source = "acctOpenDate", target = "acctOpenDate")
        @Mapping(source = "acctExpiraionDate", target = "acctExpiraionDate")
        @Mapping(source = "acctReissueDate", target = "acctReissueDate")
        @Mapping(source = "acctCurrCycCredit", target = "acctCurrCycCredit")
        @Mapping(source = "acctCurrCycDebit", target = "acctCurrCycDebit")
        @Mapping(source = "acctAddrZip", target = "acctAddrZip")
        @Mapping(source = "acctGroupId", target = "acctGroupId")
        @Mapping(source = "FILLER_1", target = "filler")
        AwsM2CarddemoAcctdataVsamKsdsDto toTarget(AccountRecord source);

        @Mapping(source = "acctId", target = "acctId")
        @Mapping(source = "acctActiveStatus", target = "acctActiveStatus")
        @Mapping(source = "acctCurrBal", target = "acctCurrBal")
        @Mapping(source = "acctCreditLimit", target = "acctCreditLimit")
        @Mapping(source = "acctCashCreditLimit", target = "acctCashCreditLimit")
        @Mapping(source = "acctOpenDate", target = "acctOpenDate")
        @Mapping(source = "acctExpiraionDate", target = "acctExpiraionDate")
        @Mapping(source = "acctReissueDate", target = "acctReissueDate")
        @Mapping(source = "acctCurrCycCredit", target = "acctCurrCycCredit")
        @Mapping(source = "acctCurrCycDebit", target = "acctCurrCycDebit")
        @Mapping(source = "acctAddrZip", target = "acctAddrZip")
        @Mapping(source = "acctGroupId", target = "acctGroupId")
        @Mapping(source = "filler", target = "FILLER_1")
        AccountRecord toSource(AwsM2CarddemoAcctdataVsamKsdsDto source);
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cobil00cCarddemoCommarea}</li>
     * <li>target class: {@link Cosgn00cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @org.mapstruct.Builder(disableBuilder = true))
    public interface Cobil00cCarddemoCommareaToCosgn00cDfhcommarea {
        Cobil00cCarddemoCommareaToCosgn00cDfhcommarea INSTANCE = Mappers
                .getMapper(Cobil00cCarddemoCommareaToCosgn00cDfhcommarea.class);

        Cosgn00cDfhcommarea toTarget(Cobil00cCarddemoCommarea source);

        Cobil00cCarddemoCommarea toSource(Cosgn00cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cobil00cCarddemoCommarea source,
                @MappingTarget Cosgn00cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset()
                    + source.getCdemoCb00Info().getCdemoCb00TrnidFirst()
                    + source.getCdemoCb00Info().getCdemoCb00TrnidLast()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCb00Info().getCdemoCb00PageNum(), 8)
                    + source.getCdemoCb00Info().getCdemoCb00NextPageFlg()
                    + source.getCdemoCb00Info().getCdemoCb00TrnSelFlg()
                    + source.getCdemoCb00Info().getCdemoCb00TrnSelected());
        }

        @AfterMapping
        default void makeSource(Cosgn00cDfhcommarea source,
                @MappingTarget Cobil00cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    StringUtils.substring(source.getLkCommarea(), 0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    StringUtils.substring(source.getLkCommarea(), 4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    StringUtils.substring(source.getLkCommarea(), 12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    StringUtils.substring(source.getLkCommarea(), 16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    StringUtils.substring(source.getLkCommarea(), 24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    StringUtils.substring(source.getLkCommarea(), 32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    StringUtils.substring(source.getLkCommarea(), 43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    StringUtils.substring(source.getLkCommarea(), 68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    StringUtils.substring(source.getLkCommarea(), 93, 118));
            try {
                target.getCdemoAccountInfo().setCdemoAcctId(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 118, 129),
                                11));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    StringUtils.substring(source.getLkCommarea(), 129, 130));
            try {
                target.getCdemoCardInfo().setCdemoCardNum(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 130, 146),
                                16));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoMoreInfo().setCdemoLastMap(
                    StringUtils.substring(source.getLkCommarea(), 146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    StringUtils.substring(source.getLkCommarea(), 153, 160));
            target.getCdemoCb00Info().setCdemoCb00TrnidFirst(
                    StringUtils.substring(source.getLkCommarea(), 160, 176));
            target.getCdemoCb00Info().setCdemoCb00TrnidLast(
                    StringUtils.substring(source.getLkCommarea(), 176, 192));
            target.getCdemoCb00Info().setCdemoCb00PageNum(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 192, 200), 8)));
            target.getCdemoCb00Info().setCdemoCb00NextPageFlg(
                    StringUtils.substring(source.getLkCommarea(), 200, 201));
            target.getCdemoCb00Info().setCdemoCb00TrnSelFlg(
                    StringUtils.substring(source.getLkCommarea(), 201, 202));
            target.getCdemoCb00Info().setCdemoCb00TrnSelected(
                    StringUtils.substring(source.getLkCommarea(), 202, 218));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cobil00cCarddemoCommarea}</li>
     * <li>target class: {@link Cobil00cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @org.mapstruct.Builder(disableBuilder = true))
    public interface Cobil00cCarddemoCommareaToCobil00cDfhcommarea {
        Cobil00cCarddemoCommareaToCobil00cDfhcommarea INSTANCE = Mappers
                .getMapper(Cobil00cCarddemoCommareaToCobil00cDfhcommarea.class);

        Cobil00cDfhcommarea toTarget(Cobil00cCarddemoCommarea source);

        Cobil00cCarddemoCommarea toSource(Cobil00cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cobil00cCarddemoCommarea source,
                @MappingTarget Cobil00cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset()
                    + source.getCdemoCb00Info().getCdemoCb00TrnidFirst()
                    + source.getCdemoCb00Info().getCdemoCb00TrnidLast()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCb00Info().getCdemoCb00PageNum(), 8)
                    + source.getCdemoCb00Info().getCdemoCb00NextPageFlg()
                    + source.getCdemoCb00Info().getCdemoCb00TrnSelFlg()
                    + source.getCdemoCb00Info().getCdemoCb00TrnSelected());
        }

        @AfterMapping
        default void makeSource(Cobil00cDfhcommarea source,
                @MappingTarget Cobil00cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    StringUtils.substring(source.getLkCommarea(), 0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    StringUtils.substring(source.getLkCommarea(), 4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    StringUtils.substring(source.getLkCommarea(), 12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    StringUtils.substring(source.getLkCommarea(), 16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    StringUtils.substring(source.getLkCommarea(), 24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    StringUtils.substring(source.getLkCommarea(), 32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    StringUtils.substring(source.getLkCommarea(), 43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    StringUtils.substring(source.getLkCommarea(), 68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    StringUtils.substring(source.getLkCommarea(), 93, 118));
            try {
                target.getCdemoAccountInfo().setCdemoAcctId(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 118, 129),
                                11));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    StringUtils.substring(source.getLkCommarea(), 129, 130));
            try {
                target.getCdemoCardInfo().setCdemoCardNum(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 130, 146),
                                16));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoMoreInfo().setCdemoLastMap(
                    StringUtils.substring(source.getLkCommarea(), 146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    StringUtils.substring(source.getLkCommarea(), 153, 160));
            target.getCdemoCb00Info().setCdemoCb00TrnidFirst(
                    StringUtils.substring(source.getLkCommarea(), 160, 176));
            target.getCdemoCb00Info().setCdemoCb00TrnidLast(
                    StringUtils.substring(source.getLkCommarea(), 176, 192));
            target.getCdemoCb00Info().setCdemoCb00PageNum(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 192, 200), 8)));
            target.getCdemoCb00Info().setCdemoCb00NextPageFlg(
                    StringUtils.substring(source.getLkCommarea(), 200, 201));
            target.getCdemoCb00Info().setCdemoCb00TrnSelFlg(
                    StringUtils.substring(source.getLkCommarea(), 201, 202));
            target.getCdemoCb00Info().setCdemoCb00TrnSelected(
                    StringUtils.substring(source.getLkCommarea(), 202, 218));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link CardXrefRecord}</li>
     * <li>target class: {@link AwsM2CarddemoCardxrefVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @org.mapstruct.Builder(disableBuilder = true))
    public interface CardXrefRecordToAwsM2CarddemoCardxrefVsamKsdsDto {
        CardXrefRecordToAwsM2CarddemoCardxrefVsamKsdsDto INSTANCE = Mappers
                .getMapper(CardXrefRecordToAwsM2CarddemoCardxrefVsamKsdsDto.class);

        @Mapping(source = "xrefCardNum", target = "xrefCardNum")
        @Mapping(source = "xrefCustId", target = "xrefCustId")
        @Mapping(source = "xrefAcctId", target = "xrefAcctId")
        @Mapping(source = "FILLER_1", target = "filler")
        AwsM2CarddemoCardxrefVsamKsdsDto toTarget(CardXrefRecord source);

        @Mapping(source = "xrefCardNum", target = "xrefCardNum")
        @Mapping(source = "xrefCustId", target = "xrefCustId")
        @Mapping(source = "xrefAcctId", target = "xrefAcctId")
        @Mapping(source = "filler", target = "FILLER_1")
        CardXrefRecord toSource(AwsM2CarddemoCardxrefVsamKsdsDto source);
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link Cobil00cCarddemoCommarea}</li>
     * <li>target class: {@link Comen01cDfhcommarea}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @org.mapstruct.Builder(disableBuilder = true))
    public interface Cobil00cCarddemoCommareaToComen01cDfhcommarea {
        Cobil00cCarddemoCommareaToComen01cDfhcommarea INSTANCE = Mappers
                .getMapper(Cobil00cCarddemoCommareaToComen01cDfhcommarea.class);

        Comen01cDfhcommarea toTarget(Cobil00cCarddemoCommarea source);

        Cobil00cCarddemoCommarea toSource(Comen01cDfhcommarea source);

        @AfterMapping
        default void makeTarget(Cobil00cCarddemoCommarea source,
                @MappingTarget Comen01cDfhcommarea target) {
            target.setLkCommarea(source.getCdemoGeneralInfo()
                    .getCdemoFromTranid()
                    + source.getCdemoGeneralInfo().getCdemoFromProgram()
                    + source.getCdemoGeneralInfo().getCdemoToTranid()
                    + source.getCdemoGeneralInfo().getCdemoToProgram()
                    + source.getCdemoGeneralInfo().getCdemoUserId()
                    + source.getCdemoGeneralInfo().getCdemoUserType()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoGeneralInfo().getCdemoPgmContext(), 1)
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCustomerInfo().getCdemoCustId(), 9)
                    + source.getCdemoCustomerInfo().getCdemoCustFname()
                    + source.getCdemoCustomerInfo().getCdemoCustMname()
                    + source.getCdemoCustomerInfo().getCdemoCustLname()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoAccountInfo().getCdemoAcctId(), 11)
                    + source.getCdemoAccountInfo().getCdemoAcctStatus()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCardInfo().getCdemoCardNum(), 16)
                    + source.getCdemoMoreInfo().getCdemoLastMap()
                    + source.getCdemoMoreInfo().getCdemoLastMapset()
                    + source.getCdemoCb00Info().getCdemoCb00TrnidFirst()
                    + source.getCdemoCb00Info().getCdemoCb00TrnidLast()
                    + DataConverter.convZonedLongToString(source
                            .getCdemoCb00Info().getCdemoCb00PageNum(), 8)
                    + source.getCdemoCb00Info().getCdemoCb00NextPageFlg()
                    + source.getCdemoCb00Info().getCdemoCb00TrnSelFlg()
                    + source.getCdemoCb00Info().getCdemoCb00TrnSelected());
        }

        @AfterMapping
        default void makeSource(Comen01cDfhcommarea source,
                @MappingTarget Cobil00cCarddemoCommarea target) {
            target.getCdemoGeneralInfo().setCdemoFromTranid(
                    StringUtils.substring(source.getLkCommarea(), 0, 4));
            target.getCdemoGeneralInfo().setCdemoFromProgram(
                    StringUtils.substring(source.getLkCommarea(), 4, 12));
            target.getCdemoGeneralInfo().setCdemoToTranid(
                    StringUtils.substring(source.getLkCommarea(), 12, 16));
            target.getCdemoGeneralInfo().setCdemoToProgram(
                    StringUtils.substring(source.getLkCommarea(), 16, 24));
            target.getCdemoGeneralInfo().setCdemoUserId(
                    StringUtils.substring(source.getLkCommarea(), 24, 32));
            target.getCdemoGeneralInfo().setCdemoUserType(
                    StringUtils.substring(source.getLkCommarea(), 32, 33));
            target.getCdemoGeneralInfo().setCdemoPgmContext(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 33, 34), 1)));
            target.getCdemoCustomerInfo().setCdemoCustId(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 34, 43), 9)));
            target.getCdemoCustomerInfo().setCdemoCustFname(
                    StringUtils.substring(source.getLkCommarea(), 43, 68));
            target.getCdemoCustomerInfo().setCdemoCustMname(
                    StringUtils.substring(source.getLkCommarea(), 68, 93));
            target.getCdemoCustomerInfo().setCdemoCustLname(
                    StringUtils.substring(source.getLkCommarea(), 93, 118));
            try {
                target.getCdemoAccountInfo().setCdemoAcctId(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 118, 129),
                                11));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoAccountInfo().setCdemoAcctStatus(
                    StringUtils.substring(source.getLkCommarea(), 129, 130));
            try {
                target.getCdemoCardInfo().setCdemoCardNum(
                        DataConverter.convZonedStringToLong(StringUtils
                                .substring(source.getLkCommarea(), 130, 146),
                                16));
            } catch (Exception e) {
                e.printStackTrace();
            }
            target.getCdemoMoreInfo().setCdemoLastMap(
                    StringUtils.substring(source.getLkCommarea(), 146, 153));
            target.getCdemoMoreInfo().setCdemoLastMapset(
                    StringUtils.substring(source.getLkCommarea(), 153, 160));
            target.getCdemoCb00Info().setCdemoCb00TrnidFirst(
                    StringUtils.substring(source.getLkCommarea(), 160, 176));
            target.getCdemoCb00Info().setCdemoCb00TrnidLast(
                    StringUtils.substring(source.getLkCommarea(), 176, 192));
            target.getCdemoCb00Info().setCdemoCb00PageNum(
                    ((int) DataConverter.convZonedStringToLong(StringUtils
                            .substring(source.getLkCommarea(), 192, 200), 8)));
            target.getCdemoCb00Info().setCdemoCb00NextPageFlg(
                    StringUtils.substring(source.getLkCommarea(), 200, 201));
            target.getCdemoCb00Info().setCdemoCb00TrnSelFlg(
                    StringUtils.substring(source.getLkCommarea(), 201, 202));
            target.getCdemoCb00Info().setCdemoCb00TrnSelected(
                    StringUtils.substring(source.getLkCommarea(), 202, 218));
        }
    }

    /** 
     * <p>Mapper class to convert data for CICS processing</p>
     * <ul>
     * <li>source class: {@link TranRecord}</li>
     * <li>target class: {@link AwsM2CarddemoTransactVsamKsdsDto}</li>
     * </ul>
     */
    @Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @org.mapstruct.Builder(disableBuilder = true))
    public interface TranRecordToAwsM2CarddemoTransactVsamKsdsDto {
        TranRecordToAwsM2CarddemoTransactVsamKsdsDto INSTANCE = Mappers
                .getMapper(TranRecordToAwsM2CarddemoTransactVsamKsdsDto.class);

        @Mapping(source = "tranId", target = "tranId")
        @Mapping(source = "tranTypeCd", target = "tranTypeCd")
        @Mapping(source = "tranCatCd", target = "tranCatCd")
        @Mapping(source = "tranSource", target = "tranSource")
        @Mapping(source = "tranDesc", target = "tranDesc")
        @Mapping(source = "tranAmt", target = "tranAmt")
        @Mapping(source = "tranMerchantId", target = "tranMerchantId")
        @Mapping(source = "tranMerchantName", target = "tranMerchantName")
        @Mapping(source = "tranMerchantCity", target = "tranMerchantCity")
        @Mapping(source = "tranMerchantZip", target = "tranMerchantZip")
        @Mapping(source = "tranCardNum", target = "tranCardNum")
        @Mapping(source = "tranOrigTs", target = "tranOrigTs")
        @Mapping(source = "tranProcTs", target = "tranProcTs")
        @Mapping(source = "FILLER_1", target = "filler")
        AwsM2CarddemoTransactVsamKsdsDto toTarget(TranRecord source);

        @Mapping(source = "tranId", target = "tranId")
        @Mapping(source = "tranTypeCd", target = "tranTypeCd")
        @Mapping(source = "tranCatCd", target = "tranCatCd")
        @Mapping(source = "tranSource", target = "tranSource")
        @Mapping(source = "tranDesc", target = "tranDesc")
        @Mapping(source = "tranAmt", target = "tranAmt")
        @Mapping(source = "tranMerchantId", target = "tranMerchantId")
        @Mapping(source = "tranMerchantName", target = "tranMerchantName")
        @Mapping(source = "tranMerchantCity", target = "tranMerchantCity")
        @Mapping(source = "tranMerchantZip", target = "tranMerchantZip")
        @Mapping(source = "tranCardNum", target = "tranCardNum")
        @Mapping(source = "tranOrigTs", target = "tranOrigTs")
        @Mapping(source = "tranProcTs", target = "tranProcTs")
        @Mapping(source = "filler", target = "FILLER_1")
        TranRecord toSource(AwsM2CarddemoTransactVsamKsdsDto source);
    }
}
