package com.tmax.openframe;

import com.tmax.openframe.online.handle.service.AbendHandler;
import com.tmax.openframe.online.task.service.ProgramControl;
import com.tmax.openframe.dto.Comen01cInputDto;
import com.tmax.openframe.mapper.CoactvwcMapperInterface.*;
import com.tmax.openframe.online.task.service.OtherUserTaskInvoker;
import com.tmax.openframe.online.task.domain.dto.TaskDto.*;
import com.tmax.openframe.online.task.domain.dto.Data;
import com.tmax.openframe.online.task.service.Task;
import com.tmax.openframe.dto.CoactvwcOutputDto;
import com.tmax.openframe.online.exception.ConditionException;
import com.tmax.openframe.dto.CoactvwcInputDto;
import com.tmax.openframe.dto.AwsM2CarddemoCardxrefVsamKsdsDto;
import com.tmax.openframe.online.daoexecutor.service.ReadPointManager;
import com.tmax.openframe.online.daoexecutor.service.RecordKeyAccessor;
import com.tmax.openframe.dto.AwsM2CarddemoAcctdataVsamKsdsDto;
import com.tmax.openframe.dto.AwsM2CarddemoCustdataVsamKsdsDto;
import com.tmax.openframe.online.exception.OnlineException;
import com.tmax.openframe.online.exception.AbendException;
import static com.tmax.openframe.variable.group.CarddemoCommarea.CdemoGeneralInfo.*;
import static com.tmax.openframe.variable.group.CcWorkAreas.CcWorkArea.*;
import static com.tmax.openframe.variable.group.CoactvwcWsMiscStorage.*;
import static com.tmax.openframe.variable.group.CoactvwcWsMiscStorage.CoactvwcWsFileReadFlags.*;
import com.tmax.openframe.runtime.cobol.CobStream;
import com.tmax.openframe.runtime.cobol.CobStringUtils;
import com.tmax.openframe.runtime.cobol.IntrinsicFunction;
import com.tmax.openframe.runtime.cobol.PictureFormatter;
import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.flow.ControlManager;
import com.tmax.openframe.variable.CoactvwcVariableContainer;
import com.tmax.openframe.variable.group.Cactvwai;
import com.tmax.openframe.variable.group.CarddemoCommarea;
import com.tmax.openframe.variable.group.CcWorkAreas;
import com.tmax.openframe.variable.group.CoactvwcWsMiscStorage;
import com.tmax.openframe.variable.group.CoactvwcWsThisProgcommarea;
import java.math.*;
import java.util.*;
import java.util.function.Consumer;
import lombok.*;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:14 KST</p>
 * <hr>
 * <p>Java class for defining logics of COBOL program</p>
 * <ul>
 * <li>The name of COBOL program: COACTVWC.cbl</li>
 * <li>Variable container class: {@link CoactvwcVariableContainer}</li>
 * </ul>
 */
@Service
@RequiredArgsConstructor
@Transactional
@Primary
public class Coactvwc {
    /** 
     * <p>Class that manages an execution flow of the program</p>
     */
    protected final ControlManager controlManager;
    Consumer<OpenFrameContext> _0000Main = this::_0000Main;
    Consumer<OpenFrameContext> commonReturn = this::commonReturn;
    Consumer<OpenFrameContext> _0000MainExit = this::_0000MainExit;
    Consumer<OpenFrameContext> _1000SendMap = this::_1000SendMap;
    Consumer<OpenFrameContext> _1000SendMapExit = this::_1000SendMapExit;
    Consumer<OpenFrameContext> _1100ScreenInit = this::_1100ScreenInit;
    Consumer<OpenFrameContext> _1100ScreenInitExit = this::_1100ScreenInitExit;
    Consumer<OpenFrameContext> _1200SetupScreenVars = this::_1200SetupScreenVars;
    Consumer<OpenFrameContext> _1200SetupScreenVarsExit = this::_1200SetupScreenVarsExit;
    Consumer<OpenFrameContext> _1300SetupScreenAttrs = this::_1300SetupScreenAttrs;
    Consumer<OpenFrameContext> _1300SetupScreenAttrsExit = this::_1300SetupScreenAttrsExit;
    Consumer<OpenFrameContext> _1400SendScreen = this::_1400SendScreen;
    Consumer<OpenFrameContext> _1400SendScreenExit = this::_1400SendScreenExit;
    Consumer<OpenFrameContext> _2000ProcessInputs = this::_2000ProcessInputs;
    Consumer<OpenFrameContext> _2000ProcessInputsExit = this::_2000ProcessInputsExit;
    Consumer<OpenFrameContext> _2100ReceiveMap = this::_2100ReceiveMap;
    Consumer<OpenFrameContext> _2100ReceiveMapExit = this::_2100ReceiveMapExit;
    Consumer<OpenFrameContext> _2200EditMapInputs = this::_2200EditMapInputs;
    Consumer<OpenFrameContext> _2200EditMapInputsExit = this::_2200EditMapInputsExit;
    Consumer<OpenFrameContext> _2210EditAccount = this::_2210EditAccount;
    Consumer<OpenFrameContext> _2210EditAccountExit = this::_2210EditAccountExit;
    Consumer<OpenFrameContext> _9000ReadAcct = this::_9000ReadAcct;
    Consumer<OpenFrameContext> _9000ReadAcctExit = this::_9000ReadAcctExit;
    Consumer<OpenFrameContext> _9200GetcardxrefByacct = this::_9200GetcardxrefByacct;
    Consumer<OpenFrameContext> _9200GetcardxrefByacctExit = this::_9200GetcardxrefByacctExit;
    Consumer<OpenFrameContext> _9300GetacctdataByacct = this::_9300GetacctdataByacct;
    Consumer<OpenFrameContext> _9300GetacctdataByacctExit = this::_9300GetacctdataByacctExit;
    Consumer<OpenFrameContext> _9400GetcustdataBycust = this::_9400GetcustdataBycust;
    Consumer<OpenFrameContext> _9400GetcustdataBycustExit = this::_9400GetcustdataBycustExit;
    Consumer<OpenFrameContext> sendPlainText = this::sendPlainText;
    Consumer<OpenFrameContext> sendPlainTextExit = this::sendPlainTextExit;
    Consumer<OpenFrameContext> sendLongText = this::sendLongText;
    Consumer<OpenFrameContext> sendLongTextExit = this::sendLongTextExit;
    Consumer<OpenFrameContext> yyyyStorePfkey = this::yyyyStorePfkey;
    Consumer<OpenFrameContext> yyyyStorePfkeyExit = this::yyyyStorePfkeyExit;
    Consumer<OpenFrameContext> abendRoutine = this::abendRoutine;
    /** 
     * <p>Execution flow of COBOL program that defined in the procedure division</p>
     */
    ArrayList<Consumer> methodList = new ArrayList<>();
    {
        methodList.add(_0000Main);
        methodList.add(commonReturn);
        methodList.add(_0000MainExit);
        methodList.add(_1000SendMap);
        methodList.add(_1000SendMapExit);
        methodList.add(_1100ScreenInit);
        methodList.add(_1100ScreenInitExit);
        methodList.add(_1200SetupScreenVars);
        methodList.add(_1200SetupScreenVarsExit);
        methodList.add(_1300SetupScreenAttrs);
        methodList.add(_1300SetupScreenAttrsExit);
        methodList.add(_1400SendScreen);
        methodList.add(_1400SendScreenExit);
        methodList.add(_2000ProcessInputs);
        methodList.add(_2000ProcessInputsExit);
        methodList.add(_2100ReceiveMap);
        methodList.add(_2100ReceiveMapExit);
        methodList.add(_2200EditMapInputs);
        methodList.add(_2200EditMapInputsExit);
        methodList.add(_2210EditAccount);
        methodList.add(_2210EditAccountExit);
        methodList.add(_9000ReadAcct);
        methodList.add(_9000ReadAcctExit);
        methodList.add(_9200GetcardxrefByacct);
        methodList.add(_9200GetcardxrefByacctExit);
        methodList.add(_9300GetacctdataByacct);
        methodList.add(_9300GetacctdataByacctExit);
        methodList.add(_9400GetcustdataBycust);
        methodList.add(_9400GetcustdataBycustExit);
        methodList.add(sendPlainText);
        methodList.add(sendPlainTextExit);
        methodList.add(sendLongText);
        methodList.add(sendLongTextExit);
        methodList.add(yyyyStorePfkey);
        methodList.add(yyyyStorePfkeyExit);
        methodList.add(abendRoutine);
    }
    private final ReadPointManager readPointManager;
    private final RecordKeyAccessor recordKeyAccessor;
    private final Task task;
    private final TaskInvoker taskInvoker;
    private final ProgramControl programControl;
    private final AbendHandler abendHandler;

    /** 
     * <p>Method for executing a program logic that defined in the procedure division</p>
     * @param generalContext context that is necessary for executing program
     * @return return value of program
     */
    public int run(Map<String, Object> generalContext) {
        OpenFrameContext context = new OpenFrameContext(generalContext,
                methodList);
        if (context.getProgramVariableContainer("Coactvwc") == null) {
            CoactvwcVariableContainer container = new CoactvwcVariableContainer();
            context.setProgramVariableContainer("Coactvwc", container);
        }
        controlManager.run(context);
        return context.getReturnValue();
    }

    // *****************************************************************
    // * Program:     COACTVWC.CBL                                     *
    // * Layer:       Business logic                                   *
    // * Function:    Accept and process Account View request          *
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // *      OCCURS 1 TO 32767 TIMES DEPENDING ON EIBCALEN.

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:261] 0000-MAIN Paragraph</p>
     */
    void _0000Main(OpenFrameContext context) {
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // [T-Up#INFO][COACTVWC.cbl:263] EXEC_CICS statement
        /*
                       EXEC CICS HANDLE ABEND
                                 LABEL(ABEND-ROUTINE)
                       END-EXEC
         */
        abendHandler.setLabel(abendRoutine);
        // [T-Up#INFO][COACTVWC.cbl:267] INITIALIZE statement
        container.getCcWorkAreas().setCcWorkArea(
                CcWorkAreas.CcWorkArea.createDefaultValueInstance());
        container.setWsMiscStorage(CoactvwcWsMiscStorage
                .createDefaultValueInstance());
        container.setWsCommarea(StringUtils.repeat(' ', 2000));
        // *****************************************************************
        // * Store our context
        // *****************************************************************
        // [T-Up#INFO][COACTVWC.cbl:273] MOVE statement
        container.getWsMiscStorage().getWsCicsProcessngVars()
                .setWsTranid(container.getWsLiterals().getLitThistranid());
        // *****************************************************************
        // * Ensure error message is cleared                               *
        // *****************************************************************
        // [T-Up#INFO][COACTVWC.cbl:277] SET statement
        container.getWsMiscStorage().setWsReturnMsg(WS_RETURN_MSG_OFF);
        // *****************************************************************
        // * Store passed data if  any                *
        // *****************************************************************
        // [T-Up#INFO][COACTVWC.cbl:281] IF statement
        if (task.hasCommarea() == 0
                || CobStringUtils.compare(container.getCarddemoCommarea()
                        .getCdemoGeneralInfo().getCdemoFromProgram(), container
                        .getWsLiterals().getLitMenupgm()) == 0
                && !(container.getCarddemoCommarea().getCdemoGeneralInfo()
                        .getCdemoPgmContext() == CDEMO_PGM_REENTER)) {
            // [T-Up#INFO][COACTVWC.cbl:284] INITIALIZE statement
            container.setCarddemoCommarea(CarddemoCommarea
                    .createDefaultValueInstance());
            container.setWsThisProgcommarea(CoactvwcWsThisProgcommarea
                    .createDefaultValueInstance());
        } else {
            // [T-Up#INFO][COACTVWC.cbl:287] MOVE statement
            container.getCarddemoCommarea().set(
                    container.getDfhcommarea().get().substring(0, 160));
            // [T-Up#INFO][COACTVWC.cbl:289] MOVE statement
            container.getWsThisProgcommarea().set(
                    container.getDfhcommarea().get().substring(160, 172));
        }
        // *****************************************************************
        // * Remap PFkeys as needed.
        // * Store the Mapped PF Key
        // *****************************************************************
        // [T-Up#INFO][COACTVWC.cbl:298] PERFORM statement
        controlManager.run(context, yyyyStorePfkey, yyyyStorePfkeyExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // *****************************************************************
        // * Check the AID to see if its valid at this point               *
        // * F3 - Exit
        // * Enter show screen again
        // *****************************************************************
        // [T-Up#INFO][COACTVWC.cbl:305] SET statement
        container.getWsMiscStorage().setWsPfkFlag(PFK_INVALID);
        // [T-Up#INFO][COACTVWC.cbl:306] IF statement
        if (CobStringUtils.compare(container.getCcWorkAreas().getCcWorkArea()
                .getCcardAid(), CCARD_AID_ENTER) == 0
                || CobStringUtils.compare(container.getCcWorkAreas()
                        .getCcWorkArea().getCcardAid(), CCARD_AID_PFK03) == 0) {
            // [T-Up#INFO][COACTVWC.cbl:308] SET statement
            container.getWsMiscStorage().setWsPfkFlag(PFK_VALID);
        }
        // [T-Up#INFO][COACTVWC.cbl:311] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage().getWsPfkFlag(),
                PFK_INVALID) == 0) {
            // [T-Up#INFO][COACTVWC.cbl:312] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_ENTER);
        }
        // *****************************************************************
        // * Decide what to do based on inputs received
        // *****************************************************************
        // *****************************************************************
        // *****************************************************************
        // * Decide what to do based on inputs received
        // *****************************************************************
        // [T-Up#INFO][COACTVWC.cbl:322] EVALUATE statement
        if (CobStringUtils.compare(container.getCcWorkAreas().getCcWorkArea()
                .getCcardAid(), CCARD_AID_PFK03) == 0) {
            // ******************************************************************
            // *            XCTL TO CALLING PROGRAM OR MAIN MENU
            // ******************************************************************
            // [T-Up#INFO][COACTVWC.cbl:327] IF statement
            if (CobStringUtils.compare(container.getCarddemoCommarea()
                    .getCdemoGeneralInfo().getCdemoFromTranid(),
                    StringUtils.repeat((char) 0x00, 4)) == 0
                    || CobStringUtils.compare(container.getCarddemoCommarea()
                            .getCdemoGeneralInfo().getCdemoFromTranid(),
                            StringUtils.repeat(' ', 4)) == 0) {
                // [T-Up#INFO][COACTVWC.cbl:329] MOVE statement
                container
                        .getCarddemoCommarea()
                        .getCdemoGeneralInfo()
                        .setCdemoToTranid(
                                container.getWsLiterals().getLitMenutranid());
            } else {
                // [T-Up#INFO][COACTVWC.cbl:331] MOVE statement
                container
                        .getCarddemoCommarea()
                        .getCdemoGeneralInfo()
                        .setCdemoToTranid(
                                container.getCarddemoCommarea()
                                        .getCdemoGeneralInfo()
                                        .getCdemoFromTranid());
            }
            // [T-Up#INFO][COACTVWC.cbl:333] IF statement
            if (CobStringUtils.compare(container.getCarddemoCommarea()
                    .getCdemoGeneralInfo().getCdemoFromProgram(),
                    StringUtils.repeat((char) 0x00, 8)) == 0
                    || CobStringUtils.compare(container.getCarddemoCommarea()
                            .getCdemoGeneralInfo().getCdemoFromProgram(),
                            StringUtils.repeat(' ', 8)) == 0) {
                // [T-Up#INFO][COACTVWC.cbl:335] MOVE statement
                container
                        .getCarddemoCommarea()
                        .getCdemoGeneralInfo()
                        .setCdemoToProgram(
                                container.getWsLiterals().getLitMenupgm());
            } else {
                // [T-Up#INFO][COACTVWC.cbl:337] MOVE statement
                container
                        .getCarddemoCommarea()
                        .getCdemoGeneralInfo()
                        .setCdemoToProgram(
                                container.getCarddemoCommarea()
                                        .getCdemoGeneralInfo()
                                        .getCdemoFromProgram());
            }
            // [T-Up#INFO][COACTVWC.cbl:340] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoGeneralInfo()
                    .setCdemoFromTranid(
                            container.getWsLiterals().getLitThistranid());
            // [T-Up#INFO][COACTVWC.cbl:341] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoGeneralInfo()
                    .setCdemoFromProgram(
                            container.getWsLiterals().getLitThispgm());
            // [T-Up#INFO][COACTVWC.cbl:343] SET statement
            container.getCarddemoCommarea().getCdemoGeneralInfo()
                    .setCdemoUserType(CDEMO_USRTYP_USER);
            // [T-Up#INFO][COACTVWC.cbl:344] SET statement
            container.getCarddemoCommarea().getCdemoGeneralInfo()
                    .setCdemoPgmContext(CDEMO_PGM_ENTER);
            // [T-Up#INFO][COACTVWC.cbl:345] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoMoreInfo()
                    .setCdemoLastMapset(
                            container.getWsLiterals().getLitThismapset());
            // [T-Up#INFO][COACTVWC.cbl:346] MOVE statement
            container.getCarddemoCommarea().getCdemoMoreInfo()
                    .setCdemoLastMap(container.getWsLiterals().getLitThismap());
            // [T-Up#INFO][COACTVWC.cbl:348] EXEC_CICS statement
            /*
                                   EXEC CICS XCTL
                                             PROGRAM ('COMEN01C')
                                             COMMAREA(CARDDEMO-COMMAREA)
                                   END-EXEC
             */
            Comen01cInputDto comen01cInputDto = new Comen01cInputDto();
            comen01cInputDto
                    .setDfhcommarea(CarddemoCommareaToComen01cDfhcommarea.INSTANCE
                            .toTarget(container.getCarddemoCommarea()));
            programControl.forward("CM00", comen01cInputDto);
            context.setReturnFlag(true);
        } else if (container.getCarddemoCommarea().getCdemoGeneralInfo()
                .getCdemoPgmContext() == CDEMO_PGM_ENTER) {
            // ******************************************************************
            // *            COMING FROM SOME OTHER CONTEXT
            // *            SELECTION CRITERIA TO BE GATHERED
            // ******************************************************************
            // [T-Up#INFO][COACTVWC.cbl:357] PERFORM statement
            controlManager.run(context, _1000SendMap, _1000SendMapExit);
            if (controlManager.isTerminate(context)) {
                return;
            }
            // [T-Up#INFO][COACTVWC.cbl:359] GO TO statement
            context.setGotoTarget(commonReturn);
            return;
        } else if (container.getCarddemoCommarea().getCdemoGeneralInfo()
                .getCdemoPgmContext() == CDEMO_PGM_REENTER) {
            // [T-Up#INFO][COACTVWC.cbl:361] PERFORM statement
            controlManager.run(context, _2000ProcessInputs,
                    _2000ProcessInputsExit);
            if (controlManager.isTerminate(context)) {
                return;
            }
            // [T-Up#INFO][COACTVWC.cbl:363] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsInputFlag(), INPUT_ERROR) == 0) {
                // [T-Up#INFO][COACTVWC.cbl:364] PERFORM statement
                controlManager.run(context, _1000SendMap, _1000SendMapExit);
                if (controlManager.isTerminate(context)) {
                    return;
                }
                // [T-Up#INFO][COACTVWC.cbl:366] GO TO statement
                context.setGotoTarget(commonReturn);
                return;
            } else {
                // [T-Up#INFO][COACTVWC.cbl:368] PERFORM statement
                controlManager.run(context, _9000ReadAcct, _9000ReadAcctExit);
                if (controlManager.isTerminate(context)) {
                    return;
                }
                // [T-Up#INFO][COACTVWC.cbl:370] PERFORM statement
                controlManager.run(context, _1000SendMap, _1000SendMapExit);
                if (controlManager.isTerminate(context)) {
                    return;
                }
                // [T-Up#INFO][COACTVWC.cbl:372] GO TO statement
                context.setGotoTarget(commonReturn);
                return;
            }
        } else {
            // [T-Up#INFO][COACTVWC.cbl:375] MOVE statement
            container.getAbendData().setAbendCulprit(
                    container.getWsLiterals().getLitThispgm());
            // [T-Up#INFO][COACTVWC.cbl:376] MOVE statement
            container.getAbendData().setAbendCode("0001");
            // [T-Up#INFO][COACTVWC.cbl:377] MOVE statement
            container.getAbendData()
                    .setAbendReason(StringUtils.repeat(' ', 50));
            // [T-Up#INFO][COACTVWC.cbl:378] MOVE statement
            container.getWsMiscStorage().setWsReturnMsg(
                    "UNEXPECTED DATA SCENARIO");
            // [T-Up#INFO][COACTVWC.cbl:380] PERFORM statement
            controlManager.run(context, sendPlainText, sendPlainTextExit);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
        // * If we had an error setup error message that slipped through
        // * Display and return
        // [T-Up#INFO][COACTVWC.cbl:386] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage()
                .getWsInputFlag(), INPUT_ERROR) == 0) {
            // [T-Up#INFO][COACTVWC.cbl:387] MOVE statement
            container
                    .getCcWorkAreas()
                    .getCcWorkArea()
                    .setCcardErrorMsg(
                            container.getWsMiscStorage().getWsReturnMsg());
            // [T-Up#INFO][COACTVWC.cbl:388] PERFORM statement
            controlManager.run(context, _1000SendMap, _1000SendMapExit);
            if (controlManager.isTerminate(context)) {
                return;
            }
            // [T-Up#INFO][COACTVWC.cbl:390] GO TO statement
            context.setGotoTarget(commonReturn);
            return;
        }
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:393] COMMON-RETURN Paragraph</p>
     */
    void commonReturn(OpenFrameContext context) {
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // [T-Up#INFO][COACTVWC.cbl:394] MOVE statement
        container
                .getCcWorkAreas()
                .getCcWorkArea()
                .setCcardErrorMsg(container.getWsMiscStorage().getWsReturnMsg());
        // [T-Up#INFO][COACTVWC.cbl:396] MOVE statement
        container.setWsCommarea(container.getCarddemoCommarea().get());
        // [T-Up#INFO][COACTVWC.cbl:397] MOVE statement
        container.setWsCommarea(StringUtils.overlay(container.getWsCommarea(),
                container.getWsThisProgcommarea().get(), 160, 172));
        // [T-Up#INFO][COACTVWC.cbl:401] EXEC_CICS statement
        /*
                       EXEC CICS RETURN
                            TRANSID (LIT-THISTRANID)
                            COMMAREA (WS-COMMAREA)
                            LENGTH(LENGTH OF WS-COMMAREA)
                       END-EXEC
         */
        TaskDto taskDto = TaskDto.builder()
                .destination(container.getWsLiterals().getLitThistranid())
                .data(Data.session(container.getWsCommarea())).build();
        taskInvoker.setNextTask(taskDto);
        context.setReturnFlag(true);
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:407] 0000-MAIN-EXIT Paragraph</p>
     */
    void _0000MainExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:408] EXIT statement
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:412] 1000-SEND-MAP Paragraph</p>
     */
    void _1000SendMap(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:413] PERFORM statement
        controlManager.run(context, _1100ScreenInit, _1100ScreenInitExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COACTVWC.cbl:415] PERFORM statement
        controlManager.run(context, _1200SetupScreenVars,
                _1200SetupScreenVarsExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COACTVWC.cbl:417] PERFORM statement
        controlManager.run(context, _1300SetupScreenAttrs,
                _1300SetupScreenAttrsExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COACTVWC.cbl:419] PERFORM statement
        controlManager.run(context, _1400SendScreen, _1400SendScreenExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:423] 1000-SEND-MAP-EXIT Paragraph</p>
     */
    void _1000SendMapExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:424] EXIT statement
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:427] 1100-SCREEN-INIT Paragraph</p>
     */
    void _1100ScreenInit(OpenFrameContext context) {
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // [T-Up#INFO][COACTVWC.cbl:428] MOVE statement
        container.setCactvwao(Cactvwai.createDefaultValueInstance().get());
        // [T-Up#INFO][COACTVWC.cbl:430] MOVE statement
        container.getWsDateTime().getWsCurdateData()
                .set(IntrinsicFunction.functionCurrentDate());
        // [T-Up#INFO][COACTVWC.cbl:432] MOVE statement
        container.setTitle01o(container.getCcdaScreenTitle().getCcdaTitle01());
        // [T-Up#INFO][COACTVWC.cbl:433] MOVE statement
        container.setTitle02o(container.getCcdaScreenTitle().getCcdaTitle02());
        // [T-Up#INFO][COACTVWC.cbl:434] MOVE statement
        container.setTrnnameo(container.getWsLiterals().getLitThistranid());
        // [T-Up#INFO][COACTVWC.cbl:435] MOVE statement
        container.setPgmnameo(container.getWsLiterals().getLitThispgm());
        // [T-Up#INFO][COACTVWC.cbl:437] MOVE statement
        container.getWsDateTime().getWsCurdateData()
                .set(IntrinsicFunction.functionCurrentDate());
        // [T-Up#INFO][COACTVWC.cbl:439] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateMm(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurdate().getWsCurdateMonth());
        // [T-Up#INFO][COACTVWC.cbl:440] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateDd(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurdate().getWsCurdateDay());
        // [T-Up#INFO][COACTVWC.cbl:441] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateYy(
                        Integer.parseInt(CobStream
                                .convZonedIntToString(
                                        container.getWsDateTime()
                                                .getWsCurdateData()
                                                .getWsCurdate()
                                                .getWsCurdateYear(), 4)
                                .substring(2, 4).trim()));
        // [T-Up#INFO][COACTVWC.cbl:443] MOVE statement
        container.setCurdateo(container.getWsDateTime().getWsCurdateMmDdYy()
                .get());
        // [T-Up#INFO][COACTVWC.cbl:445] MOVE statement
        container
                .getWsDateTime()
                .getWsCurtimeHhMmSs()
                .setWsCurtimeHh(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurtime().getWsCurtimeHours());
        // [T-Up#INFO][COACTVWC.cbl:446] MOVE statement
        container
                .getWsDateTime()
                .getWsCurtimeHhMmSs()
                .setWsCurtimeMm(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurtime().getWsCurtimeMinute());
        // [T-Up#INFO][COACTVWC.cbl:447] MOVE statement
        container
                .getWsDateTime()
                .getWsCurtimeHhMmSs()
                .setWsCurtimeSs(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurtime().getWsCurtimeSecond());
        // [T-Up#INFO][COACTVWC.cbl:449] MOVE statement
        container.setCurtimeo(container.getWsDateTime().getWsCurtimeHhMmSs()
                .get());
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:453] 1100-SCREEN-INIT-EXIT Paragraph</p>
     */
    void _1100ScreenInitExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:454] EXIT statement
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:456] 1200-SETUP-SCREEN-VARS Paragraph</p>
     */
    void _1200SetupScreenVars(OpenFrameContext context) {
        StringBuilder tempStringBuilder1;
        StringBuilder tempStringBuilder2;
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // *    INITIALIZE SEARCH CRITERIA
        // [T-Up#INFO][COACTVWC.cbl:458] IF statement
        if (task.hasCommarea() == 0) {
            // [T-Up#INFO][COACTVWC.cbl:459] SET statement
            container.getWsMiscStorage().setWsInfoMsg(WS_PROMPT_FOR_INPUT);
        } else {
            // [T-Up#INFO][COACTVWC.cbl:461] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsEditAcctFlag(), FLG_ACCTFILTER_BLANK) == 0) {
                // [T-Up#INFO][COACTVWC.cbl:462] MOVE statement
                container.setAcctsido(StringUtils.repeat((char) 0x00, 11));
            } else {
                // [T-Up#INFO][COACTVWC.cbl:464] MOVE statement
                container.setAcctsido(container.getCcWorkAreas()
                        .getCcWorkArea().getCcAcctId());
            }
            // [T-Up#INFO][COACTVWC.cbl:467] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsFileReadFlags().getWsAccountMasterReadFlag(),
                    FOUND_ACCT_IN_MASTER) == 0
                    || CobStringUtils.compare(container.getWsMiscStorage()
                            .getWsFileReadFlags().getWsCustMasterReadFlag(),
                            FOUND_CUST_IN_MASTER) == 0) {
                // [T-Up#INFO][COACTVWC.cbl:469] MOVE statement
                container.setAcsttuso(container.getAccountRecord()
                        .getAcctActiveStatus());
                // [T-Up#INFO][COACTVWC.cbl:471] MOVE statement
                container.setAcurbalo(container.getAccountRecord()
                        .getAcctCurrBal().toString());
                // [T-Up#INFO][COACTVWC.cbl:473] MOVE statement
                container.setAcrdlimo(container.getAccountRecord()
                        .getAcctCreditLimit().toString());
                // [T-Up#INFO][COACTVWC.cbl:475] MOVE statement
                container.setAcshlimo(container.getAccountRecord()
                        .getAcctCashCreditLimit().toString());
                // [T-Up#INFO][COACTVWC.cbl:478] MOVE statement
                container.setAcrcycro(container.getAccountRecord()
                        .getAcctCurrCycCredit().toString());
                // [T-Up#INFO][COACTVWC.cbl:481] MOVE statement
                container.setAcrcydbo(container.getAccountRecord()
                        .getAcctCurrCycDebit().toString());
                // [T-Up#INFO][COACTVWC.cbl:483] MOVE statement
                container.setAdtopeno(container.getAccountRecord()
                        .getAcctOpenDate());
                // [T-Up#INFO][COACTVWC.cbl:484] MOVE statement
                container.setAexpdto(container.getAccountRecord()
                        .getAcctExpiraionDate());
                // [T-Up#INFO][COACTVWC.cbl:485] MOVE statement
                container.setAreisdto(container.getAccountRecord()
                        .getAcctReissueDate());
                // [T-Up#INFO][COACTVWC.cbl:486] MOVE statement
                container.setAaddgrpo(container.getAccountRecord()
                        .getAcctGroupId());
            }
            // [T-Up#INFO][COACTVWC.cbl:489] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsFileReadFlags().getWsCustMasterReadFlag(),
                    FOUND_CUST_IN_MASTER) == 0) {
                // [T-Up#INFO][COACTVWC.cbl:490] MOVE statement
                container.setAcstnumo(StringUtils.leftPad(String.valueOf(Math
                        .abs(container.getCustomerRecord().getCustId())), 9,
                        '0'));
                // *         MOVE CUST-SSN             TO ACSTSSNO OF CACTVWAO
                // [T-Up#INFO][COACTVWC.cbl:492] STRING statement
                tempStringBuilder1 = new StringBuilder();
                tempStringBuilder2 = new StringBuilder(container.getAcstssno());
                tempStringBuilder1
                        .append(CobStream.convZonedIntToString(
                                container.getCustomerRecord().getCustSsn(), 9)
                                .substring(0, 3))
                        .append("-")
                        .append(CobStream.convZonedIntToString(
                                container.getCustomerRecord().getCustSsn(), 9)
                                .substring(3, 5))
                        .append("-")
                        .append(CobStream.convZonedIntToString(
                                container.getCustomerRecord().getCustSsn(), 9)
                                .substring(5, 9));
                if (tempStringBuilder1.length() <= 12) {
                    tempStringBuilder2.replace(0, tempStringBuilder1.length(),
                            tempStringBuilder1.toString());
                    container.setAcstssno(tempStringBuilder2.toString());
                }
                // [T-Up#INFO][COACTVWC.cbl:501] MOVE statement
                container.setAcstfcoo(StringUtils.leftPad(String.valueOf(Math
                        .abs(container.getCustomerRecord()
                                .getCustFicoCreditScore())), 3, '0'));
                // [T-Up#INFO][COACTVWC.cbl:503] MOVE statement
                container.setAcstdobo(container.getCustomerRecord()
                        .getCustDobYyyyMmDd());
                // [T-Up#INFO][COACTVWC.cbl:504] MOVE statement
                container.setAcsfnamo(container.getCustomerRecord()
                        .getCustFirstName());
                // [T-Up#INFO][COACTVWC.cbl:505] MOVE statement
                container.setAcsmnamo(container.getCustomerRecord()
                        .getCustMiddleName());
                // [T-Up#INFO][COACTVWC.cbl:506] MOVE statement
                container.setAcslnamo(container.getCustomerRecord()
                        .getCustLastName());
                // [T-Up#INFO][COACTVWC.cbl:507] MOVE statement
                container.setAcsadl1o(container.getCustomerRecord()
                        .getCustAddrLine1());
                // [T-Up#INFO][COACTVWC.cbl:508] MOVE statement
                container.setAcsadl2o(container.getCustomerRecord()
                        .getCustAddrLine2());
                // [T-Up#INFO][COACTVWC.cbl:509] MOVE statement
                container.setAcscityo(container.getCustomerRecord()
                        .getCustAddrLine3());
                // [T-Up#INFO][COACTVWC.cbl:510] MOVE statement
                container.setAcsstteo(container.getCustomerRecord()
                        .getCustAddrStateCd());
                // [T-Up#INFO][COACTVWC.cbl:511] MOVE statement
                container.setAcszipco(container.getCustomerRecord()
                        .getCustAddrZip());
                // [T-Up#INFO][COACTVWC.cbl:512] MOVE statement
                container.setAcsctryo(container.getCustomerRecord()
                        .getCustAddrCountryCd());
                // [T-Up#INFO][COACTVWC.cbl:513] MOVE statement
                container.setAcsphn1o(container.getCustomerRecord()
                        .getCustPhoneNum1());
                // [T-Up#INFO][COACTVWC.cbl:514] MOVE statement
                container.setAcsphn2o(container.getCustomerRecord()
                        .getCustPhoneNum2());
                // [T-Up#INFO][COACTVWC.cbl:515] MOVE statement
                container.setAcsgovto(container.getCustomerRecord()
                        .getCustGovtIssuedId());
                // [T-Up#INFO][COACTVWC.cbl:516] MOVE statement
                container.setAcseftco(container.getCustomerRecord()
                        .getCustEftAccountId());
                // [T-Up#INFO][COACTVWC.cbl:517] MOVE statement
                container.setAcspflgo(container.getCustomerRecord()
                        .getCustPriCardHolderInd());
            }
        }
        // *    SETUP MESSAGE
        // [T-Up#INFO][COACTVWC.cbl:524] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage().getWsInfoMsg(),
                WS_NO_INFO_MESSAGE_1) == 0
                || CobStringUtils.compare(container.getWsMiscStorage()
                        .getWsInfoMsg(), WS_NO_INFO_MESSAGE_2) == 0) {
            // [T-Up#INFO][COACTVWC.cbl:525] SET statement
            container.getWsMiscStorage().setWsInfoMsg(WS_PROMPT_FOR_INPUT);
        }
        // [T-Up#INFO][COACTVWC.cbl:528] MOVE statement
        container.setErrmsgo(container.getWsMiscStorage().getWsReturnMsg());
        // [T-Up#INFO][COACTVWC.cbl:530] MOVE statement
        container.setInfomsgo(container.getWsMiscStorage().getWsInfoMsg());
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:533] 1200-SETUP-SCREEN-VARS-EXIT Paragraph</p>
     */
    void _1200SetupScreenVarsExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:534] EXIT statement
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:537] 1300-SETUP-SCREEN-ATTRS Paragraph</p>
     */
    void _1300SetupScreenAttrs(OpenFrameContext context) {
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // *    PROTECT OR UNPROTECT BASED ON CONTEXT
        // [T-Up#INFO][COACTVWC.cbl:539] MOVE statement
        container.getCactvwai().setAcctsida(
                container.getDfhbmsca().getDfhbmfse());
        // *    POSITION CURSOR
        // [T-Up#INFO][COACTVWC.cbl:542] EVALUATE statement
        if ((CobStringUtils.compare(container.getWsMiscStorage()
                .getWsEditAcctFlag(), FLG_ACCTFILTER_NOT_OK) == 0)
                || (CobStringUtils.compare(container.getWsMiscStorage()
                        .getWsEditAcctFlag(), FLG_ACCTFILTER_BLANK) == 0)) {
            // [T-Up#INFO][COACTVWC.cbl:545] MOVE statement
            container.getCactvwai().setAcctsidl(-1);
        } else {
            // [T-Up#INFO][COACTVWC.cbl:547] MOVE statement
            container.getCactvwai().setAcctsidl(-1);
        }
        // *    SETUP COLOR
        // [T-Up#INFO][COACTVWC.cbl:551] MOVE statement
        container.setAcctsidc(container.getDfhbmsca().getDfhdfcol());
        // [T-Up#INFO][COACTVWC.cbl:553] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage()
                .getWsEditAcctFlag(), FLG_ACCTFILTER_NOT_OK) == 0) {
            // [T-Up#INFO][COACTVWC.cbl:554] MOVE statement
            container.setAcctsidc(container.getDfhbmsca().getDfhred());
        }
        // [T-Up#INFO][COACTVWC.cbl:557] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage()
                .getWsEditAcctFlag(), FLG_ACCTFILTER_BLANK) == 0
                && container.getCarddemoCommarea().getCdemoGeneralInfo()
                        .getCdemoPgmContext() == CDEMO_PGM_REENTER) {
            // [T-Up#INFO][COACTVWC.cbl:559] MOVE statement
            container.setAcctsido("*");
            // [T-Up#INFO][COACTVWC.cbl:560] MOVE statement
            container.setAcctsidc(container.getDfhbmsca().getDfhred());
        }
        // [T-Up#INFO][COACTVWC.cbl:563] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage().getWsInfoMsg(),
                WS_NO_INFO_MESSAGE_1) == 0
                || CobStringUtils.compare(container.getWsMiscStorage()
                        .getWsInfoMsg(), WS_NO_INFO_MESSAGE_2) == 0) {
            // [T-Up#INFO][COACTVWC.cbl:564] MOVE statement
            container.setInfomsgc(container.getDfhbmsca().getDfhbmdar());
        } else {
            // [T-Up#INFO][COACTVWC.cbl:566] MOVE statement
            container.setInfomsgc(container.getDfhbmsca().getDfhneutr());
        }
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:570] 1300-SETUP-SCREEN-ATTRS-EXIT Paragraph</p>
     */
    void _1300SetupScreenAttrsExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:571] EXIT statement
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:573] 1400-SEND-SCREEN Paragraph</p>
     */
    void _1400SendScreen(OpenFrameContext context) {
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // [T-Up#INFO][COACTVWC.cbl:575] MOVE statement
        container
                .getCcWorkAreas()
                .getCcWorkArea()
                .setCcardNextMapset(
                        container.getWsLiterals().getLitThismapset());
        // [T-Up#INFO][COACTVWC.cbl:576] MOVE statement
        container.getCcWorkAreas().getCcWorkArea()
                .setCcardNextMap(container.getWsLiterals().getLitThismap());
        // [T-Up#INFO][COACTVWC.cbl:577] SET statement
        container.getCarddemoCommarea().getCdemoGeneralInfo()
                .setCdemoPgmContext(CDEMO_PGM_REENTER);
        // [T-Up#INFO][COACTVWC.cbl:579] EXEC_CICS statement
        /*
                       EXEC CICS SEND MAP('CACTVWA')
                                      MAPSET('COACTVW')
                                      FROM(CACTVWAO)
                                      CURSOR
                                      ERASE
                                      FREEKB
                                      RESP(WS-RESP-CD)
                       END-EXEC
         */
        try {
            ((CoactvwcOutputDto) task.getOutputDto())
                    .setPageName("COACTVW_CACTVWA");
            ((CoactvwcOutputDto) task.getOutputDto()).setCactvwao(container
                    .getCactvwao());
        } catch (ConditionException e) {
        } finally {
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsRespCd(task.getLastResp());
        }
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:588] 1400-SEND-SCREEN-EXIT Paragraph</p>
     */
    void _1400SendScreenExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:589] EXIT statement
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:592] 2000-PROCESS-INPUTS Paragraph</p>
     */
    void _2000ProcessInputs(OpenFrameContext context) {
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // [T-Up#INFO][COACTVWC.cbl:593] PERFORM statement
        controlManager.run(context, _2100ReceiveMap, _2100ReceiveMapExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COACTVWC.cbl:595] PERFORM statement
        controlManager.run(context, _2200EditMapInputs, _2200EditMapInputsExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COACTVWC.cbl:597] MOVE statement
        container
                .getCcWorkAreas()
                .getCcWorkArea()
                .setCcardErrorMsg(container.getWsMiscStorage().getWsReturnMsg());
        // [T-Up#INFO][COACTVWC.cbl:598] MOVE statement
        container.getCcWorkAreas().getCcWorkArea()
                .setCcardNextProg(container.getWsLiterals().getLitThispgm());
        // [T-Up#INFO][COACTVWC.cbl:599] MOVE statement
        container
                .getCcWorkAreas()
                .getCcWorkArea()
                .setCcardNextMapset(
                        container.getWsLiterals().getLitThismapset());
        // [T-Up#INFO][COACTVWC.cbl:600] MOVE statement
        container.getCcWorkAreas().getCcWorkArea()
                .setCcardNextMap(container.getWsLiterals().getLitThismap());
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:603] 2000-PROCESS-INPUTS-EXIT Paragraph</p>
     */
    void _2000ProcessInputsExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:604] EXIT statement
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:606] 2100-RECEIVE-MAP Paragraph</p>
     */
    void _2100ReceiveMap(OpenFrameContext context) {
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // [T-Up#INFO][COACTVWC.cbl:607] EXEC_CICS statement
        /*
                       EXEC CICS RECEIVE MAP('CACTVWA')
                                 MAPSET('COACTVW')
                                 INTO(CACTVWAI)
                                 RESP(WS-RESP-CD)
                                 RESP2(WS-REAS-CD)
                       END-EXEC
         */
        try {
            container.setCactvwai(((CoactvwcInputDto) task.getInputDto())
                    .getCactvwai());
        } catch (ConditionException e) {
        } finally {
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsRespCd(task.getLastResp());
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsReasCd(task.getLastResp2());
        }
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:615] 2100-RECEIVE-MAP-EXIT Paragraph</p>
     */
    void _2100ReceiveMapExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:616] EXIT statement
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:618] 2200-EDIT-MAP-INPUTS Paragraph</p>
     */
    void _2200EditMapInputs(OpenFrameContext context) {
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // [T-Up#INFO][COACTVWC.cbl:620] SET statement
        container.getWsMiscStorage().setWsInputFlag(INPUT_OK);
        // [T-Up#INFO][COACTVWC.cbl:621] SET statement
        container.getWsMiscStorage().setWsEditAcctFlag(FLG_ACCTFILTER_ISVALID);
        // *    REPLACE * WITH LOW-VALUES
        // [T-Up#INFO][COACTVWC.cbl:624] IF statement
        if (CobStringUtils.compare(PictureFormatter.intFormatWithoutSign(
                container.getCactvwai().getAcctsidi(), "00000000000"), "*") == 0
                || CobStringUtils.compare(PictureFormatter
                        .intFormatWithoutSign(container.getCactvwai()
                                .getAcctsidi(), "00000000000"), StringUtils
                        .repeat(' ', 11)) == 0) {
            // [T-Up#INFO][COACTVWC.cbl:626] MOVE statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcAcctId(StringUtils.repeat((char) 0x00, 11));
        } else {
            // [T-Up#INFO][COACTVWC.cbl:628] MOVE statement
            container
                    .getCcWorkAreas()
                    .getCcWorkArea()
                    .setCcAcctId(
                            StringUtils.leftPad(
                                    String.valueOf(Math.abs(container
                                            .getCactvwai().getAcctsidi())), 11,
                                    '0'));
        }
        // *    INDIVIDUAL FIELD EDITS
        // [T-Up#INFO][COACTVWC.cbl:632] PERFORM statement
        controlManager.run(context, _2210EditAccount, _2210EditAccountExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // *    CROSS FIELD EDITS
        // [T-Up#INFO][COACTVWC.cbl:636] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage()
                .getWsEditAcctFlag(), FLG_ACCTFILTER_BLANK) == 0) {
            // [T-Up#INFO][COACTVWC.cbl:637] SET statement
            container.getWsMiscStorage().setWsReturnMsg(
                    NO_SEARCH_CRITERIA_RECEIVED);
        }
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:641] 2200-EDIT-MAP-INPUTS-EXIT Paragraph</p>
     */
    void _2200EditMapInputsExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:642] EXIT statement
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:645] 2210-EDIT-ACCOUNT Paragraph</p>
     */
    void _2210EditAccount(OpenFrameContext context) {
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // [T-Up#INFO][COACTVWC.cbl:646] SET statement
        container.getWsMiscStorage().setWsEditAcctFlag(FLG_ACCTFILTER_NOT_OK);
        // *    Not supplied
        // [T-Up#INFO][COACTVWC.cbl:649] IF statement
        if (CobStringUtils.compare(container.getCcWorkAreas().getCcWorkArea()
                .getCcAcctId(), StringUtils.repeat((char) 0x00, 11)) == 0
                || CobStringUtils.compare(container.getCcWorkAreas()
                        .getCcWorkArea().getCcAcctId(),
                        StringUtils.repeat(' ', 11)) == 0) {
            // [T-Up#INFO][COACTVWC.cbl:651] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COACTVWC.cbl:652] SET statement
            container.getWsMiscStorage()
                    .setWsEditAcctFlag(FLG_ACCTFILTER_BLANK);
            // [T-Up#INFO][COACTVWC.cbl:653] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsReturnMsg(), WS_RETURN_MSG_OFF) == 0) {
                // [T-Up#INFO][COACTVWC.cbl:654] SET statement
                container.getWsMiscStorage().setWsReturnMsg(WS_PROMPT_FOR_ACCT);
            }
            // [T-Up#INFO][COACTVWC.cbl:656] MOVE statement
            container.getCarddemoCommarea().getCdemoAccountInfo()
                    .setCdemoAcctId((long) 0);
            // [T-Up#INFO][COACTVWC.cbl:657] GO TO statement
            context.setGotoTarget(_2210EditAccountExit);
            return;
        }
        // *
        // *    Not numeric
        // *    Not 11 characters
        // [T-Up#INFO][COACTVWC.cbl:662] IF statement
        if (!StringUtils.isNumeric(container.getCcWorkAreas().getCcWorkArea()
                .getCcAcctId())
                || CobStringUtils.compare(container.getCcWorkAreas()
                        .getCcWorkArea().getCcAcctId(),
                        StringUtils.repeat('0', 11)) == 0) {
            // [T-Up#INFO][COACTVWC.cbl:664] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COACTVWC.cbl:665] SET statement
            container.getWsMiscStorage().setWsEditAcctFlag(
                    FLG_ACCTFILTER_NOT_OK);
            // [T-Up#INFO][COACTVWC.cbl:666] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsReturnMsg(), WS_RETURN_MSG_OFF) == 0) {
                // [T-Up#INFO][COACTVWC.cbl:667] MOVE statement
                container.getWsMiscStorage().setWsReturnMsg(
                        "Account Filter must  be a non-zero 11 digit number");
            }
            // [T-Up#INFO][COACTVWC.cbl:671] MOVE statement
            container.getCarddemoCommarea().getCdemoAccountInfo()
                    .setCdemoAcctId((long) 0);
            // [T-Up#INFO][COACTVWC.cbl:672] GO TO statement
            context.setGotoTarget(_2210EditAccountExit);
            return;
        } else {
            // [T-Up#INFO][COACTVWC.cbl:674] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoAccountInfo()
                    .setCdemoAcctId(
                            Long.parseLong(container.getCcWorkAreas()
                                    .getCcWorkArea().getCcAcctId().trim()));
            // [T-Up#INFO][COACTVWC.cbl:675] SET statement
            container.getWsMiscStorage().setWsEditAcctFlag(
                    FLG_ACCTFILTER_ISVALID);
        }
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:679] 2210-EDIT-ACCOUNT-EXIT Paragraph</p>
     */
    void _2210EditAccountExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:680] EXIT statement
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:683] 9000-READ-ACCT Paragraph</p>
     */
    void _9000ReadAcct(OpenFrameContext context) {
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // [T-Up#INFO][COACTVWC.cbl:685] SET statement
        container.getWsMiscStorage().setWsInfoMsg(WS_NO_INFO_MESSAGE_1);
        // [T-Up#INFO][COACTVWC.cbl:687] MOVE statement
        container
                .getWsMiscStorage()
                .getWsXrefRid()
                .setWsCardRidAcctId(
                        container.getCarddemoCommarea().getCdemoAccountInfo()
                                .getCdemoAcctId());
        // [T-Up#INFO][COACTVWC.cbl:689] PERFORM statement
        controlManager.run(context, _9200GetcardxrefByacct,
                _9200GetcardxrefByacctExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // *    IF DID-NOT-FIND-ACCT-IN-CARDXREF
        // [T-Up#INFO][COACTVWC.cbl:693] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage()
                .getWsEditAcctFlag(), FLG_ACCTFILTER_NOT_OK) == 0) {
            // [T-Up#INFO][COACTVWC.cbl:694] GO TO statement
            context.setGotoTarget(_9000ReadAcctExit);
            return;
        }
        // [T-Up#INFO][COACTVWC.cbl:697] PERFORM statement
        controlManager.run(context, _9300GetacctdataByacct,
                _9300GetacctdataByacctExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COACTVWC.cbl:700] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage()
                .getWsReturnMsg(), DID_NOT_FIND_ACCT_IN_ACCTDAT) == 0) {
            // [T-Up#INFO][COACTVWC.cbl:701] GO TO statement
            context.setGotoTarget(_9000ReadAcctExit);
            return;
        }
        // [T-Up#INFO][COACTVWC.cbl:704] MOVE statement
        container
                .getWsMiscStorage()
                .getWsXrefRid()
                .setWsCardRidCustId(
                        container.getCarddemoCommarea().getCdemoCustomerInfo()
                                .getCdemoCustId());
        // [T-Up#INFO][COACTVWC.cbl:706] PERFORM statement
        controlManager.run(context, _9400GetcustdataBycust,
                _9400GetcustdataBycustExit);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COACTVWC.cbl:709] IF statement
        if (CobStringUtils.compare(container.getWsMiscStorage()
                .getWsReturnMsg(), DID_NOT_FIND_CUST_IN_CUSTDAT) == 0) {
            // [T-Up#INFO][COACTVWC.cbl:710] GO TO statement
            context.setGotoTarget(_9000ReadAcctExit);
            return;
        }
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:716] 9000-READ-ACCT-EXIT Paragraph</p>
     */
    void _9000ReadAcctExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:717] EXIT statement
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:719] 9200-GETCARDXREF-BYACCT Paragraph</p>
     */
    void _9200GetcardxrefByacct(OpenFrameContext context) {
        StringBuilder tempStringBuilder1;
        StringBuilder tempStringBuilder2;
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // *    Read the Card file. Access via alternate index ACCTID
        // *
        // [T-Up#INFO][COACTVWC.cbl:723] EXEC_CICS statement
        /*
                       EXEC CICS READ
                            DATASET   (LIT-CARDXREFNAME-ACCT-PATH)
                            RIDFLD    (WS-CARD-RID-ACCT-ID-X)
                            KEYLENGTH (LENGTH OF WS-CARD-RID-ACCT-ID-X)
                            INTO      (CARD-XREF-RECORD)
                            LENGTH    (LENGTH OF CARD-XREF-RECORD)
                            RESP      (WS-RESP-CD)
                            RESP2     (WS-REAS-CD)
                       END-EXEC
         */
        try {
            AwsM2CarddemoCardxrefVsamKsdsDto awsM2CarddemoCardxrefVsamKsdsDto = recordKeyAccessor
                    .alternateIndex().read(
                            "awsM2CarddemoCardxrefVsamKsdsDao",
                            "Aix11",
                            new BigDecimal(container.getWsMiscStorage()
                                    .getWsXrefRid().getWsCardRidAcctIdX()));
            container
                    .setCardXrefRecord(CardXrefRecordToAwsM2CarddemoCardxrefVsamKsdsDto.INSTANCE
                            .toSource(awsM2CarddemoCardxrefVsamKsdsDto));
        } catch (ConditionException e) {
        } finally {
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsRespCd(task.getLastResp());
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsReasCd(task.getLastResp2());
        }
        // [T-Up#INFO][COACTVWC.cbl:733] EVALUATE statement
        if (container.getWsMiscStorage().getWsCicsProcessngVars().getWsRespCd() == 0) {
            // [T-Up#INFO][COACTVWC.cbl:735] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCustomerInfo()
                    .setCdemoCustId(
                            container.getCardXrefRecord().getXrefCustId());
            // [T-Up#INFO][COACTVWC.cbl:736] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCardInfo()
                    .setCdemoCardNum(
                            Long.parseLong(container.getCardXrefRecord()
                                    .getXrefCardNum().trim()));
        } else if (container.getWsMiscStorage().getWsCicsProcessngVars()
                .getWsRespCd() == 13) {
            // [T-Up#INFO][COACTVWC.cbl:738] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COACTVWC.cbl:739] SET statement
            container.getWsMiscStorage().setWsEditAcctFlag(
                    FLG_ACCTFILTER_NOT_OK);
            // [T-Up#INFO][COACTVWC.cbl:740] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsReturnMsg(), WS_RETURN_MSG_OFF) == 0) {
                // [T-Up#INFO][COACTVWC.cbl:741] MOVE statement
                container
                        .getWsMiscStorage()
                        .getWsFileErrorMessage()
                        .setErrorResp(
                                StringUtils.leftPad(
                                        String.valueOf(Math.abs(container
                                                .getWsMiscStorage()
                                                .getWsCicsProcessngVars()
                                                .getWsRespCd())), 9, '0'));
                // [T-Up#INFO][COACTVWC.cbl:742] MOVE statement
                container
                        .getWsMiscStorage()
                        .getWsFileErrorMessage()
                        .setErrorResp2(
                                StringUtils.leftPad(
                                        String.valueOf(Math.abs(container
                                                .getWsMiscStorage()
                                                .getWsCicsProcessngVars()
                                                .getWsReasCd())), 9, '0'));
                // [T-Up#INFO][COACTVWC.cbl:743] STRING statement
                tempStringBuilder1 = new StringBuilder();
                tempStringBuilder2 = new StringBuilder(container
                        .getWsMiscStorage().getWsReturnMsg());
                tempStringBuilder1
                        .append("Account:")
                        .append(container.getWsMiscStorage().getWsXrefRid()
                                .getWsCardRidAcctIdX())
                        .append(" not found in")
                        .append(" Cross ref file.  Resp:")
                        .append(container.getWsMiscStorage()
                                .getWsFileErrorMessage().getErrorResp())
                        .append(" Reas:")
                        .append(container.getWsMiscStorage()
                                .getWsFileErrorMessage().getErrorResp2());
                if (tempStringBuilder1.length() <= 75) {
                    tempStringBuilder2.replace(0, tempStringBuilder1.length(),
                            tempStringBuilder1.toString());
                    container.getWsMiscStorage().setWsReturnMsg(
                            tempStringBuilder2.toString());
                }
            }
        } else {
            // [T-Up#INFO][COACTVWC.cbl:756] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COACTVWC.cbl:757] SET statement
            container.getWsMiscStorage().setWsEditAcctFlag(
                    FLG_ACCTFILTER_NOT_OK);
            // [T-Up#INFO][COACTVWC.cbl:758] MOVE statement
            container.getWsMiscStorage().getWsFileErrorMessage()
                    .setErrorOpname("READ");
            // [T-Up#INFO][COACTVWC.cbl:759] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorFile(
                            container.getWsLiterals()
                                    .getLitCardxrefnameAcctPath());
            // [T-Up#INFO][COACTVWC.cbl:760] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorResp(
                            StringUtils.leftPad(
                                    String.valueOf(Math.abs(container
                                            .getWsMiscStorage()
                                            .getWsCicsProcessngVars()
                                            .getWsRespCd())), 9, '0'));
            // [T-Up#INFO][COACTVWC.cbl:761] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorResp2(
                            StringUtils.leftPad(
                                    String.valueOf(Math.abs(container
                                            .getWsMiscStorage()
                                            .getWsCicsProcessngVars()
                                            .getWsReasCd())), 9, '0'));
            // [T-Up#INFO][COACTVWC.cbl:762] MOVE statement
            container.getWsMiscStorage().setWsReturnMsg(
                    container.getWsMiscStorage().getWsFileErrorMessage().get());
        }
    }

    // *                                              WS-LONG-MSG
    // *          PERFORM SEND-LONG-TEXT

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:767] 9200-GETCARDXREF-BYACCT-EXIT Paragraph</p>
     */
    void _9200GetcardxrefByacctExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:768] EXIT statement
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:770] 9300-GETACCTDATA-BYACCT Paragraph</p>
     */
    void _9300GetacctdataByacct(OpenFrameContext context) {
        StringBuilder tempStringBuilder1;
        StringBuilder tempStringBuilder2;
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // [T-Up#INFO][COACTVWC.cbl:772] EXEC_CICS statement
        /*
                       EXEC CICS READ
                            DATASET   (LIT-ACCTFILENAME)
                            RIDFLD    (WS-CARD-RID-ACCT-ID-X)
                            KEYLENGTH (LENGTH OF WS-CARD-RID-ACCT-ID-X)
                            INTO      (ACCOUNT-RECORD)
                            LENGTH    (LENGTH OF ACCOUNT-RECORD)
                            RESP      (WS-RESP-CD)
                            RESP2     (WS-REAS-CD)
                       END-EXEC
         */
        try {
            AwsM2CarddemoAcctdataVsamKsdsDto awsM2CarddemoAcctdataVsamKsdsDto = recordKeyAccessor
                    .read("awsM2CarddemoAcctdataVsamKsdsDao", new BigDecimal(
                            container.getWsMiscStorage().getWsXrefRid()
                                    .getWsCardRidAcctIdX()));
            container
                    .setAccountRecord(AccountRecordToAwsM2CarddemoAcctdataVsamKsdsDto.INSTANCE
                            .toSource(awsM2CarddemoAcctdataVsamKsdsDto));
        } catch (ConditionException e) {
        } finally {
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsRespCd(task.getLastResp());
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsReasCd(task.getLastResp2());
        }
        // [T-Up#INFO][COACTVWC.cbl:782] EVALUATE statement
        if (container.getWsMiscStorage().getWsCicsProcessngVars().getWsRespCd() == 0) {
            // [T-Up#INFO][COACTVWC.cbl:784] SET statement
            container.getWsMiscStorage().getWsFileReadFlags()
                    .setWsAccountMasterReadFlag(FOUND_ACCT_IN_MASTER);
        } else if (container.getWsMiscStorage().getWsCicsProcessngVars()
                .getWsRespCd() == 13) {
            // [T-Up#INFO][COACTVWC.cbl:786] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COACTVWC.cbl:787] SET statement
            container.getWsMiscStorage().setWsEditAcctFlag(
                    FLG_ACCTFILTER_NOT_OK);
            // *           SET DID-NOT-FIND-ACCT-IN-ACCTDAT TO TRUE
            // [T-Up#INFO][COACTVWC.cbl:789] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsReturnMsg(), WS_RETURN_MSG_OFF) == 0) {
                // [T-Up#INFO][COACTVWC.cbl:790] MOVE statement
                container
                        .getWsMiscStorage()
                        .getWsFileErrorMessage()
                        .setErrorResp(
                                StringUtils.leftPad(
                                        String.valueOf(Math.abs(container
                                                .getWsMiscStorage()
                                                .getWsCicsProcessngVars()
                                                .getWsRespCd())), 9, '0'));
                // [T-Up#INFO][COACTVWC.cbl:791] MOVE statement
                container
                        .getWsMiscStorage()
                        .getWsFileErrorMessage()
                        .setErrorResp2(
                                StringUtils.leftPad(
                                        String.valueOf(Math.abs(container
                                                .getWsMiscStorage()
                                                .getWsCicsProcessngVars()
                                                .getWsReasCd())), 9, '0'));
                // [T-Up#INFO][COACTVWC.cbl:792] STRING statement
                tempStringBuilder1 = new StringBuilder();
                tempStringBuilder2 = new StringBuilder(container
                        .getWsMiscStorage().getWsReturnMsg());
                tempStringBuilder1
                        .append("Account:")
                        .append(container.getWsMiscStorage().getWsXrefRid()
                                .getWsCardRidAcctIdX())
                        .append(" not found in")
                        .append(" Acct Master file.Resp:")
                        .append(container.getWsMiscStorage()
                                .getWsFileErrorMessage().getErrorResp())
                        .append(" Reas:")
                        .append(container.getWsMiscStorage()
                                .getWsFileErrorMessage().getErrorResp2());
                if (tempStringBuilder1.length() <= 75) {
                    tempStringBuilder2.replace(0, tempStringBuilder1.length(),
                            tempStringBuilder1.toString());
                    container.getWsMiscStorage().setWsReturnMsg(
                            tempStringBuilder2.toString());
                }
            }
        } else {
            // *
            // [T-Up#INFO][COACTVWC.cbl:806] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COACTVWC.cbl:807] SET statement
            container.getWsMiscStorage().setWsEditAcctFlag(
                    FLG_ACCTFILTER_NOT_OK);
            // [T-Up#INFO][COACTVWC.cbl:808] MOVE statement
            container.getWsMiscStorage().getWsFileErrorMessage()
                    .setErrorOpname("READ");
            // [T-Up#INFO][COACTVWC.cbl:809] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorFile(
                            container.getWsLiterals().getLitAcctfilename());
            // [T-Up#INFO][COACTVWC.cbl:810] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorResp(
                            StringUtils.leftPad(
                                    String.valueOf(Math.abs(container
                                            .getWsMiscStorage()
                                            .getWsCicsProcessngVars()
                                            .getWsRespCd())), 9, '0'));
            // [T-Up#INFO][COACTVWC.cbl:811] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorResp2(
                            StringUtils.leftPad(
                                    String.valueOf(Math.abs(container
                                            .getWsMiscStorage()
                                            .getWsCicsProcessngVars()
                                            .getWsReasCd())), 9, '0'));
            // [T-Up#INFO][COACTVWC.cbl:812] MOVE statement
            container.getWsMiscStorage().setWsReturnMsg(
                    container.getWsMiscStorage().getWsFileErrorMessage().get());
        }
    }

    // *                                              WS-LONG-MSG
    // *           PERFORM SEND-LONG-TEXT

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:817] 9300-GETACCTDATA-BYACCT-EXIT Paragraph</p>
     */
    void _9300GetacctdataByacctExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:818] EXIT statement
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:821] 9400-GETCUSTDATA-BYCUST Paragraph</p>
     */
    void _9400GetcustdataBycust(OpenFrameContext context) {
        StringBuilder tempStringBuilder1;
        StringBuilder tempStringBuilder2;
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // [T-Up#INFO][COACTVWC.cbl:822] EXEC_CICS statement
        /*
                       EXEC CICS READ
                            DATASET   (LIT-CUSTFILENAME)
                            RIDFLD    (WS-CARD-RID-CUST-ID-X)
                            KEYLENGTH (LENGTH OF WS-CARD-RID-CUST-ID-X)
                            INTO      (CUSTOMER-RECORD)
                            LENGTH    (LENGTH OF CUSTOMER-RECORD)
                            RESP      (WS-RESP-CD)
                            RESP2     (WS-REAS-CD)
                       END-EXEC
         */
        try {
            AwsM2CarddemoCustdataVsamKsdsDto awsM2CarddemoCustdataVsamKsdsDto = recordKeyAccessor
                    .read("awsM2CarddemoCustdataVsamKsdsDao", new BigDecimal(
                            container.getWsMiscStorage().getWsXrefRid()
                                    .getWsCardRidCustIdX()));
            container
                    .setCustomerRecord(CustomerRecordToAwsM2CarddemoCustdataVsamKsdsDto.INSTANCE
                            .toSource(awsM2CarddemoCustdataVsamKsdsDto));
        } catch (ConditionException e) {
        } finally {
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsRespCd(task.getLastResp());
            container.getWsMiscStorage().getWsCicsProcessngVars()
                    .setWsReasCd(task.getLastResp2());
        }
        // [T-Up#INFO][COACTVWC.cbl:832] EVALUATE statement
        if (container.getWsMiscStorage().getWsCicsProcessngVars().getWsRespCd() == 0) {
            // [T-Up#INFO][COACTVWC.cbl:834] SET statement
            container.getWsMiscStorage().getWsFileReadFlags()
                    .setWsCustMasterReadFlag(FOUND_CUST_IN_MASTER);
        } else if (container.getWsMiscStorage().getWsCicsProcessngVars()
                .getWsRespCd() == 13) {
            // [T-Up#INFO][COACTVWC.cbl:836] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COACTVWC.cbl:837] SET statement
            container.getWsMiscStorage().setWsEditCustFlag(
                    FLG_CUSTFILTER_NOT_OK);
            // *           SET DID-NOT-FIND-CUST-IN-CUSTDAT TO TRUE
            // [T-Up#INFO][COACTVWC.cbl:839] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorResp(
                            StringUtils.leftPad(
                                    String.valueOf(Math.abs(container
                                            .getWsMiscStorage()
                                            .getWsCicsProcessngVars()
                                            .getWsRespCd())), 9, '0'));
            // [T-Up#INFO][COACTVWC.cbl:840] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorResp2(
                            StringUtils.leftPad(
                                    String.valueOf(Math.abs(container
                                            .getWsMiscStorage()
                                            .getWsCicsProcessngVars()
                                            .getWsReasCd())), 9, '0'));
            // [T-Up#INFO][COACTVWC.cbl:841] IF statement
            if (CobStringUtils.compare(container.getWsMiscStorage()
                    .getWsReturnMsg(), WS_RETURN_MSG_OFF) == 0) {
                // [T-Up#INFO][COACTVWC.cbl:842] STRING statement
                tempStringBuilder1 = new StringBuilder();
                tempStringBuilder2 = new StringBuilder(container
                        .getWsMiscStorage().getWsReturnMsg());
                tempStringBuilder1
                        .append("CustId:")
                        .append(container.getWsMiscStorage().getWsXrefRid()
                                .getWsCardRidCustIdX())
                        .append(" not found")
                        .append(" in customer master.Resp: ")
                        .append(container.getWsMiscStorage()
                                .getWsFileErrorMessage().getErrorResp())
                        .append(" REAS:")
                        .append(container.getWsMiscStorage()
                                .getWsFileErrorMessage().getErrorResp2());
                if (tempStringBuilder1.length() <= 75) {
                    tempStringBuilder2.replace(0, tempStringBuilder1.length(),
                            tempStringBuilder1.toString());
                    container.getWsMiscStorage().setWsReturnMsg(
                            tempStringBuilder2.toString());
                }
            }
        } else {
            // [T-Up#INFO][COACTVWC.cbl:855] SET statement
            container.getWsMiscStorage().setWsInputFlag(INPUT_ERROR);
            // [T-Up#INFO][COACTVWC.cbl:856] SET statement
            container.getWsMiscStorage().setWsEditCustFlag(
                    FLG_CUSTFILTER_NOT_OK);
            // [T-Up#INFO][COACTVWC.cbl:857] MOVE statement
            container.getWsMiscStorage().getWsFileErrorMessage()
                    .setErrorOpname("READ");
            // [T-Up#INFO][COACTVWC.cbl:858] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorFile(
                            container.getWsLiterals().getLitCustfilename());
            // [T-Up#INFO][COACTVWC.cbl:859] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorResp(
                            StringUtils.leftPad(
                                    String.valueOf(Math.abs(container
                                            .getWsMiscStorage()
                                            .getWsCicsProcessngVars()
                                            .getWsRespCd())), 9, '0'));
            // [T-Up#INFO][COACTVWC.cbl:860] MOVE statement
            container
                    .getWsMiscStorage()
                    .getWsFileErrorMessage()
                    .setErrorResp2(
                            StringUtils.leftPad(
                                    String.valueOf(Math.abs(container
                                            .getWsMiscStorage()
                                            .getWsCicsProcessngVars()
                                            .getWsReasCd())), 9, '0'));
            // [T-Up#INFO][COACTVWC.cbl:861] MOVE statement
            container.getWsMiscStorage().setWsReturnMsg(
                    container.getWsMiscStorage().getWsFileErrorMessage().get());
        }
    }

    // *                                              WS-LONG-MSG
    // *           PERFORM SEND-LONG-TEXT

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:866] 9400-GETCUSTDATA-BYCUST-EXIT Paragraph</p>
     */
    void _9400GetcustdataBycustExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:867] EXIT statement
    }

    // *****************************************************************
    // * Plain text exit - Dont use in production                      *
    // *****************************************************************

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:873] SEND-PLAIN-TEXT Paragraph</p>
     */
    void sendPlainText(OpenFrameContext context) {
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // [T-Up#INFO][COACTVWC.cbl:874] EXEC_CICS statement
        /*
                       EXEC CICS SEND TEXT
                                 FROM(WS-RETURN-MSG)
                                 LENGTH(LENGTH OF WS-RETURN-MSG)
                                 ERASE
                                 FREEKB
                       END-EXEC
         */
        task.getOutputDto().getSystemDto()
                .setNotification(container.getWsMiscStorage().getWsReturnMsg());
        // [T-Up#INFO][COACTVWC.cbl:881] EXEC_CICS statement
        /*
                       EXEC CICS RETURN
                       END-EXEC
         */
        context.setReturnFlag(true);
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:884] SEND-PLAIN-TEXT-EXIT Paragraph</p>
     */
    void sendPlainTextExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:885] EXIT statement
    }

    // *****************************************************************
    // * Display Long text and exit                                    *
    // * This is primarily for debugging and should not be used in     *
    // * regular course                                                *
    // *****************************************************************

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:892] SEND-LONG-TEXT Paragraph</p>
     */
    void sendLongText(OpenFrameContext context) {
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // [T-Up#INFO][COACTVWC.cbl:893] EXEC_CICS statement
        /*
                       EXEC CICS SEND TEXT
                                 FROM(WS-LONG-MSG)
                                 LENGTH(LENGTH OF WS-LONG-MSG)
                                 ERASE
                                 FREEKB
                       END-EXEC
         */
        task.getOutputDto().getSystemDto()
                .setNotification(container.getWsMiscStorage().getWsLongMsg());
        // [T-Up#INFO][COACTVWC.cbl:900] EXEC_CICS statement
        /*
                       EXEC CICS RETURN
                       END-EXEC
         */
        context.setReturnFlag(true);
    }

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:903] SEND-LONG-TEXT-EXIT Paragraph</p>
     */
    void sendLongTextExit(OpenFrameContext context) {
        // [T-Up#INFO][COACTVWC.cbl:904] EXIT statement
    }

    // *****************************************************************
    // *Common code to store PFKey
    // ******************************************************************
    //       *COPY 'CSSTRPFY'
    //       *    .
    // *(/home/oflab/repository/pds/TEST/COBOL_COPYBOOK/CSSTRPFY.cpy)
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************

    /** 
     * <p>[T-Up#INFO][CSSTRPFY.cpy:18] YYYY-STORE-PFKEY Paragraph</p>
     */
    void yyyyStorePfkey(OpenFrameContext context) {
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // *****************************************************************
        // * Map AID to PFKey in COMMON Area
        // *****************************************************************
        // [T-Up#INFO][CSSTRPFY.cpy:22] EVALUATE statement
        if (CobStringUtils.compare(task.getPressedKey(), container.getDfhaid()
                .getDfhenter()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:24] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_ENTER);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhclear()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:26] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_CLEAR);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpa1()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:28] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PA1);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpa2()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:30] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PA2);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf1()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:32] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK01);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf2()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:34] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK02);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf3()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:36] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK03);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf4()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:38] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK04);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf5()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:40] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK05);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf6()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:42] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK06);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf7()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:44] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK07);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf8()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:46] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK08);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf9()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:48] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK09);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf10()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:50] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK10);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf11()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:52] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK11);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf12()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:54] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK12);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf13()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:56] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK01);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf14()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:58] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK02);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf15()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:60] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK03);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf16()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:62] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK04);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf17()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:64] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK05);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf18()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:66] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK06);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf19()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:68] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK07);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf20()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:70] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK08);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf21()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:72] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK09);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf22()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:74] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK10);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf23()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:76] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK11);
        } else if (CobStringUtils.compare(task.getPressedKey(), container
                .getDfhaid().getDfhpf24()) == 0) {
            // [T-Up#INFO][CSSTRPFY.cpy:78] SET statement
            container.getCcWorkAreas().getCcWorkArea()
                    .setCcardAid(CCARD_AID_PFK12);
        }
    }

    /** 
     * <p>[T-Up#INFO][CSSTRPFY.cpy:81] YYYY-STORE-PFKEY-EXIT Paragraph</p>
     */
    void yyyyStorePfkeyExit(OpenFrameContext context) {
        // [T-Up#INFO][CSSTRPFY.cpy:82] EXIT statement
    }

    // *
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:15:59 CDT
    // *

    /** 
     * <p>[T-Up#INFO][COACTVWC.cbl:912] ABEND-ROUTINE Paragraph</p>
     */
    void abendRoutine(OpenFrameContext context) {
        CoactvwcVariableContainer container = (CoactvwcVariableContainer) context
                .getProgramVariableContainer("Coactvwc");
        // [T-Up#INFO][COACTVWC.cbl:914] IF statement
        if (CobStringUtils.compare(container.getAbendData().getAbendMsg(),
                StringUtils.repeat((char) 0x00, 72)) == 0) {
            // [T-Up#INFO][COACTVWC.cbl:915] MOVE statement
            container.getAbendData().setAbendMsg("UNEXPECTED ABEND OCCURRED.");
        }
        // [T-Up#INFO][COACTVWC.cbl:918] MOVE statement
        container.getAbendData().setAbendCulprit(
                container.getWsLiterals().getLitThispgm());
        // [T-Up#INFO][COACTVWC.cbl:920] EXEC_CICS statement
        /*
                       EXEC CICS SEND
                                        FROM (ABEND-DATA)
                                        LENGTH(LENGTH OF ABEND-DATA)
                                        NOHANDLE
                       END-EXEC
         */
        try {
            task.getOutputDto().getSystemDto()
                    .setNotification(container.getAbendData());
        } catch (OnlineException e) {
        }
        // [T-Up#INFO][COACTVWC.cbl:926] EXEC_CICS statement
        /*
                       EXEC CICS HANDLE ABEND
                            CANCEL
                       END-EXEC
         */
        abendHandler.cancel();
        // [T-Up#INFO][COACTVWC.cbl:930] EXEC_CICS statement
        /*
                       EXEC CICS ABEND
                            ABCODE('9999')
                       END-EXEC
         */
        throw new AbendException();
    }

    // *
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:12:32 CDT
    // *
}
