package com.tmax.openframe;

import com.tmax.openframe.online.task.service.ProgramControl;
import com.tmax.openframe.dto.Cosgn00cInputDto;
import com.tmax.openframe.online.task.service.OtherUserTaskInvoker;
import com.tmax.openframe.online.task.domain.dto.TaskDto.*;
import com.tmax.openframe.online.task.domain.dto.Data;
import com.tmax.openframe.mapper.Comen01cMapperInterface.*;
import com.tmax.openframe.dto.CoactvwcInputDto;
import com.tmax.openframe.dto.CoactupcInputDto;
import com.tmax.openframe.dto.CocrdlicInputDto;
import com.tmax.openframe.dto.CocrdslcInputDto;
import com.tmax.openframe.dto.CocrdupcInputDto;
import com.tmax.openframe.dto.Cotrn00cInputDto;
import com.tmax.openframe.dto.Cotrn01cInputDto;
import com.tmax.openframe.dto.Cotrn02cInputDto;
import com.tmax.openframe.dto.Corpt00cInputDto;
import com.tmax.openframe.dto.Cobil00cInputDto;
import com.tmax.openframe.online.task.service.Task;
import com.tmax.openframe.dto.Comen01cOutputDto;
import com.tmax.openframe.dto.Comen01cInputDto;
import com.tmax.openframe.online.exception.ConditionException;
import static com.tmax.openframe.variable.group.CarddemoCommarea.CdemoGeneralInfo.*;
import static com.tmax.openframe.variable.group.Comen01cWsVariables.*;
import com.tmax.openframe.runtime.cobol.CobStream;
import com.tmax.openframe.runtime.cobol.CobStringUtils;
import com.tmax.openframe.runtime.cobol.IntrinsicFunction;
import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.flow.ControlManager;
import com.tmax.openframe.variable.Comen01cVariableContainer;
import com.tmax.openframe.variable.group.Comen1ai;
import java.math.*;
import java.util.*;
import java.util.function.Consumer;
import java.util.regex.Pattern;
import lombok.*;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:17 KST</p>
 * <hr>
 * <p>Java class for defining logics of COBOL program</p>
 * <ul>
 * <li>The name of COBOL program: COMEN01C.cbl</li>
 * <li>Variable container class: {@link Comen01cVariableContainer}</li>
 * </ul>
 */
@Service
@RequiredArgsConstructor
@Transactional
@Primary
public class Comen01c {
    /** 
     * <p>Class that manages an execution flow of the program</p>
     */
    protected final ControlManager controlManager;
    Consumer<OpenFrameContext> mainPara = this::mainPara;
    Consumer<OpenFrameContext> processEnterKey = this::processEnterKey;
    Consumer<OpenFrameContext> returnToSignonScreen = this::returnToSignonScreen;
    Consumer<OpenFrameContext> sendMenuScreen = this::sendMenuScreen;
    Consumer<OpenFrameContext> receiveMenuScreen = this::receiveMenuScreen;
    Consumer<OpenFrameContext> populateHeaderInfo = this::populateHeaderInfo;
    Consumer<OpenFrameContext> buildMenuOptions = this::buildMenuOptions;
    /** 
     * <p>Execution flow of COBOL program that defined in the procedure division</p>
     */
    ArrayList<Consumer> methodList = new ArrayList<>();
    {
        methodList.add(mainPara);
        methodList.add(processEnterKey);
        methodList.add(returnToSignonScreen);
        methodList.add(sendMenuScreen);
        methodList.add(receiveMenuScreen);
        methodList.add(populateHeaderInfo);
        methodList.add(buildMenuOptions);
    }
    private final Task task;
    private final TaskInvoker taskInvoker;
    private final ProgramControl programControl;

    /** 
     * <p>Method for executing a program logic that defined in the procedure division</p>
     * @param generalContext context that is necessary for executing program
     * @return return value of program
     */
    public int run(Map<String, Object> generalContext) {
        OpenFrameContext context = new OpenFrameContext(generalContext,
                methodList);
        if (context.getProgramVariableContainer("Comen01c") == null) {
            Comen01cVariableContainer container = new Comen01cVariableContainer();
            context.setProgramVariableContainer("Comen01c", container);
        }
        controlManager.run(context);
        return context.getReturnValue();
    }

    // ******************************************************************
    // * Program     : COMEN01C.CBL
    // * Application : CardDemo
    // * Type        : CICS COBOL Program
    // * Function    : Main Menu for the Regular users
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // *      OCCURS 1 TO 32767 TIMES DEPENDING ON EIBCALEN.
    // *----------------------------------------------------------------*
    // *                       PROCEDURE DIVISION
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COMEN01C.cbl:75] MAIN-PARA Paragraph</p>
     */
    void mainPara(OpenFrameContext context) {
        Comen01cVariableContainer container = (Comen01cVariableContainer) context
                .getProgramVariableContainer("Comen01c");
        // [T-Up#INFO][COMEN01C.cbl:77] SET statement
        container.getWsVariables().setWsErrFlg(ERR_FLG_OFF);
        // [T-Up#INFO][COMEN01C.cbl:79] MOVE statement
        container.getWsVariables().setWsMessage(StringUtils.repeat(' ', 80));
        container.setErrmsgo(StringUtils.repeat(' ', 78));
        // [T-Up#INFO][COMEN01C.cbl:82] IF statement
        if (task.hasCommarea() == 0) {
            // [T-Up#INFO][COMEN01C.cbl:83] MOVE statement
            container.getCarddemoCommarea().getCdemoGeneralInfo()
                    .setCdemoFromProgram("COSGN00C");
            // [T-Up#INFO][COMEN01C.cbl:84] EXEC_CICS statement
            /*
                               EXEC CICS
                               XCTL PROGRAM('COSGN00C')
                               END-EXEC
             */
            Cosgn00cInputDto cosgn00cInputDto = new Cosgn00cInputDto();
            programControl.forward("CC00", cosgn00cInputDto);
            context.setReturnFlag(true);
            // [T-Up#INFO][COMEN01C.cbl:87] PERFORM statement
            controlManager.run(context, returnToSignonScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        } else {
            // [T-Up#INFO][COMEN01C.cbl:89] MOVE statement
            container.getCarddemoCommarea().set(
                    StringUtils.overlay(container.getCarddemoCommarea().get(),
                            container.getDfhcommarea().get().substring(0, 160),
                            0, 160));
            // [T-Up#INFO][COMEN01C.cbl:90] IF statement
            if (!(container.getCarddemoCommarea().getCdemoGeneralInfo()
                    .getCdemoPgmContext() == CDEMO_PGM_REENTER)) {
                // [T-Up#INFO][COMEN01C.cbl:91] SET statement
                container.getCarddemoCommarea().getCdemoGeneralInfo()
                        .setCdemoPgmContext(CDEMO_PGM_REENTER);
                // [T-Up#INFO][COMEN01C.cbl:92] MOVE statement
                container.setComen1ao(Comen1ai.createDefaultValueInstance()
                        .get());
                // [T-Up#INFO][COMEN01C.cbl:93] PERFORM statement
                controlManager.run(context, sendMenuScreen);
                if (controlManager.isTerminate(context)) {
                    return;
                }
            } else {
                // [T-Up#INFO][COMEN01C.cbl:95] PERFORM statement
                controlManager.run(context, receiveMenuScreen);
                if (controlManager.isTerminate(context)) {
                    return;
                }
                // [T-Up#INFO][COMEN01C.cbl:96] EVALUATE statement
                if (CobStringUtils.compare(task.getPressedKey(), container
                        .getDfhaid().getDfhenter()) == 0) {
                    // [T-Up#INFO][COMEN01C.cbl:98] PERFORM statement
                    controlManager.run(context, processEnterKey);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                } else if (CobStringUtils.compare(task.getPressedKey(),
                        container.getDfhaid().getDfhpf3()) == 0) {
                    // [T-Up#INFO][COMEN01C.cbl:100] MOVE statement
                    container.getCarddemoCommarea().getCdemoGeneralInfo()
                            .setCdemoToProgram("COSGN00C");
                    // [T-Up#INFO][COMEN01C.cbl:101] EXEC_CICS statement
                    /*
                                                   EXEC CICS
                                                   XCTL PROGRAM('COSGN00C')
                                                   END-EXEC
                     */
                    Cosgn00cInputDto cosgn00cInputDto = new Cosgn00cInputDto();
                    programControl.forward("CC00", cosgn00cInputDto);
                    context.setReturnFlag(true);
                    // [T-Up#INFO][COMEN01C.cbl:104] PERFORM statement
                    controlManager.run(context, returnToSignonScreen);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                } else {
                    // [T-Up#INFO][COMEN01C.cbl:106] MOVE statement
                    container.getWsVariables().setWsErrFlg("Y");
                    // [T-Up#INFO][COMEN01C.cbl:107] MOVE statement
                    container.getWsVariables().setWsMessage(
                            container.getCcdaCommonMessages()
                                    .getCcdaMsgInvalidKey());
                    // [T-Up#INFO][COMEN01C.cbl:108] PERFORM statement
                    controlManager.run(context, sendMenuScreen);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                }
            }
        }
        // [T-Up#INFO][COMEN01C.cbl:113] EXEC_CICS statement
        /*
                       EXEC CICS RETURN
                                 TRANSID (WS-TRANID)
                                 COMMAREA (CARDDEMO-COMMAREA)
                       END-EXEC
         */
        TaskDto taskDto = TaskDto
                .builder()
                .destination("CM00")
                .data(Data
                        .session(CarddemoCommareaToComen01cDfhcommarea.INSTANCE
                                .toTarget(container.getCarddemoCommarea())))
                .build();
        taskInvoker.setNextTask(taskDto);
        context.setReturnFlag(true);
    }

    // *----------------------------------------------------------------*
    // *                      PROCESS-ENTER-KEY
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COMEN01C.cbl:121] PROCESS-ENTER-KEY Paragraph</p>
     */
    void processEnterKey(OpenFrameContext context) {
        StringBuilder tempStringBuilder1;
        StringBuilder tempStringBuilder2;
        Comen01cVariableContainer container = (Comen01cVariableContainer) context
                .getProgramVariableContainer("Comen01c");
        // [T-Up#INFO][COMEN01C.cbl:123] PERFORM statement
        container.getWsVariables().setWsIdx(2);
        while (!(CobStringUtils.compare(
                container
                        .getComen1ai()
                        .getOptioni()
                        .substring(container.getWsVariables().getWsIdx() - 1,
                                container.getWsVariables().getWsIdx() - 1 + 1),
                StringUtils.repeat(' ', 2)) != 0 || container.getWsVariables()
                .getWsIdx() == 1)) {
            container.getWsVariables().setWsIdx(
                    container.getWsVariables().getWsIdx() + -1);
        }
        // [T-Up#INFO][COMEN01C.cbl:128] MOVE statement
        container.getWsVariables()
                .setWsOptionX(
                        container
                                .getComen1ai()
                                .getOptioni()
                                .substring(
                                        0,
                                        0 + container.getWsVariables()
                                                .getWsIdx()));
        // [T-Up#INFO][COMEN01C.cbl:129] INSPECT statement
        tempStringBuilder1 = new StringBuilder();
        for (char ch : container.getWsVariables().getWsOptionX().toCharArray()) {
            if (ch == " ".charAt(0)) {
                tempStringBuilder1.append("0".charAt(0));
            } else {
                tempStringBuilder1.append(ch);
            }
        }
        container.getWsVariables().setWsOptionX(tempStringBuilder1.toString());
        // [T-Up#INFO][COMEN01C.cbl:130] MOVE statement
        container.getWsVariables().setWsOption(
                Integer.parseInt(container.getWsVariables().getWsOptionX()
                        .trim()));
        // [T-Up#INFO][COMEN01C.cbl:131] MOVE statement
        container.setOptiono(StringUtils.leftPad(String.valueOf(Math
                .abs(container.getWsVariables().getWsOption())), 2, '0'));
        // [T-Up#INFO][COMEN01C.cbl:133] IF statement
        if (!true
                || container.getWsVariables().getWsOption() > container
                        .getCarddemoMainMenuOptions().getCdemoMenuOptCount()
                || container.getWsVariables().getWsOption() == 0) {
            // [T-Up#INFO][COMEN01C.cbl:136] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COMEN01C.cbl:137] MOVE statement
            container.getWsVariables().setWsMessage(
                    "Please enter a valid option number...");
            // [T-Up#INFO][COMEN01C.cbl:139] PERFORM statement
            controlManager.run(context, sendMenuScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
        // [T-Up#INFO][COMEN01C.cbl:142] IF statement
        if (CobStringUtils.compare(container.getCarddemoCommarea()
                .getCdemoGeneralInfo().getCdemoUserType(), CDEMO_USRTYP_USER) == 0
                && CobStringUtils.compare(
                        container
                                .getCarddemoMainMenuOptions()
                                .getCdemoMenuOptions()
                                .getCdemoMenuOpt()
                                .getCdemoMenuOptUsrtype(
                                        container.getWsVariables()
                                                .getWsOption() - 1), "A") == 0) {
            // [T-Up#INFO][COMEN01C.cbl:144] SET statement
            container.getWsVariables().setWsErrFlg(ERR_FLG_ON);
            // [T-Up#INFO][COMEN01C.cbl:145] MOVE statement
            container.getWsVariables()
                    .setWsMessage(StringUtils.repeat(' ', 80));
            // [T-Up#INFO][COMEN01C.cbl:146] MOVE statement
            container.getWsVariables().setWsMessage(
                    "No access - Admin Only option... ");
            // [T-Up#INFO][COMEN01C.cbl:148] PERFORM statement
            controlManager.run(context, sendMenuScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
        // [T-Up#INFO][COMEN01C.cbl:151] IF statement
        if (!(CobStringUtils.compare(container.getWsVariables().getWsErrFlg(),
                ERR_FLG_ON) == 0)) {
            // [T-Up#INFO][COMEN01C.cbl:152] IF statement
            if (CobStringUtils
                    .compare(
                            container
                                    .getCarddemoMainMenuOptions()
                                    .getCdemoMenuOptions()
                                    .getCdemoMenuOpt()
                                    .getCdemoMenuOptPgmname(
                                            container.getWsVariables()
                                                    .getWsOption() - 1)
                                    .substring(0, 5), "DUMMY") != 0) {
                // [T-Up#INFO][COMEN01C.cbl:153] MOVE statement
                container
                        .getCarddemoCommarea()
                        .getCdemoGeneralInfo()
                        .setCdemoFromTranid(
                                container.getWsVariables().getWsTranid());
                // [T-Up#INFO][COMEN01C.cbl:154] MOVE statement
                container
                        .getCarddemoCommarea()
                        .getCdemoGeneralInfo()
                        .setCdemoFromProgram(
                                container.getWsVariables().getWsPgmname());
                // *            MOVE WS-USER-ID   TO CDEMO-USER-ID
                // *            MOVE SEC-USR-TYPE TO CDEMO-USER-TYPE
                // [T-Up#INFO][COMEN01C.cbl:157] MOVE statement
                container.getCarddemoCommarea().getCdemoGeneralInfo()
                        .setCdemoPgmContext(0);
                // [T-Up#INFO][COMEN01C.cbl:158] EVALUATE statement
                switch (container
                        .getCarddemoMainMenuOptions()
                        .getCdemoMenuOptions()
                        .getCdemoMenuOpt()
                        .getCdemoMenuOptPgmname(
                                container.getWsVariables().getWsOption() - 1)) {
                case "COACTVWC": {
                    // [T-Up#INFO][COMEN01C.cbl:160] EXEC_CICS statement
                    /*
                                               EXEC CICS
                                                   XCTL PROGRAM('COACTVWC')
                                                   COMMAREA(CARDDEMO-COMMAREA)
                                               END-EXEC
                     */
                    CoactvwcInputDto coactvwcInputDto = new CoactvwcInputDto();
                    coactvwcInputDto
                            .setDfhcommarea(CarddemoCommareaToCoactvwcDfhcommarea.INSTANCE
                                    .toTarget(container.getCarddemoCommarea()));
                    programControl.forward("CAVW", coactvwcInputDto);
                    context.setReturnFlag(true);
                    break;
                }
                case "COACTUPC": {
                    // [T-Up#INFO][COMEN01C.cbl:165] EXEC_CICS statement
                    /*
                                               EXEC CICS
                                                   XCTL PROGRAM('COACTUPC')
                                                   COMMAREA(CARDDEMO-COMMAREA)
                                               END-EXEC
                     */
                    CoactupcInputDto coactupcInputDto = new CoactupcInputDto();
                    coactupcInputDto
                            .setDfhcommarea(CarddemoCommareaToCoactupcDfhcommarea.INSTANCE
                                    .toTarget(container.getCarddemoCommarea()));
                    programControl.forward("CAUP", coactupcInputDto);
                    context.setReturnFlag(true);
                    break;
                }
                case "COCRDLIC": {
                    // [T-Up#INFO][COMEN01C.cbl:170] EXEC_CICS statement
                    /*
                                               EXEC CICS
                                                   XCTL PROGRAM('COCRDLIC')
                                                   COMMAREA(CARDDEMO-COMMAREA)
                                               END-EXEC
                     */
                    CocrdlicInputDto cocrdlicInputDto = new CocrdlicInputDto();
                    cocrdlicInputDto
                            .setDfhcommarea(CarddemoCommareaToCocrdlicDfhcommarea.INSTANCE
                                    .toTarget(container.getCarddemoCommarea()));
                    programControl.forward("CCLI", cocrdlicInputDto);
                    context.setReturnFlag(true);
                    break;
                }
                case "COCRDSLC": {
                    // [T-Up#INFO][COMEN01C.cbl:175] EXEC_CICS statement
                    /*
                                               EXEC CICS
                                                   XCTL PROGRAM('COCRDSLC')
                                                   COMMAREA(CARDDEMO-COMMAREA)
                                               END-EXEC
                     */
                    CocrdslcInputDto cocrdslcInputDto = new CocrdslcInputDto();
                    cocrdslcInputDto
                            .setDfhcommarea(CarddemoCommareaToCocrdslcDfhcommarea.INSTANCE
                                    .toTarget(container.getCarddemoCommarea()));
                    programControl.forward("CCDL", cocrdslcInputDto);
                    context.setReturnFlag(true);
                    break;
                }
                case "COCRDUPC": {
                    // [T-Up#INFO][COMEN01C.cbl:180] EXEC_CICS statement
                    /*
                                               EXEC CICS
                                                   XCTL PROGRAM('COCRDUPC')
                                                   COMMAREA(CARDDEMO-COMMAREA)
                                               END-EXEC
                     */
                    CocrdupcInputDto cocrdupcInputDto = new CocrdupcInputDto();
                    cocrdupcInputDto
                            .setDfhcommarea(CarddemoCommareaToCocrdupcDfhcommarea.INSTANCE
                                    .toTarget(container.getCarddemoCommarea()));
                    programControl.forward("CCUP", cocrdupcInputDto);
                    context.setReturnFlag(true);
                    break;
                }
                case "COTRN00C": {
                    // [T-Up#INFO][COMEN01C.cbl:185] EXEC_CICS statement
                    /*
                                               EXEC CICS
                                                   XCTL PROGRAM('COTRN00C')
                                                   COMMAREA(CARDDEMO-COMMAREA)
                                               END-EXEC
                     */
                    Cotrn00cInputDto cotrn00cInputDto = new Cotrn00cInputDto();
                    cotrn00cInputDto
                            .setDfhcommarea(CarddemoCommareaToCotrn00cDfhcommarea.INSTANCE
                                    .toTarget(container.getCarddemoCommarea()));
                    programControl.forward("CT00", cotrn00cInputDto);
                    context.setReturnFlag(true);
                    break;
                }
                case "COTRN01C": {
                    // [T-Up#INFO][COMEN01C.cbl:190] EXEC_CICS statement
                    /*
                                               EXEC CICS
                                                   XCTL PROGRAM('COTRN01C')
                                                   COMMAREA(CARDDEMO-COMMAREA)
                                               END-EXEC
                     */
                    Cotrn01cInputDto cotrn01cInputDto = new Cotrn01cInputDto();
                    cotrn01cInputDto
                            .setDfhcommarea(CarddemoCommareaToCotrn01cDfhcommarea.INSTANCE
                                    .toTarget(container.getCarddemoCommarea()));
                    programControl.forward("CT01", cotrn01cInputDto);
                    context.setReturnFlag(true);
                    break;
                }
                case "COTRN02C": {
                    // [T-Up#INFO][COMEN01C.cbl:195] EXEC_CICS statement
                    /*
                                               EXEC CICS
                                                   XCTL PROGRAM('COTRN02C')
                                                   COMMAREA(CARDDEMO-COMMAREA)
                                               END-EXEC
                     */
                    Cotrn02cInputDto cotrn02cInputDto = new Cotrn02cInputDto();
                    cotrn02cInputDto
                            .setDfhcommarea(CarddemoCommareaToCotrn02cDfhcommarea.INSTANCE
                                    .toTarget(container.getCarddemoCommarea()));
                    programControl.forward("CT02", cotrn02cInputDto);
                    context.setReturnFlag(true);
                    break;
                }
                case "CORPT00C": {
                    // [T-Up#INFO][COMEN01C.cbl:200] EXEC_CICS statement
                    /*
                                               EXEC CICS
                                                   XCTL PROGRAM('CORPT00C')
                                                   COMMAREA(CARDDEMO-COMMAREA)
                                               END-EXEC
                     */
                    Corpt00cInputDto corpt00cInputDto = new Corpt00cInputDto();
                    corpt00cInputDto
                            .setDfhcommarea(CarddemoCommareaToCorpt00cDfhcommarea.INSTANCE
                                    .toTarget(container.getCarddemoCommarea()));
                    programControl.forward("CR00", corpt00cInputDto);
                    context.setReturnFlag(true);
                    break;
                }
                case "COBIL00C": {
                    // [T-Up#INFO][COMEN01C.cbl:205] EXEC_CICS statement
                    /*
                                               EXEC CICS
                                                   XCTL PROGRAM('COBIL00C')
                                                   COMMAREA(CARDDEMO-COMMAREA)
                                               END-EXEC
                     */
                    Cobil00cInputDto cobil00cInputDto = new Cobil00cInputDto();
                    cobil00cInputDto
                            .setDfhcommarea(CarddemoCommareaToCobil00cDfhcommarea.INSTANCE
                                    .toTarget(container.getCarddemoCommarea()));
                    programControl.forward("CB00", cobil00cInputDto);
                    context.setReturnFlag(true);
                    break;
                }
                default: {
                    // [T-Up#INFO][COMEN01C.cbl:210] CONTINUE statement
                    break;
                }
                }
            }
            // [T-Up#INFO][COMEN01C.cbl:213] MOVE statement
            container.getWsVariables()
                    .setWsMessage(StringUtils.repeat(' ', 80));
            // [T-Up#INFO][COMEN01C.cbl:214] MOVE statement
            container.setErrmsgc(container.getDfhbmsca().getDfhgreen());
            // [T-Up#INFO][COMEN01C.cbl:215] STRING statement
            tempStringBuilder1 = new StringBuilder();
            tempStringBuilder2 = new StringBuilder(container.getWsVariables()
                    .getWsMessage());
            tempStringBuilder1
                    .append("This option ")
                    .append(container
                            .getCarddemoMainMenuOptions()
                            .getCdemoMenuOptions()
                            .getCdemoMenuOpt()
                            .getCdemoMenuOptName(
                                    container.getWsVariables().getWsOption() - 1)
                            .split(Pattern.quote(" "))[0])
                    .append("is coming soon ...");
            if (tempStringBuilder1.length() <= 80) {
                tempStringBuilder2.replace(0, tempStringBuilder1.length(),
                        tempStringBuilder1.toString());
                container.getWsVariables().setWsMessage(
                        tempStringBuilder2.toString());
            }
            // [T-Up#INFO][COMEN01C.cbl:220] PERFORM statement
            controlManager.run(context, sendMenuScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
    }

    // *----------------------------------------------------------------*
    // *                      RETURN-TO-SIGNON-SCREEN
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COMEN01C.cbl:226] RETURN-TO-SIGNON-SCREEN Paragraph</p>
     */
    void returnToSignonScreen(OpenFrameContext context) {
    }

    // *     IF CDEMO-TO-PROGRAM = LOW-VALUES OR SPACES
    // *         MOVE 'COSGN00C' TO CDEMO-TO-PROGRAM
    // *     END-IF
    // *     EXEC CICS
    // *         XCTL PROGRAM(CDEMO-TO-PROGRAM)
    // *     END-EXEC.
    // *----------------------------------------------------------------*
    // *                      SEND-MENU-SCREEN
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COMEN01C.cbl:238] SEND-MENU-SCREEN Paragraph</p>
     */
    void sendMenuScreen(OpenFrameContext context) {
        Comen01cVariableContainer container = (Comen01cVariableContainer) context
                .getProgramVariableContainer("Comen01c");
        // [T-Up#INFO][COMEN01C.cbl:240] PERFORM statement
        controlManager.run(context, populateHeaderInfo);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COMEN01C.cbl:241] PERFORM statement
        controlManager.run(context, buildMenuOptions);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COMEN01C.cbl:243] MOVE statement
        container.setErrmsgo(container.getWsVariables().getWsMessage());
        // [T-Up#INFO][COMEN01C.cbl:245] EXEC_CICS statement
        /*
                       EXEC CICS SEND
                                 MAP('COMEN1A')
                                 MAPSET('COMEN01')
                                 FROM(COMEN1AO)
                                 ERASE
                       END-EXEC
         */
        ((Comen01cOutputDto) task.getOutputDto())
                .setPageName("COMEN01_COMEN1A");
        ((Comen01cOutputDto) task.getOutputDto()).setComen1ao(container
                .getComen1ao());
    }

    // *----------------------------------------------------------------*
    // *                      RECEIVE-MENU-SCREEN
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COMEN01C.cbl:255] RECEIVE-MENU-SCREEN Paragraph</p>
     */
    void receiveMenuScreen(OpenFrameContext context) {
        Comen01cVariableContainer container = (Comen01cVariableContainer) context
                .getProgramVariableContainer("Comen01c");
        // [T-Up#INFO][COMEN01C.cbl:257] EXEC_CICS statement
        /*
                       EXEC CICS RECEIVE
                                 MAP('COMEN1A')
                                 MAPSET('COMEN01')
                                 INTO(COMEN1AI)
                                 RESP(WS-RESP-CD)
                                 RESP2(WS-REAS-CD)
                       END-EXEC
         */
        try {
            container.setComen1ai(((Comen01cInputDto) task.getInputDto())
                    .getComen1ai());
        } catch (ConditionException e) {
        } finally {
            container.getWsVariables().setWsRespCd(task.getLastResp());
            container.getWsVariables().setWsReasCd(task.getLastResp2());
        }
    }

    // *----------------------------------------------------------------*
    // *                      POPULATE-HEADER-INFO
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COMEN01C.cbl:268] POPULATE-HEADER-INFO Paragraph</p>
     */
    void populateHeaderInfo(OpenFrameContext context) {
        Comen01cVariableContainer container = (Comen01cVariableContainer) context
                .getProgramVariableContainer("Comen01c");
        // [T-Up#INFO][COMEN01C.cbl:270] MOVE statement
        container.getWsDateTime().getWsCurdateData()
                .set(IntrinsicFunction.functionCurrentDate());
        // [T-Up#INFO][COMEN01C.cbl:272] MOVE statement
        container.setTitle01o(container.getCcdaScreenTitle().getCcdaTitle01());
        // [T-Up#INFO][COMEN01C.cbl:273] MOVE statement
        container.setTitle02o(container.getCcdaScreenTitle().getCcdaTitle02());
        // [T-Up#INFO][COMEN01C.cbl:274] MOVE statement
        container.setTrnnameo(container.getWsVariables().getWsTranid());
        // [T-Up#INFO][COMEN01C.cbl:275] MOVE statement
        container.setPgmnameo(container.getWsVariables().getWsPgmname());
        // [T-Up#INFO][COMEN01C.cbl:277] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateMm(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurdate().getWsCurdateMonth());
        // [T-Up#INFO][COMEN01C.cbl:278] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateDd(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurdate().getWsCurdateDay());
        // [T-Up#INFO][COMEN01C.cbl:279] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateYy(
                        Integer.parseInt(CobStream
                                .convZonedIntToString(
                                        container.getWsDateTime()
                                                .getWsCurdateData()
                                                .getWsCurdate()
                                                .getWsCurdateYear(), 4)
                                .substring(2, 4).trim()));
        // [T-Up#INFO][COMEN01C.cbl:281] MOVE statement
        container.setCurdateo(container.getWsDateTime().getWsCurdateMmDdYy()
                .get());
        // [T-Up#INFO][COMEN01C.cbl:283] MOVE statement
        container
                .getWsDateTime()
                .getWsCurtimeHhMmSs()
                .setWsCurtimeHh(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurtime().getWsCurtimeHours());
        // [T-Up#INFO][COMEN01C.cbl:284] MOVE statement
        container
                .getWsDateTime()
                .getWsCurtimeHhMmSs()
                .setWsCurtimeMm(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurtime().getWsCurtimeMinute());
        // [T-Up#INFO][COMEN01C.cbl:285] MOVE statement
        container
                .getWsDateTime()
                .getWsCurtimeHhMmSs()
                .setWsCurtimeSs(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurtime().getWsCurtimeSecond());
        // [T-Up#INFO][COMEN01C.cbl:287] MOVE statement
        container.setCurtimeo(container.getWsDateTime().getWsCurtimeHhMmSs()
                .get());
    }

    // *----------------------------------------------------------------*
    // *                      BUILD-MENU-OPTIONS
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COMEN01C.cbl:292] BUILD-MENU-OPTIONS Paragraph</p>
     */
    void buildMenuOptions(OpenFrameContext context) {
        StringBuilder tempStringBuilder1;
        StringBuilder tempStringBuilder2;
        Comen01cVariableContainer container = (Comen01cVariableContainer) context
                .getProgramVariableContainer("Comen01c");
        // [T-Up#INFO][COMEN01C.cbl:294] PERFORM statement
        container.getWsVariables().setWsIdx(1);
        while (!(container.getWsVariables().getWsIdx() > container
                .getCarddemoMainMenuOptions().getCdemoMenuOptCount())) {
            // [T-Up#INFO][COMEN01C.cbl:297] MOVE statement
            container.getWsVariables().setWsMenuOptTxt(
                    StringUtils.repeat(' ', 40));
            // [T-Up#INFO][COMEN01C.cbl:299] STRING statement
            tempStringBuilder1 = new StringBuilder();
            tempStringBuilder2 = new StringBuilder(container.getWsVariables()
                    .getWsMenuOptTxt());
            tempStringBuilder1
                    .append(container
                            .getCarddemoMainMenuOptions()
                            .getCdemoMenuOptions()
                            .getCdemoMenuOpt()
                            .getCdemoMenuOptNum(
                                    container.getWsVariables().getWsIdx() - 1))
                    .append(". ")
                    .append(container
                            .getCarddemoMainMenuOptions()
                            .getCdemoMenuOptions()
                            .getCdemoMenuOpt()
                            .getCdemoMenuOptName(
                                    container.getWsVariables().getWsIdx() - 1));
            if (tempStringBuilder1.length() <= 40) {
                tempStringBuilder2.replace(0, tempStringBuilder1.length(),
                        tempStringBuilder1.toString());
                container.getWsVariables().setWsMenuOptTxt(
                        tempStringBuilder2.toString());
            }
            // [T-Up#INFO][COMEN01C.cbl:304] EVALUATE statement
            switch (container.getWsVariables().getWsIdx()) {
            case 1: {
                // [T-Up#INFO][COMEN01C.cbl:306] MOVE statement
                container.setOptn001o(container.getWsVariables()
                        .getWsMenuOptTxt());
                break;
            }
            case 2: {
                // [T-Up#INFO][COMEN01C.cbl:308] MOVE statement
                container.setOptn002o(container.getWsVariables()
                        .getWsMenuOptTxt());
                break;
            }
            case 3: {
                // [T-Up#INFO][COMEN01C.cbl:310] MOVE statement
                container.setOptn003o(container.getWsVariables()
                        .getWsMenuOptTxt());
                break;
            }
            case 4: {
                // [T-Up#INFO][COMEN01C.cbl:312] MOVE statement
                container.setOptn004o(container.getWsVariables()
                        .getWsMenuOptTxt());
                break;
            }
            case 5: {
                // [T-Up#INFO][COMEN01C.cbl:314] MOVE statement
                container.setOptn005o(container.getWsVariables()
                        .getWsMenuOptTxt());
                break;
            }
            case 6: {
                // [T-Up#INFO][COMEN01C.cbl:316] MOVE statement
                container.setOptn006o(container.getWsVariables()
                        .getWsMenuOptTxt());
                break;
            }
            case 7: {
                // [T-Up#INFO][COMEN01C.cbl:318] MOVE statement
                container.setOptn007o(container.getWsVariables()
                        .getWsMenuOptTxt());
                break;
            }
            case 8: {
                // [T-Up#INFO][COMEN01C.cbl:320] MOVE statement
                container.setOptn008o(container.getWsVariables()
                        .getWsMenuOptTxt());
                break;
            }
            case 9: {
                // [T-Up#INFO][COMEN01C.cbl:322] MOVE statement
                container.setOptn009o(container.getWsVariables()
                        .getWsMenuOptTxt());
                break;
            }
            case 10: {
                // [T-Up#INFO][COMEN01C.cbl:324] MOVE statement
                container.setOptn010o(container.getWsVariables()
                        .getWsMenuOptTxt());
                break;
            }
            case 11: {
                // [T-Up#INFO][COMEN01C.cbl:326] MOVE statement
                container.setOptn011o(container.getWsVariables()
                        .getWsMenuOptTxt());
                break;
            }
            case 12: {
                // [T-Up#INFO][COMEN01C.cbl:328] MOVE statement
                container.setOptn012o(container.getWsVariables()
                        .getWsMenuOptTxt());
                break;
            }
            default: {
                // [T-Up#INFO][COMEN01C.cbl:330] CONTINUE statement
                break;
            }
            }
            container.getWsVariables().setWsIdx(
                    container.getWsVariables().getWsIdx() + 1);
        }
    }

    // *
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:12:33 CDT
    // *
}
