package com.tmax.openframe;

import com.tmax.openframe.online.task.service.ProgramControl;
import com.tmax.openframe.dto.Cosgn00cInputDto;
import com.tmax.openframe.mapper.Cotrn00cMapperInterface.*;
import com.tmax.openframe.dto.Comen01cInputDto;
import com.tmax.openframe.online.task.service.OtherUserTaskInvoker;
import com.tmax.openframe.online.task.domain.dto.TaskDto.*;
import com.tmax.openframe.online.task.domain.dto.Data;
import com.tmax.openframe.dto.Cotrn01cInputDto;
import com.tmax.openframe.online.task.service.Task;
import com.tmax.openframe.dto.Cotrn00cOutputDto;
import com.tmax.openframe.dto.Cotrn00cInputDto;
import com.tmax.openframe.online.exception.ConditionException;
import com.tmax.openframe.dao.AwsM2CarddemoTransactVsamKsdsDao;
import com.tmax.openframe.dto.AwsM2CarddemoTransactVsamKsdsDto;
import com.tmax.openframe.online.daoexecutor.service.ReadPointManager;
import com.tmax.openframe.online.daoexecutor.domain.dto.ReadPoint;
import com.tmax.openframe.online.daoexecutor.service.ReadPointAccessor;
import static com.tmax.openframe.variable.group.Cotrn00cCarddemoCommarea.Cotrn00cCdemoCt00Info.*;
import static com.tmax.openframe.variable.group.Cotrn00cCarddemoCommarea.Cotrn00cCdemoGeneralInfo.*;
import static com.tmax.openframe.variable.group.Cotrn00cWsVariables.*;
import com.tmax.openframe.runtime.cobol.CobStream;
import com.tmax.openframe.runtime.cobol.CobStringUtils;
import com.tmax.openframe.runtime.cobol.IntrinsicFunction;
import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.flow.ControlManager;
import com.tmax.openframe.variable.Cotrn00cVariableContainer;
import com.tmax.openframe.variable.group.Cotrn0ai;
import java.math.*;
import java.util.*;
import java.util.function.Consumer;
import lombok.*;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:18 KST</p>
 * <hr>
 * <p>Java class for defining logics of COBOL program</p>
 * <ul>
 * <li>The name of COBOL program: COTRN00C.cbl</li>
 * <li>Variable container class: {@link Cotrn00cVariableContainer}</li>
 * </ul>
 */
@Service
@RequiredArgsConstructor
@Transactional
@Primary
public class Cotrn00c {
    /** 
     * <p>Class that manages an execution flow of the program</p>
     */
    protected final ControlManager controlManager;
    Consumer<OpenFrameContext> mainPara = this::mainPara;
    Consumer<OpenFrameContext> processEnterKey = this::processEnterKey;
    Consumer<OpenFrameContext> processPf7Key = this::processPf7Key;
    Consumer<OpenFrameContext> processPf8Key = this::processPf8Key;
    Consumer<OpenFrameContext> processPageForward = this::processPageForward;
    Consumer<OpenFrameContext> processPageBackward = this::processPageBackward;
    Consumer<OpenFrameContext> populateTranData = this::populateTranData;
    Consumer<OpenFrameContext> initializeTranData = this::initializeTranData;
    Consumer<OpenFrameContext> returnToPrevScreen = this::returnToPrevScreen;
    Consumer<OpenFrameContext> sendTrnlstScreen = this::sendTrnlstScreen;
    Consumer<OpenFrameContext> receiveTrnlstScreen = this::receiveTrnlstScreen;
    Consumer<OpenFrameContext> populateHeaderInfo = this::populateHeaderInfo;
    Consumer<OpenFrameContext> startbrTransactFile = this::startbrTransactFile;
    Consumer<OpenFrameContext> readnextTransactFile = this::readnextTransactFile;
    Consumer<OpenFrameContext> readprevTransactFile = this::readprevTransactFile;
    Consumer<OpenFrameContext> endbrTransactFile = this::endbrTransactFile;
    /** 
     * <p>Execution flow of COBOL program that defined in the procedure division</p>
     */
    ArrayList<Consumer> methodList = new ArrayList<>();
    {
        methodList.add(mainPara);
        methodList.add(processEnterKey);
        methodList.add(processPf7Key);
        methodList.add(processPf8Key);
        methodList.add(processPageForward);
        methodList.add(processPageBackward);
        methodList.add(populateTranData);
        methodList.add(initializeTranData);
        methodList.add(returnToPrevScreen);
        methodList.add(sendTrnlstScreen);
        methodList.add(receiveTrnlstScreen);
        methodList.add(populateHeaderInfo);
        methodList.add(startbrTransactFile);
        methodList.add(readnextTransactFile);
        methodList.add(readprevTransactFile);
        methodList.add(endbrTransactFile);
    }
    private final ReadPointAccessor readPointAccessor;
    private final ReadPointManager readPointManager;
    private final Task task;
    private final TaskInvoker taskInvoker;
    private final ProgramControl programControl;

    /** 
     * <p>Method for executing a program logic that defined in the procedure division</p>
     * @param generalContext context that is necessary for executing program
     * @return return value of program
     */
    public int run(Map<String, Object> generalContext) {
        OpenFrameContext context = new OpenFrameContext(generalContext,
                methodList);
        if (context.getProgramVariableContainer("Cotrn00c") == null) {
            Cotrn00cVariableContainer container = new Cotrn00cVariableContainer();
            context.setProgramVariableContainer("Cotrn00c", container);
        }
        controlManager.run(context);
        return context.getReturnValue();
    }

    // ******************************************************************
    // * Program     : COTRN00C.CBL
    // * Application : CardDemo
    // * Type        : CICS COBOL Program
    // * Function    : List Transactions from TRANSACT file
    // ******************************************************************
    // * Copyright Amazon.com, Inc. or its affiliates.
    // * All Rights Reserved.
    // *
    // * Licensed under the Apache License, Version 2.0 (the "License").
    // * You may not use this file except in compliance with the License.
    // * You may obtain a copy of the License at
    // *
    // *    http://www.apache.org/licenses/LICENSE-2.0
    // *
    // * Unless required by applicable law or agreed to in writing,
    // * software distributed under the License is distributed on an
    // * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
    // * either express or implied. See the License for the specific
    // * language governing permissions and limitations under the License
    // ******************************************************************
    // *      OCCURS 1 TO 32767 TIMES DEPENDING ON EIBCALEN.
    // *----------------------------------------------------------------*
    // *                       PROCEDURE DIVISION
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:95] MAIN-PARA Paragraph</p>
     */
    void mainPara(OpenFrameContext context) {
        Cotrn00cVariableContainer container = (Cotrn00cVariableContainer) context
                .getProgramVariableContainer("Cotrn00c");
        // [T-Up#INFO][COTRN00C.cbl:97] SET statement
        container.getWsVariables().setWsErrFlg(ERR_FLG_OFF);
        // [T-Up#INFO][COTRN00C.cbl:98] SET statement
        container.getWsVariables().setWsTransactEof(TRANSACT_NOT_EOF);
        // [T-Up#INFO][COTRN00C.cbl:99] SET statement
        container.getCarddemoCommarea().getCdemoCt00Info()
                .setCdemoCt00NextPageFlg(NEXT_PAGE_NO);
        // [T-Up#INFO][COTRN00C.cbl:100] SET statement
        container.getWsVariables().setWsSendEraseFlg(SEND_ERASE_YES);
        // [T-Up#INFO][COTRN00C.cbl:102] MOVE statement
        container.getWsVariables().setWsMessage(StringUtils.repeat(' ', 80));
        container.setErrmsgo(StringUtils.repeat(' ', 78));
        // [T-Up#INFO][COTRN00C.cbl:105] MOVE statement
        container.getCotrn0ai().setTrnidinl(-1);
        // [T-Up#INFO][COTRN00C.cbl:107] IF statement
        if (task.hasCommarea() == 0) {
            // [T-Up#INFO][COTRN00C.cbl:108] MOVE statement
            container.getCarddemoCommarea().getCdemoGeneralInfo()
                    .setCdemoToProgram("COSGN00C");
            // [T-Up#INFO][COTRN00C.cbl:109] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoGeneralInfo()
                    .setCdemoFromTranid(
                            container.getWsVariables().getWsTranid());
            // [T-Up#INFO][COTRN00C.cbl:110] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoGeneralInfo()
                    .setCdemoFromProgram(
                            container.getWsVariables().getWsPgmname());
            // [T-Up#INFO][COTRN00C.cbl:111] MOVE statement
            container.getCarddemoCommarea().getCdemoGeneralInfo()
                    .setCdemoPgmContext(0);
            // [T-Up#INFO][COTRN00C.cbl:112] EXEC_CICS statement
            /*
                               EXEC CICS
                               XCTL PROGRAM('COSGN00C')
                               COMMAREA(CARDDEMO-COMMAREA)
                               END-EXEC
             */
            Cosgn00cInputDto cosgn00cInputDto = new Cosgn00cInputDto();
            cosgn00cInputDto
                    .setDfhcommarea(Cotrn00cCarddemoCommareaToCosgn00cDfhcommarea.INSTANCE
                            .toTarget(container.getCarddemoCommarea()));
            programControl.forward("CC00", cosgn00cInputDto);
            context.setReturnFlag(true);
            // [T-Up#INFO][COTRN00C.cbl:116] PERFORM statement
            controlManager.run(context, returnToPrevScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        } else {
            // [T-Up#INFO][COTRN00C.cbl:118] MOVE statement
            container.getCarddemoCommarea().set(
                    StringUtils.overlay(container.getCarddemoCommarea().get(),
                            container.getDfhcommarea().get().substring(0, 218),
                            0, 218));
            // [T-Up#INFO][COTRN00C.cbl:119] IF statement
            if (!(container.getCarddemoCommarea().getCdemoGeneralInfo()
                    .getCdemoPgmContext() == CDEMO_PGM_REENTER)) {
                // [T-Up#INFO][COTRN00C.cbl:120] SET statement
                container.getCarddemoCommarea().getCdemoGeneralInfo()
                        .setCdemoPgmContext(CDEMO_PGM_REENTER);
                // [T-Up#INFO][COTRN00C.cbl:121] MOVE statement
                container.setCotrn0ao(Cotrn0ai.createDefaultValueInstance()
                        .get());
                // [T-Up#INFO][COTRN00C.cbl:122] PERFORM statement
                controlManager.run(context, processEnterKey);
                if (controlManager.isTerminate(context)) {
                    return;
                }
                // [T-Up#INFO][COTRN00C.cbl:123] PERFORM statement
                controlManager.run(context, sendTrnlstScreen);
                if (controlManager.isTerminate(context)) {
                    return;
                }
            } else {
                // [T-Up#INFO][COTRN00C.cbl:125] PERFORM statement
                controlManager.run(context, receiveTrnlstScreen);
                if (controlManager.isTerminate(context)) {
                    return;
                }
                // [T-Up#INFO][COTRN00C.cbl:126] EVALUATE statement
                if (CobStringUtils.compare(task.getPressedKey(), container
                        .getDfhaid().getDfhenter()) == 0) {
                    // [T-Up#INFO][COTRN00C.cbl:128] PERFORM statement
                    controlManager.run(context, processEnterKey);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                } else if (CobStringUtils.compare(task.getPressedKey(),
                        container.getDfhaid().getDfhpf3()) == 0) {
                    // [T-Up#INFO][COTRN00C.cbl:130] MOVE statement
                    container.getCarddemoCommarea().getCdemoGeneralInfo()
                            .setCdemoToProgram("COMEN01C");
                    // [T-Up#INFO][COTRN00C.cbl:131] MOVE statement
                    container
                            .getCarddemoCommarea()
                            .getCdemoGeneralInfo()
                            .setCdemoFromTranid(
                                    container.getWsVariables().getWsTranid());
                    // [T-Up#INFO][COTRN00C.cbl:132] MOVE statement
                    container
                            .getCarddemoCommarea()
                            .getCdemoGeneralInfo()
                            .setCdemoFromProgram(
                                    container.getWsVariables().getWsPgmname());
                    // [T-Up#INFO][COTRN00C.cbl:133] MOVE statement
                    container.getCarddemoCommarea().getCdemoGeneralInfo()
                            .setCdemoPgmContext(0);
                    // [T-Up#INFO][COTRN00C.cbl:134] EXEC_CICS statement
                    /*
                                                   EXEC CICS
                                                   XCTL PROGRAM('COMEN01C')
                                                   COMMAREA(CARDDEMO-COMMAREA)
                                                   END-EXEC
                     */
                    Comen01cInputDto comen01cInputDto = new Comen01cInputDto();
                    comen01cInputDto
                            .setDfhcommarea(Cotrn00cCarddemoCommareaToComen01cDfhcommarea.INSTANCE
                                    .toTarget(container.getCarddemoCommarea()));
                    programControl.forward("CM00", comen01cInputDto);
                    context.setReturnFlag(true);
                    // [T-Up#INFO][COTRN00C.cbl:138] PERFORM statement
                    controlManager.run(context, returnToPrevScreen);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                } else if (CobStringUtils.compare(task.getPressedKey(),
                        container.getDfhaid().getDfhpf7()) == 0) {
                    // [T-Up#INFO][COTRN00C.cbl:140] PERFORM statement
                    controlManager.run(context, processPf7Key);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                } else if (CobStringUtils.compare(task.getPressedKey(),
                        container.getDfhaid().getDfhpf8()) == 0) {
                    // [T-Up#INFO][COTRN00C.cbl:142] PERFORM statement
                    controlManager.run(context, processPf8Key);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                } else {
                    // [T-Up#INFO][COTRN00C.cbl:144] MOVE statement
                    container.getWsVariables().setWsErrFlg("Y");
                    // [T-Up#INFO][COTRN00C.cbl:145] MOVE statement
                    container.getCotrn0ai().setTrnidinl(-1);
                    // [T-Up#INFO][COTRN00C.cbl:146] MOVE statement
                    container.getWsVariables().setWsMessage(
                            container.getCcdaCommonMessages()
                                    .getCcdaMsgInvalidKey());
                    // [T-Up#INFO][COTRN00C.cbl:147] PERFORM statement
                    controlManager.run(context, sendTrnlstScreen);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                }
            }
        }
        // [T-Up#INFO][COTRN00C.cbl:152] EXEC_CICS statement
        /*
                       EXEC CICS RETURN
                                 TRANSID (WS-TRANID)
                                 COMMAREA (CARDDEMO-COMMAREA)
                       END-EXEC
         */
        TaskDto taskDto = TaskDto
                .builder()
                .destination("CT00")
                .data(Data
                        .session(Cotrn00cCarddemoCommareaToCotrn00cDfhcommarea.INSTANCE
                                .toTarget(container.getCarddemoCommarea())))
                .build();
        taskInvoker.setNextTask(taskDto);
        context.setReturnFlag(true);
    }

    // *----------------------------------------------------------------*
    // *                      PROCESS-ENTER-KEY
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:160] PROCESS-ENTER-KEY Paragraph</p>
     */
    void processEnterKey(OpenFrameContext context) {
        Cotrn00cVariableContainer container = (Cotrn00cVariableContainer) context
                .getProgramVariableContainer("Cotrn00c");
        // [T-Up#INFO][COTRN00C.cbl:162] EVALUATE statement
        if (CobStringUtils.compare(container.getCotrn0ai().getSel0001i(), " ") != 0
                && CobStringUtils.compare(
                        container.getCotrn0ai().getSel0001i(),
                        StringUtils.repeat((char) 0x00, 1)) != 0) {
            // [T-Up#INFO][COTRN00C.cbl:164] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelFlg(
                            container.getCotrn0ai().getSel0001i());
            // [T-Up#INFO][COTRN00C.cbl:165] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelected(
                            container.getCotrn0ai().getTrnid01i());
        } else if (CobStringUtils.compare(
                container.getCotrn0ai().getSel0002i(), " ") != 0
                && CobStringUtils.compare(
                        container.getCotrn0ai().getSel0002i(),
                        StringUtils.repeat((char) 0x00, 1)) != 0) {
            // [T-Up#INFO][COTRN00C.cbl:167] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelFlg(
                            container.getCotrn0ai().getSel0002i());
            // [T-Up#INFO][COTRN00C.cbl:168] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelected(
                            container.getCotrn0ai().getTrnid02i());
        } else if (CobStringUtils.compare(
                container.getCotrn0ai().getSel0003i(), " ") != 0
                && CobStringUtils.compare(
                        container.getCotrn0ai().getSel0003i(),
                        StringUtils.repeat((char) 0x00, 1)) != 0) {
            // [T-Up#INFO][COTRN00C.cbl:170] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelFlg(
                            container.getCotrn0ai().getSel0003i());
            // [T-Up#INFO][COTRN00C.cbl:171] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelected(
                            container.getCotrn0ai().getTrnid03i());
        } else if (CobStringUtils.compare(
                container.getCotrn0ai().getSel0004i(), " ") != 0
                && CobStringUtils.compare(
                        container.getCotrn0ai().getSel0004i(),
                        StringUtils.repeat((char) 0x00, 1)) != 0) {
            // [T-Up#INFO][COTRN00C.cbl:173] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelFlg(
                            container.getCotrn0ai().getSel0004i());
            // [T-Up#INFO][COTRN00C.cbl:174] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelected(
                            container.getCotrn0ai().getTrnid04i());
        } else if (CobStringUtils.compare(
                container.getCotrn0ai().getSel0005i(), " ") != 0
                && CobStringUtils.compare(
                        container.getCotrn0ai().getSel0005i(),
                        StringUtils.repeat((char) 0x00, 1)) != 0) {
            // [T-Up#INFO][COTRN00C.cbl:176] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelFlg(
                            container.getCotrn0ai().getSel0005i());
            // [T-Up#INFO][COTRN00C.cbl:177] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelected(
                            container.getCotrn0ai().getTrnid05i());
        } else if (CobStringUtils.compare(
                container.getCotrn0ai().getSel0006i(), " ") != 0
                && CobStringUtils.compare(
                        container.getCotrn0ai().getSel0006i(),
                        StringUtils.repeat((char) 0x00, 1)) != 0) {
            // [T-Up#INFO][COTRN00C.cbl:179] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelFlg(
                            container.getCotrn0ai().getSel0006i());
            // [T-Up#INFO][COTRN00C.cbl:180] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelected(
                            container.getCotrn0ai().getTrnid06i());
        } else if (CobStringUtils.compare(
                container.getCotrn0ai().getSel0007i(), " ") != 0
                && CobStringUtils.compare(
                        container.getCotrn0ai().getSel0007i(),
                        StringUtils.repeat((char) 0x00, 1)) != 0) {
            // [T-Up#INFO][COTRN00C.cbl:182] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelFlg(
                            container.getCotrn0ai().getSel0007i());
            // [T-Up#INFO][COTRN00C.cbl:183] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelected(
                            container.getCotrn0ai().getTrnid07i());
        } else if (CobStringUtils.compare(
                container.getCotrn0ai().getSel0008i(), " ") != 0
                && CobStringUtils.compare(
                        container.getCotrn0ai().getSel0008i(),
                        StringUtils.repeat((char) 0x00, 1)) != 0) {
            // [T-Up#INFO][COTRN00C.cbl:185] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelFlg(
                            container.getCotrn0ai().getSel0008i());
            // [T-Up#INFO][COTRN00C.cbl:186] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelected(
                            container.getCotrn0ai().getTrnid08i());
        } else if (CobStringUtils.compare(
                container.getCotrn0ai().getSel0009i(), " ") != 0
                && CobStringUtils.compare(
                        container.getCotrn0ai().getSel0009i(),
                        StringUtils.repeat((char) 0x00, 1)) != 0) {
            // [T-Up#INFO][COTRN00C.cbl:188] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelFlg(
                            container.getCotrn0ai().getSel0009i());
            // [T-Up#INFO][COTRN00C.cbl:189] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelected(
                            container.getCotrn0ai().getTrnid09i());
        } else if (CobStringUtils.compare(
                container.getCotrn0ai().getSel0010i(), " ") != 0
                && CobStringUtils.compare(
                        container.getCotrn0ai().getSel0010i(),
                        StringUtils.repeat((char) 0x00, 1)) != 0) {
            // [T-Up#INFO][COTRN00C.cbl:191] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelFlg(
                            container.getCotrn0ai().getSel0010i());
            // [T-Up#INFO][COTRN00C.cbl:192] MOVE statement
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnSelected(
                            container.getCotrn0ai().getTrnid10i());
        } else {
            // [T-Up#INFO][COTRN00C.cbl:194] MOVE statement
            container.getCarddemoCommarea().getCdemoCt00Info()
                    .setCdemoCt00TrnSelFlg(" ");
            // [T-Up#INFO][COTRN00C.cbl:195] MOVE statement
            container.getCarddemoCommarea().getCdemoCt00Info()
                    .setCdemoCt00TrnSelected(StringUtils.repeat(' ', 16));
        }
        // [T-Up#INFO][COTRN00C.cbl:197] IF statement
        if (CobStringUtils.compare(container.getCarddemoCommarea()
                .getCdemoCt00Info().getCdemoCt00TrnSelFlg(), " ") != 0
                && CobStringUtils.compare(container.getCarddemoCommarea()
                        .getCdemoCt00Info().getCdemoCt00TrnSelFlg(),
                        StringUtils.repeat((char) 0x00, 1)) != 0
                && CobStringUtils.compare(container.getCarddemoCommarea()
                        .getCdemoCt00Info().getCdemoCt00TrnSelected(),
                        StringUtils.repeat(' ', 16)) != 0
                && CobStringUtils.compare(container.getCarddemoCommarea()
                        .getCdemoCt00Info().getCdemoCt00TrnSelected(),
                        StringUtils.repeat((char) 0x00, 16)) != 0) {
            // [T-Up#INFO][COTRN00C.cbl:199] EVALUATE statement
            switch (container.getCarddemoCommarea().getCdemoCt00Info()
                    .getCdemoCt00TrnSelFlg()) {
            case "S":
            case "s": {
                // [T-Up#INFO][COTRN00C.cbl:202] MOVE statement
                container.getCarddemoCommarea().getCdemoGeneralInfo()
                        .setCdemoToProgram("COTRN01C");
                // [T-Up#INFO][COTRN00C.cbl:203] MOVE statement
                container
                        .getCarddemoCommarea()
                        .getCdemoGeneralInfo()
                        .setCdemoFromTranid(
                                container.getWsVariables().getWsTranid());
                // [T-Up#INFO][COTRN00C.cbl:204] MOVE statement
                container
                        .getCarddemoCommarea()
                        .getCdemoGeneralInfo()
                        .setCdemoFromProgram(
                                container.getWsVariables().getWsPgmname());
                // [T-Up#INFO][COTRN00C.cbl:205] MOVE statement
                container.getCarddemoCommarea().getCdemoGeneralInfo()
                        .setCdemoPgmContext(0);
                // [T-Up#INFO][COTRN00C.cbl:206] EXEC_CICS statement
                /*
                                            EXEC CICS
                                                XCTL PROGRAM('COTRN01C')
                                                COMMAREA(CARDDEMO-COMMAREA)
                                            END-EXEC
                 */
                Cotrn01cInputDto cotrn01cInputDto = new Cotrn01cInputDto();
                cotrn01cInputDto
                        .setDfhcommarea(Cotrn00cCarddemoCommareaToCotrn01cDfhcommarea.INSTANCE
                                .toTarget(container.getCarddemoCommarea()));
                programControl.forward("CT01", cotrn01cInputDto);
                context.setReturnFlag(true);
                break;
            }
            default: {
                // *                SET TRANSACT-EOF TO TRUE
                // [T-Up#INFO][COTRN00C.cbl:212] MOVE statement
                container.getWsVariables().setWsMessage(
                        "Invalid selection. Valid value is S");
                // [T-Up#INFO][COTRN00C.cbl:215] MOVE statement
                container.getCotrn0ai().setTrnidinl(-1);
                break;
            }
            }
        }
        // *                PERFORM SEND-TRNLST-SCREEN
        // [T-Up#INFO][COTRN00C.cbl:220] IF statement
        if (CobStringUtils.compare(container.getCotrn0ai().getTrnidini(),
                StringUtils.repeat(' ', 16)) == 0
                || CobStringUtils.compare(
                        container.getCotrn0ai().getTrnidini(),
                        StringUtils.repeat((char) 0x00, 16)) == 0) {
            // [T-Up#INFO][COTRN00C.cbl:221] MOVE statement
            container.getTranRecord().setTranId(
                    StringUtils.repeat((char) 0x00, 16));
        } else {
            // [T-Up#INFO][COTRN00C.cbl:223] IF statement
            if (StringUtils.isNumeric(container.getCotrn0ai().getTrnidini())) {
                // [T-Up#INFO][COTRN00C.cbl:224] MOVE statement
                container.getTranRecord().setTranId(
                        container.getCotrn0ai().getTrnidini());
            } else {
                // [T-Up#INFO][COTRN00C.cbl:226] MOVE statement
                container.getWsVariables().setWsErrFlg("Y");
                // [T-Up#INFO][COTRN00C.cbl:227] MOVE statement
                container.getWsVariables().setWsMessage(
                        "Tran ID must be Numeric ...");
                // [T-Up#INFO][COTRN00C.cbl:230] MOVE statement
                container.getCotrn0ai().setTrnidinl(-1);
                // [T-Up#INFO][COTRN00C.cbl:231] PERFORM statement
                controlManager.run(context, sendTrnlstScreen);
                if (controlManager.isTerminate(context)) {
                    return;
                }
            }
        }
        // [T-Up#INFO][COTRN00C.cbl:235] MOVE statement
        container.getCotrn0ai().setTrnidinl(-1);
        // [T-Up#INFO][COTRN00C.cbl:238] MOVE statement
        container.getCarddemoCommarea().getCdemoCt00Info()
                .setCdemoCt00PageNum(0);
        // [T-Up#INFO][COTRN00C.cbl:239] PERFORM statement
        controlManager.run(context, processPageForward);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COTRN00C.cbl:241] IF statement
        if (!(CobStringUtils.compare(container.getWsVariables().getWsErrFlg(),
                ERR_FLG_ON) == 0)) {
            // [T-Up#INFO][COTRN00C.cbl:242] MOVE statement
            container.setTrnidino(StringUtils.repeat(' ', 16));
        }
    }

    // *----------------------------------------------------------------*
    // *                      PROCESS-PF7-KEY
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:248] PROCESS-PF7-KEY Paragraph</p>
     */
    void processPf7Key(OpenFrameContext context) {
        Cotrn00cVariableContainer container = (Cotrn00cVariableContainer) context
                .getProgramVariableContainer("Cotrn00c");
        // [T-Up#INFO][COTRN00C.cbl:250] IF statement
        if (CobStringUtils.compare(container.getCarddemoCommarea()
                .getCdemoCt00Info().getCdemoCt00TrnidFirst(),
                StringUtils.repeat(' ', 16)) == 0
                || CobStringUtils.compare(container.getCarddemoCommarea()
                        .getCdemoCt00Info().getCdemoCt00TrnidFirst(),
                        StringUtils.repeat((char) 0x00, 16)) == 0) {
            // [T-Up#INFO][COTRN00C.cbl:251] MOVE statement
            container.getTranRecord().setTranId(
                    StringUtils.repeat((char) 0x00, 16));
        } else {
            // [T-Up#INFO][COTRN00C.cbl:253] MOVE statement
            container.getTranRecord().setTranId(
                    container.getCarddemoCommarea().getCdemoCt00Info()
                            .getCdemoCt00TrnidFirst());
        }
        // [T-Up#INFO][COTRN00C.cbl:256] SET statement
        container.getCarddemoCommarea().getCdemoCt00Info()
                .setCdemoCt00NextPageFlg(NEXT_PAGE_YES);
        // [T-Up#INFO][COTRN00C.cbl:257] MOVE statement
        container.getCotrn0ai().setTrnidinl(-1);
        // [T-Up#INFO][COTRN00C.cbl:259] IF statement
        if (container.getCarddemoCommarea().getCdemoCt00Info()
                .getCdemoCt00PageNum() > 1) {
            // [T-Up#INFO][COTRN00C.cbl:260] PERFORM statement
            controlManager.run(context, processPageBackward);
            if (controlManager.isTerminate(context)) {
                return;
            }
        } else {
            // [T-Up#INFO][COTRN00C.cbl:262] MOVE statement
            container.getWsVariables().setWsMessage(
                    "You are already at the top of the page...");
            // [T-Up#INFO][COTRN00C.cbl:264] SET statement
            container.getWsVariables().setWsSendEraseFlg(SEND_ERASE_NO);
            // [T-Up#INFO][COTRN00C.cbl:265] PERFORM statement
            controlManager.run(context, sendTrnlstScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
    }

    // *----------------------------------------------------------------*
    // *                      PROCESS-PF8-KEY
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:271] PROCESS-PF8-KEY Paragraph</p>
     */
    void processPf8Key(OpenFrameContext context) {
        Cotrn00cVariableContainer container = (Cotrn00cVariableContainer) context
                .getProgramVariableContainer("Cotrn00c");
        // [T-Up#INFO][COTRN00C.cbl:273] IF statement
        if (CobStringUtils.compare(container.getCarddemoCommarea()
                .getCdemoCt00Info().getCdemoCt00TrnidLast(),
                StringUtils.repeat(' ', 16)) == 0
                || CobStringUtils.compare(container.getCarddemoCommarea()
                        .getCdemoCt00Info().getCdemoCt00TrnidLast(),
                        StringUtils.repeat((char) 0x00, 16)) == 0) {
            // [T-Up#INFO][COTRN00C.cbl:274] MOVE statement
            container.getTranRecord().setTranId(
                    StringUtils.repeat((char) 0xFF, 16));
        } else {
            // [T-Up#INFO][COTRN00C.cbl:276] MOVE statement
            container.getTranRecord().setTranId(
                    container.getCarddemoCommarea().getCdemoCt00Info()
                            .getCdemoCt00TrnidLast());
        }
        // [T-Up#INFO][COTRN00C.cbl:279] MOVE statement
        container.getCotrn0ai().setTrnidinl(-1);
        // [T-Up#INFO][COTRN00C.cbl:281] IF statement
        if (CobStringUtils.compare(container.getCarddemoCommarea()
                .getCdemoCt00Info().getCdemoCt00NextPageFlg(), NEXT_PAGE_YES) == 0) {
            // [T-Up#INFO][COTRN00C.cbl:282] PERFORM statement
            controlManager.run(context, processPageForward);
            if (controlManager.isTerminate(context)) {
                return;
            }
        } else {
            // [T-Up#INFO][COTRN00C.cbl:284] MOVE statement
            container.getWsVariables().setWsMessage(
                    "You are already at the bottom of the page...");
            // [T-Up#INFO][COTRN00C.cbl:286] SET statement
            container.getWsVariables().setWsSendEraseFlg(SEND_ERASE_NO);
            // [T-Up#INFO][COTRN00C.cbl:287] PERFORM statement
            controlManager.run(context, sendTrnlstScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
    }

    // *----------------------------------------------------------------*
    // *                      PROCESS-PAGE-FORWARD
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:293] PROCESS-PAGE-FORWARD Paragraph</p>
     */
    void processPageForward(OpenFrameContext context) {
        Cotrn00cVariableContainer container = (Cotrn00cVariableContainer) context
                .getProgramVariableContainer("Cotrn00c");
        // [T-Up#INFO][COTRN00C.cbl:295] PERFORM statement
        controlManager.run(context, startbrTransactFile);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COTRN00C.cbl:297] IF statement
        if (!(CobStringUtils.compare(container.getWsVariables().getWsErrFlg(),
                ERR_FLG_ON) == 0)) {
            // [T-Up#INFO][COTRN00C.cbl:299] IF statement
            if (CobStringUtils.compare(task.getPressedKey(), container
                    .getDfhaid().getDfhenter()) != 0
                    && CobStringUtils.compare(task.getPressedKey(), container
                            .getDfhaid().getDfhpf7()) != 0
                    && CobStringUtils.compare(task.getPressedKey(), container
                            .getDfhaid().getDfhpf3()) != 0) {
                // [T-Up#INFO][COTRN00C.cbl:300] PERFORM statement
                controlManager.run(context, readnextTransactFile);
                if (controlManager.isTerminate(context)) {
                    return;
                }
            }
            // [T-Up#INFO][COTRN00C.cbl:303] IF statement
            if (CobStringUtils.compare(container.getWsVariables()
                    .getWsTransactEof(), TRANSACT_NOT_EOF) == 0
                    && CobStringUtils.compare(container.getWsVariables()
                            .getWsErrFlg(), ERR_FLG_OFF) == 0) {
                // [T-Up#INFO][COTRN00C.cbl:304] PERFORM statement
                container.getWsVariables().setWsIdx(1);
                while (!(container.getWsVariables().getWsIdx() > 10)) {
                    // [T-Up#INFO][COTRN00C.cbl:305] PERFORM statement
                    controlManager.run(context, initializeTranData);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                    container.getWsVariables().setWsIdx(
                            container.getWsVariables().getWsIdx() + 1);
                }
            }
            // [T-Up#INFO][COTRN00C.cbl:309] MOVE statement
            container.getWsVariables().setWsIdx(1);
            // [T-Up#INFO][COTRN00C.cbl:311] PERFORM statement
            while (!(container.getWsVariables().getWsIdx() >= 11
                    || CobStringUtils.compare(container.getWsVariables()
                            .getWsTransactEof(), TRANSACT_EOF) == 0 || CobStringUtils
                        .compare(container.getWsVariables().getWsErrFlg(),
                                ERR_FLG_ON) == 0)) {
                // [T-Up#INFO][COTRN00C.cbl:312] PERFORM statement
                controlManager.run(context, readnextTransactFile);
                if (controlManager.isTerminate(context)) {
                    return;
                }
                // [T-Up#INFO][COTRN00C.cbl:313] IF statement
                if (CobStringUtils.compare(container.getWsVariables()
                        .getWsTransactEof(), TRANSACT_NOT_EOF) == 0
                        && CobStringUtils.compare(container.getWsVariables()
                                .getWsErrFlg(), ERR_FLG_OFF) == 0) {
                    // [T-Up#INFO][COTRN00C.cbl:314] PERFORM statement
                    controlManager.run(context, populateTranData);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                    // [T-Up#INFO][COTRN00C.cbl:315] COMPUTE statement
                    container.getWsVariables().setWsIdx(
                            container.getWsVariables().getWsIdx() + 1);
                }
            }
            // [T-Up#INFO][COTRN00C.cbl:319] IF statement
            if (CobStringUtils.compare(container.getWsVariables()
                    .getWsTransactEof(), TRANSACT_NOT_EOF) == 0
                    && CobStringUtils.compare(container.getWsVariables()
                            .getWsErrFlg(), ERR_FLG_OFF) == 0) {
                // [T-Up#INFO][COTRN00C.cbl:320] COMPUTE statement
                container
                        .getCarddemoCommarea()
                        .getCdemoCt00Info()
                        .setCdemoCt00PageNum(
                                container.getCarddemoCommarea()
                                        .getCdemoCt00Info()
                                        .getCdemoCt00PageNum() + 1);
                // [T-Up#INFO][COTRN00C.cbl:322] PERFORM statement
                controlManager.run(context, readnextTransactFile);
                if (controlManager.isTerminate(context)) {
                    return;
                }
                // [T-Up#INFO][COTRN00C.cbl:323] IF statement
                if (CobStringUtils.compare(container.getWsVariables()
                        .getWsTransactEof(), TRANSACT_NOT_EOF) == 0
                        && CobStringUtils.compare(container.getWsVariables()
                                .getWsErrFlg(), ERR_FLG_OFF) == 0) {
                    // [T-Up#INFO][COTRN00C.cbl:324] SET statement
                    container.getCarddemoCommarea().getCdemoCt00Info()
                            .setCdemoCt00NextPageFlg(NEXT_PAGE_YES);
                } else {
                    // [T-Up#INFO][COTRN00C.cbl:326] SET statement
                    container.getCarddemoCommarea().getCdemoCt00Info()
                            .setCdemoCt00NextPageFlg(NEXT_PAGE_NO);
                }
            } else {
                // [T-Up#INFO][COTRN00C.cbl:329] SET statement
                container.getCarddemoCommarea().getCdemoCt00Info()
                        .setCdemoCt00NextPageFlg(NEXT_PAGE_NO);
                // [T-Up#INFO][COTRN00C.cbl:330] IF statement
                if (container.getWsVariables().getWsIdx() > 1) {
                    // [T-Up#INFO][COTRN00C.cbl:331] COMPUTE statement
                    container
                            .getCarddemoCommarea()
                            .getCdemoCt00Info()
                            .setCdemoCt00PageNum(
                                    container.getCarddemoCommarea()
                                            .getCdemoCt00Info()
                                            .getCdemoCt00PageNum() + 1);
                }
            }
            // [T-Up#INFO][COTRN00C.cbl:336] PERFORM statement
            controlManager.run(context, endbrTransactFile);
            if (controlManager.isTerminate(context)) {
                return;
            }
            // [T-Up#INFO][COTRN00C.cbl:338] MOVE statement
            container.getCotrn0ai().setPagenumi(
                    StringUtils.leftPad(
                            String.valueOf(Math.abs(container
                                    .getCarddemoCommarea().getCdemoCt00Info()
                                    .getCdemoCt00PageNum())), 8, '0'));
            // [T-Up#INFO][COTRN00C.cbl:339] MOVE statement
            container.setTrnidino(StringUtils.repeat(' ', 16));
            // [T-Up#INFO][COTRN00C.cbl:340] PERFORM statement
            controlManager.run(context, sendTrnlstScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
    }

    // *----------------------------------------------------------------*
    // *                      PROCESS-PAGE-BACKWARD
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:347] PROCESS-PAGE-BACKWARD Paragraph</p>
     */
    void processPageBackward(OpenFrameContext context) {
        Cotrn00cVariableContainer container = (Cotrn00cVariableContainer) context
                .getProgramVariableContainer("Cotrn00c");
        // [T-Up#INFO][COTRN00C.cbl:349] PERFORM statement
        controlManager.run(context, startbrTransactFile);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COTRN00C.cbl:351] IF statement
        if (!(CobStringUtils.compare(container.getWsVariables().getWsErrFlg(),
                ERR_FLG_ON) == 0)) {
            // [T-Up#INFO][COTRN00C.cbl:353] IF statement
            if (CobStringUtils.compare(task.getPressedKey(), container
                    .getDfhaid().getDfhenter()) != 0
                    && CobStringUtils.compare(task.getPressedKey(), container
                            .getDfhaid().getDfhpf8()) != 0) {
                // [T-Up#INFO][COTRN00C.cbl:354] PERFORM statement
                controlManager.run(context, readprevTransactFile);
                if (controlManager.isTerminate(context)) {
                    return;
                }
            }
            // [T-Up#INFO][COTRN00C.cbl:357] IF statement
            if (CobStringUtils.compare(container.getWsVariables()
                    .getWsTransactEof(), TRANSACT_NOT_EOF) == 0
                    && CobStringUtils.compare(container.getWsVariables()
                            .getWsErrFlg(), ERR_FLG_OFF) == 0) {
                // [T-Up#INFO][COTRN00C.cbl:358] PERFORM statement
                container.getWsVariables().setWsIdx(1);
                while (!(container.getWsVariables().getWsIdx() > 10)) {
                    // [T-Up#INFO][COTRN00C.cbl:359] PERFORM statement
                    controlManager.run(context, initializeTranData);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                    container.getWsVariables().setWsIdx(
                            container.getWsVariables().getWsIdx() + 1);
                }
            }
            // [T-Up#INFO][COTRN00C.cbl:363] MOVE statement
            container.getWsVariables().setWsIdx(10);
            // [T-Up#INFO][COTRN00C.cbl:365] PERFORM statement
            while (!(container.getWsVariables().getWsIdx() <= 0
                    || CobStringUtils.compare(container.getWsVariables()
                            .getWsTransactEof(), TRANSACT_EOF) == 0 || CobStringUtils
                        .compare(container.getWsVariables().getWsErrFlg(),
                                ERR_FLG_ON) == 0)) {
                // [T-Up#INFO][COTRN00C.cbl:366] PERFORM statement
                controlManager.run(context, readprevTransactFile);
                if (controlManager.isTerminate(context)) {
                    return;
                }
                // [T-Up#INFO][COTRN00C.cbl:367] IF statement
                if (CobStringUtils.compare(container.getWsVariables()
                        .getWsTransactEof(), TRANSACT_NOT_EOF) == 0
                        && CobStringUtils.compare(container.getWsVariables()
                                .getWsErrFlg(), ERR_FLG_OFF) == 0) {
                    // [T-Up#INFO][COTRN00C.cbl:368] PERFORM statement
                    controlManager.run(context, populateTranData);
                    if (controlManager.isTerminate(context)) {
                        return;
                    }
                    // [T-Up#INFO][COTRN00C.cbl:369] COMPUTE statement
                    container.getWsVariables().setWsIdx(
                            container.getWsVariables().getWsIdx() - 1);
                }
            }
            // [T-Up#INFO][COTRN00C.cbl:373] IF statement
            if (CobStringUtils.compare(container.getWsVariables()
                    .getWsTransactEof(), TRANSACT_NOT_EOF) == 0
                    && CobStringUtils.compare(container.getWsVariables()
                            .getWsErrFlg(), ERR_FLG_OFF) == 0) {
                // [T-Up#INFO][COTRN00C.cbl:374] PERFORM statement
                controlManager.run(context, readprevTransactFile);
                if (controlManager.isTerminate(context)) {
                    return;
                }
                // [T-Up#INFO][COTRN00C.cbl:375] IF statement
                if (CobStringUtils.compare(container.getCarddemoCommarea()
                        .getCdemoCt00Info().getCdemoCt00NextPageFlg(),
                        NEXT_PAGE_YES) == 0) {
                    // [T-Up#INFO][COTRN00C.cbl:376] IF statement
                    if (CobStringUtils.compare(container.getWsVariables()
                            .getWsTransactEof(), TRANSACT_NOT_EOF) == 0
                            && CobStringUtils.compare(container
                                    .getWsVariables().getWsErrFlg(),
                                    ERR_FLG_OFF) == 0
                            && container.getCarddemoCommarea()
                                    .getCdemoCt00Info().getCdemoCt00PageNum() > 1) {
                        // [T-Up#INFO][COTRN00C.cbl:378] SUBTRACT statement
                        container
                                .getCarddemoCommarea()
                                .getCdemoCt00Info()
                                .setCdemoCt00PageNum(
                                        container.getCarddemoCommarea()
                                                .getCdemoCt00Info()
                                                .getCdemoCt00PageNum() - 1);
                    } else {
                        // [T-Up#INFO][COTRN00C.cbl:380] MOVE statement
                        container.getCarddemoCommarea().getCdemoCt00Info()
                                .setCdemoCt00PageNum(1);
                    }
                }
            }
            // [T-Up#INFO][COTRN00C.cbl:385] PERFORM statement
            controlManager.run(context, endbrTransactFile);
            if (controlManager.isTerminate(context)) {
                return;
            }
            // [T-Up#INFO][COTRN00C.cbl:387] MOVE statement
            container.getCotrn0ai().setPagenumi(
                    StringUtils.leftPad(
                            String.valueOf(Math.abs(container
                                    .getCarddemoCommarea().getCdemoCt00Info()
                                    .getCdemoCt00PageNum())), 8, '0'));
            // [T-Up#INFO][COTRN00C.cbl:388] PERFORM statement
            controlManager.run(context, sendTrnlstScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
    }

    // *----------------------------------------------------------------*
    // *                      POPULATE-TRAN-DATA
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:395] POPULATE-TRAN-DATA Paragraph</p>
     */
    void populateTranData(OpenFrameContext context) {
        Cotrn00cVariableContainer container = (Cotrn00cVariableContainer) context
                .getProgramVariableContainer("Cotrn00c");
        // [T-Up#INFO][COTRN00C.cbl:397] MOVE statement
        container.getWsVariables().setWsTranAmt(
                container.getTranRecord().getTranAmt());
        // [T-Up#INFO][COTRN00C.cbl:398] MOVE statement
        container.getWsDateTime().getWsTimestamp()
                .set(container.getTranRecord().getTranOrigTs());
        // [T-Up#INFO][COTRN00C.cbl:399] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateYy(
                        Integer.parseInt(CobStream
                                .convZonedIntToString(
                                        container.getWsDateTime()
                                                .getWsTimestamp()
                                                .getWsTimestampDtYyyy(), 4)
                                .substring(2, 4).trim()));
        // [T-Up#INFO][COTRN00C.cbl:400] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateMm(
                        container.getWsDateTime().getWsTimestamp()
                                .getWsTimestampDtMm());
        // [T-Up#INFO][COTRN00C.cbl:401] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateDd(
                        container.getWsDateTime().getWsTimestamp()
                                .getWsTimestampDtDd());
        // [T-Up#INFO][COTRN00C.cbl:402] MOVE statement
        container.getWsVariables().setWsTranDate(
                container.getWsDateTime().getWsCurdateMmDdYy().get());
        // [T-Up#INFO][COTRN00C.cbl:404] EVALUATE statement
        switch (container.getWsVariables().getWsIdx()) {
        case 1: {
            // [T-Up#INFO][COTRN00C.cbl:406] MOVE statement
            container.getCotrn0ai().setTrnid01i(
                    container.getTranRecord().getTranId());
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnidFirst(
                            container.getTranRecord().getTranId());
            // [T-Up#INFO][COTRN00C.cbl:408] MOVE statement
            container.getCotrn0ai().setTdate01i(
                    container.getWsVariables().getWsTranDate());
            // [T-Up#INFO][COTRN00C.cbl:409] MOVE statement
            container.getCotrn0ai().setTdesc01i(
                    container.getTranRecord().getTranDesc());
            // [T-Up#INFO][COTRN00C.cbl:410] MOVE statement
            container.getCotrn0ai().setTamt001i(
                    container.getWsVariables().getWsTranAmt());
            break;
        }
        case 2: {
            // [T-Up#INFO][COTRN00C.cbl:412] MOVE statement
            container.getCotrn0ai().setTrnid02i(
                    container.getTranRecord().getTranId());
            // [T-Up#INFO][COTRN00C.cbl:413] MOVE statement
            container.getCotrn0ai().setTdate02i(
                    container.getWsVariables().getWsTranDate());
            // [T-Up#INFO][COTRN00C.cbl:414] MOVE statement
            container.getCotrn0ai().setTdesc02i(
                    container.getTranRecord().getTranDesc());
            // [T-Up#INFO][COTRN00C.cbl:415] MOVE statement
            container.getCotrn0ai().setTamt002i(
                    container.getWsVariables().getWsTranAmt());
            break;
        }
        case 3: {
            // [T-Up#INFO][COTRN00C.cbl:417] MOVE statement
            container.getCotrn0ai().setTrnid03i(
                    container.getTranRecord().getTranId());
            // [T-Up#INFO][COTRN00C.cbl:418] MOVE statement
            container.getCotrn0ai().setTdate03i(
                    container.getWsVariables().getWsTranDate());
            // [T-Up#INFO][COTRN00C.cbl:419] MOVE statement
            container.getCotrn0ai().setTdesc03i(
                    container.getTranRecord().getTranDesc());
            // [T-Up#INFO][COTRN00C.cbl:420] MOVE statement
            container.getCotrn0ai().setTamt003i(
                    container.getWsVariables().getWsTranAmt());
            break;
        }
        case 4: {
            // [T-Up#INFO][COTRN00C.cbl:422] MOVE statement
            container.getCotrn0ai().setTrnid04i(
                    container.getTranRecord().getTranId());
            // [T-Up#INFO][COTRN00C.cbl:423] MOVE statement
            container.getCotrn0ai().setTdate04i(
                    container.getWsVariables().getWsTranDate());
            // [T-Up#INFO][COTRN00C.cbl:424] MOVE statement
            container.getCotrn0ai().setTdesc04i(
                    container.getTranRecord().getTranDesc());
            // [T-Up#INFO][COTRN00C.cbl:425] MOVE statement
            container.getCotrn0ai().setTamt004i(
                    container.getWsVariables().getWsTranAmt());
            break;
        }
        case 5: {
            // [T-Up#INFO][COTRN00C.cbl:427] MOVE statement
            container.getCotrn0ai().setTrnid05i(
                    container.getTranRecord().getTranId());
            // [T-Up#INFO][COTRN00C.cbl:428] MOVE statement
            container.getCotrn0ai().setTdate05i(
                    container.getWsVariables().getWsTranDate());
            // [T-Up#INFO][COTRN00C.cbl:429] MOVE statement
            container.getCotrn0ai().setTdesc05i(
                    container.getTranRecord().getTranDesc());
            // [T-Up#INFO][COTRN00C.cbl:430] MOVE statement
            container.getCotrn0ai().setTamt005i(
                    container.getWsVariables().getWsTranAmt());
            break;
        }
        case 6: {
            // [T-Up#INFO][COTRN00C.cbl:432] MOVE statement
            container.getCotrn0ai().setTrnid06i(
                    container.getTranRecord().getTranId());
            // [T-Up#INFO][COTRN00C.cbl:433] MOVE statement
            container.getCotrn0ai().setTdate06i(
                    container.getWsVariables().getWsTranDate());
            // [T-Up#INFO][COTRN00C.cbl:434] MOVE statement
            container.getCotrn0ai().setTdesc06i(
                    container.getTranRecord().getTranDesc());
            // [T-Up#INFO][COTRN00C.cbl:435] MOVE statement
            container.getCotrn0ai().setTamt006i(
                    container.getWsVariables().getWsTranAmt());
            break;
        }
        case 7: {
            // [T-Up#INFO][COTRN00C.cbl:437] MOVE statement
            container.getCotrn0ai().setTrnid07i(
                    container.getTranRecord().getTranId());
            // [T-Up#INFO][COTRN00C.cbl:438] MOVE statement
            container.getCotrn0ai().setTdate07i(
                    container.getWsVariables().getWsTranDate());
            // [T-Up#INFO][COTRN00C.cbl:439] MOVE statement
            container.getCotrn0ai().setTdesc07i(
                    container.getTranRecord().getTranDesc());
            // [T-Up#INFO][COTRN00C.cbl:440] MOVE statement
            container.getCotrn0ai().setTamt007i(
                    container.getWsVariables().getWsTranAmt());
            break;
        }
        case 8: {
            // [T-Up#INFO][COTRN00C.cbl:442] MOVE statement
            container.getCotrn0ai().setTrnid08i(
                    container.getTranRecord().getTranId());
            // [T-Up#INFO][COTRN00C.cbl:443] MOVE statement
            container.getCotrn0ai().setTdate08i(
                    container.getWsVariables().getWsTranDate());
            // [T-Up#INFO][COTRN00C.cbl:444] MOVE statement
            container.getCotrn0ai().setTdesc08i(
                    container.getTranRecord().getTranDesc());
            // [T-Up#INFO][COTRN00C.cbl:445] MOVE statement
            container.getCotrn0ai().setTamt008i(
                    container.getWsVariables().getWsTranAmt());
            break;
        }
        case 9: {
            // [T-Up#INFO][COTRN00C.cbl:447] MOVE statement
            container.getCotrn0ai().setTrnid09i(
                    container.getTranRecord().getTranId());
            // [T-Up#INFO][COTRN00C.cbl:448] MOVE statement
            container.getCotrn0ai().setTdate09i(
                    container.getWsVariables().getWsTranDate());
            // [T-Up#INFO][COTRN00C.cbl:449] MOVE statement
            container.getCotrn0ai().setTdesc09i(
                    container.getTranRecord().getTranDesc());
            // [T-Up#INFO][COTRN00C.cbl:450] MOVE statement
            container.getCotrn0ai().setTamt009i(
                    container.getWsVariables().getWsTranAmt());
            break;
        }
        case 10: {
            // [T-Up#INFO][COTRN00C.cbl:452] MOVE statement
            container.getCotrn0ai().setTrnid10i(
                    container.getTranRecord().getTranId());
            container
                    .getCarddemoCommarea()
                    .getCdemoCt00Info()
                    .setCdemoCt00TrnidLast(
                            container.getTranRecord().getTranId());
            // [T-Up#INFO][COTRN00C.cbl:454] MOVE statement
            container.getCotrn0ai().setTdate10i(
                    container.getWsVariables().getWsTranDate());
            // [T-Up#INFO][COTRN00C.cbl:455] MOVE statement
            container.getCotrn0ai().setTdesc10i(
                    container.getTranRecord().getTranDesc());
            // [T-Up#INFO][COTRN00C.cbl:456] MOVE statement
            container.getCotrn0ai().setTamt010i(
                    container.getWsVariables().getWsTranAmt());
            break;
        }
        default: {
            // [T-Up#INFO][COTRN00C.cbl:458] CONTINUE statement
            break;
        }
        }
    }

    // *----------------------------------------------------------------*
    // *                      INITIALIZE-TRAN-DATA
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:464] INITIALIZE-TRAN-DATA Paragraph</p>
     */
    void initializeTranData(OpenFrameContext context) {
        Cotrn00cVariableContainer container = (Cotrn00cVariableContainer) context
                .getProgramVariableContainer("Cotrn00c");
        // [T-Up#INFO][COTRN00C.cbl:466] EVALUATE statement
        switch (container.getWsVariables().getWsIdx()) {
        case 1: {
            // [T-Up#INFO][COTRN00C.cbl:468] MOVE statement
            container.getCotrn0ai().setTrnid01i(StringUtils.repeat(' ', 16));
            // [T-Up#INFO][COTRN00C.cbl:469] MOVE statement
            container.getCotrn0ai().setTdate01i(StringUtils.repeat(' ', 8));
            // [T-Up#INFO][COTRN00C.cbl:470] MOVE statement
            container.getCotrn0ai().setTdesc01i(StringUtils.repeat(' ', 26));
            // [T-Up#INFO][COTRN00C.cbl:471] MOVE statement
            container.getCotrn0ai().setTamt001i(StringUtils.repeat(' ', 12));
            break;
        }
        case 2: {
            // [T-Up#INFO][COTRN00C.cbl:473] MOVE statement
            container.getCotrn0ai().setTrnid02i(StringUtils.repeat(' ', 16));
            // [T-Up#INFO][COTRN00C.cbl:474] MOVE statement
            container.getCotrn0ai().setTdate02i(StringUtils.repeat(' ', 8));
            // [T-Up#INFO][COTRN00C.cbl:475] MOVE statement
            container.getCotrn0ai().setTdesc02i(StringUtils.repeat(' ', 26));
            // [T-Up#INFO][COTRN00C.cbl:476] MOVE statement
            container.getCotrn0ai().setTamt002i(StringUtils.repeat(' ', 12));
            break;
        }
        case 3: {
            // [T-Up#INFO][COTRN00C.cbl:478] MOVE statement
            container.getCotrn0ai().setTrnid03i(StringUtils.repeat(' ', 16));
            // [T-Up#INFO][COTRN00C.cbl:479] MOVE statement
            container.getCotrn0ai().setTdate03i(StringUtils.repeat(' ', 8));
            // [T-Up#INFO][COTRN00C.cbl:480] MOVE statement
            container.getCotrn0ai().setTdesc03i(StringUtils.repeat(' ', 26));
            // [T-Up#INFO][COTRN00C.cbl:481] MOVE statement
            container.getCotrn0ai().setTamt003i(StringUtils.repeat(' ', 12));
            break;
        }
        case 4: {
            // [T-Up#INFO][COTRN00C.cbl:483] MOVE statement
            container.getCotrn0ai().setTrnid04i(StringUtils.repeat(' ', 16));
            // [T-Up#INFO][COTRN00C.cbl:484] MOVE statement
            container.getCotrn0ai().setTdate04i(StringUtils.repeat(' ', 8));
            // [T-Up#INFO][COTRN00C.cbl:485] MOVE statement
            container.getCotrn0ai().setTdesc04i(StringUtils.repeat(' ', 26));
            // [T-Up#INFO][COTRN00C.cbl:486] MOVE statement
            container.getCotrn0ai().setTamt004i(StringUtils.repeat(' ', 12));
            break;
        }
        case 5: {
            // [T-Up#INFO][COTRN00C.cbl:488] MOVE statement
            container.getCotrn0ai().setTrnid05i(StringUtils.repeat(' ', 16));
            // [T-Up#INFO][COTRN00C.cbl:489] MOVE statement
            container.getCotrn0ai().setTdate05i(StringUtils.repeat(' ', 8));
            // [T-Up#INFO][COTRN00C.cbl:490] MOVE statement
            container.getCotrn0ai().setTdesc05i(StringUtils.repeat(' ', 26));
            // [T-Up#INFO][COTRN00C.cbl:491] MOVE statement
            container.getCotrn0ai().setTamt005i(StringUtils.repeat(' ', 12));
            break;
        }
        case 6: {
            // [T-Up#INFO][COTRN00C.cbl:493] MOVE statement
            container.getCotrn0ai().setTrnid06i(StringUtils.repeat(' ', 16));
            // [T-Up#INFO][COTRN00C.cbl:494] MOVE statement
            container.getCotrn0ai().setTdate06i(StringUtils.repeat(' ', 8));
            // [T-Up#INFO][COTRN00C.cbl:495] MOVE statement
            container.getCotrn0ai().setTdesc06i(StringUtils.repeat(' ', 26));
            // [T-Up#INFO][COTRN00C.cbl:496] MOVE statement
            container.getCotrn0ai().setTamt006i(StringUtils.repeat(' ', 12));
            break;
        }
        case 7: {
            // [T-Up#INFO][COTRN00C.cbl:498] MOVE statement
            container.getCotrn0ai().setTrnid07i(StringUtils.repeat(' ', 16));
            // [T-Up#INFO][COTRN00C.cbl:499] MOVE statement
            container.getCotrn0ai().setTdate07i(StringUtils.repeat(' ', 8));
            // [T-Up#INFO][COTRN00C.cbl:500] MOVE statement
            container.getCotrn0ai().setTdesc07i(StringUtils.repeat(' ', 26));
            // [T-Up#INFO][COTRN00C.cbl:501] MOVE statement
            container.getCotrn0ai().setTamt007i(StringUtils.repeat(' ', 12));
            break;
        }
        case 8: {
            // [T-Up#INFO][COTRN00C.cbl:503] MOVE statement
            container.getCotrn0ai().setTrnid08i(StringUtils.repeat(' ', 16));
            // [T-Up#INFO][COTRN00C.cbl:504] MOVE statement
            container.getCotrn0ai().setTdate08i(StringUtils.repeat(' ', 8));
            // [T-Up#INFO][COTRN00C.cbl:505] MOVE statement
            container.getCotrn0ai().setTdesc08i(StringUtils.repeat(' ', 26));
            // [T-Up#INFO][COTRN00C.cbl:506] MOVE statement
            container.getCotrn0ai().setTamt008i(StringUtils.repeat(' ', 12));
            break;
        }
        case 9: {
            // [T-Up#INFO][COTRN00C.cbl:508] MOVE statement
            container.getCotrn0ai().setTrnid09i(StringUtils.repeat(' ', 16));
            // [T-Up#INFO][COTRN00C.cbl:509] MOVE statement
            container.getCotrn0ai().setTdate09i(StringUtils.repeat(' ', 8));
            // [T-Up#INFO][COTRN00C.cbl:510] MOVE statement
            container.getCotrn0ai().setTdesc09i(StringUtils.repeat(' ', 26));
            // [T-Up#INFO][COTRN00C.cbl:511] MOVE statement
            container.getCotrn0ai().setTamt009i(StringUtils.repeat(' ', 12));
            break;
        }
        case 10: {
            // [T-Up#INFO][COTRN00C.cbl:513] MOVE statement
            container.getCotrn0ai().setTrnid10i(StringUtils.repeat(' ', 16));
            // [T-Up#INFO][COTRN00C.cbl:514] MOVE statement
            container.getCotrn0ai().setTdate10i(StringUtils.repeat(' ', 8));
            // [T-Up#INFO][COTRN00C.cbl:515] MOVE statement
            container.getCotrn0ai().setTdesc10i(StringUtils.repeat(' ', 26));
            // [T-Up#INFO][COTRN00C.cbl:516] MOVE statement
            container.getCotrn0ai().setTamt010i(StringUtils.repeat(' ', 12));
            break;
        }
        default: {
            // [T-Up#INFO][COTRN00C.cbl:518] CONTINUE statement
            break;
        }
        }
    }

    // *----------------------------------------------------------------*
    // *                      RETURN-TO-PREV-SCREEN
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:524] RETURN-TO-PREV-SCREEN Paragraph</p>
     */
    void returnToPrevScreen(OpenFrameContext context) {
    }

    // *     IF CDEMO-TO-PROGRAM = LOW-VALUES OR SPACES
    // *         MOVE 'COSGN00C' TO CDEMO-TO-PROGRAM
    // *     END-IF
    // *     MOVE WS-TRANID    TO CDEMO-FROM-TRANID
    // *     MOVE WS-PGMNAME   TO CDEMO-FROM-PROGRAM
    // *     MOVE ZEROS        TO CDEMO-PGM-CONTEXT
    // *     EXEC CICS
    // *         XCTL PROGRAM(CDEMO-TO-PROGRAM)
    // *         COMMAREA(CARDDEMO-COMMAREA)
    // *     END-EXEC.
    // *----------------------------------------------------------------*
    // *                      SEND-TRNLST-SCREEN
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:541] SEND-TRNLST-SCREEN Paragraph</p>
     */
    void sendTrnlstScreen(OpenFrameContext context) {
        Cotrn00cVariableContainer container = (Cotrn00cVariableContainer) context
                .getProgramVariableContainer("Cotrn00c");
        // [T-Up#INFO][COTRN00C.cbl:543] PERFORM statement
        controlManager.run(context, populateHeaderInfo);
        if (controlManager.isTerminate(context)) {
            return;
        }
        // [T-Up#INFO][COTRN00C.cbl:545] MOVE statement
        container.setErrmsgo(container.getWsVariables().getWsMessage());
        // [T-Up#INFO][COTRN00C.cbl:547] IF statement
        if (CobStringUtils.compare(container.getWsVariables()
                .getWsSendEraseFlg(), SEND_ERASE_YES) == 0) {
            // [T-Up#INFO][COTRN00C.cbl:548] EXEC_CICS statement
            /*
                               EXEC CICS SEND
                                         MAP('COTRN0A')
                                         MAPSET('COTRN00')
                                         FROM(COTRN0AO)
                                         ERASE
                                         CURSOR
                               END-EXEC
             */
            ((Cotrn00cOutputDto) task.getOutputDto())
                    .setPageName("COTRN00_COTRN0A");
            ((Cotrn00cOutputDto) task.getOutputDto()).setCotrn0ao(container
                    .getCotrn0ao());
        } else {
            // [T-Up#INFO][COTRN00C.cbl:556] EXEC_CICS statement
            /*
                               EXEC CICS SEND
                                         MAP('COTRN0A')
                                         MAPSET('COTRN00')
                                         FROM(COTRN0AO)
                                         CURSOR
                               END-EXEC
             */
            ((Cotrn00cOutputDto) task.getOutputDto())
                    .setPageName("COTRN00_COTRN0A");
            ((Cotrn00cOutputDto) task.getOutputDto()).setCotrn0ao(container
                    .getCotrn0ao());
        }
    }

    // *                  ERASE
    // *----------------------------------------------------------------*
    // *                      RECEIVE-TRNLST-SCREEN
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:568] RECEIVE-TRNLST-SCREEN Paragraph</p>
     */
    void receiveTrnlstScreen(OpenFrameContext context) {
        Cotrn00cVariableContainer container = (Cotrn00cVariableContainer) context
                .getProgramVariableContainer("Cotrn00c");
        // [T-Up#INFO][COTRN00C.cbl:570] EXEC_CICS statement
        /*
                       EXEC CICS RECEIVE
                                 MAP('COTRN0A')
                                 MAPSET('COTRN00')
                                 INTO(COTRN0AI)
                                 RESP(WS-RESP-CD)
                                 RESP2(WS-REAS-CD)
                       END-EXEC
         */
        try {
            container.setCotrn0ai(((Cotrn00cInputDto) task.getInputDto())
                    .getCotrn0ai());
        } catch (ConditionException e) {
        } finally {
            container.getWsVariables().setWsRespCd(task.getLastResp());
            container.getWsVariables().setWsReasCd(task.getLastResp2());
        }
    }

    // *----------------------------------------------------------------*
    // *                      POPULATE-HEADER-INFO
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:581] POPULATE-HEADER-INFO Paragraph</p>
     */
    void populateHeaderInfo(OpenFrameContext context) {
        Cotrn00cVariableContainer container = (Cotrn00cVariableContainer) context
                .getProgramVariableContainer("Cotrn00c");
        // [T-Up#INFO][COTRN00C.cbl:583] MOVE statement
        container.getWsDateTime().getWsCurdateData()
                .set(IntrinsicFunction.functionCurrentDate());
        // [T-Up#INFO][COTRN00C.cbl:585] MOVE statement
        container.setTitle01o(container.getCcdaScreenTitle().getCcdaTitle01());
        // [T-Up#INFO][COTRN00C.cbl:586] MOVE statement
        container.setTitle02o(container.getCcdaScreenTitle().getCcdaTitle02());
        // [T-Up#INFO][COTRN00C.cbl:587] MOVE statement
        container.setTrnnameo(container.getWsVariables().getWsTranid());
        // [T-Up#INFO][COTRN00C.cbl:588] MOVE statement
        container.setPgmnameo(container.getWsVariables().getWsPgmname());
        // [T-Up#INFO][COTRN00C.cbl:590] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateMm(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurdate().getWsCurdateMonth());
        // [T-Up#INFO][COTRN00C.cbl:591] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateDd(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurdate().getWsCurdateDay());
        // [T-Up#INFO][COTRN00C.cbl:592] MOVE statement
        container
                .getWsDateTime()
                .getWsCurdateMmDdYy()
                .setWsCurdateYy(
                        Integer.parseInt(CobStream
                                .convZonedIntToString(
                                        container.getWsDateTime()
                                                .getWsCurdateData()
                                                .getWsCurdate()
                                                .getWsCurdateYear(), 4)
                                .substring(2, 4).trim()));
        // [T-Up#INFO][COTRN00C.cbl:594] MOVE statement
        container.setCurdateo(container.getWsDateTime().getWsCurdateMmDdYy()
                .get());
        // [T-Up#INFO][COTRN00C.cbl:596] MOVE statement
        container
                .getWsDateTime()
                .getWsCurtimeHhMmSs()
                .setWsCurtimeHh(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurtime().getWsCurtimeHours());
        // [T-Up#INFO][COTRN00C.cbl:597] MOVE statement
        container
                .getWsDateTime()
                .getWsCurtimeHhMmSs()
                .setWsCurtimeMm(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurtime().getWsCurtimeMinute());
        // [T-Up#INFO][COTRN00C.cbl:598] MOVE statement
        container
                .getWsDateTime()
                .getWsCurtimeHhMmSs()
                .setWsCurtimeSs(
                        container.getWsDateTime().getWsCurdateData()
                                .getWsCurtime().getWsCurtimeSecond());
        // [T-Up#INFO][COTRN00C.cbl:600] MOVE statement
        container.setCurtimeo(container.getWsDateTime().getWsCurtimeHhMmSs()
                .get());
    }

    // *----------------------------------------------------------------*
    // *                      STARTBR-TRANSACT-FILE
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:605] STARTBR-TRANSACT-FILE Paragraph</p>
     */
    void startbrTransactFile(OpenFrameContext context) {
        Cotrn00cVariableContainer container = (Cotrn00cVariableContainer) context
                .getProgramVariableContainer("Cotrn00c");
        // [T-Up#INFO][COTRN00C.cbl:607] EXEC_CICS statement
        /*
                       EXEC CICS STARTBR
                            DATASET   (WS-TRANSACT-FILE)
                            RIDFLD    (TRAN-ID)
                            KEYLENGTH (LENGTH OF TRAN-ID)
                            RESP      (WS-RESP-CD)
                            RESP2     (WS-REAS-CD)
                       END-EXEC
         */
        try {
            ReadPoint readPoint = readPointManager
                    .declare(
                            "awsM2CarddemoTransactVsamKsdsDao",
                            0,
                            (AwsM2CarddemoTransactVsamKsdsDto awsM2CarddemoTransactVsamKsdsDto) -> {
                                return awsM2CarddemoTransactVsamKsdsDto
                                        .getTranId();
                            });
            AwsM2CarddemoTransactVsamKsdsDto awsM2CarddemoTransactVsamKsdsDto = readPointAccessor
                    .open(readPoint, container.getTranRecord().getTranId());
            container.getTranRecord().setTranId(
                    awsM2CarddemoTransactVsamKsdsDto.getTranId());
        } catch (ConditionException e) {
        } finally {
            container.getWsVariables().setWsRespCd(task.getLastResp());
            container.getWsVariables().setWsReasCd(task.getLastResp2());
        }
        // *         GTEQ
        // [T-Up#INFO][COTRN00C.cbl:616] EVALUATE statement
        if (container.getWsVariables().getWsRespCd() == 0) {
            // [T-Up#INFO][COTRN00C.cbl:618] CONTINUE statement
        } else if (container.getWsVariables().getWsRespCd() == 13) {
            // [T-Up#INFO][COTRN00C.cbl:620] CONTINUE statement
            // [T-Up#INFO][COTRN00C.cbl:621] SET statement
            container.getWsVariables().setWsTransactEof(TRANSACT_EOF);
            // [T-Up#INFO][COTRN00C.cbl:622] MOVE statement
            container.getWsVariables().setWsMessage(
                    "You are at the top of the page...");
            // [T-Up#INFO][COTRN00C.cbl:624] MOVE statement
            container.getCotrn0ai().setTrnidinl(-1);
            // [T-Up#INFO][COTRN00C.cbl:625] PERFORM statement
            controlManager.run(context, sendTrnlstScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        } else {
            // [T-Up#INFO][COTRN00C.cbl:627] DISPLAY statement
            System.out.print("RESP:");
            System.out.print(container.getWsVariables().getWsRespCd());
            System.out.print("REAS:");
            System.out.println(container.getWsVariables().getWsReasCd());
            // [T-Up#INFO][COTRN00C.cbl:628] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COTRN00C.cbl:629] MOVE statement
            container.getWsVariables().setWsMessage(
                    "Unable to lookup transaction...");
            // [T-Up#INFO][COTRN00C.cbl:631] MOVE statement
            container.getCotrn0ai().setTrnidinl(-1);
            // [T-Up#INFO][COTRN00C.cbl:632] PERFORM statement
            controlManager.run(context, sendTrnlstScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
    }

    // *----------------------------------------------------------------*
    // *                      READNEXT-TRANSACT-FILE
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:638] READNEXT-TRANSACT-FILE Paragraph</p>
     */
    void readnextTransactFile(OpenFrameContext context) {
        Cotrn00cVariableContainer container = (Cotrn00cVariableContainer) context
                .getProgramVariableContainer("Cotrn00c");
        // [T-Up#INFO][COTRN00C.cbl:640] EXEC_CICS statement
        /*
                       EXEC CICS READNEXT
                            DATASET   (WS-TRANSACT-FILE)
                            INTO      (TRAN-RECORD)
                            LENGTH    (LENGTH OF TRAN-RECORD)
                            RIDFLD    (TRAN-ID)
                            KEYLENGTH (LENGTH OF TRAN-ID)
                            RESP      (WS-RESP-CD)
                            RESP2     (WS-REAS-CD)
                       END-EXEC
         */
        try {
            ReadPoint readPoint = readPointManager.find(0);
            AwsM2CarddemoTransactVsamKsdsDto awsM2CarddemoTransactVsamKsdsDto = readPointAccessor
                    .readNext(readPoint, container.getTranRecord().getTranId());
            container.getTranRecord().setTranId(
                    awsM2CarddemoTransactVsamKsdsDto.getTranId());
            container
                    .setTranRecord(TranRecordToAwsM2CarddemoTransactVsamKsdsDto.INSTANCE
                            .toSource(awsM2CarddemoTransactVsamKsdsDto));
        } catch (ConditionException e) {
        } finally {
            container.getWsVariables().setWsRespCd(task.getLastResp());
            container.getWsVariables().setWsReasCd(task.getLastResp2());
        }
        // [T-Up#INFO][COTRN00C.cbl:650] EVALUATE statement
        if (container.getWsVariables().getWsRespCd() == 0) {
            // [T-Up#INFO][COTRN00C.cbl:652] CONTINUE statement
        } else if (container.getWsVariables().getWsRespCd() == 20) {
            // [T-Up#INFO][COTRN00C.cbl:654] CONTINUE statement
            // [T-Up#INFO][COTRN00C.cbl:655] SET statement
            container.getWsVariables().setWsTransactEof(TRANSACT_EOF);
            // [T-Up#INFO][COTRN00C.cbl:656] MOVE statement
            container.getWsVariables().setWsMessage(
                    "You have reached the bottom of the page...");
            // [T-Up#INFO][COTRN00C.cbl:658] MOVE statement
            container.getCotrn0ai().setTrnidinl(-1);
            // [T-Up#INFO][COTRN00C.cbl:659] PERFORM statement
            controlManager.run(context, sendTrnlstScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        } else {
            // [T-Up#INFO][COTRN00C.cbl:661] DISPLAY statement
            System.out.print("RESP:");
            System.out.print(container.getWsVariables().getWsRespCd());
            System.out.print("REAS:");
            System.out.println(container.getWsVariables().getWsReasCd());
            // [T-Up#INFO][COTRN00C.cbl:662] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COTRN00C.cbl:663] MOVE statement
            container.getWsVariables().setWsMessage(
                    "Unable to lookup transaction...");
            // [T-Up#INFO][COTRN00C.cbl:665] MOVE statement
            container.getCotrn0ai().setTrnidinl(-1);
            // [T-Up#INFO][COTRN00C.cbl:666] PERFORM statement
            controlManager.run(context, sendTrnlstScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
    }

    // *----------------------------------------------------------------*
    // *                      READPREV-TRANSACT-FILE
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:672] READPREV-TRANSACT-FILE Paragraph</p>
     */
    void readprevTransactFile(OpenFrameContext context) {
        Cotrn00cVariableContainer container = (Cotrn00cVariableContainer) context
                .getProgramVariableContainer("Cotrn00c");
        // [T-Up#INFO][COTRN00C.cbl:674] EXEC_CICS statement
        /*
                       EXEC CICS READPREV
                            DATASET   (WS-TRANSACT-FILE)
                            INTO      (TRAN-RECORD)
                            LENGTH    (LENGTH OF TRAN-RECORD)
                            RIDFLD    (TRAN-ID)
                            KEYLENGTH (LENGTH OF TRAN-ID)
                            RESP      (WS-RESP-CD)
                            RESP2     (WS-REAS-CD)
                       END-EXEC
         */
        try {
            ReadPoint readPoint = readPointManager.find(0);
            AwsM2CarddemoTransactVsamKsdsDto awsM2CarddemoTransactVsamKsdsDto = readPointAccessor
                    .readPrev(readPoint, container.getTranRecord().getTranId());
            container.getTranRecord().setTranId(
                    awsM2CarddemoTransactVsamKsdsDto.getTranId());
            container
                    .setTranRecord(TranRecordToAwsM2CarddemoTransactVsamKsdsDto.INSTANCE
                            .toSource(awsM2CarddemoTransactVsamKsdsDto));
        } catch (ConditionException e) {
        } finally {
            container.getWsVariables().setWsRespCd(task.getLastResp());
            container.getWsVariables().setWsReasCd(task.getLastResp2());
        }
        // [T-Up#INFO][COTRN00C.cbl:684] EVALUATE statement
        if (container.getWsVariables().getWsRespCd() == 0) {
            // [T-Up#INFO][COTRN00C.cbl:686] CONTINUE statement
        } else if (container.getWsVariables().getWsRespCd() == 20) {
            // [T-Up#INFO][COTRN00C.cbl:688] CONTINUE statement
            // [T-Up#INFO][COTRN00C.cbl:689] SET statement
            container.getWsVariables().setWsTransactEof(TRANSACT_EOF);
            // [T-Up#INFO][COTRN00C.cbl:690] MOVE statement
            container.getWsVariables().setWsMessage(
                    "You have reached the top of the page...");
            // [T-Up#INFO][COTRN00C.cbl:692] MOVE statement
            container.getCotrn0ai().setTrnidinl(-1);
            // [T-Up#INFO][COTRN00C.cbl:693] PERFORM statement
            controlManager.run(context, sendTrnlstScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        } else {
            // [T-Up#INFO][COTRN00C.cbl:695] DISPLAY statement
            System.out.print("RESP:");
            System.out.print(container.getWsVariables().getWsRespCd());
            System.out.print("REAS:");
            System.out.println(container.getWsVariables().getWsReasCd());
            // [T-Up#INFO][COTRN00C.cbl:696] MOVE statement
            container.getWsVariables().setWsErrFlg("Y");
            // [T-Up#INFO][COTRN00C.cbl:697] MOVE statement
            container.getWsVariables().setWsMessage(
                    "Unable to lookup transaction...");
            // [T-Up#INFO][COTRN00C.cbl:699] MOVE statement
            container.getCotrn0ai().setTrnidinl(-1);
            // [T-Up#INFO][COTRN00C.cbl:700] PERFORM statement
            controlManager.run(context, sendTrnlstScreen);
            if (controlManager.isTerminate(context)) {
                return;
            }
        }
    }

    // *----------------------------------------------------------------*
    // *                      ENDBR-TRANSACT-FILE
    // *----------------------------------------------------------------*

    /** 
     * <p>[T-Up#INFO][COTRN00C.cbl:706] ENDBR-TRANSACT-FILE Paragraph</p>
     */
    void endbrTransactFile(OpenFrameContext context) {
        Cotrn00cVariableContainer container = (Cotrn00cVariableContainer) context
                .getProgramVariableContainer("Cotrn00c");
        // [T-Up#INFO][COTRN00C.cbl:708] EXEC_CICS statement
        /*
                       EXEC CICS ENDBR
                            DATASET   (WS-TRANSACT-FILE)
                       END-EXEC
         */
        ReadPoint readPoint = readPointManager.find(0);
        readPointAccessor.close(readPoint);
    }

    // *
    // * Ver: CardDemo_v1.0-15-g27d6c6f-68 Date: 2022-07-19 23:12:34 CDT
    // *
}
