package com.tmax.openframe.file;

import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.file.KeyOperationType;
import com.tmax.openframe.variable.group.Cbact01cFdAcctfileRec;
import java.math.*;
import java.util.*;
import lombok.*;
import org.springframework.stereotype.Repository;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:09 KST</p>
 */
@Repository
public class Cbact01cFdAcctfileFile extends Cbact01cFileOpAcctfileFile {
    public void open(OpenFrameContext context) {
    }

    public void close(OpenFrameContext context) {
    }
}
