package com.tmax.openframe.file;

import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.file.FileBaseOperation;
import com.tmax.openframe.runtime.file.FileStatus;
import com.tmax.openframe.variable.Cbact03cVariableContainer;
import com.tmax.openframe.variable.group.Cbact03cFdXreffileRec;
import java.math.*;
import java.util.*;
import lombok.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:10 KST</p>
 * <hr>
 * <p>Class that defines file I/O methods</p>
 * <ul>
 * <li>File description name: XREFFILE-FILE</li>
 * <li>file record class: {@link Cbact03cFdXreffileRec}</li>
 * <li>key field: {@link Cbact03cFdXreffileRec#fdXrefCardNum}</li>
 * </ul>
 */
public abstract class Cbact03cFileOpXreffileFile implements
        FileBaseOperation<Cbact03cFdXreffileRec, String> {
    public Cbact03cFdXreffileRec readNext(OpenFrameContext context) {
        if (getFileStatus(context) == FileStatus.AT_END_CONDITION_SEQ_READ) {
            setFileStatus(context, FileStatus.ALREADY_AT_END_CONDITION);
            return null;
        } else {
            return readNextRecord(context);
        }
    }

    public void setFileStatus(OpenFrameContext context, FileStatus status) {
        Cbact03cVariableContainer container = (Cbact03cVariableContainer) context
                .getProgramVariableContainer("Cbact03c");
        container.getXreffileStatus().set(status.getValue());
        context.setFileStatus("Cbact03c", "XreffileFile", status);
    }

    public FileStatus getFileStatus(OpenFrameContext context) {
        return context.getFileStatus("Cbact03c", "XreffileFile");
    }
}
