package com.tmax.openframe.file;

import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.file.FileBaseOperation;
import com.tmax.openframe.runtime.file.FileStatus;
import com.tmax.openframe.variable.Cbact04cVariableContainer;
import com.tmax.openframe.variable.group.Cbact04cFdDiscgrpRec;
import java.math.*;
import java.util.*;
import lombok.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:10 KST</p>
 * <hr>
 * <p>Class that defines file I/O methods</p>
 * <ul>
 * <li>File description name: DISCGRP-FILE</li>
 * <li>file record class: {@link Cbact04cFdDiscgrpRec}</li>
 * <li>key field: {@link Cbact04cFdDiscgrpRec#fdDiscgrpKey}</li>
 * </ul>
 */
public abstract class Cbact04cFileOpDiscgrpFile
        implements
        FileBaseOperation<Cbact04cFdDiscgrpRec, Cbact04cFdDiscgrpRec.Cbact04cFdDiscgrpKey> {
    public Cbact04cFdDiscgrpRec readNext(OpenFrameContext context) {
        if (getFileStatus(context) == FileStatus.AT_END_CONDITION_SEQ_READ) {
            setFileStatus(context, FileStatus.ALREADY_AT_END_CONDITION);
            return null;
        } else {
            return readNextRecord(context);
        }
    }

    public void setFileStatus(OpenFrameContext context, FileStatus status) {
        Cbact04cVariableContainer container = (Cbact04cVariableContainer) context
                .getProgramVariableContainer("Cbact04c");
        container.getDiscgrpStatus().set(status.getValue());
        context.setFileStatus("Cbact04c", "DiscgrpFile", status);
    }

    public FileStatus getFileStatus(OpenFrameContext context) {
        return context.getFileStatus("Cbact04c", "DiscgrpFile");
    }
}
