package com.tmax.openframe.file;

import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.file.FileBaseOperation;
import com.tmax.openframe.runtime.file.FileStatus;
import com.tmax.openframe.variable.Cbact04cVariableContainer;
import com.tmax.openframe.variable.group.Cbact04cFdTranfileRec;
import java.math.*;
import java.util.*;
import lombok.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:10 KST</p>
 * <hr>
 * <p>Class that defines file I/O methods</p>
 * <ul>
 * <li>File description name: TRANSACT-FILE</li>
 * <li>file record class: {@link Cbact04cFdTranfileRec}</li>
 * </ul>
 */
public abstract class Cbact04cFileOpTransactFile implements
        FileBaseOperation<Cbact04cFdTranfileRec, Long> {
    public Cbact04cFdTranfileRec readNext(OpenFrameContext context) {
        if (getFileStatus(context) == FileStatus.AT_END_CONDITION_SEQ_READ) {
            setFileStatus(context, FileStatus.ALREADY_AT_END_CONDITION);
            return null;
        } else {
            return readNextRecord(context);
        }
    }

    protected void setNextSeqId(OpenFrameContext context) {
        Long currentSeqId = getCurrentSeqId(context) + 1L;
        setCurrentSeqId(context, currentSeqId);
    }

    protected void setCurrentSeqId(OpenFrameContext context, Long currentSeqId) {
        context.setFileSeqId("Cbact04c", "TransactFile", currentSeqId);
    }

    public Long getCurrentSeqId(OpenFrameContext context) {
        return context.getFileSeqId("Cbact04c", "TransactFile");
    }

    public void setFileStatus(OpenFrameContext context, FileStatus status) {
        Cbact04cVariableContainer container = (Cbact04cVariableContainer) context
                .getProgramVariableContainer("Cbact04c");
        container.getTranfileStatus().set(status.getValue());
        context.setFileStatus("Cbact04c", "TransactFile", status);
    }

    public FileStatus getFileStatus(OpenFrameContext context) {
        return context.getFileStatus("Cbact04c", "TransactFile");
    }
}
