package com.tmax.openframe.file;

import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.file.FileBaseOperation;
import com.tmax.openframe.runtime.file.FileStatus;
import com.tmax.openframe.variable.Cbcus01cVariableContainer;
import com.tmax.openframe.variable.group.Cbcus01cFdCustfileRec;
import java.math.*;
import java.util.*;
import lombok.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:10 KST</p>
 * <hr>
 * <p>Class that defines file I/O methods</p>
 * <ul>
 * <li>File description name: CUSTFILE-FILE</li>
 * <li>file record class: {@link Cbcus01cFdCustfileRec}</li>
 * <li>key field: {@link Cbcus01cFdCustfileRec#fdCustId}</li>
 * </ul>
 */
public abstract class Cbcus01cFileOpCustfileFile implements
        FileBaseOperation<Cbcus01cFdCustfileRec, Integer> {
    public Cbcus01cFdCustfileRec readNext(OpenFrameContext context) {
        if (getFileStatus(context) == FileStatus.AT_END_CONDITION_SEQ_READ) {
            setFileStatus(context, FileStatus.ALREADY_AT_END_CONDITION);
            return null;
        } else {
            return readNextRecord(context);
        }
    }

    public void setFileStatus(OpenFrameContext context, FileStatus status) {
        Cbcus01cVariableContainer container = (Cbcus01cVariableContainer) context
                .getProgramVariableContainer("Cbcus01c");
        container.getCustfileStatus().set(status.getValue());
        context.setFileStatus("Cbcus01c", "CustfileFile", status);
    }

    public FileStatus getFileStatus(OpenFrameContext context) {
        return context.getFileStatus("Cbcus01c", "CustfileFile");
    }
}
