package com.tmax.openframe.file;

import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.file.FileBaseOperation;
import com.tmax.openframe.runtime.file.FileStatus;
import com.tmax.openframe.variable.Cbtrn02cVariableContainer;
import com.tmax.openframe.variable.group.Cbtrn02cFdTranCatBalRecord;
import java.math.*;
import java.util.*;
import lombok.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:10 KST</p>
 * <hr>
 * <p>Class that defines file I/O methods</p>
 * <ul>
 * <li>File description name: TCATBAL-FILE</li>
 * <li>file record class: {@link Cbtrn02cFdTranCatBalRecord}</li>
 * <li>key field: {@link Cbtrn02cFdTranCatBalRecord#fdTranCatKey}</li>
 * </ul>
 */
public abstract class Cbtrn02cFileOpTcatbalFile
        implements
        FileBaseOperation<Cbtrn02cFdTranCatBalRecord, Cbtrn02cFdTranCatBalRecord.Cbtrn02cFdTranCatKey> {
    public Cbtrn02cFdTranCatBalRecord readNext(OpenFrameContext context) {
        if (getFileStatus(context) == FileStatus.AT_END_CONDITION_SEQ_READ) {
            setFileStatus(context, FileStatus.ALREADY_AT_END_CONDITION);
            return null;
        } else {
            return readNextRecord(context);
        }
    }

    public void setFileStatus(OpenFrameContext context, FileStatus status) {
        Cbtrn02cVariableContainer container = (Cbtrn02cVariableContainer) context
                .getProgramVariableContainer("Cbtrn02c");
        container.getTcatbalfStatus().set(status.getValue());
        context.setFileStatus("Cbtrn02c", "TcatbalFile", status);
    }

    public FileStatus getFileStatus(OpenFrameContext context) {
        return context.getFileStatus("Cbtrn02c", "TcatbalFile");
    }
}
