package com.tmax.openframe.file;

import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.file.FileBaseOperation;
import com.tmax.openframe.runtime.file.FileStatus;
import com.tmax.openframe.variable.Cbtrn03cVariableContainer;
import java.math.*;
import java.util.*;
import lombok.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:11 KST</p>
 * <hr>
 * <p>Class that defines file I/O methods</p>
 * <ul>
 * <li>File description name: DATE-PARMS-FILE</li>
 * <li>file record class: {@link String}</li>
 * </ul>
 */
public abstract class Cbtrn03cFileOpDateParmsFile implements
        FileBaseOperation<String, Long> {
    public String readNext(OpenFrameContext context) {
        if (getFileStatus(context) == FileStatus.AT_END_CONDITION_SEQ_READ) {
            setFileStatus(context, FileStatus.ALREADY_AT_END_CONDITION);
            return null;
        } else {
            return readNextRecord(context);
        }
    }

    protected void setNextSeqId(OpenFrameContext context) {
        Long currentSeqId = getCurrentSeqId(context) + 1L;
        setCurrentSeqId(context, currentSeqId);
    }

    protected void setCurrentSeqId(OpenFrameContext context, Long currentSeqId) {
        context.setFileSeqId("Cbtrn03c", "DateParmsFile", currentSeqId);
    }

    public Long getCurrentSeqId(OpenFrameContext context) {
        return context.getFileSeqId("Cbtrn03c", "DateParmsFile");
    }

    public void setFileStatus(OpenFrameContext context, FileStatus status) {
        Cbtrn03cVariableContainer container = (Cbtrn03cVariableContainer) context
                .getProgramVariableContainer("Cbtrn03c");
        container.getDateparmStatus().set(status.getValue());
        context.setFileStatus("Cbtrn03c", "DateParmsFile", status);
    }

    public FileStatus getFileStatus(OpenFrameContext context) {
        return context.getFileStatus("Cbtrn03c", "DateParmsFile");
    }
}
