package com.tmax.openframe.file;

import com.tmax.openframe.runtime.context.OpenFrameContext;
import com.tmax.openframe.runtime.file.FileBaseOperation;
import com.tmax.openframe.runtime.file.FileStatus;
import com.tmax.openframe.variable.Cbtrn03cVariableContainer;
import com.tmax.openframe.variable.group.Cbtrn03cFdCardxrefRec;
import java.math.*;
import java.util.*;
import lombok.*;

/** 
 * <p>This source code was generated by T-Up OpenFrame COBOL to Java migrator</p>
 * <p>  Generation date : 2024/03/20 15:15:11 KST</p>
 * <hr>
 * <p>Class that defines file I/O methods</p>
 * <ul>
 * <li>File description name: XREF-FILE</li>
 * <li>file record class: {@link Cbtrn03cFdCardxrefRec}</li>
 * <li>key field: {@link Cbtrn03cFdCardxrefRec#fdXrefCardNum}</li>
 * </ul>
 */
public abstract class Cbtrn03cFileOpXrefFile implements
        FileBaseOperation<Cbtrn03cFdCardxrefRec, String> {
    public Cbtrn03cFdCardxrefRec readNext(OpenFrameContext context) {
        if (getFileStatus(context) == FileStatus.AT_END_CONDITION_SEQ_READ) {
            setFileStatus(context, FileStatus.ALREADY_AT_END_CONDITION);
            return null;
        } else {
            return readNextRecord(context);
        }
    }

    public void setFileStatus(OpenFrameContext context, FileStatus status) {
        Cbtrn03cVariableContainer container = (Cbtrn03cVariableContainer) context
                .getProgramVariableContainer("Cbtrn03c");
        container.getCardxrefStatus().set(status.getValue());
        context.setFileStatus("Cbtrn03c", "XrefFile", status);
    }

    public FileStatus getFileStatus(OpenFrameContext context) {
        return context.getFileStatus("Cbtrn03c", "XrefFile");
    }
}
